# activity_leader_prompt.py

AL_CRITERIA = [
    {"id": "al_c1", "name": "تخطيط وتنظيم الأنشطة الطلابية", "order": 1},
    {"id": "al_c2", "name": "تنفيذ الفعاليات والبرامج", "order": 2},
    {"id": "al_c3", "name": "تنمية المهارات واكتشاف المواهب", "order": 3},
    {"id": "al_c4", "name": "المشاركات الخارجية والمسابقات", "order": 4},
    {"id": "al_c5", "name": "توثيق الأنشطة وقياس الأثر", "order": 5}
]

AL_SUBCATEGORIES = [
    # al_c1
    {"id": "al_c1_s1", "criterion_id": "al_c1", "name": "إعداد خطة النشاط السنوية", "order": 1},
    {"id": "al_c1_s2", "criterion_id": "al_c1", "name": "تشكيل الفرق الطلابية", "order": 2},
    {"id": "al_c1_s3", "criterion_id": "al_c1", "name": "تجهيز الأدوات والموارد", "order": 3},
    {"id": "al_c1_s4", "criterion_id": "al_c1", "name": "التنسيق مع المعلمين والإدارة", "order": 4},
    {"id": "al_c1_s5", "criterion_id": "al_c1", "name": "إعداد جداول الأنشطة", "order": 5},
    # al_c2
    {"id": "al_c2_s1", "criterion_id": "al_c2", "name": "تنظيم الفعاليات والمناسبات", "order": 1},
    {"id": "al_c2_s2", "criterion_id": "al_c2", "name": "الإشراف على الأندية المدرسية", "order": 2},
    {"id": "al_c2_s3", "criterion_id": "al_c2", "name": "تنظيم الرحلات المدرسية", "order": 3},
    {"id": "al_c2_s4", "criterion_id": "al_c2", "name": "إدارة المسابقات الداخلية", "order": 4},
    {"id": "al_c2_s5", "criterion_id": "al_c2", "name": "تنفيذ ورش العمل", "order": 5},
    # al_c3
    {"id": "al_c3_s1", "criterion_id": "al_c3", "name": "اكتشاف المواهب الطلابية", "order": 1},
    {"id": "al_c3_s2", "criterion_id": "al_c3", "name": "تنمية المهارات القيادية", "order": 2},
    {"id": "al_c3_s3", "criterion_id": "al_c3", "name": "تنمية المهارات الفنية والثقافية", "order": 3},
    {"id": "al_c3_s4", "criterion_id": "al_c3", "name": "تنمية المهارات الرياضية", "order": 4},
    {"id": "al_c3_s5", "criterion_id": "al_c3", "name": "تنمية المهارات الاجتماعية", "order": 5},
    # al_c4
    {"id": "al_c4_s1", "criterion_id": "al_c4", "name": "المشاركة في المسابقات الخارجية", "order": 1},
    {"id": "al_c4_s2", "criterion_id": "al_c4", "name": "تنظيم زيارات تبادلية", "order": 2},
    {"id": "al_c4_s3", "criterion_id": "al_c4", "name": "المشاركة في الفعاليات المجتمعية", "order": 3},
    {"id": "al_c4_s4", "criterion_id": "al_c4", "name": "التنسيق مع أندية الحي", "order": 4},
    {"id": "al_c4_s5", "criterion_id": "al_c4", "name": "المشاركة في المبادرات الوطنية", "order": 5},
    # al_c5
    {"id": "al_c5_s1", "criterion_id": "al_c5", "name": "توثيق الأنشطة (صور, تقارير)", "order": 1},
    {"id": "al_c5_s2", "criterion_id": "al_c5", "name": "قياس أثر الأنشطة على الطلاب", "order": 2},
    {"id": "al_c5_s3", "criterion_id": "al_c5", "name": "إعداد تقارير ختامية للأنشطة", "order": 3},
    {"id": "al_c5_s4", "criterion_id": "al_c5", "name": "تحليل المشاركات", "order": 4},
    {"id": "al_c5_s5", "criterion_id": "al_c5", "name": "رفع التقارير للإدارة", "order": 5}
]

AL_REPORTS = [
    # ==================== al_c1_s1 (إعداد خطة النشاط السنوية) ====================
    {"id": "al_c1_s1_r001", "subcategory_id": "al_c1_s1", "name": "تقرير إعداد خطة النشاط السنوية", "order": 1},
    {"id": "al_c1_s1_r002", "subcategory_id": "al_c1_s1", "name": "سجل مسودة خطة النشاط", "order": 2},
    {"id": "al_c1_s1_r003", "subcategory_id": "al_c1_s1", "name": "تقرير عن اعتماد الخطة من الإدارة", "order": 3},
    {"id": "al_c1_s1_r004", "subcategory_id": "al_c1_s1", "name": "توثيق توزيع الخطة على المعنيين", "order": 4},
    {"id": "al_c1_s1_r005", "subcategory_id": "al_c1_s1", "name": "تقرير عن مراجعة الخطة وتحديثها", "order": 5},
    {"id": "al_c1_s1_r006", "subcategory_id": "al_c1_s1", "name": "تقرير تحليل الاحتياجات للأنشطة", "order": 6},
    {"id": "al_c1_s1_r007", "subcategory_id": "al_c1_s1", "name": "سجل اجتماعات التخطيط للأنشطة", "order": 7},
    {"id": "al_c1_s1_r008", "subcategory_id": "al_c1_s1", "name": "تقرير تحديد أهداف النشاط السنوية", "order": 8},
    {"id": "al_c1_s1_r009", "subcategory_id": "al_c1_s1", "name": "توثيق ربط الخطة برؤية المدرسة", "order": 9},
    {"id": "al_c1_s1_r010", "subcategory_id": "al_c1_s1", "name": "تقرير توزيع الميزانية للأنشطة", "order": 10},
    {"id": "al_c1_s1_r011", "subcategory_id": "al_c1_s1", "name": "سجل الأولويات في الخطة", "order": 11},
    {"id": "al_c1_s1_r012", "subcategory_id": "al_c1_s1", "name": "تقرير مشاركة الطلاب في إعداد الخطة", "order": 12},
    {"id": "al_c1_s1_r013", "subcategory_id": "al_c1_s1", "name": "توثيق مراحل تطور الخطة", "order": 13},
    {"id": "al_c1_s1_r014", "subcategory_id": "al_c1_s1", "name": "تقرير تكامل الخطة مع المنهج", "order": 14},
    {"id": "al_c1_s1_r015", "subcategory_id": "al_c1_s1", "name": "سجل الاستبيانات المستخدمة للخطة", "order": 15},
    {"id": "al_c1_s1_r016", "subcategory_id": "al_c1_s1", "name": "تقرير توقيتات الأنشطة الرئيسية", "order": 16},
    {"id": "al_c1_s1_r017", "subcategory_id": "al_c1_s1", "name": "توثيق الاعتماد المالي للخطة", "order": 17},
    {"id": "al_c1_s1_r018", "subcategory_id": "al_c1_s1", "name": "تقرير التعديلات على الخطة", "order": 18},
    {"id": "al_c1_s1_r019", "subcategory_id": "al_c1_s1", "name": "سجل تقييم الخطة من فريق العمل", "order": 19},
    {"id": "al_c1_s1_r020", "subcategory_id": "al_c1_s1", "name": "تقرير نشر الخطة في المدرسة", "order": 20},

    # ==================== al_c1_s2 (تشكيل الفرق الطلابية) ====================
    {"id": "al_c1_s2_r001", "subcategory_id": "al_c1_s2", "name": "تقرير عن تشكيل الفرق الطلابية", "order": 1},
    {"id": "al_c1_s2_r002", "subcategory_id": "al_c1_s2", "name": "سجل الفرق الطلابية وأعضائها", "order": 2},
    {"id": "al_c1_s2_r003", "subcategory_id": "al_c1_s2", "name": "تقرير عن انتخاب قادة الفرق", "order": 3},
    {"id": "al_c1_s2_r004", "subcategory_id": "al_c1_s2", "name": "توثيق اجتماعات الفرق", "order": 4},
    {"id": "al_c1_s2_r005", "subcategory_id": "al_c1_s2", "name": "تقرير عن أداء الفرق", "order": 5},
    {"id": "al_c1_s2_r006", "subcategory_id": "al_c1_s2", "name": "تقرير آلية اختيار أعضاء الفرق", "order": 6},
    {"id": "al_c1_s2_r007", "subcategory_id": "al_c1_s2", "name": "سجل مهام الفرق المدرسية", "order": 7},
    {"id": "al_c1_s2_r008", "subcategory_id": "al_c1_s2", "name": "تقرير توزيع الأدوار في الفرق", "order": 8},
    {"id": "al_c1_s2_r009", "subcategory_id": "al_c1_s2", "name": "توثيق تدريب قادة الفرق", "order": 9},
    {"id": "al_c1_s2_r010", "subcategory_id": "al_c1_s2", "name": "تقرير تقييم أداء الفرق", "order": 10},
    {"id": "al_c1_s2_r011", "subcategory_id": "al_c1_s2", "name": "سجل إنجازات الفرق", "order": 11},
    {"id": "al_c1_s2_r012", "subcategory_id": "al_c1_s2", "name": "تقرير اجتماعات التنسيق بين الفرق", "order": 12},
    {"id": "al_c1_s2_r013", "subcategory_id": "al_c1_s2", "name": "توثيق مشاركة الفرق في الأنشطة", "order": 13},
    {"id": "al_c1_s2_r014", "subcategory_id": "al_c1_s2", "name": "تقرير حل النزاعات داخل الفرق", "order": 14},
    {"id": "al_c1_s2_r015", "subcategory_id": "al_c1_s2", "name": "سجل متابعة حضور الفرق", "order": 15},
    {"id": "al_c1_s2_r016", "subcategory_id": "al_c1_s2", "name": "تقرير تحفيز الفرق", "order": 16},
    {"id": "al_c1_s2_r017", "subcategory_id": "al_c1_s2", "name": "توثيق تجديد تشكيل الفرق", "order": 17},
    {"id": "al_c1_s2_r018", "subcategory_id": "al_c1_s2", "name": "تقرير استقطاب أعضاء جدد", "order": 18},
    {"id": "al_c1_s2_r019", "subcategory_id": "al_c1_s2", "name": "سجل تطوير أداء الفرق", "order": 19},
    {"id": "al_c1_s2_r020", "subcategory_id": "al_c1_s2", "name": "تقرير ختامي لأعمال الفرق", "order": 20},

    # ==================== al_c1_s3 (تجهيز الأدوات والموارد) ====================
    {"id": "al_c1_s3_r001", "subcategory_id": "al_c1_s3", "name": "تقرير عن تجهيز أدوات الأنشطة", "order": 1},
    {"id": "al_c1_s3_r002", "subcategory_id": "al_c1_s3", "name": "سجل طلب احتياجات الأنشطة", "order": 2},
    {"id": "al_c1_s3_r003", "subcategory_id": "al_c1_s3", "name": "تقرير عن تجهيز مكان النشاط", "order": 3},
    {"id": "al_c1_s3_r004", "subcategory_id": "al_c1_s3", "name": "توثيق متابعة الصيانة للأدوات", "order": 4},
    {"id": "al_c1_s3_r005", "subcategory_id": "al_c1_s3", "name": "تقرير عن توفير المواد الاستهلاكية", "order": 5},
    {"id": "al_c1_s3_r006", "subcategory_id": "al_c1_s3", "name": "تقرير جرد أدوات الأنشطة", "order": 6},
    {"id": "al_c1_s3_r007", "subcategory_id": "al_c1_s3", "name": "سجل استلام الأدوات", "order": 7},
    {"id": "al_c1_s3_r008", "subcategory_id": "al_c1_s3", "name": "تقرير توزيع الأدوات على الفرق", "order": 8},
    {"id": "al_c1_s3_r009", "subcategory_id": "al_c1_s3", "name": "توثيق تجهيز الوسائل التعليمية", "order": 9},
    {"id": "al_c1_s3_r010", "subcategory_id": "al_c1_s3", "name": "تقرير توفير الدعم اللوجستي", "order": 10},
    {"id": "al_c1_s3_r011", "subcategory_id": "al_c1_s3", "name": "سجل صيانة الأجهزة", "order": 11},
    {"id": "al_c1_s3_r012", "subcategory_id": "al_c1_s3", "name": "تقرير تحديث الموارد", "order": 12},
    {"id": "al_c1_s3_r013", "subcategory_id": "al_c1_s3", "name": "توثيق تأمين المواد الخام", "order": 13},
    {"id": "al_c1_s3_r014", "subcategory_id": "al_c1_s3", "name": "تقرير تجهيز ورش العمل", "order": 14},
    {"id": "al_c1_s3_r015", "subcategory_id": "al_c1_s3", "name": "سجل متابعة المخزون", "order": 15},
    {"id": "al_c1_s3_r016", "subcategory_id": "al_c1_s3", "name": "تقرير استلام تبرعات للأدوات", "order": 16},
    {"id": "al_c1_s3_r017", "subcategory_id": "al_c1_s3", "name": "توثيق تجهيز الملاعب", "order": 17},
    {"id": "al_c1_s3_r018", "subcategory_id": "al_c1_s3", "name": "تقرير توفير أدوات السلامة", "order": 18},
    {"id": "al_c1_s3_r019", "subcategory_id": "al_c1_s3", "name": "سجل تجهيز المعارض", "order": 19},
    {"id": "al_c1_s3_r020", "subcategory_id": "al_c1_s3", "name": "تقرير ختامي عن الموارد", "order": 20},

    # ==================== al_c1_s4 (التنسيق مع المعلمين والإدارة) ====================
    {"id": "al_c1_s4_r001", "subcategory_id": "al_c1_s4", "name": "تقرير عن التنسيق مع المعلمين للأنشطة", "order": 1},
    {"id": "al_c1_s4_r002", "subcategory_id": "al_c1_s4", "name": "سجل اجتماعات تنسيق الأنشطة", "order": 2},
    {"id": "al_c1_s4_r003", "subcategory_id": "al_c1_s4", "name": "تقرير عن مشاركة المعلمين في الأنشطة", "order": 3},
    {"id": "al_c1_s4_r004", "subcategory_id": "al_c1_s4", "name": "توثيق التعاون مع الإدارة", "order": 4},
    {"id": "al_c1_s4_r005", "subcategory_id": "al_c1_s4", "name": "تقرير عن تذليل الصعوبات", "order": 5},
    {"id": "al_c1_s4_r006", "subcategory_id": "al_c1_s4", "name": "تقرير تنسيق الجداول مع المعلمين", "order": 6},
    {"id": "al_c1_s4_r007", "subcategory_id": "al_c1_s4", "name": "سجل التنسيق مع رؤساء الأقسام", "order": 7},
    {"id": "al_c1_s4_r008", "subcategory_id": "al_c1_s4", "name": "تقرير اجتماعات التخطيط المشترك", "order": 8},
    {"id": "al_c1_s4_r009", "subcategory_id": "al_c1_s4", "name": "توثيق تبادل الأدوار", "order": 9},
    {"id": "al_c1_s4_r010", "subcategory_id": "al_c1_s4", "name": "تقرير متابعة تنفيذ الأنشطة مع المعلمين", "order": 10},
    {"id": "al_c1_s4_r011", "subcategory_id": "al_c1_s4", "name": "سجل التنسيق لرحلات", "order": 11},
    {"id": "al_c1_s4_r012", "subcategory_id": "al_c1_s4", "name": "تقرير توفير البدائل", "order": 12},
    {"id": "al_c1_s4_r013", "subcategory_id": "al_c1_s4", "name": "توثيق التعاون مع المرشد الطلابي", "order": 13},
    {"id": "al_c1_s4_r014", "subcategory_id": "al_c1_s4", "name": "تقرير مشاركة الإدارة في الفعاليات", "order": 14},
    {"id": "al_c1_s4_r015", "subcategory_id": "al_c1_s4", "name": "سجل التواصل مع أولياء الأمور", "order": 15},
    {"id": "al_c1_s4_r016", "subcategory_id": "al_c1_s4", "name": "تقرير تنسيق المواعيد", "order": 16},
    {"id": "al_c1_s4_r017", "subcategory_id": "al_c1_s4", "name": "توثيق حل المشكلات مع الإدارة", "order": 17},
    {"id": "al_c1_s4_r018", "subcategory_id": "al_c1_s4", "name": "تقرير تقييم التعاون", "order": 18},
    {"id": "al_c1_s4_r019", "subcategory_id": "al_c1_s4", "name": "سجل التنسيق مع لجان المدرسة", "order": 19},
    {"id": "al_c1_s4_r020", "subcategory_id": "al_c1_s4", "name": "تقرير ختامي للتنسيق", "order": 20},

    # ==================== al_c1_s5 (إعداد جداول الأنشطة) ====================
    {"id": "al_c1_s5_r001", "subcategory_id": "al_c1_s5", "name": "تقرير إعداد جداول الأنشطة الأسبوعية", "order": 1},
    {"id": "al_c1_s5_r002", "subcategory_id": "al_c1_s5", "name": "سجل توزيع الجداول", "order": 2},
    {"id": "al_c1_s5_r003", "subcategory_id": "al_c1_s5", "name": "تقرير عن التزام الفرق بالجدول", "order": 3},
    {"id": "al_c1_s5_r004", "subcategory_id": "al_c1_s5", "name": "توثيق تعديلات الجدول", "order": 4},
    {"id": "al_c1_s5_r005", "subcategory_id": "al_c1_s5", "name": "تقرير عن تقييم الجداول", "order": 5},
    {"id": "al_c1_s5_r006", "subcategory_id": "al_c1_s5", "name": "تقرير إعداد الجدول الشهري", "order": 6},
    {"id": "al_c1_s5_r007", "subcategory_id": "al_c1_s5", "name": "سجل توقيتات الأنشطة", "order": 7},
    {"id": "al_c1_s5_r008", "subcategory_id": "al_c1_s5", "name": "تقرير تنسيق الجداول مع الإدارة", "order": 8},
    {"id": "al_c1_s5_r009", "subcategory_id": "al_c1_s5", "name": "توثيق تعميم الجداول", "order": 9},
    {"id": "al_c1_s5_r010", "subcategory_id": "al_c1_s5", "name": "تقرير مرونة الجداول", "order": 10},
    {"id": "al_c1_s5_r011", "subcategory_id": "al_c1_s5", "name": "سجل استلام الجداول من الفرق", "order": 11},
    {"id": "al_c1_s5_r012", "subcategory_id": "al_c1_s5", "name": "تقرير اجتماعات وضع الجداول", "order": 12},
    {"id": "al_c1_s5_r013", "subcategory_id": "al_c1_s5", "name": "توثيق تغذية راجعة للجداول", "order": 13},
    {"id": "al_c1_s5_r014", "subcategory_id": "al_c1_s5", "name": "تقرير التزام الطلاب بالجداول", "order": 14},
    {"id": "al_c1_s5_r015", "subcategory_id": "al_c1_s5", "name": "سجل متابعة تنفيذ الجداول", "order": 15},
    {"id": "al_c1_s5_r016", "subcategory_id": "al_c1_s5", "name": "تقرير تحديث الجداول", "order": 16},
    {"id": "al_c1_s5_r017", "subcategory_id": "al_c1_s5", "name": "توثيق الجداول النهائية", "order": 17},
    {"id": "al_c1_s5_r018", "subcategory_id": "al_c1_s5", "name": "تقرير توزيع الجداول الرقمية", "order": 18},
    {"id": "al_c1_s5_r019", "subcategory_id": "al_c1_s5", "name": "سجل تقييم الجداول من الفرق", "order": 19},
    {"id": "al_c1_s5_r020", "subcategory_id": "al_c1_s5", "name": "تقرير ختامي للجداول", "order": 20},

    # ==================== al_c2_s1 (تنظيم الفعاليات والمناسبات) ====================
    {"id": "al_c2_s1_r001", "subcategory_id": "al_c2_s1", "name": "تقرير عن تنظيم يوم المهنة", "order": 1},
    {"id": "al_c2_s1_r002", "subcategory_id": "al_c2_s1", "name": "سجل فعاليات اليوم الوطني", "order": 2},
    {"id": "al_c2_s1_r003", "subcategory_id": "al_c2_s1", "name": "تقرير عن تنظيم معرض المواهب", "order": 3},
    {"id": "al_c2_s1_r004", "subcategory_id": "al_c2_s1", "name": "توثيق حفلات التكريم", "order": 4},
    {"id": "al_c2_s1_r005", "subcategory_id": "al_c2_s1", "name": "تقرير عن تنظيم الأسبوع الثقافي", "order": 5},
    {"id": "al_c2_s1_r006", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم مهرجان المدرسة", "order": 6},
    {"id": "al_c2_s1_r007", "subcategory_id": "al_c2_s1", "name": "سجل فعالية اليوم العالمي للغة", "order": 7},
    {"id": "al_c2_s1_r008", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم احتفال العيد الوطني", "order": 8},
    {"id": "al_c2_s1_r009", "subcategory_id": "al_c2_s1", "name": "توثيق فعالية الأسبوع التمهيدي", "order": 9},
    {"id": "al_c2_s1_r010", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم معرض الكتاب", "order": 10},
    {"id": "al_c2_s1_r011", "subcategory_id": "al_c2_s1", "name": "سجل فعالية اليوم الرياضي", "order": 11},
    {"id": "al_c2_s1_r012", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم حفل الخريجين", "order": 12},
    {"id": "al_c2_s1_r013", "subcategory_id": "al_c2_s1", "name": "توثيق فعالية اليوم المفتوح", "order": 13},
    {"id": "al_c2_s1_r014", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم مسابقة المواهب", "order": 14},
    {"id": "al_c2_s1_r015", "subcategory_id": "al_c2_s1", "name": "سجل فعالية اليوم العالمي للطفل", "order": 15},
    {"id": "al_c2_s1_r016", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم معرض الفنون", "order": 16},
    {"id": "al_c2_s1_r017", "subcategory_id": "al_c2_s1", "name": "توثيق فعالية الأسبوع البيئي", "order": 17},
    {"id": "al_c2_s1_r018", "subcategory_id": "al_c2_s1", "name": "تقرير تنظيم يوم التطوع", "order": 18},
    {"id": "al_c2_s1_r019", "subcategory_id": "al_c2_s1", "name": "سجل فعالية اليوم العالمي للصحة", "order": 19},
    {"id": "al_c2_s1_r020", "subcategory_id": "al_c2_s1", "name": "تقرير ختامي للفعاليات", "order": 20},

    # ==================== al_c2_s2 (الإشراف على الأندية المدرسية) ====================
    {"id": "al_c2_s2_r001", "subcategory_id": "al_c2_s2", "name": "تقرير عن الإشراف على نادي الرياضيات", "order": 1},
    {"id": "al_c2_s2_r002", "subcategory_id": "al_c2_s2", "name": "سجل أنشطة نادي اللغة الإنجليزية", "order": 2},
    {"id": "al_c2_s2_r003", "subcategory_id": "al_c2_s2", "name": "تقرير عن نادي المسرح", "order": 3},
    {"id": "al_c2_s2_r004", "subcategory_id": "al_c2_s2", "name": "توثيق اجتماعات الأندية", "order": 4},
    {"id": "al_c2_s2_r005", "subcategory_id": "al_c2_s2", "name": "تقرير عن إنجازات الأندية", "order": 5},
    {"id": "al_c2_s2_r006", "subcategory_id": "al_c2_s2", "name": "تقرير الإشراف على نادي العلوم", "order": 6},
    {"id": "al_c2_s2_r007", "subcategory_id": "al_c2_s2", "name": "سجل نادي الروبوت", "order": 7},
    {"id": "al_c2_s2_r008", "subcategory_id": "al_c2_s2", "name": "تقرير نادي الخط العربي", "order": 8},
    {"id": "al_c2_s2_r009", "subcategory_id": "al_c2_s2", "name": "توثيق نادي التصوير", "order": 9},
    {"id": "al_c2_s2_r010", "subcategory_id": "al_c2_s2", "name": "تقرير نادي الفنون التشكيلية", "order": 10},
    {"id": "al_c2_s2_r011", "subcategory_id": "al_c2_s2", "name": "سجل نادي القراءة", "order": 11},
    {"id": "al_c2_s2_r012", "subcategory_id": "al_c2_s2", "name": "تقرير نادي الإبداع", "order": 12},
    {"id": "al_c2_s2_r013", "subcategory_id": "al_c2_s2", "name": "توثيق نادي القيادة", "order": 13},
    {"id": "al_c2_s2_r014", "subcategory_id": "al_c2_s2", "name": "تقرير نادي العمل التطوعي", "order": 14},
    {"id": "al_c2_s2_r015", "subcategory_id": "al_c2_s2", "name": "سجل نادي اللياقة", "order": 15},
    {"id": "al_c2_s2_r016", "subcategory_id": "al_c2_s2", "name": "تقرير نادي الشطرنج", "order": 16},
    {"id": "al_c2_s2_r017", "subcategory_id": "al_c2_s2", "name": "توثيق نادي المسرح", "order": 17},
    {"id": "al_c2_s2_r018", "subcategory_id": "al_c2_s2", "name": "تقرير نادي الموسيقى", "order": 18},
    {"id": "al_c2_s2_r019", "subcategory_id": "al_c2_s2", "name": "سجل نادي البيئة", "order": 19},
    {"id": "al_c2_s2_r020", "subcategory_id": "al_c2_s2", "name": "تقرير ختامي للأندية", "order": 20},

    # ==================== al_c2_s3 (تنظيم الرحلات المدرسية) ====================
    {"id": "al_c2_s3_r001", "subcategory_id": "al_c2_s3", "name": "تقرير عن تنظيم رحلة علمية", "order": 1},
    {"id": "al_c2_s3_r002", "subcategory_id": "al_c2_s3", "name": "سجل الموافقات للرحلات", "order": 2},
    {"id": "al_c2_s3_r003", "subcategory_id": "al_c2_s3", "name": "تقرير عن رحلة ترفيهية", "order": 3},
    {"id": "al_c2_s3_r004", "subcategory_id": "al_c2_s3", "name": "توثيق تقييم الرحلات", "order": 4},
    {"id": "al_c2_s3_r005", "subcategory_id": "al_c2_s3", "name": "تقرير عن أثر الرحلات على الطلاب", "order": 5},
    {"id": "al_c2_s3_r006", "subcategory_id": "al_c2_s3", "name": "تقرير تنظيم رحلة لمتحف", "order": 6},
    {"id": "al_c2_s3_r007", "subcategory_id": "al_c2_s3", "name": "سجل رحلة إلى مركز علمي", "order": 7},
    {"id": "al_c2_s3_r008", "subcategory_id": "al_c2_s3", "name": "تقرير رحلة إلى معرض", "order": 8},
    {"id": "al_c2_s3_r009", "subcategory_id": "al_c2_s3", "name": "توثيق رحلة إلى حديقة", "order": 9},
    {"id": "al_c2_s3_r010", "subcategory_id": "al_c2_s3", "name": "تقرير رحلة إلى جامعة", "order": 10},
    {"id": "al_c2_s3_r011", "subcategory_id": "al_c2_s3", "name": "سجل رحلة إلى مكتبة عامة", "order": 11},
    {"id": "al_c2_s3_r012", "subcategory_id": "al_c2_s3", "name": "تقرير رحلة استكشافية", "order": 12},
    {"id": "al_c2_s3_r013", "subcategory_id": "al_c2_s3", "name": "توثيق رحلة إلى مصنع", "order": 13},
    {"id": "al_c2_s3_r014", "subcategory_id": "al_c2_s3", "name": "تقرير رحلة ثقافية", "order": 14},
    {"id": "al_c2_s3_r015", "subcategory_id": "al_c2_s3", "name": "سجل رحلة إلى معسكر", "order": 15},
    {"id": "al_c2_s3_r016", "subcategory_id": "al_c2_s3", "name": "تقرير رحلة إلى منطقة أثرية", "order": 16},
    {"id": "al_c2_s3_r017", "subcategory_id": "al_c2_s3", "name": "توثيق رحلة إلى محمية", "order": 17},
    {"id": "al_c2_s3_r018", "subcategory_id": "al_c2_s3", "name": "تقرير رحلة إلى نادٍ رياضي", "order": 18},
    {"id": "al_c2_s3_r019", "subcategory_id": "al_c2_s3", "name": "سجل متابعة سلامة الرحلات", "order": 19},
    {"id": "al_c2_s3_r020", "subcategory_id": "al_c2_s3", "name": "تقرير ختامي للرحلات", "order": 20},

    # ==================== al_c2_s4 (إدارة المسابقات الداخلية) ====================
    {"id": "al_c2_s4_r001", "subcategory_id": "al_c2_s4", "name": "تقرير عن تنظيم مسابقة الخطابة", "order": 1},
    {"id": "al_c2_s4_r002", "subcategory_id": "al_c2_s4", "name": "سجل نتائج مسابقة القرآن", "order": 2},
    {"id": "al_c2_s4_r003", "subcategory_id": "al_c2_s4", "name": "تقرير عن مسابقة الروبوت", "order": 3},
    {"id": "al_c2_s4_r004", "subcategory_id": "al_c2_s4", "name": "توثيق تحكيم المسابقات", "order": 4},
    {"id": "al_c2_s4_r005", "subcategory_id": "al_c2_s4", "name": "تقرير عن جوائز الفائزين", "order": 5},
    {"id": "al_c2_s4_r006", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة الرسم", "order": 6},
    {"id": "al_c2_s4_r007", "subcategory_id": "al_c2_s4", "name": "سجل مسابقة الإلقاء", "order": 7},
    {"id": "al_c2_s4_r008", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة الرياضيات", "order": 8},
    {"id": "al_c2_s4_r009", "subcategory_id": "al_c2_s4", "name": "توثيق مسابقة العلوم", "order": 9},
    {"id": "al_c2_s4_r010", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة الإملاء", "order": 10},
    {"id": "al_c2_s4_r011", "subcategory_id": "al_c2_s4", "name": "سجل مسابقة الخط", "order": 11},
    {"id": "al_c2_s4_r012", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة التصوير", "order": 12},
    {"id": "al_c2_s4_r013", "subcategory_id": "al_c2_s4", "name": "توثيق مسابقة القصة", "order": 13},
    {"id": "al_c2_s4_r014", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة الشعر", "order": 14},
    {"id": "al_c2_s4_r015", "subcategory_id": "al_c2_s4", "name": "سجل مسابقة المعلومات العامة", "order": 15},
    {"id": "al_c2_s4_r016", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة الفنون", "order": 16},
    {"id": "al_c2_s4_r017", "subcategory_id": "al_c2_s4", "name": "توثيق مسابقة اللياقة", "order": 17},
    {"id": "al_c2_s4_r018", "subcategory_id": "al_c2_s4", "name": "تقرير مسابقة الألعاب الذهنية", "order": 18},
    {"id": "al_c2_s4_r019", "subcategory_id": "al_c2_s4", "name": "سجل تكريم الفائزين", "order": 19},
    {"id": "al_c2_s4_r020", "subcategory_id": "al_c2_s4", "name": "تقرير ختامي للمسابقات", "order": 20},

    # ==================== al_c2_s5 (تنفيذ ورش العمل) ====================
    {"id": "al_c2_s5_r001", "subcategory_id": "al_c2_s5", "name": "تقرير عن ورش عمل الرسم", "order": 1},
    {"id": "al_c2_s5_r002", "subcategory_id": "al_c2_s5", "name": "سجل ورش التصوير", "order": 2},
    {"id": "al_c2_s5_r003", "subcategory_id": "al_c2_s5", "name": "تقرير عن ورش الخط العربي", "order": 3},
    {"id": "al_c2_s5_r004", "subcategory_id": "al_c2_s5", "name": "توثيق ورش الإسعافات الأولية", "order": 4},
    {"id": "al_c2_s5_r005", "subcategory_id": "al_c2_s5", "name": "تقرير عن تفاعل الطلاب مع الورش", "order": 5},
    {"id": "al_c2_s5_r006", "subcategory_id": "al_c2_s5", "name": "تقرير ورش البرمجة", "order": 6},
    {"id": "al_c2_s5_r007", "subcategory_id": "al_c2_s5", "name": "سجل ورش الروبوت", "order": 7},
    {"id": "al_c2_s5_r008", "subcategory_id": "al_c2_s5", "name": "تقرير ورش المسرح", "order": 8},
    {"id": "al_c2_s5_r009", "subcategory_id": "al_c2_s5", "name": "توثيق ورش الموسيقى", "order": 9},
    {"id": "al_c2_s5_r010", "subcategory_id": "al_c2_s5", "name": "تقرير ورش القيادة", "order": 10},
    {"id": "al_c2_s5_r011", "subcategory_id": "al_c2_s5", "name": "سجل ورش التواصل", "order": 11},
    {"id": "al_c2_s5_r012", "subcategory_id": "al_c2_s5", "name": "تقرير ورش الإبداع", "order": 12},
    {"id": "al_c2_s5_r013", "subcategory_id": "al_c2_s5", "name": "توثيق ورش الكتابة", "order": 13},
    {"id": "al_c2_s5_r014", "subcategory_id": "al_c2_s5", "name": "تقرير ورش النحو", "order": 14},
    {"id": "al_c2_s5_r015", "subcategory_id": "al_c2_s5", "name": "سجل ورش اللغة الإنجليزية", "order": 15},
    {"id": "al_c2_s5_r016", "subcategory_id": "al_c2_s5", "name": "تقرير ورش الرياضيات", "order": 16},
    {"id": "al_c2_s5_r017", "subcategory_id": "al_c2_s5", "name": "توثيق ورش العلوم", "order": 17},
    {"id": "al_c2_s5_r018", "subcategory_id": "al_c2_s5", "name": "تقرير ورش الحرف اليدوية", "order": 18},
    {"id": "al_c2_s5_r019", "subcategory_id": "al_c2_s5", "name": "سجل تقييم الورش", "order": 19},
    {"id": "al_c2_s5_r020", "subcategory_id": "al_c2_s5", "name": "تقرير ختامي للورش", "order": 20},

    # ==================== al_c3_s1 (اكتشاف المواهب الطلابية) ====================
    {"id": "al_c3_s1_r001", "subcategory_id": "al_c3_s1", "name": "تقرير عن اكتشاف المواهب الفنية", "order": 1},
    {"id": "al_c3_s1_r002", "subcategory_id": "al_c3_s1", "name": "سجل قاعدة بيانات الموهوبين", "order": 2},
    {"id": "al_c3_s1_r003", "subcategory_id": "al_c3_s1", "name": "تقرير عن مسابقة المواهب", "order": 3},
    {"id": "al_c3_s1_r004", "subcategory_id": "al_c3_s1", "name": "توثيق اختبارات اكتشاف المواهب", "order": 4},
    {"id": "al_c3_s1_r005", "subcategory_id": "al_c3_s1", "name": "تقرير عن متابعة الموهوبين", "order": 5},
    {"id": "al_c3_s1_r006", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف المواهب الرياضية", "order": 6},
    {"id": "al_c3_s1_r007", "subcategory_id": "al_c3_s1", "name": "سجل المواهب العلمية", "order": 7},
    {"id": "al_c3_s1_r008", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف المواهب الأدبية", "order": 8},
    {"id": "al_c3_s1_r009", "subcategory_id": "al_c3_s1", "name": "توثيق اكتشاف مواهب القيادة", "order": 9},
    {"id": "al_c3_s1_r010", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف مواهب الفنون", "order": 10},
    {"id": "al_c3_s1_r011", "subcategory_id": "al_c3_s1", "name": "سجل الموهوبين في التقنية", "order": 11},
    {"id": "al_c3_s1_r012", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف مواهب المسرح", "order": 12},
    {"id": "al_c3_s1_r013", "subcategory_id": "al_c3_s1", "name": "توثيق اكتشاف مواهب الإنشاد", "order": 13},
    {"id": "al_c3_s1_r014", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف مواهب الخط", "order": 14},
    {"id": "al_c3_s1_r015", "subcategory_id": "al_c3_s1", "name": "سجل مواهب التصميم", "order": 15},
    {"id": "al_c3_s1_r016", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف مواهب التمثيل", "order": 16},
    {"id": "al_c3_s1_r017", "subcategory_id": "al_c3_s1", "name": "توثيق اكتشاف مواهب الإلقاء", "order": 17},
    {"id": "al_c3_s1_r018", "subcategory_id": "al_c3_s1", "name": "تقرير اكتشاف مواهب الابتكار", "order": 18},
    {"id": "al_c3_s1_r019", "subcategory_id": "al_c3_s1", "name": "سجل رعاية الموهوبين", "order": 19},
    {"id": "al_c3_s1_r020", "subcategory_id": "al_c3_s1", "name": "تقرير ختامي للمواهب", "order": 20},

    # ==================== al_c3_s2 (تنمية المهارات القيادية) ====================
    {"id": "al_c3_s2_r001", "subcategory_id": "al_c3_s2", "name": "تقرير عن برنامج تنمية القيادات الطلابية", "order": 1},
    {"id": "al_c3_s2_r002", "subcategory_id": "al_c3_s2", "name": "سجل تدريب الطلاب على القيادة", "order": 2},
    {"id": "al_c3_s2_r003", "subcategory_id": "al_c3_s2", "name": "تقرير عن إعداد قائد المستقبل", "order": 3},
    {"id": "al_c3_s2_r004", "subcategory_id": "al_c3_s2", "name": "توثيق مشاركة الطلاب في القيادة", "order": 4},
    {"id": "al_c3_s2_r005", "subcategory_id": "al_c3_s2", "name": "تقرير عن تطور مهارات القيادة", "order": 5},
    {"id": "al_c3_s2_r006", "subcategory_id": "al_c3_s2", "name": "تقرير ورش القيادة", "order": 6},
    {"id": "al_c3_s2_r007", "subcategory_id": "al_c3_s2", "name": "سجل تدريب مهارات التحدث", "order": 7},
    {"id": "al_c3_s2_r008", "subcategory_id": "al_c3_s2", "name": "تقرير تنمية مهارات اتخاذ القرار", "order": 8},
    {"id": "al_c3_s2_r009", "subcategory_id": "al_c3_s2", "name": "توثيق تدريب العمل الجماعي", "order": 9},
    {"id": "al_c3_s2_r010", "subcategory_id": "al_c3_s2", "name": "تقرير برنامج القيادة المدرسية", "order": 10},
    {"id": "al_c3_s2_r011", "subcategory_id": "al_c3_s2", "name": "سجل تدريب حل المشكلات", "order": 11},
    {"id": "al_c3_s2_r012", "subcategory_id": "al_c3_s2", "name": "تقرير تنمية مهارات التخطيط", "order": 12},
    {"id": "al_c3_s2_r013", "subcategory_id": "al_c3_s2", "name": "توثيق تدريب إدارة الوقت", "order": 13},
    {"id": "al_c3_s2_r014", "subcategory_id": "al_c3_s2", "name": "تقرير تنمية مهارات التفاوض", "order": 14},
    {"id": "al_c3_s2_r015", "subcategory_id": "al_c3_s2", "name": "سجل تدريب تحمل المسؤولية", "order": 15},
    {"id": "al_c3_s2_r016", "subcategory_id": "al_c3_s2", "name": "تقرير برنامج القيادة المجتمعية", "order": 16},
    {"id": "al_c3_s2_r017", "subcategory_id": "al_c3_s2", "name": "توثيق تدريب مهارات الإقناع", "order": 17},
    {"id": "al_c3_s2_r018", "subcategory_id": "al_c3_s2", "name": "تقرير تنمية مهارات الإشراف", "order": 18},
    {"id": "al_c3_s2_r019", "subcategory_id": "al_c3_s2", "name": "سجل تقييم القيادات الطلابية", "order": 19},
    {"id": "al_c3_s2_r020", "subcategory_id": "al_c3_s2", "name": "تقرير ختامي للقيادة", "order": 20},

    # ==================== al_c3_s3 (تنمية المهارات الفنية والثقافية) ====================
    {"id": "al_c3_s3_r001", "subcategory_id": "al_c3_s3", "name": "تقرير عن ورش تنمية الإبداع", "order": 1},
    {"id": "al_c3_s3_r002", "subcategory_id": "al_c3_s3", "name": "سجل مسابقات ثقافية", "order": 2},
    {"id": "al_c3_s3_r003", "subcategory_id": "al_c3_s3", "name": "تقرير عن إنتاج أعمال فنية", "order": 3},
    {"id": "al_c3_s3_r004", "subcategory_id": "al_c3_s3", "name": "توثيق معرض المواهب الفنية", "order": 4},
    {"id": "al_c3_s3_r005", "subcategory_id": "al_c3_s3", "name": "تقرير عن تطور المهارات الفنية", "order": 5},
    {"id": "al_c3_s3_r006", "subcategory_id": "al_c3_s3", "name": "تقرير ورش الرسم", "order": 6},
    {"id": "al_c3_s3_r007", "subcategory_id": "al_c3_s3", "name": "سجل ورش النحت", "order": 7},
    {"id": "al_c3_s3_r008", "subcategory_id": "al_c3_s3", "name": "تقرير ورش الفخار", "order": 8},
    {"id": "al_c3_s3_r009", "subcategory_id": "al_c3_s3", "name": "توثيق ورش الزخرفة", "order": 9},
    {"id": "al_c3_s3_r010", "subcategory_id": "al_c3_s3", "name": "تقرير ورش التصميم", "order": 10},
    {"id": "al_c3_s3_r011", "subcategory_id": "al_c3_s3", "name": "سجل مسابقات الفنون", "order": 11},
    {"id": "al_c3_s3_r012", "subcategory_id": "al_c3_s3", "name": "تقرير إنتاج أفلام قصيرة", "order": 12},
    {"id": "al_c3_s3_r013", "subcategory_id": "al_c3_s3", "name": "توثيق مسرحيات", "order": 13},
    {"id": "al_c3_s3_r014", "subcategory_id": "al_c3_s3", "name": "تقرير أندية القراءة", "order": 14},
    {"id": "al_c3_s3_r015", "subcategory_id": "al_c3_s3", "name": "سجل مسابقات الشعر", "order": 15},
    {"id": "al_c3_s3_r016", "subcategory_id": "al_c3_s3", "name": "تقرير ورش الكتابة الإبداعية", "order": 16},
    {"id": "al_c3_s3_r017", "subcategory_id": "al_c3_s3", "name": "توثيق أيام ثقافية", "order": 17},
    {"id": "al_c3_s3_r018", "subcategory_id": "al_c3_s3", "name": "تقرير زيارات للمتاحف", "order": 18},
    {"id": "al_c3_s3_r019", "subcategory_id": "al_c3_s3", "name": "سجل تقييم المهارات الفنية", "order": 19},
    {"id": "al_c3_s3_r020", "subcategory_id": "al_c3_s3", "name": "تقرير ختامي للفنون", "order": 20},

    # ==================== al_c3_s4 (تنمية المهارات الرياضية) ====================
    {"id": "al_c3_s4_r001", "subcategory_id": "al_c3_s4", "name": "تقرير عن الأنشطة الرياضية", "order": 1},
    {"id": "al_c3_s4_r002", "subcategory_id": "al_c3_s4", "name": "سجل مشاركة الطلاب في الرياضة", "order": 2},
    {"id": "al_c3_s4_r003", "subcategory_id": "al_c3_s4", "name": "تقرير عن دوري المدرسة", "order": 3},
    {"id": "al_c3_s4_r004", "subcategory_id": "al_c3_s4", "name": "توثيق اكتشاف المواهب الرياضية", "order": 4},
    {"id": "al_c3_s4_r005", "subcategory_id": "al_c3_s4", "name": "تقرير عن تحسين اللياقة البدنية", "order": 5},
    {"id": "al_c3_s4_r006", "subcategory_id": "al_c3_s4", "name": "تقرير تدريب كرة القدم", "order": 6},
    {"id": "al_c3_s4_r007", "subcategory_id": "al_c3_s4", "name": "سجل تدريب كرة السلة", "order": 7},
    {"id": "al_c3_s4_r008", "subcategory_id": "al_c3_s4", "name": "تقرير تدريب السباحة", "order": 8},
    {"id": "al_c3_s4_r009", "subcategory_id": "al_c3_s4", "name": "توثيق تدريب ألعاب القوى", "order": 9},
    {"id": "al_c3_s4_r010", "subcategory_id": "al_c3_s4", "name": "تقرير بطولة تنس الطاولة", "order": 10},
    {"id": "al_c3_s4_r011", "subcategory_id": "al_c3_s4", "name": "سجل تدريب الكرة الطائرة", "order": 11},
    {"id": "al_c3_s4_r012", "subcategory_id": "al_c3_s4", "name": "تقرير تدريب الشطرنج", "order": 12},
    {"id": "al_c3_s4_r013", "subcategory_id": "al_c3_s4", "name": "توثيق يوم رياضي", "order": 13},
    {"id": "al_c3_s4_r014", "subcategory_id": "al_c3_s4", "name": "تقرير مسابقات الجري", "order": 14},
    {"id": "al_c3_s4_r015", "subcategory_id": "al_c3_s4", "name": "سجل تدريب الجمباز", "order": 15},
    {"id": "al_c3_s4_r016", "subcategory_id": "al_c3_s4", "name": "تقرير تدريب الكاراتيه", "order": 16},
    {"id": "al_c3_s4_r017", "subcategory_id": "al_c3_s4", "name": "توثيق تدريب الريشة الطائرة", "order": 17},
    {"id": "al_c3_s4_r018", "subcategory_id": "al_c3_s4", "name": "تقرير تدريب كرة اليد", "order": 18},
    {"id": "al_c3_s4_r019", "subcategory_id": "al_c3_s4", "name": "سجل تقييم اللياقة", "order": 19},
    {"id": "al_c3_s4_r020", "subcategory_id": "al_c3_s4", "name": "تقرير ختامي للرياضة", "order": 20},

    # ==================== al_c3_s5 (تنمية المهارات الاجتماعية) ====================
    {"id": "al_c3_s5_r001", "subcategory_id": "al_c3_s5", "name": "تقرير عن ورش العمل الجماعي", "order": 1},
    {"id": "al_c3_s5_r002", "subcategory_id": "al_c3_s5", "name": "سجل أنشطة التعاون", "order": 2},
    {"id": "al_c3_s5_r003", "subcategory_id": "al_c3_s5", "name": "تقرير عن برامج التواصل", "order": 3},
    {"id": "al_c3_s5_r004", "subcategory_id": "al_c3_s5", "name": "توثيق مبادرات خدمة المجتمع", "order": 4},
    {"id": "al_c3_s5_r005", "subcategory_id": "al_c3_s5", "name": "تقرير عن تطور المهارات الاجتماعية", "order": 5},
    {"id": "al_c3_s5_r006", "subcategory_id": "al_c3_s5", "name": "تقرير ورش التواصل", "order": 6},
    {"id": "al_c3_s5_r007", "subcategory_id": "al_c3_s5", "name": "سجل أنشطة التعارف", "order": 7},
    {"id": "al_c3_s5_r008", "subcategory_id": "al_c3_s5", "name": "تقرير برنامج الذكاء العاطفي", "order": 8},
    {"id": "al_c3_s5_r009", "subcategory_id": "al_c3_s5", "name": "توثيق مبادرات التطوع", "order": 9},
    {"id": "al_c3_s5_r010", "subcategory_id": "al_c3_s5", "name": "تقرير ورش حل النزاعات", "order": 10},
    {"id": "al_c3_s5_r011", "subcategory_id": "al_c3_s5", "name": "سجل أنشطة التعاطف", "order": 11},
    {"id": "al_c3_s5_r012", "subcategory_id": "al_c3_s5", "name": "تقرير برنامج الصداقة", "order": 12},
    {"id": "al_c3_s5_r013", "subcategory_id": "al_c3_s5", "name": "توثيق أنشطة الاندماج", "order": 13},
    {"id": "al_c3_s5_r014", "subcategory_id": "al_c3_s5", "name": "تقرير ورش العمل الجماعي", "order": 14},
    {"id": "al_c3_s5_r015", "subcategory_id": "al_c3_s5", "name": "سجل مبادرات العطاء", "order": 15},
    {"id": "al_c3_s5_r016", "subcategory_id": "al_c3_s5", "name": "تقرير برنامج القيم", "order": 16},
    {"id": "al_c3_s5_r017", "subcategory_id": "al_c3_s5", "name": "توثيق أنشطة الاحترام", "order": 17},
    {"id": "al_c3_s5_r018", "subcategory_id": "al_c3_s5", "name": "تقرير ورش القيادة الاجتماعية", "order": 18},
    {"id": "al_c3_s5_r019", "subcategory_id": "al_c3_s5", "name": "سجل تقييم المهارات الاجتماعية", "order": 19},
    {"id": "al_c3_s5_r020", "subcategory_id": "al_c3_s5", "name": "تقرير ختامي للمهارات", "order": 20},

    # ==================== al_c4_s1 (المشاركة في المسابقات الخارجية) ====================
    {"id": "al_c4_s1_r001", "subcategory_id": "al_c4_s1", "name": "تقرير عن المشاركة في مسابقة الإبداع", "order": 1},
    {"id": "al_c4_s1_r002", "subcategory_id": "al_c4_s1", "name": "سجل المشاركات الخارجية", "order": 2},
    {"id": "al_c4_s1_r003", "subcategory_id": "al_c4_s1", "name": "تقرير عن نتائج المشاركات", "order": 3},
    {"id": "al_c4_s1_r004", "subcategory_id": "al_c4_s1", "name": "توثيق شهادات التكريم", "order": 4},
    {"id": "al_c4_s1_r005", "subcategory_id": "al_c4_s1", "name": "تقرير عن أثر المشاركات", "order": 5},
    {"id": "al_c4_s1_r006", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في مسابقة الرياضيات", "order": 6},
    {"id": "al_c4_s1_r007", "subcategory_id": "al_c4_s1", "name": "سجل المشاركة في مسابقة العلوم", "order": 7},
    {"id": "al_c4_s1_r008", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في مسابقة الروبوت", "order": 8},
    {"id": "al_c4_s1_r009", "subcategory_id": "al_c4_s1", "name": "توثيق المشاركة في مسابقة القرآن", "order": 9},
    {"id": "al_c4_s1_r010", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في مسابقة الخطابة", "order": 10},
    {"id": "al_c4_s1_r011", "subcategory_id": "al_c4_s1", "name": "سجل المشاركة في مسابقة الرسم", "order": 11},
    {"id": "al_c4_s1_r012", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في مسابقة التصوير", "order": 12},
    {"id": "al_c4_s1_r013", "subcategory_id": "al_c4_s1", "name": "توثيق المشاركة في مسابقة الشعر", "order": 13},
    {"id": "al_c4_s1_r014", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في مسابقة القصة", "order": 14},
    {"id": "al_c4_s1_r015", "subcategory_id": "al_c4_s1", "name": "سجل المشاركة في مسابقة الإلقاء", "order": 15},
    {"id": "al_c4_s1_r016", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في أولمبياد", "order": 16},
    {"id": "al_c4_s1_r017", "subcategory_id": "al_c4_s1", "name": "توثيق المشاركة في مسابقة اللياقة", "order": 17},
    {"id": "al_c4_s1_r018", "subcategory_id": "al_c4_s1", "name": "تقرير المشاركة في مسابقة الفنون", "order": 18},
    {"id": "al_c4_s1_r019", "subcategory_id": "al_c4_s1", "name": "سجل تقييم المشاركات", "order": 19},
    {"id": "al_c4_s1_r020", "subcategory_id": "al_c4_s1", "name": "تقرير ختامي للمسابقات الخارجية", "order": 20},

    # ==================== al_c4_s2 (تنظيم زيارات تبادلية) ====================
    {"id": "al_c4_s2_r001", "subcategory_id": "al_c4_s2", "name": "تقرير عن زيارة مدرسة أخرى", "order": 1},
    {"id": "al_c4_s2_r002", "subcategory_id": "al_c4_s2", "name": "سجل تبادل الزيارات", "order": 2},
    {"id": "al_c4_s2_r003", "subcategory_id": "al_c4_s2", "name": "تقرير عن استقبال وفود طلابية", "order": 3},
    {"id": "al_c4_s2_r004", "subcategory_id": "al_c4_s2", "name": "توثيق تبادل الخبرات", "order": 4},
    {"id": "al_c4_s2_r005", "subcategory_id": "al_c4_s2", "name": "تقرير عن استفادة الطلاب", "order": 5},
    {"id": "al_c4_s2_r006", "subcategory_id": "al_c4_s2", "name": "تقرير زيارة لمدرسة متميزة", "order": 6},
    {"id": "al_c4_s2_r007", "subcategory_id": "al_c4_s2", "name": "سجل زيارة لمدرسة أجنبية", "order": 7},
    {"id": "al_c4_s2_r008", "subcategory_id": "al_c4_s2", "name": "تقرير استقبال طلاب من مدرسة أخرى", "order": 8},
    {"id": "al_c4_s2_r009", "subcategory_id": "al_c4_s2", "name": "توثيق ورش مشتركة مع مدرسة", "order": 9},
    {"id": "al_c4_s2_r010", "subcategory_id": "al_c4_s2", "name": "تقرير زيارة لمركز تدريب", "order": 10},
    {"id": "al_c4_s2_r011", "subcategory_id": "al_c4_s2", "name": "سجل تبادل زيارات المعلمين", "order": 11},
    {"id": "al_c4_s2_r012", "subcategory_id": "al_c4_s2", "name": "تقرير زيارة لمكتبة عامة", "order": 12},
    {"id": "al_c4_s2_r013", "subcategory_id": "al_c4_s2", "name": "توثيق تبادل الخبرات الإدارية", "order": 13},
    {"id": "al_c4_s2_r014", "subcategory_id": "al_c4_s2", "name": "تقرير زيارة لجامعة", "order": 14},
    {"id": "al_c4_s2_r015", "subcategory_id": "al_c4_s2", "name": "سجل تبادل زيارات الطلاب", "order": 15},
    {"id": "al_c4_s2_r016", "subcategory_id": "al_c4_s2", "name": "تقرير زيارة لمتحف", "order": 16},
    {"id": "al_c4_s2_r017", "subcategory_id": "al_c4_s2", "name": "توثيق استقبال وفد أجنبي", "order": 17},
    {"id": "al_c4_s2_r018", "subcategory_id": "al_c4_s2", "name": "تقرير زيارة لمعرض", "order": 18},
    {"id": "al_c4_s2_r019", "subcategory_id": "al_c4_s2", "name": "سجل تقييم الزيارات", "order": 19},
    {"id": "al_c4_s2_r020", "subcategory_id": "al_c4_s2", "name": "تقرير ختامي للزيارات", "order": 20},

    # ==================== al_c4_s3 (المشاركة في الفعاليات المجتمعية) ====================
    {"id": "al_c4_s3_r001", "subcategory_id": "al_c4_s3", "name": "تقرير عن مشاركة في مهرجان الحي", "order": 1},
    {"id": "al_c4_s3_r002", "subcategory_id": "al_c4_s3", "name": "سجل المشاركة في الفعاليات المجتمعية", "order": 2},
    {"id": "al_c4_s3_r003", "subcategory_id": "al_c4_s3", "name": "تقرير عن تنظيم حملة تطوعية", "order": 3},
    {"id": "al_c4_s3_r004", "subcategory_id": "al_c4_s3", "name": "توثيق شراكة مع مؤسسة", "order": 4},
    {"id": "al_c4_s3_r005", "subcategory_id": "al_c4_s3", "name": "تقرير عن أثر المشاركة المجتمعية", "order": 5},
    {"id": "al_c4_s3_r006", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في يوم البيئة", "order": 6},
    {"id": "al_c4_s3_r007", "subcategory_id": "al_c4_s3", "name": "سجل المشاركة في حملة نظافة", "order": 7},
    {"id": "al_c4_s3_r008", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في مهرجان تسوق", "order": 8},
    {"id": "al_c4_s3_r009", "subcategory_id": "al_c4_s3", "name": "توثيق المشاركة في معرض خيري", "order": 9},
    {"id": "al_c4_s3_r010", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في فعالية صحية", "order": 10},
    {"id": "al_c4_s3_r011", "subcategory_id": "al_c4_s3", "name": "سجل المشاركة في يوم اليتيم", "order": 11},
    {"id": "al_c4_s3_r012", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في حملة تبرعات", "order": 12},
    {"id": "al_c4_s3_r013", "subcategory_id": "al_c4_s3", "name": "توثيق المشاركة في مهرجان رياضي", "order": 13},
    {"id": "al_c4_s3_r014", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في فعالية ثقافية", "order": 14},
    {"id": "al_c4_s3_r015", "subcategory_id": "al_c4_s3", "name": "سجل المشاركة في يوم المهنة", "order": 15},
    {"id": "al_c4_s3_r016", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في معرض الكتاب", "order": 16},
    {"id": "al_c4_s3_r017", "subcategory_id": "al_c4_s3", "name": "توثيق المشاركة في مهرجان التراث", "order": 17},
    {"id": "al_c4_s3_r018", "subcategory_id": "al_c4_s3", "name": "تقرير المشاركة في حملة توعية", "order": 18},
    {"id": "al_c4_s3_r019", "subcategory_id": "al_c4_s3", "name": "سجل تقييم المشاركات المجتمعية", "order": 19},
    {"id": "al_c4_s3_r020", "subcategory_id": "al_c4_s3", "name": "تقرير ختامي للمشاركات المجتمعية", "order": 20},

    # ==================== al_c4_s4 (التنسيق مع أندية الحي) ====================
    {"id": "al_c4_s4_r001", "subcategory_id": "al_c4_s4", "name": "تقرير عن التنسيق مع نادي الحي", "order": 1},
    {"id": "al_c4_s4_r002", "subcategory_id": "al_c4_s4", "name": "سجل اتفاقيات الشراكة", "order": 2},
    {"id": "al_c4_s4_r003", "subcategory_id": "al_c4_s4", "name": "تقرير عن أنشطة مشتركة مع النادي", "order": 3},
    {"id": "al_c4_s4_r004", "subcategory_id": "al_c4_s4", "name": "توثيق استفادة الطلاب من النادي", "order": 4},
    {"id": "al_c4_s4_r005", "subcategory_id": "al_c4_s4", "name": "تقرير عن استمرارية الشراكة", "order": 5},
    {"id": "al_c4_s4_r006", "subcategory_id": "al_c4_s4", "name": "تقرير التنسيق مع نادي رياضي", "order": 6},
    {"id": "al_c4_s4_r007", "subcategory_id": "al_c4_s4", "name": "سجل التنسيق مع نادي ثقافي", "order": 7},
    {"id": "al_c4_s4_r008", "subcategory_id": "al_c4_s4", "name": "تقرير أنشطة مشتركة مع نادي", "order": 8},
    {"id": "al_c4_s4_r009", "subcategory_id": "al_c4_s4", "name": "توثيق استخدام مرافق النادي", "order": 9},
    {"id": "al_c4_s4_r010", "subcategory_id": "al_c4_s4", "name": "تقرير مشاركة النادي في المدرسة", "order": 10},
    {"id": "al_c4_s4_r011", "subcategory_id": "al_c4_s4", "name": "سجل اجتماعات التنسيق مع النادي", "order": 11},
    {"id": "al_c4_s4_r012", "subcategory_id": "al_c4_s4", "name": "تقرير برامج تدريبية في النادي", "order": 12},
    {"id": "al_c4_s4_r013", "subcategory_id": "al_c4_s4", "name": "توثيق مسابقات مع النادي", "order": 13},
    {"id": "al_c4_s4_r014", "subcategory_id": "al_c4_s4", "name": "تقرير استضافة النادي للطلاب", "order": 14},
    {"id": "al_c4_s4_r015", "subcategory_id": "al_c4_s4", "name": "سجل تبادل الزيارات مع النادي", "order": 15},
    {"id": "al_c4_s4_r016", "subcategory_id": "al_c4_s4", "name": "تقرير دعم النادي للأنشطة", "order": 16},
    {"id": "al_c4_s4_r017", "subcategory_id": "al_c4_s4", "name": "توثيق توقيع مذكرات تفاهم", "order": 17},
    {"id": "al_c4_s4_r018", "subcategory_id": "al_c4_s4", "name": "تقرير استمرارية التعاون", "order": 18},
    {"id": "al_c4_s4_r019", "subcategory_id": "al_c4_s4", "name": "سجل تقييم الشراكة", "order": 19},
    {"id": "al_c4_s4_r020", "subcategory_id": "al_c4_s4", "name": "تقرير ختامي للتنسيق مع النادي", "order": 20},

    # ==================== al_c4_s5 (المشاركة في المبادرات الوطنية) ====================
    {"id": "al_c4_s5_r001", "subcategory_id": "al_c4_s5", "name": "تقرير عن المشاركة في مبادرات وطنية", "order": 1},
    {"id": "al_c4_s5_r002", "subcategory_id": "al_c4_s5", "name": "سجل تفعيل اليوم الوطني", "order": 2},
    {"id": "al_c4_s5_r003", "subcategory_id": "al_c4_s5", "name": "تقرير عن مسيرة الولاء", "order": 3},
    {"id": "al_c4_s5_r004", "subcategory_id": "al_c4_s5", "name": "توثيق تفعيل رؤية 2030", "order": 4},
    {"id": "al_c4_s5_r005", "subcategory_id": "al_c4_s5", "name": "تقرير عن أثر المبادرات الوطنية", "order": 5},
    {"id": "al_c4_s5_r006", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة وطنية", "order": 6},
    {"id": "al_c4_s5_r007", "subcategory_id": "al_c4_s5", "name": "سجل تفعيل يوم التأسيس", "order": 7},
    {"id": "al_c4_s5_r008", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة بيئية", "order": 8},
    {"id": "al_c4_s5_r009", "subcategory_id": "al_c4_s5", "name": "توثيق المشاركة في حملة وطنية", "order": 9},
    {"id": "al_c4_s5_r010", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة تطوعية", "order": 10},
    {"id": "al_c4_s5_r011", "subcategory_id": "al_c4_s5", "name": "سجل تفعيل اليوم العالمي للغة العربية", "order": 11},
    {"id": "al_c4_s5_r012", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة صحية", "order": 12},
    {"id": "al_c4_s5_r013", "subcategory_id": "al_c4_s5", "name": "توثيق المشاركة في مبادرة أمنية", "order": 13},
    {"id": "al_c4_s5_r014", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة تعليمية", "order": 14},
    {"id": "al_c4_s5_r015", "subcategory_id": "al_c4_s5", "name": "سجل تفعيل اليوم العالمي للمعلم", "order": 15},
    {"id": "al_c4_s5_r016", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة ثقافية", "order": 16},
    {"id": "al_c4_s5_r017", "subcategory_id": "al_c4_s5", "name": "توثيق المشاركة في مبادرة رياضية", "order": 17},
    {"id": "al_c4_s5_r018", "subcategory_id": "al_c4_s5", "name": "تقرير المشاركة في مبادرة اجتماعية", "order": 18},
    {"id": "al_c4_s5_r019", "subcategory_id": "al_c4_s5", "name": "سجل تقييم المبادرات", "order": 19},
    {"id": "al_c4_s5_r020", "subcategory_id": "al_c4_s5", "name": "تقرير ختامي للمبادرات", "order": 20},

    # ==================== al_c5_s1 (توثيق الأنشطة) ====================
    {"id": "al_c5_s1_r001", "subcategory_id": "al_c5_s1", "name": "تقرير عن توثيق الأنشطة بالصور", "order": 1},
    {"id": "al_c5_s1_r002", "subcategory_id": "al_c5_s1", "name": "سجل أرشفة التقارير", "order": 2},
    {"id": "al_c5_s1_r003", "subcategory_id": "al_c5_s1", "name": "تقرير عن إصدار مجلة النشاط", "order": 3},
    {"id": "al_c5_s1_r004", "subcategory_id": "al_c5_s1", "name": "توثيق فيديوهات الأنشطة", "order": 4},
    {"id": "al_c5_s1_r005", "subcategory_id": "al_c5_s1", "name": "تقرير عن حفظ الوثائق", "order": 5},
    {"id": "al_c5_s1_r006", "subcategory_id": "al_c5_s1", "name": "تقرير توثيق الأنشطة إلكترونياً", "order": 6},
    {"id": "al_c5_s1_r007", "subcategory_id": "al_c5_s1", "name": "سجل أرشفة الصور", "order": 7},
    {"id": "al_c5_s1_r008", "subcategory_id": "al_c5_s1", "name": "تقرير إعداد ألبوم الأنشطة", "order": 8},
    {"id": "al_c5_s1_r009", "subcategory_id": "al_c5_s1", "name": "توثيق الأنشطة في الموقع", "order": 9},
    {"id": "al_c5_s1_r010", "subcategory_id": "al_c5_s1", "name": "تقرير توثيق الأنشطة في وسائل التواصل", "order": 10},
    {"id": "al_c5_s1_r011", "subcategory_id": "al_c5_s1", "name": "سجل أرشفة الفيديوهات", "order": 11},
    {"id": "al_c5_s1_r012", "subcategory_id": "al_c5_s1", "name": "تقرير إنتاج تقارير مصورة", "order": 12},
    {"id": "al_c5_s1_r013", "subcategory_id": "al_c5_s1", "name": "توثيق شهادات المشاركة", "order": 13},
    {"id": "al_c5_s1_r014", "subcategory_id": "al_c5_s1", "name": "تقرير توثيق قصص النجاح", "order": 14},
    {"id": "al_c5_s1_r015", "subcategory_id": "al_c5_s1", "name": "سجل أرشفة المطبوعات", "order": 15},
    {"id": "al_c5_s1_r016", "subcategory_id": "al_c5_s1", "name": "تقرير توثيق الأنشطة في مجلة المدرسة", "order": 16},
    {"id": "al_c5_s1_r017", "subcategory_id": "al_c5_s1", "name": "توثيق الأنشطة في منصة المدرسة", "order": 17},
    {"id": "al_c5_s1_r018", "subcategory_id": "al_c5_s1", "name": "تقرير أرشفة التقارير السنوية", "order": 18},
    {"id": "al_c5_s1_r019", "subcategory_id": "al_c5_s1", "name": "سجل توثيق الإنجازات", "order": 19},
    {"id": "al_c5_s1_r020", "subcategory_id": "al_c5_s1", "name": "تقرير ختامي للتوثيق", "order": 20},

    # ==================== al_c5_s2 (قياس أثر الأنشطة) ====================
    {"id": "al_c5_s2_r001", "subcategory_id": "al_c5_s2", "name": "تقرير عن استبيان رضا الطلاب", "order": 1},
    {"id": "al_c5_s2_r002", "subcategory_id": "al_c5_s2", "name": "سجل قياس أثر الأنشطة", "order": 2},
    {"id": "al_c5_s2_r003", "subcategory_id": "al_c5_s2", "name": "تقرير عن تحسين المهارات بعد الأنشطة", "order": 3},
    {"id": "al_c5_s2_r004", "subcategory_id": "al_c5_s2", "name": "توثيق قصص نجاح", "order": 4},
    {"id": "al_c5_s2_r005", "subcategory_id": "al_c5_s2", "name": "تقرير عن أثر الأنشطة على التحصيل", "order": 5},
    {"id": "al_c5_s2_r006", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على السلوك", "order": 6},
    {"id": "al_c5_s2_r007", "subcategory_id": "al_c5_s2", "name": "سجل استبيان أولياء الأمور", "order": 7},
    {"id": "al_c5_s2_r008", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على المهارات", "order": 8},
    {"id": "al_c5_s2_r009", "subcategory_id": "al_c5_s2", "name": "توثيق تحليل نتائج الاستبيانات", "order": 9},
    {"id": "al_c5_s2_r010", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على القيم", "order": 10},
    {"id": "al_c5_s2_r011", "subcategory_id": "al_c5_s2", "name": "سجل قياس أثر الأنشطة على التحصيل", "order": 11},
    {"id": "al_c5_s2_r012", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على الموهوبين", "order": 12},
    {"id": "al_c5_s2_r013", "subcategory_id": "al_c5_s2", "name": "توثيق قياس أثر الأنشطة على الانتماء", "order": 13},
    {"id": "al_c5_s2_r014", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على المجتمع", "order": 14},
    {"id": "al_c5_s2_r015", "subcategory_id": "al_c5_s2", "name": "سجل استبيان المعلمين", "order": 15},
    {"id": "al_c5_s2_r016", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على البيئة", "order": 16},
    {"id": "al_c5_s2_r017", "subcategory_id": "al_c5_s2", "name": "توثيق قياس أثر الأنشطة على الصحة", "order": 17},
    {"id": "al_c5_s2_r018", "subcategory_id": "al_c5_s2", "name": "تقرير قياس أثر الأنشطة على الابتكار", "order": 18},
    {"id": "al_c5_s2_r019", "subcategory_id": "al_c5_s2", "name": "سجل تحليل الأثر", "order": 19},
    {"id": "al_c5_s2_r020", "subcategory_id": "al_c5_s2", "name": "تقرير ختامي لقياس الأثر", "order": 20},

    # ==================== al_c5_s3 (إعداد تقارير ختامية) ====================
    {"id": "al_c5_s3_r001", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي عن النشاط", "order": 1},
    {"id": "al_c5_s3_r002", "subcategory_id": "al_c5_s3", "name": "سجل إحصاءات المشاركة", "order": 2},
    {"id": "al_c5_s3_r003", "subcategory_id": "al_c5_s3", "name": "تقرير عن إنجازات النشاط", "order": 3},
    {"id": "al_c5_s3_r004", "subcategory_id": "al_c5_s3", "name": "توثيق التوصيات", "order": 4},
    {"id": "al_c5_s3_r005", "subcategory_id": "al_c5_s3", "name": "تقرير عن خطة العام القادم", "order": 5},
    {"id": "al_c5_s3_r006", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للفصل الدراسي", "order": 6},
    {"id": "al_c5_s3_r007", "subcategory_id": "al_c5_s3", "name": "سجل التقرير الختامي للأنشطة", "order": 7},
    {"id": "al_c5_s3_r008", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للأندية", "order": 8},
    {"id": "al_c5_s3_r009", "subcategory_id": "al_c5_s3", "name": "توثيق التقرير الختامي للرحلات", "order": 9},
    {"id": "al_c5_s3_r010", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للمسابقات", "order": 10},
    {"id": "al_c5_s3_r011", "subcategory_id": "al_c5_s3", "name": "سجل التقرير الختامي للورش", "order": 11},
    {"id": "al_c5_s3_r012", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للفعاليات", "order": 12},
    {"id": "al_c5_s3_r013", "subcategory_id": "al_c5_s3", "name": "توثيق التقرير الختامي للمواهب", "order": 13},
    {"id": "al_c5_s3_r014", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للقيادة", "order": 14},
    {"id": "al_c5_s3_r015", "subcategory_id": "al_c5_s3", "name": "سجل التقرير الختامي للمشاركات", "order": 15},
    {"id": "al_c5_s3_r016", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للزيارات", "order": 16},
    {"id": "al_c5_s3_r017", "subcategory_id": "al_c5_s3", "name": "توثيق التقرير الختامي للمبادرات", "order": 17},
    {"id": "al_c5_s3_r018", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي للتوثيق", "order": 18},
    {"id": "al_c5_s3_r019", "subcategory_id": "al_c5_s3", "name": "سجل التقرير الختامي للأثر", "order": 19},
    {"id": "al_c5_s3_r020", "subcategory_id": "al_c5_s3", "name": "تقرير ختامي شامل", "order": 20},

    # ==================== al_c5_s4 (تحليل المشاركات) ====================
    {"id": "al_c5_s4_r001", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركات", "order": 1},
    {"id": "al_c5_s4_r002", "subcategory_id": "al_c5_s4", "name": "سجل نسب المشاركة", "order": 2},
    {"id": "al_c5_s4_r003", "subcategory_id": "al_c5_s4", "name": "تقرير عن الفئات المستهدفة", "order": 3},
    {"id": "al_c5_s4_r004", "subcategory_id": "al_c5_s4", "name": "توثيق تطور المشاركة", "order": 4},
    {"id": "al_c5_s4_r005", "subcategory_id": "al_c5_s4", "name": "تقرير عن توصيات التحسين", "order": 5},
    {"id": "al_c5_s4_r006", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة في الأنشطة", "order": 6},
    {"id": "al_c5_s4_r007", "subcategory_id": "al_c5_s4", "name": "سجل تحليل المشاركة حسب المرحلة", "order": 7},
    {"id": "al_c5_s4_r008", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة في الأندية", "order": 8},
    {"id": "al_c5_s4_r009", "subcategory_id": "al_c5_s4", "name": "توثيق تحليل المشاركة في المسابقات", "order": 9},
    {"id": "al_c5_s4_r010", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة في الرحلات", "order": 10},
    {"id": "al_c5_s4_r011", "subcategory_id": "al_c5_s4", "name": "سجل تحليل المشاركة في الورش", "order": 11},
    {"id": "al_c5_s4_r012", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة في المبادرات", "order": 12},
    {"id": "al_c5_s4_r013", "subcategory_id": "al_c5_s4", "name": "توثيق تحليل المشاركة في الزيارات", "order": 13},
    {"id": "al_c5_s4_r014", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة في الفعاليات", "order": 14},
    {"id": "al_c5_s4_r015", "subcategory_id": "al_c5_s4", "name": "سجل تحليل المشاركة حسب الجنس", "order": 15},
    {"id": "al_c5_s4_r016", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة حسب الصف", "order": 16},
    {"id": "al_c5_s4_r017", "subcategory_id": "al_c5_s4", "name": "توثيق تحليل المشاركة في الأنشطة الخارجية", "order": 17},
    {"id": "al_c5_s4_r018", "subcategory_id": "al_c5_s4", "name": "تقرير تحليل المشاركة في الأسبوع الثقافي", "order": 18},
    {"id": "al_c5_s4_r019", "subcategory_id": "al_c5_s4", "name": "سجل تحليل المشاركة في اليوم المفتوح", "order": 19},
    {"id": "al_c5_s4_r020", "subcategory_id": "al_c5_s4", "name": "تقرير ختامي لتحليل المشاركات", "order": 20},

    # ==================== al_c5_s5 (رفع التقارير للإدارة) ====================
    {"id": "al_c5_s5_r001", "subcategory_id": "al_c5_s5", "name": "تقرير رفع للإدارة عن النشاط", "order": 1},
    {"id": "al_c5_s5_r002", "subcategory_id": "al_c5_s5", "name": "سجل التقارير المرفوعة", "order": 2},
    {"id": "al_c5_s5_r003", "subcategory_id": "al_c5_s5", "name": "تقرير عن اجتماعات عرض النتائج", "order": 3},
    {"id": "al_c5_s5_r004", "subcategory_id": "al_c5_s5", "name": "توثيق متابعة توصيات الإدارة", "order": 4},
    {"id": "al_c5_s5_r005", "subcategory_id": "al_c5_s5", "name": "تقرير عن استفادة الإدارة من التقارير", "order": 5},
    {"id": "al_c5_s5_r006", "subcategory_id": "al_c5_s5", "name": "تقرير رفع خطة النشاط للإدارة", "order": 6},
    {"id": "al_c5_s5_r007", "subcategory_id": "al_c5_s5", "name": "سجل رفع تقارير الأندية", "order": 7},
    {"id": "al_c5_s5_r008", "subcategory_id": "al_c5_s5", "name": "تقرير رفع تقارير الرحلات للإدارة", "order": 8},
    {"id": "al_c5_s5_r009", "subcategory_id": "al_c5_s5", "name": "توثيق رفع تقارير المسابقات", "order": 9},
    {"id": "al_c5_s5_r010", "subcategory_id": "al_c5_s5", "name": "تقرير رفع تقارير الورش للإدارة", "order": 10},
    {"id": "al_c5_s5_r011", "subcategory_id": "al_c5_s5", "name": "سجل رفع تقارير المواهب", "order": 11},
    {"id": "al_c5_s5_r012", "subcategory_id": "al_c5_s5", "name": "تقرير رفع تقارير المشاركات الخارجية", "order": 12},
    {"id": "al_c5_s5_r013", "subcategory_id": "al_c5_s5", "name": "توثيق رفع تقارير الزيارات", "order": 13},
    {"id": "al_c5_s5_r014", "subcategory_id": "al_c5_s5", "name": "تقرير رفع تقارير المبادرات", "order": 14},
    {"id": "al_c5_s5_r015", "subcategory_id": "al_c5_s5", "name": "سجل رفع تقارير التوثيق", "order": 15},
    {"id": "al_c5_s5_r016", "subcategory_id": "al_c5_s5", "name": "تقرير رفع تقارير قياس الأثر", "order": 16},
    {"id": "al_c5_s5_r017", "subcategory_id": "al_c5_s5", "name": "توثيق رفع التقارير الختامية", "order": 17},
    {"id": "al_c5_s5_r018", "subcategory_id": "al_c5_s5", "name": "تقرير رفع تحليل المشاركات للإدارة", "order": 18},
    {"id": "al_c5_s5_r019", "subcategory_id": "al_c5_s5", "name": "سجل متابعة اعتماد الإدارة", "order": 19},
    {"id": "al_c5_s5_r020", "subcategory_id": "al_c5_s5", "name": "تقرير ختامي لرفع التقارير", "order": 20},
]

ACTIVITY_LEADER_PROMPT_TEMPLATE = """أنت رائد نشاط طلابي مسؤول عن تخطيط وتنفيذ البرامج والفعاليات الطلابية وفق معايير النشاط المعتمدة.

المطلوب:
- عرض معيار الأداء الوظيفي.
- عرض التصنيف الفرعي.
- كتابة تقرير مهني يوضح كيفية تنفيذ الأنشطة المرتبطة بهذا التصنيف.

التقرير المطلوب: "{report_name}"
وهو يندرج تحت التصنيف الفرعي: "{subcategory_name}"
ضمن المعيار التربوي: "{criterion_name}"

{subject_line}
{lesson_line}
{grade_line}
{target_line}
{place_line}
{count_line}

ضوابط الكتابة:
- لغة تربوية رسمية.
- إبراز التخطيط المسبق للبرامج وبنائها على احتياج المدرسة.
- توضيح آلية التنفيذ وتنظيم الفعاليات.
- بيان دور الأنشطة في تنمية مهارات الطلبة وقيمهم.
- الإشارة إلى قياس الأثر وتحليل نتائج المشاركة.
- إبراز الشراكات المجتمعية والمشاركات الخارجية إن وجدت.
- توضيح دور التحفيز واكتشاف المواهب.
- صياغة واقعية تطبيقية من 5–7 أسطر.

دورك كرائد النشاط

1. تنمية مهارات الطلاب القيادية والاجتماعية من خلال برامج نشاط هادفة تعزز الانتماء المدرسي وتدعم التكامل بين التعلم الصفي واللاصفّي.

2. صممت برنامجًا نشاطيًا يعزز روح الفريق والمسؤولية لدى الطلاب ويربط مهاراتهم العملية بالقيم التربوية الداعمة للتعلم.

3. شكلت فرق عمل طلابية، وحددت أدوارًا واضحة، ونظمت أنشطة تطبيقية داخل مرافق المدرسة، وتابعت الأداء لضمان تحقيق الأهداف التربوية.

4. استخدمت التعلم بالمشروعات، والعمل التعاوني، والتكليفات العملية، والتحفيز المعنوي لتعزيز مشاركة الطلاب الفاعلة.

5. أظهر الطلاب تفاعلًا مرتفعًا وتحسنًا في مهارات التواصل وتحمل المسؤولية، وانعكس ذلك إيجابًا على سلوكهم داخل الصف.

6. الحاجة إلى تنويع مجالات الأنشطة لتناسب ميول جميع الطلاب، وتطوير أدوات تقويم أثر النشاط على التحصيل والسلوك.

7. أوصي ببناء خطة نشاط سنوية متدرجة، وتعزيز تكامل الأنشطة مع أهداف المدرسة، وتوسيع الشراكات لدعم استدامة البرامج الطلابية.
**الحقول المطلوبة:**
1. الهدف التربوي
2. نبذة مختصرة
3. إجراءات التنفيذ
4. الاستراتيجيات المستخدمة
5. نقاط القوة
6. نقاط التحسين
7. التوصيات

يرجى تقديم الإجابة باللغة العربية الفصحى، وتنظيمها بحيث يكون كل حقل في سطر منفصل يبدأ برقمه فقط دون ذكر العنوان."""