# health_guide_prompt_updated.py
# -*- coding: utf-8 -*-

# قائمة المعايير (تم إزالة خاصية weight)
HG_CRITERIA = [
    {"id": "hg_c1", "name": "تنفيذ البرامج الصحية المدرسية", "order": 1},
    {"id": "hg_c2", "name": "رصد الحالات الصحية ومتابعتها", "order": 2},
    {"id": "hg_c3", "name": "تعزيز البيئة الصحية في المدرسة", "order": 3},
    {"id": "hg_c4", "name": "التوعية الصحية للطلاب والمجتمع", "order": 4},
    {"id": "hg_c5", "name": "التنسيق مع الجهات الصحية", "order": 5}
]

# التصنيفات الفرعية (كما هي)
HG_SUBCATEGORIES = [
    # hg_c1
    {"id": "hg_c1_s1", "criterion_id": "hg_c1", "name": "تنظيم برامج التطعيمات", "order": 1},
    {"id": "hg_c1_s2", "criterion_id": "hg_c1", "name": "تنفيذ برامج الكشف المبكر", "order": 2},
    {"id": "hg_c1_s3", "criterion_id": "hg_c1", "name": "متابعة النظافة العامة والنظافة الشخصية", "order": 3},
    {"id": "hg_c1_s4", "criterion_id": "hg_c1", "name": "إدارة عيادة المدرسة", "order": 4},
    {"id": "hg_c1_s5", "criterion_id": "hg_c1", "name": "تنظيم حملات التبرع بالدم", "order": 5},
    # hg_c2
    {"id": "hg_c2_s1", "criterion_id": "hg_c2", "name": "رصد حالات الأمراض المعدية", "order": 1},
    {"id": "hg_c2_s2", "criterion_id": "hg_c2", "name": "متابعة الطلاب ذوي الأمراض المزمنة", "order": 2},
    {"id": "hg_c2_s3", "criterion_id": "hg_c2", "name": "تقديم الإسعافات الأولية", "order": 3},
    {"id": "hg_c2_s4", "criterion_id": "hg_c2", "name": "تحويل الحالات للرعاية الصحية", "order": 4},
    {"id": "hg_c2_s5", "criterion_id": "hg_c2", "name": "توثيق السجلات الصحية", "order": 5},
    # hg_c3
    {"id": "hg_c3_s1", "criterion_id": "hg_c3", "name": "الإشراف على نظافة المرافق", "order": 1},
    {"id": "hg_c3_s2", "criterion_id": "hg_c3", "name": "متابعة سلامة الأغذية في المقصف", "order": 2},
    {"id": "hg_c3_s3", "criterion_id": "hg_c3", "name": "التأكد من تهوية الفصول", "order": 3},
    {"id": "hg_c3_s4", "criterion_id": "hg_c3", "name": "تنظيم حملات مكافحة الحشرات", "order": 4},
    {"id": "hg_c3_s5", "criterion_id": "hg_c3", "name": "تعزيز السلوكيات الصحية", "order": 5},
    # hg_c4
    {"id": "hg_c4_s1", "criterion_id": "hg_c4", "name": "تقديم محاضرات توعوية عن التغذية", "order": 1},
    {"id": "hg_c4_s2", "criterion_id": "hg_c4", "name": "تنظيم ورش عن النظافة الشخصية", "order": 2},
    {"id": "hg_c4_s3", "criterion_id": "hg_c4", "name": "توعية حول الأمراض المزمنة", "order": 3},
    {"id": "hg_c4_s4", "criterion_id": "hg_c4", "name": "توعية حول الصحة النفسية", "order": 4},
    {"id": "hg_c4_s5", "criterion_id": "hg_c4", "name": "توعية حول الإسعافات الأولية", "order": 5},
    # hg_c5
    {"id": "hg_c5_s1", "criterion_id": "hg_c5", "name": "التنسيق مع المراكز الصحية", "order": 1},
    {"id": "hg_c5_s2", "criterion_id": "hg_c5", "name": "التعاون مع مستشفيات المنطقة", "order": 2},
    {"id": "hg_c5_s3", "criterion_id": "hg_c5", "name": "متابعة حملات التوعية مع الجهات الخارجية", "order": 3},
    {"id": "hg_c5_s4", "criterion_id": "hg_c5", "name": "المشاركة في لجان الصحة المدرسية", "order": 4},
    {"id": "hg_c5_s5", "criterion_id": "hg_c5", "name": "التنسيق مع الصحة العامة", "order": 5}
]

# قائمة التقارير الموسعة (500 تقرير، 20 لكل تصنيف فرعي)
HG_REPORTS = [
    # hg_c1_s1 (تنظيم برامج التطعيمات)
    {"id": "hg_c1_s1_r001", "subcategory_id": "hg_c1_s1", "name": "تقرير عن تنظيم حملة التطعيمات بالمدرسة", "order": 1},
    {"id": "hg_c1_s1_r002", "subcategory_id": "hg_c1_s1", "name": "سجل متابعة تطعيم الطلاب المستجدين", "order": 2},
    {"id": "hg_c1_s1_r003", "subcategory_id": "hg_c1_s1", "name": "خطة تنفيذ برنامج التطعيمات المدرسية", "order": 3},
    {"id": "hg_c1_s1_r004", "subcategory_id": "hg_c1_s1", "name": "إحصائية التغطية بالتطعيمات الأساسية", "order": 4},
    {"id": "hg_c1_s1_r005", "subcategory_id": "hg_c1_s1", "name": "تقييم فعالية حملة التطعيم ضد الإنفلونزا", "order": 5},
    {"id": "hg_c1_s1_r006", "subcategory_id": "hg_c1_s1", "name": "توعية أولياء الأمور بأهمية التطعيمات", "order": 6},
    {"id": "hg_c1_s1_r007", "subcategory_id": "hg_c1_s1", "name": "تنسيق مع المركز الصحي لتوفير اللقاحات", "order": 7},
    {"id": "hg_c1_s1_r008", "subcategory_id": "hg_c1_s1", "name": "تحسين إجراءات تسجيل التطعيمات في نظام نور", "order": 8},
    {"id": "hg_c1_s1_r009", "subcategory_id": "hg_c1_s1", "name": "متابعة حالات التأخر في التطعيم", "order": 9},
    {"id": "hg_c1_s1_r010", "subcategory_id": "hg_c1_s1", "name": "إجراءات التطعيم للطلاب المستجدين", "order": 10},
    {"id": "hg_c1_s1_r011", "subcategory_id": "hg_c1_s1", "name": "دليل التطعيمات المدرسية للعاملين الصحيين", "order": 11},
    {"id": "hg_c1_s1_r012", "subcategory_id": "hg_c1_s1", "name": "ورشة عمل حول سلامة التطعيمات", "order": 12},
    {"id": "hg_c1_s1_r013", "subcategory_id": "hg_c1_s1", "name": "حملة توعوية عن التطعيمات عبر الإذاعة المدرسية", "order": 13},
    {"id": "hg_c1_s1_r014", "subcategory_id": "hg_c1_s1", "name": "مسح ميداني لاحتياجات الطلاب من التطعيمات", "order": 14},
    {"id": "hg_c1_s1_r015", "subcategory_id": "hg_c1_s1", "name": "استبيان قياس رضا أولياء الأمور عن التطعيمات", "order": 15},
    {"id": "hg_c1_s1_r016", "subcategory_id": "hg_c1_s1", "name": "توثيق الإجراءات المتبعة في حالات التأخير", "order": 16},
    {"id": "hg_c1_s1_r017", "subcategory_id": "hg_c1_s1", "name": "تقرير دوري شهري عن التطعيمات", "order": 17},
    {"id": "hg_c1_s1_r018", "subcategory_id": "hg_c1_s1", "name": "تحليل نتائج التطعيمات وأثرها", "order": 18},
    {"id": "hg_c1_s1_r019", "subcategory_id": "hg_c1_s1", "name": "مذكرة تفاهم مع المركز الصحي بشأن التطعيمات", "order": 19},
    {"id": "hg_c1_s1_r020", "subcategory_id": "hg_c1_s1", "name": "إنجازات برنامج التطعيمات خلال العام", "order": 20},

    # hg_c1_s2 (تنفيذ برامج الكشف المبكر)
    {"id": "hg_c1_s2_r001", "subcategory_id": "hg_c1_s2", "name": "تقرير عن تنفيذ برنامج الكشف المبكر عن السمنة", "order": 1},
    {"id": "hg_c1_s2_r002", "subcategory_id": "hg_c1_s2", "name": "سجل قياس الطول والوزن للطلاب", "order": 2},
    {"id": "hg_c1_s2_r003", "subcategory_id": "hg_c1_s2", "name": "خطة الكشف المبكر عن اضطرابات النظر", "order": 3},
    {"id": "hg_c1_s2_r004", "subcategory_id": "hg_c1_s2", "name": "إحصائية نتائج الكشف المبكر عن السمنة", "order": 4},
    {"id": "hg_c1_s2_r005", "subcategory_id": "hg_c1_s2", "name": "تقييم برنامج فحص الأسنان للطلاب", "order": 5},
    {"id": "hg_c1_s2_r006", "subcategory_id": "hg_c1_s2", "name": "توعية الطلاب بأهمية الكشف المبكر", "order": 6},
    {"id": "hg_c1_s2_r007", "subcategory_id": "hg_c1_s2", "name": "تنسيق مع أخصائي التغذية للكشف عن السمنة", "order": 7},
    {"id": "hg_c1_s2_r008", "subcategory_id": "hg_c1_s2", "name": "تحسين دقة أدوات القياس في الكشف المبكر", "order": 8},
    {"id": "hg_c1_s2_r009", "subcategory_id": "hg_c1_s2", "name": "متابعة الحالات التي تحتاج تدخلًا بعد الكشف", "order": 9},
    {"id": "hg_c1_s2_r010", "subcategory_id": "hg_c1_s2", "name": "إجراءات الكشف المبكر للطلاب المستجدين", "order": 10},
    {"id": "hg_c1_s2_r011", "subcategory_id": "hg_c1_s2", "name": "دليل الكشف المبكر للمعلمين الصحيين", "order": 11},
    {"id": "hg_c1_s2_r012", "subcategory_id": "hg_c1_s2", "name": "ورشة عمل عن تقنيات القياس الصحي", "order": 12},
    {"id": "hg_c1_s2_r013", "subcategory_id": "hg_c1_s2", "name": "حملة توعوية عن الكشف المبكر عبر وسائل التواصل", "order": 13},
    {"id": "hg_c1_s2_r014", "subcategory_id": "hg_c1_s2", "name": "مسح ميداني لانتشار السمنة بين الطلاب", "order": 14},
    {"id": "hg_c1_s2_r015", "subcategory_id": "hg_c1_s2", "name": "استبيان قياس وعي الطلاب بالكشف المبكر", "order": 15},
    {"id": "hg_c1_s2_r016", "subcategory_id": "hg_c1_s2", "name": "توثيق نتائج الكشف المبكر في السجلات", "order": 16},
    {"id": "hg_c1_s2_r017", "subcategory_id": "hg_c1_s2", "name": "تقرير دوري فصلي عن الكشف المبكر", "order": 17},
    {"id": "hg_c1_s2_r018", "subcategory_id": "hg_c1_s2", "name": "تحليل اتجاهات السمنة على مدى ثلاث سنوات", "order": 18},
    {"id": "hg_c1_s2_r019", "subcategory_id": "hg_c1_s2", "name": "مذكرة تفاهم مع مستشفى للكشف المبكر", "order": 19},
    {"id": "hg_c1_s2_r020", "subcategory_id": "hg_c1_s2", "name": "إنجازات برنامج الكشف المبكر خلال العام", "order": 20},

    # hg_c1_s3 (متابعة النظافة العامة والنظافة الشخصية)
    {"id": "hg_c1_s3_r001", "subcategory_id": "hg_c1_s3", "name": "تقرير عن متابعة نظافة الفصول", "order": 1},
    {"id": "hg_c1_s3_r002", "subcategory_id": "hg_c1_s3", "name": "سجل تفتيش دورات المياه", "order": 2},
    {"id": "hg_c1_s3_r003", "subcategory_id": "hg_c1_s3", "name": "خطة تحسين النظافة العامة بالمدرسة", "order": 3},
    {"id": "hg_c1_s3_r004", "subcategory_id": "hg_c1_s3", "name": "إحصائية مدى التزام الطلاب بالنظافة الشخصية", "order": 4},
    {"id": "hg_c1_s3_r005", "subcategory_id": "hg_c1_s3", "name": "تقييم حملات النظافة المدرسية", "order": 5},
    {"id": "hg_c1_s3_r006", "subcategory_id": "hg_c1_s3", "name": "توعية الطلاب بأهمية غسل اليدين", "order": 6},
    {"id": "hg_c1_s3_r007", "subcategory_id": "hg_c1_s3", "name": "تنسيق مع مشرف النظافة لتحسين الخدمات", "order": 7},
    {"id": "hg_c1_s3_r008", "subcategory_id": "hg_c1_s3", "name": "تحسين توفر أدوات النظافة في المرافق", "order": 8},
    {"id": "hg_c1_s3_r009", "subcategory_id": "hg_c1_s3", "name": "متابعة نظافة المقصف المدرسي", "order": 9},
    {"id": "hg_c1_s3_r010", "subcategory_id": "hg_c1_s3", "name": "إجراءات النظافة الوقائية أثناء الأوبئة", "order": 10},
    {"id": "hg_c1_s3_r011", "subcategory_id": "hg_c1_s3", "name": "دليل النظافة الشخصية للطلاب", "order": 11},
    {"id": "hg_c1_s3_r012", "subcategory_id": "hg_c1_s3", "name": "ورشة عمل عن النظافة للطلاب", "order": 12},
    {"id": "hg_c1_s3_r013", "subcategory_id": "hg_c1_s3", "name": "حملة توعوية عن النظافة عبر الإذاعة", "order": 13},
    {"id": "hg_c1_s3_r014", "subcategory_id": "hg_c1_s3", "name": "مسح ميداني لمستوى النظافة في المرافق", "order": 14},
    {"id": "hg_c1_s3_r015", "subcategory_id": "hg_c1_s3", "name": "استبيان رضا الطلاب عن نظافة المدرسة", "order": 15},
    {"id": "hg_c1_s3_r016", "subcategory_id": "hg_c1_s3", "name": "توثيق مخالفات النظافة والإجراءات المتخذة", "order": 16},
    {"id": "hg_c1_s3_r017", "subcategory_id": "hg_c1_s3", "name": "تقرير دوري أسبوعي عن النظافة", "order": 17},
    {"id": "hg_c1_s3_r018", "subcategory_id": "hg_c1_s3", "name": "تحليل علاقة النظافة بانخفاض الغياب", "order": 18},
    {"id": "hg_c1_s3_r019", "subcategory_id": "hg_c1_s3", "name": "مذكرة تفاهم مع شركة نظافة", "order": 19},
    {"id": "hg_c1_s3_r020", "subcategory_id": "hg_c1_s3", "name": "إنجازات برنامج النظافة خلال العام", "order": 20},

    # hg_c1_s4 (إدارة عيادة المدرسة)
    {"id": "hg_c1_s4_r001", "subcategory_id": "hg_c1_s4", "name": "تقرير عن إدارة عيادة المدرسة", "order": 1},
    {"id": "hg_c1_s4_r002", "subcategory_id": "hg_c1_s4", "name": "سجل زيارات الطلاب للعيادة", "order": 2},
    {"id": "hg_c1_s4_r003", "subcategory_id": "hg_c1_s4", "name": "خطة تطوير العيادة المدرسية", "order": 3},
    {"id": "hg_c1_s4_r004", "subcategory_id": "hg_c1_s4", "name": "إحصائية أنواع الحالات المراجعة للعيادة", "order": 4},
    {"id": "hg_c1_s4_r005", "subcategory_id": "hg_c1_s4", "name": "تقييم تجهيزات العيادة والأدوية", "order": 5},
    {"id": "hg_c1_s4_r006", "subcategory_id": "hg_c1_s4", "name": "توعية الطلاب بخدمات العيادة", "order": 6},
    {"id": "hg_c1_s4_r007", "subcategory_id": "hg_c1_s4", "name": "تنسيق مع الصحة المدرسية لصيانة الأجهزة", "order": 7},
    {"id": "hg_c1_s4_r008", "subcategory_id": "hg_c1_s4", "name": "تحسين جاهزية العيادة للطوارئ", "order": 8},
    {"id": "hg_c1_s4_r009", "subcategory_id": "hg_c1_s4", "name": "متابعة صلاحية الأدوية والمستلزمات", "order": 9},
    {"id": "hg_c1_s4_r010", "subcategory_id": "hg_c1_s4", "name": "إجراءات استقبال الحالات الطارئة", "order": 10},
    {"id": "hg_c1_s4_r011", "subcategory_id": "hg_c1_s4", "name": "دليل عمل العيادة المدرسية", "order": 11},
    {"id": "hg_c1_s4_r012", "subcategory_id": "hg_c1_s4", "name": "ورشة عمل للمرشدين الصحيين عن إدارة العيادة", "order": 12},
    {"id": "hg_c1_s4_r013", "subcategory_id": "hg_c1_s4", "name": "حملة توعوية عن خدمات العيادة", "order": 13},
    {"id": "hg_c1_s4_r014", "subcategory_id": "hg_c1_s4", "name": "مسح ميداني لاحتياجات العيادة", "order": 14},
    {"id": "hg_c1_s4_r015", "subcategory_id": "hg_c1_s4", "name": "استبيان رضا الطلاب عن العيادة", "order": 15},
    {"id": "hg_c1_s4_r016", "subcategory_id": "hg_c1_s4", "name": "توثيق أعمال الصيانة الدورية", "order": 16},
    {"id": "hg_c1_s4_r017", "subcategory_id": "hg_c1_s4", "name": "تقرير دوري شهري عن العيادة", "order": 17},
    {"id": "hg_c1_s4_r018", "subcategory_id": "hg_c1_s4", "name": "تحليل أنماط المراجعة للعيادة", "order": 18},
    {"id": "hg_c1_s4_r019", "subcategory_id": "hg_c1_s4", "name": "مذكرة تفاهم مع جهة صحية لدعم العيادة", "order": 19},
    {"id": "hg_c1_s4_r020", "subcategory_id": "hg_c1_s4", "name": "إنجازات العيادة المدرسية خلال العام", "order": 20},

    # hg_c1_s5 (تنظيم حملات التبرع بالدم)
    {"id": "hg_c1_s5_r001", "subcategory_id": "hg_c1_s5", "name": "تقرير عن تنظيم حملة للتبرع بالدم", "order": 1},
    {"id": "hg_c1_s5_r002", "subcategory_id": "hg_c1_s5", "name": "سجل المشاركين في حملة التبرع", "order": 2},
    {"id": "hg_c1_s5_r003", "subcategory_id": "hg_c1_s5", "name": "خطة تنفيذ حملة التبرع بالدم", "order": 3},
    {"id": "hg_c1_s5_r004", "subcategory_id": "hg_c1_s5", "name": "إحصائية عدد المتبرعين وفصائل الدم", "order": 4},
    {"id": "hg_c1_s5_r005", "subcategory_id": "hg_c1_s5", "name": "تقييم أثر الحملة على الوعي المجتمعي", "order": 5},
    {"id": "hg_c1_s5_r006", "subcategory_id": "hg_c1_s5", "name": "توعية الطلاب بأهمية التبرع بالدم", "order": 6},
    {"id": "hg_c1_s5_r007", "subcategory_id": "hg_c1_s5", "name": "تنسيق مع بنك الدم لإنجاح الحملة", "order": 7},
    {"id": "hg_c1_s5_r008", "subcategory_id": "hg_c1_s5", "name": "تحسين إجراءات تسجيل المتبرعين", "order": 8},
    {"id": "hg_c1_s5_r009", "subcategory_id": "hg_c1_s5", "name": "متابعة الحالات بعد التبرع", "order": 9},
    {"id": "hg_c1_s5_r010", "subcategory_id": "hg_c1_s5", "name": "إجراءات السلامة أثناء التبرع", "order": 10},
    {"id": "hg_c1_s5_r011", "subcategory_id": "hg_c1_s5", "name": "دليل التبرع بالدم للراغبين", "order": 11},
    {"id": "hg_c1_s5_r012", "subcategory_id": "hg_c1_s5", "name": "ورشة عمل عن فوائد التبرع", "order": 12},
    {"id": "hg_c1_s5_r013", "subcategory_id": "hg_c1_s5", "name": "حملة توعوية عن التبرع عبر وسائل التواصل", "order": 13},
    {"id": "hg_c1_s5_r014", "subcategory_id": "hg_c1_s5", "name": "مسح ميداني للرغبة في التبرع", "order": 14},
    {"id": "hg_c1_s5_r015", "subcategory_id": "hg_c1_s5", "name": "استبيان رضا المتبرعين عن الحملة", "order": 15},
    {"id": "hg_c1_s5_r016", "subcategory_id": "hg_c1_s5", "name": "توثيق الفعاليات المصاحبة للحملة", "order": 16},
    {"id": "hg_c1_s5_r017", "subcategory_id": "hg_c1_s5", "name": "تقرير دوري سنوي عن حملات التبرع", "order": 17},
    {"id": "hg_c1_s5_r018", "subcategory_id": "hg_c1_s5", "name": "تحليل تزايد المشاركة في الحملات", "order": 18},
    {"id": "hg_c1_s5_r019", "subcategory_id": "hg_c1_s5", "name": "مذكرة تفاهم مع بنك الدم", "order": 19},
    {"id": "hg_c1_s5_r020", "subcategory_id": "hg_c1_s5", "name": "إنجازات حملات التبرع بالدم", "order": 20},

    # hg_c2_s1 (رصد حالات الأمراض المعدية)
    {"id": "hg_c2_s1_r001", "subcategory_id": "hg_c2_s1", "name": "تقرير عن رصد حالات الأمراض المعدية", "order": 1},
    {"id": "hg_c2_s1_r002", "subcategory_id": "hg_c2_s1", "name": "سجل متابعة حالات العدوى", "order": 2},
    {"id": "hg_c2_s1_r003", "subcategory_id": "hg_c2_s1", "name": "خطة الترصد الوبائي في المدرسة", "order": 3},
    {"id": "hg_c2_s1_r004", "subcategory_id": "hg_c2_s1", "name": "إحصائية الأمراض المعدية المسجلة", "order": 4},
    {"id": "hg_c2_s1_r005", "subcategory_id": "hg_c2_s1", "name": "تقييم إجراءات العزل المتبعة", "order": 5},
    {"id": "hg_c2_s1_r006", "subcategory_id": "hg_c2_s1", "name": "توعية الطلاب بالوقاية من العدوى", "order": 6},
    {"id": "hg_c2_s1_r007", "subcategory_id": "hg_c2_s1", "name": "تنسيق مع الصحة العامة بشأن الأمراض", "order": 7},
    {"id": "hg_c2_s1_r008", "subcategory_id": "hg_c2_s1", "name": "تحسين سرعة الإبلاغ عن الحالات", "order": 8},
    {"id": "hg_c2_s1_r009", "subcategory_id": "hg_c2_s1", "name": "متابعة المخالطين للحالات المصابة", "order": 9},
    {"id": "hg_c2_s1_r010", "subcategory_id": "hg_c2_s1", "name": "إجراءات التعامل مع الطفح الجلدي", "order": 10},
    {"id": "hg_c2_s1_r011", "subcategory_id": "hg_c2_s1", "name": "دليل رصد الأمراض المعدية", "order": 11},
    {"id": "hg_c2_s1_r012", "subcategory_id": "hg_c2_s1", "name": "ورشة عمل عن الترصد الوبائي", "order": 12},
    {"id": "hg_c2_s1_r013", "subcategory_id": "hg_c2_s1", "name": "حملة توعوية عن النظافة للوقاية من العدوى", "order": 13},
    {"id": "hg_c2_s1_r014", "subcategory_id": "hg_c2_s1", "name": "مسح ميداني لمصادر العدوى المحتملة", "order": 14},
    {"id": "hg_c2_s1_r015", "subcategory_id": "hg_c2_s1", "name": "استبيان وعي الطلاب بالعدوى", "order": 15},
    {"id": "hg_c2_s1_r016", "subcategory_id": "hg_c2_s1", "name": "توثيق إجراءات الإبلاغ اليومي", "order": 16},
    {"id": "hg_c2_s1_r017", "subcategory_id": "hg_c2_s1", "name": "تقرير دوري أسبوعي عن الأمراض المعدية", "order": 17},
    {"id": "hg_c2_s1_r018", "subcategory_id": "hg_c2_s1", "name": "تحليل موسمية الأمراض المعدية", "order": 18},
    {"id": "hg_c2_s1_r019", "subcategory_id": "hg_c2_s1", "name": "مذكرة تفاهم مع مركز مكافحة العدوى", "order": 19},
    {"id": "hg_c2_s1_r020", "subcategory_id": "hg_c2_s1", "name": "إنجازات برنامج رصد الأمراض", "order": 20},

    # hg_c2_s2 (متابعة الطلاب ذوي الأمراض المزمنة)
    {"id": "hg_c2_s2_r001", "subcategory_id": "hg_c2_s2", "name": "تقرير عن متابعة الطلاب المصابين بالسكري", "order": 1},
    {"id": "hg_c2_s2_r002", "subcategory_id": "hg_c2_s2", "name": "سجل متابعة الطلاب المصابين بالربو", "order": 2},
    {"id": "hg_c2_s2_r003", "subcategory_id": "hg_c2_s2", "name": "خطة رعاية الطلاب ذوي الأمراض المزمنة", "order": 3},
    {"id": "hg_c2_s2_r004", "subcategory_id": "hg_c2_s2", "name": "إحصائية توزيع الأمراض المزمنة بين الطلاب", "order": 4},
    {"id": "hg_c2_s2_r005", "subcategory_id": "hg_c2_s2", "name": "تقييم مدى الانتظام في متابعة الحالات", "order": 5},
    {"id": "hg_c2_s2_r006", "subcategory_id": "hg_c2_s2", "name": "توعية الطلاب بالتعايش مع الأمراض المزمنة", "order": 6},
    {"id": "hg_c2_s2_r007", "subcategory_id": "hg_c2_s2", "name": "تنسيق مع أولياء الأمور لمتابعة الحالات", "order": 7},
    {"id": "hg_c2_s2_r008", "subcategory_id": "hg_c2_s2", "name": "تحسين توفر الأدوية الطارئة في المدرسة", "order": 8},
    {"id": "hg_c2_s2_r009", "subcategory_id": "hg_c2_s2", "name": "متابعة الحالات المحولة إلى المستشفى", "order": 9},
    {"id": "hg_c2_s2_r010", "subcategory_id": "hg_c2_s2", "name": "إجراءات التعامل مع نوبات الربو", "order": 10},
    {"id": "hg_c2_s2_r011", "subcategory_id": "hg_c2_s2", "name": "دليل رعاية الطلاب المزمنين", "order": 11},
    {"id": "hg_c2_s2_r012", "subcategory_id": "hg_c2_s2", "name": "ورشة عمل للمعلمين عن الأمراض المزمنة", "order": 12},
    {"id": "hg_c2_s2_r013", "subcategory_id": "hg_c2_s2", "name": "حملة توعوية عن مرض السكري", "order": 13},
    {"id": "hg_c2_s2_r014", "subcategory_id": "hg_c2_s2", "name": "مسح ميداني لانتشار الأمراض المزمنة", "order": 14},
    {"id": "hg_c2_s2_r015", "subcategory_id": "hg_c2_s2", "name": "استبيان رضا أولياء الأمور عن المتابعة", "order": 15},
    {"id": "hg_c2_s2_r016", "subcategory_id": "hg_c2_s2", "name": "توثيق خطط الرعاية الفردية", "order": 16},
    {"id": "hg_c2_s2_r017", "subcategory_id": "hg_c2_s2", "name": "تقرير دوري شهري عن الحالات المزمنة", "order": 17},
    {"id": "hg_c2_s2_r018", "subcategory_id": "hg_c2_s2", "name": "تحليل تطور الحالات المزمنة", "order": 18},
    {"id": "hg_c2_s2_r019", "subcategory_id": "hg_c2_s2", "name": "مذكرة تفاهم مع مستشفى لدعم المزمنين", "order": 19},
    {"id": "hg_c2_s2_r020", "subcategory_id": "hg_c2_s2", "name": "إنجازات برنامج رعاية المزمنين", "order": 20},

    # hg_c2_s3 (تقديم الإسعافات الأولية)
    {"id": "hg_c2_s3_r001", "subcategory_id": "hg_c2_s3", "name": "تقرير عن تقديم الإسعافات الأولية للطلاب", "order": 1},
    {"id": "hg_c2_s3_r002", "subcategory_id": "hg_c2_s3", "name": "سجل حالات الإصابات والإسعافات", "order": 2},
    {"id": "hg_c2_s3_r003", "subcategory_id": "hg_c2_s3", "name": "خطة الاستعداد للطوارئ والإسعافات", "order": 3},
    {"id": "hg_c2_s3_r004", "subcategory_id": "hg_c2_s3", "name": "إحصائية أنواع الإصابات الأكثر شيوعًا", "order": 4},
    {"id": "hg_c2_s3_r005", "subcategory_id": "hg_c2_s3", "name": "تقييم سرعة الاستجابة للحالات الطارئة", "order": 5},
    {"id": "hg_c2_s3_r006", "subcategory_id": "hg_c2_s3", "name": "توعية الطلاب بأساسيات الإسعافات", "order": 6},
    {"id": "hg_c2_s3_r007", "subcategory_id": "hg_c2_s3", "name": "تنسيق مع الهلال الأحمر للتدريب", "order": 7},
    {"id": "hg_c2_s3_r008", "subcategory_id": "hg_c2_s3", "name": "تحسين تجهيز حقائب الإسعافات", "order": 8},
    {"id": "hg_c2_s3_r009", "subcategory_id": "hg_c2_s3", "name": "متابعة صيانة حقائب الإسعافات", "order": 9},
    {"id": "hg_c2_s3_r010", "subcategory_id": "hg_c2_s3", "name": "إجراءات الإسعاف في حالات الاختناق", "order": 10},
    {"id": "hg_c2_s3_r011", "subcategory_id": "hg_c2_s3", "name": "دليل الإسعافات الأولية للمعلمين", "order": 11},
    {"id": "hg_c2_s3_r012", "subcategory_id": "hg_c2_s3", "name": "ورشة عمل عن الإسعافات للمعلمين", "order": 12},
    {"id": "hg_c2_s3_r013", "subcategory_id": "hg_c2_s3", "name": "حملة توعوية عن الإسعافات عبر الإذاعة", "order": 13},
    {"id": "hg_c2_s3_r014", "subcategory_id": "hg_c2_s3", "name": "مسح ميداني لمدى معرفة المعلمين بالإسعافات", "order": 14},
    {"id": "hg_c2_s3_r015", "subcategory_id": "hg_c2_s3", "name": "استبيان رضا الطلاب عن الإسعافات المقدمة", "order": 15},
    {"id": "hg_c2_s3_r016", "subcategory_id": "hg_c2_s3", "name": "توثيق حالات الإسعاف والتحويل", "order": 16},
    {"id": "hg_c2_s3_r017", "subcategory_id": "hg_c2_s3", "name": "تقرير دوري شهري عن الإسعافات", "order": 17},
    {"id": "hg_c2_s3_r018", "subcategory_id": "hg_c2_s3", "name": "تحليل أسباب الإصابات الطلابية", "order": 18},
    {"id": "hg_c2_s3_r019", "subcategory_id": "hg_c2_s3", "name": "مذكرة تفاهم مع الهلال الأحمر", "order": 19},
    {"id": "hg_c2_s3_r020", "subcategory_id": "hg_c2_s3", "name": "إنجازات برنامج الإسعافات الأولية", "order": 20},

    # hg_c2_s4 (تحويل الحالات للرعاية الصحية)
    {"id": "hg_c2_s4_r001", "subcategory_id": "hg_c2_s4", "name": "تقرير عن تحويل حالات للمستشفى", "order": 1},
    {"id": "hg_c2_s4_r002", "subcategory_id": "hg_c2_s4", "name": "سجل تحويل الحالات الصحية", "order": 2},
    {"id": "hg_c2_s4_r003", "subcategory_id": "hg_c2_s4", "name": "خطة إحالة الطلاب للرعاية المتخصصة", "order": 3},
    {"id": "hg_c2_s4_r004", "subcategory_id": "hg_c2_s4", "name": "إحصائية أسباب تحويل الحالات", "order": 4},
    {"id": "hg_c2_s4_r005", "subcategory_id": "hg_c2_s4", "name": "تقييم فعالية التحويل والمتابعة", "order": 5},
    {"id": "hg_c2_s4_r006", "subcategory_id": "hg_c2_s4", "name": "توعية أولياء الأمور بإجراءات التحويل", "order": 6},
    {"id": "hg_c2_s4_r007", "subcategory_id": "hg_c2_s4", "name": "تنسيق مع المستشفيات لاستقبال الحالات", "order": 7},
    {"id": "hg_c2_s4_r008", "subcategory_id": "hg_c2_s4", "name": "تحسين سرعة إجراءات التحويل", "order": 8},
    {"id": "hg_c2_s4_r009", "subcategory_id": "hg_c2_s4", "name": "متابعة نتائج التحويل", "order": 9},
    {"id": "hg_c2_s4_r010", "subcategory_id": "hg_c2_s4", "name": "إجراءات تحويل حالات الطوارئ", "order": 10},
    {"id": "hg_c2_s4_r011", "subcategory_id": "hg_c2_s4", "name": "دليل تحويل الحالات للمراكز الصحية", "order": 11},
    {"id": "hg_c2_s4_r012", "subcategory_id": "hg_c2_s4", "name": "ورشة عمل عن آليات التحويل", "order": 12},
    {"id": "hg_c2_s4_r013", "subcategory_id": "hg_c2_s4", "name": "حملة توعوية عن أهمية التحويل المبكر", "order": 13},
    {"id": "hg_c2_s4_r014", "subcategory_id": "hg_c2_s4", "name": "مسح ميداني لمدى رضا أولياء الأمور عن التحويل", "order": 14},
    {"id": "hg_c2_s4_r015", "subcategory_id": "hg_c2_s4", "name": "استبيان جودة الخدمة بعد التحويل", "order": 15},
    {"id": "hg_c2_s4_r016", "subcategory_id": "hg_c2_s4", "name": "توثيق إجراءات التحويل", "order": 16},
    {"id": "hg_c2_s4_r017", "subcategory_id": "hg_c2_s4", "name": "تقرير دوري شهري عن التحويلات", "order": 17},
    {"id": "hg_c2_s4_r018", "subcategory_id": "hg_c2_s4", "name": "تحليل أسباب التحويل المتكررة", "order": 18},
    {"id": "hg_c2_s4_r019", "subcategory_id": "hg_c2_s4", "name": "مذكرة تفاهم مع مستشفى للتحويل", "order": 19},
    {"id": "hg_c2_s4_r020", "subcategory_id": "hg_c2_s4", "name": "إنجازات برنامج تحويل الحالات", "order": 20},

    # hg_c2_s5 (توثيق السجلات الصحية)
    {"id": "hg_c2_s5_r001", "subcategory_id": "hg_c2_s5", "name": "تقرير عن توثيق السجلات الصحية للطلاب", "order": 1},
    {"id": "hg_c2_s5_r002", "subcategory_id": "hg_c2_s5", "name": "سجل تحديث السجلات الصحية", "order": 2},
    {"id": "hg_c2_s5_r003", "subcategory_id": "hg_c2_s5", "name": "خطة تنظيم ملفات الطلاب الصحية", "order": 3},
    {"id": "hg_c2_s5_r004", "subcategory_id": "hg_c2_s5", "name": "إحصائية اكتمال السجلات الصحية", "order": 4},
    {"id": "hg_c2_s5_r005", "subcategory_id": "hg_c2_s5", "name": "تقييم دقة البيانات في نظام نور الصحي", "order": 5},
    {"id": "hg_c2_s5_r006", "subcategory_id": "hg_c2_s5", "name": "توعية المعلمين بأهمية التوثيق", "order": 6},
    {"id": "hg_c2_s5_r007", "subcategory_id": "hg_c2_s5", "name": "تنسيق مع قسم نظم المعلومات لدعم التوثيق", "order": 7},
    {"id": "hg_c2_s5_r008", "subcategory_id": "hg_c2_s5", "name": "تحسين جودة إدخال البيانات", "order": 8},
    {"id": "hg_c2_s5_r009", "subcategory_id": "hg_c2_s5", "name": "متابعة السجلات المفقودة", "order": 9},
    {"id": "hg_c2_s5_r010", "subcategory_id": "hg_c2_s5", "name": "إجراءات أرشفة السجلات", "order": 10},
    {"id": "hg_c2_s5_r011", "subcategory_id": "hg_c2_s5", "name": "دليل توثيق السجلات الصحية", "order": 11},
    {"id": "hg_c2_s5_r012", "subcategory_id": "hg_c2_s5", "name": "ورشة عمل عن التوثيق الإلكتروني", "order": 12},
    {"id": "hg_c2_s5_r013", "subcategory_id": "hg_c2_s5", "name": "حملة توعوية عن أهمية السجلات الصحية", "order": 13},
    {"id": "hg_c2_s5_r014", "subcategory_id": "hg_c2_s5", "name": "مسح ميداني لمدى دقة السجلات", "order": 14},
    {"id": "hg_c2_s5_r015", "subcategory_id": "hg_c2_s5", "name": "استبيان رضا المستخدمين عن السجلات", "order": 15},
    {"id": "hg_c2_s5_r016", "subcategory_id": "hg_c2_s5", "name": "توثيق مراجعات السجلات", "order": 16},
    {"id": "hg_c2_s5_r017", "subcategory_id": "hg_c2_s5", "name": "تقرير دوري شهري عن التوثيق", "order": 17},
    {"id": "hg_c2_s5_r018", "subcategory_id": "hg_c2_s5", "name": "تحليل نسب اكتمال السجلات", "order": 18},
    {"id": "hg_c2_s5_r019", "subcategory_id": "hg_c2_s5", "name": "مذكرة تفاهم مع جهة لدعم الأرشفة", "order": 19},
    {"id": "hg_c2_s5_r020", "subcategory_id": "hg_c2_s5", "name": "إنجازات برنامج توثيق السجلات", "order": 20},

    # hg_c3_s1 (الإشراف على نظافة المرافق)
    {"id": "hg_c3_s1_r001", "subcategory_id": "hg_c3_s1", "name": "تقرير عن الإشراف على نظافة المدرسة", "order": 1},
    {"id": "hg_c3_s1_r002", "subcategory_id": "hg_c3_s1", "name": "سجل جولات تفقد النظافة", "order": 2},
    {"id": "hg_c3_s1_r003", "subcategory_id": "hg_c3_s1", "name": "خطة الإشراف على نظافة المرافق", "order": 3},
    {"id": "hg_c3_s1_r004", "subcategory_id": "hg_c3_s1", "name": "إحصائية مستوى النظافة في المرافق", "order": 4},
    {"id": "hg_c3_s1_r005", "subcategory_id": "hg_c3_s1", "name": "تقييم أداء عمال النظافة", "order": 5},
    {"id": "hg_c3_s1_r006", "subcategory_id": "hg_c3_s1", "name": "توعية الطلاب بالحفاظ على نظافة المرافق", "order": 6},
    {"id": "hg_c3_s1_r007", "subcategory_id": "hg_c3_s1", "name": "تنسيق مع مشرف النظافة لتحسين الأداء", "order": 7},
    {"id": "hg_c3_s1_r008", "subcategory_id": "hg_c3_s1", "name": "تحسين جدولة أعمال النظافة", "order": 8},
    {"id": "hg_c3_s1_r009", "subcategory_id": "hg_c3_s1", "name": "متابعة نظافة الساحات الخارجية", "order": 9},
    {"id": "hg_c3_s1_r010", "subcategory_id": "hg_c3_s1", "name": "إجراءات التعامل مع مخالفات النظافة", "order": 10},
    {"id": "hg_c3_s1_r011", "subcategory_id": "hg_c3_s1", "name": "دليل النظافة للمرافق المدرسية", "order": 11},
    {"id": "hg_c3_s1_r012", "subcategory_id": "hg_c3_s1", "name": "ورشة عمل لعمال النظافة", "order": 12},
    {"id": "hg_c3_s1_r013", "subcategory_id": "hg_c3_s1", "name": "حملة توعوية عن النظافة", "order": 13},
    {"id": "hg_c3_s1_r014", "subcategory_id": "hg_c3_s1", "name": "مسح ميداني لرضا الطلاب عن النظافة", "order": 14},
    {"id": "hg_c3_s1_r015", "subcategory_id": "hg_c3_s1", "name": "استبيان رضا المعلمين عن النظافة", "order": 15},
    {"id": "hg_c3_s1_r016", "subcategory_id": "hg_c3_s1", "name": "توثيق ملاحظات النظافة", "order": 16},
    {"id": "hg_c3_s1_r017", "subcategory_id": "hg_c3_s1", "name": "تقرير دوري أسبوعي عن النظافة", "order": 17},
    {"id": "hg_c3_s1_r018", "subcategory_id": "hg_c3_s1", "name": "تحليل تأثير النظافة على الغياب", "order": 18},
    {"id": "hg_c3_s1_r019", "subcategory_id": "hg_c3_s1", "name": "مذكرة تفاهم مع شركة نظافة", "order": 19},
    {"id": "hg_c3_s1_r020", "subcategory_id": "hg_c3_s1", "name": "إنجازات برنامج الإشراف على النظافة", "order": 20},

    # hg_c3_s2 (متابعة سلامة الأغذية في المقصف)
    {"id": "hg_c3_s2_r001", "subcategory_id": "hg_c3_s2", "name": "تقرير عن متابعة المقصف المدرسي", "order": 1},
    {"id": "hg_c3_s2_r002", "subcategory_id": "hg_c3_s2", "name": "سجل زيارات تفتيش المقصف", "order": 2},
    {"id": "hg_c3_s2_r003", "subcategory_id": "hg_c3_s2", "name": "خطة الرقابة على سلامة الأغذية", "order": 3},
    {"id": "hg_c3_s2_r004", "subcategory_id": "hg_c3_s2", "name": "إحصائية مدى التزام المقصف بالاشتراطات", "order": 4},
    {"id": "hg_c3_s2_r005", "subcategory_id": "hg_c3_s2", "name": "تقييم جودة الأغذية المقدمة", "order": 5},
    {"id": "hg_c3_s2_r006", "subcategory_id": "hg_c3_s2", "name": "توعية العاملين بالمقصف بالسلامة الغذائية", "order": 6},
    {"id": "hg_c3_s2_r007", "subcategory_id": "hg_c3_s2", "name": "تنسيق مع هيئة الغذاء والدواء للتفتيش", "order": 7},
    {"id": "hg_c3_s2_r008", "subcategory_id": "hg_c3_s2", "name": "تحسين اشتراطات تخزين الأغذية", "order": 8},
    {"id": "hg_c3_s2_r009", "subcategory_id": "hg_c3_s2", "name": "متابعة صلاحية المنتجات", "order": 9},
    {"id": "hg_c3_s2_r010", "subcategory_id": "hg_c3_s2", "name": "إجراءات التعامل مع الأغذية الفاسدة", "order": 10},
    {"id": "hg_c3_s2_r011", "subcategory_id": "hg_c3_s2", "name": "دليل سلامة الأغذية للمقصف", "order": 11},
    {"id": "hg_c3_s2_r012", "subcategory_id": "hg_c3_s2", "name": "ورشة عمل للعاملين عن النظافة", "order": 12},
    {"id": "hg_c3_s2_r013", "subcategory_id": "hg_c3_s2", "name": "حملة توعوية للطلاب عن الغذاء الصحي", "order": 13},
    {"id": "hg_c3_s2_r014", "subcategory_id": "hg_c3_s2", "name": "مسح ميداني لرضا الطلاب عن المقصف", "order": 14},
    {"id": "hg_c3_s2_r015", "subcategory_id": "hg_c3_s2", "name": "استبيان حول سلامة الأغذية", "order": 15},
    {"id": "hg_c3_s2_r016", "subcategory_id": "hg_c3_s2", "name": "توثيق مخالفات المقصف", "order": 16},
    {"id": "hg_c3_s2_r017", "subcategory_id": "hg_c3_s2", "name": "تقرير دوري شهري عن المقصف", "order": 17},
    {"id": "hg_c3_s2_r018", "subcategory_id": "hg_c3_s2", "name": "تحليل مدى التزام المقصف بالمعايير", "order": 18},
    {"id": "hg_c3_s2_r019", "subcategory_id": "hg_c3_s2", "name": "مذكرة تفاهم مع هيئة الغذاء", "order": 19},
    {"id": "hg_c3_s2_r020", "subcategory_id": "hg_c3_s2", "name": "إنجازات برنامج سلامة الأغذية", "order": 20},

    # hg_c3_s3 (التأكد من تهوية الفصول)
    {"id": "hg_c3_s3_r001", "subcategory_id": "hg_c3_s3", "name": "تقرير عن متابعة تهوية الفصول", "order": 1},
    {"id": "hg_c3_s3_r002", "subcategory_id": "hg_c3_s3", "name": "سجل قياس جودة الهواء", "order": 2},
    {"id": "hg_c3_s3_r003", "subcategory_id": "hg_c3_s3", "name": "خطة تحسين التهوية بالفصول", "order": 3},
    {"id": "hg_c3_s3_r004", "subcategory_id": "hg_c3_s3", "name": "إحصائية مدى كفاية التهوية", "order": 4},
    {"id": "hg_c3_s3_r005", "subcategory_id": "hg_c3_s3", "name": "تقييم أداء أجهزة التكييف", "order": 5},
    {"id": "hg_c3_s3_r006", "subcategory_id": "hg_c3_s3", "name": "توعية الطلاب بأهمية التهوية", "order": 6},
    {"id": "hg_c3_s3_r007", "subcategory_id": "hg_c3_s3", "name": "تنسيق مع الصيانة لصيانة المكيفات", "order": 7},
    {"id": "hg_c3_s3_r008", "subcategory_id": "hg_c3_s3", "name": "تحسين فتحات التهوية الطبيعية", "order": 8},
    {"id": "hg_c3_s3_r009", "subcategory_id": "hg_c3_s3", "name": "متابعة نظافة فلاتر التكييف", "order": 9},
    {"id": "hg_c3_s3_r010", "subcategory_id": "hg_c3_s3", "name": "إجراءات التهوية أثناء الاختبارات", "order": 10},
    {"id": "hg_c3_s3_r011", "subcategory_id": "hg_c3_s3", "name": "دليل التهوية الجيدة في الفصول", "order": 11},
    {"id": "hg_c3_s3_r012", "subcategory_id": "hg_c3_s3", "name": "ورشة عمل عن جودة الهواء الداخلي", "order": 12},
    {"id": "hg_c3_s3_r013", "subcategory_id": "hg_c3_s3", "name": "حملة توعوية عن فوائد التهوية", "order": 13},
    {"id": "hg_c3_s3_r014", "subcategory_id": "hg_c3_s3", "name": "مسح ميداني لقياس جودة الهواء", "order": 14},
    {"id": "hg_c3_s3_r015", "subcategory_id": "hg_c3_s3", "name": "استبيان رضا الطلاب عن التهوية", "order": 15},
    {"id": "hg_c3_s3_r016", "subcategory_id": "hg_c3_s3", "name": "توثيق أعمال الصيانة", "order": 16},
    {"id": "hg_c3_s3_r017", "subcategory_id": "hg_c3_s3", "name": "تقرير دوري شهري عن التهوية", "order": 17},
    {"id": "hg_c3_s3_r018", "subcategory_id": "hg_c3_s3", "name": "تحليل تأثير التهوية على التركيز", "order": 18},
    {"id": "hg_c3_s3_r019", "subcategory_id": "hg_c3_s3", "name": "مذكرة تفاهم مع شركة صيانة", "order": 19},
    {"id": "hg_c3_s3_r020", "subcategory_id": "hg_c3_s3", "name": "إنجازات برنامج تحسين التهوية", "order": 20},

    # hg_c3_s4 (تنظيم حملات مكافحة الحشرات)
    {"id": "hg_c3_s4_r001", "subcategory_id": "hg_c3_s4", "name": "تقرير عن تنظيم حملة مكافحة الحشرات", "order": 1},
    {"id": "hg_c3_s4_r002", "subcategory_id": "hg_c3_s4", "name": "سجل متابعة الرش الدوري", "order": 2},
    {"id": "hg_c3_s4_r003", "subcategory_id": "hg_c3_s4", "name": "خطة مكافحة الحشرات", "order": 3},
    {"id": "hg_c3_s4_r004", "subcategory_id": "hg_c3_s4", "name": "إحصائية انتشار الحشرات", "order": 4},
    {"id": "hg_c3_s4_r005", "subcategory_id": "hg_c3_s4", "name": "تقييم فعالية حملات المكافحة", "order": 5},
    {"id": "hg_c3_s4_r006", "subcategory_id": "hg_c3_s4", "name": "توعية الطلاب بأضرار الحشرات", "order": 6},
    {"id": "hg_c3_s4_r007", "subcategory_id": "hg_c3_s4", "name": "تنسيق مع البلدية للرش", "order": 7},
    {"id": "hg_c3_s4_r008", "subcategory_id": "hg_c3_s4", "name": "تحسين إجراءات الرش الوقائي", "order": 8},
    {"id": "hg_c3_s4_r009", "subcategory_id": "hg_c3_s4", "name": "متابعة رش الفصول", "order": 9},
    {"id": "hg_c3_s4_r010", "subcategory_id": "hg_c3_s4", "name": "إجراءات مكافحة البعوض", "order": 10},
    {"id": "hg_c3_s4_r011", "subcategory_id": "hg_c3_s4", "name": "دليل مكافحة الحشرات", "order": 11},
    {"id": "hg_c3_s4_r012", "subcategory_id": "hg_c3_s4", "name": "ورشة عمل للعاملين عن مكافحة الحشرات", "order": 12},
    {"id": "hg_c3_s4_r013", "subcategory_id": "hg_c3_s4", "name": "حملة توعوية عن النظافة لمنع الحشرات", "order": 13},
    {"id": "hg_c3_s4_r014", "subcategory_id": "hg_c3_s4", "name": "مسح ميداني لبؤر الحشرات", "order": 14},
    {"id": "hg_c3_s4_r015", "subcategory_id": "hg_c3_s4", "name": "استبيان رضا الطلاب عن المكافحة", "order": 15},
    {"id": "hg_c3_s4_r016", "subcategory_id": "hg_c3_s4", "name": "توثيق أعمال المكافحة", "order": 16},
    {"id": "hg_c3_s4_r017", "subcategory_id": "hg_c3_s4", "name": "تقرير دوري فصلي عن المكافحة", "order": 17},
    {"id": "hg_c3_s4_r018", "subcategory_id": "hg_c3_s4", "name": "تحليل نتائج المكافحة", "order": 18},
    {"id": "hg_c3_s4_r019", "subcategory_id": "hg_c3_s4", "name": "مذكرة تفاهم مع البلدية", "order": 19},
    {"id": "hg_c3_s4_r020", "subcategory_id": "hg_c3_s4", "name": "إنجازات برنامج مكافحة الحشرات", "order": 20},

    # hg_c3_s5 (تعزيز السلوكيات الصحية)
    {"id": "hg_c3_s5_r001", "subcategory_id": "hg_c3_s5", "name": "تقرير عن برنامج تعزيز السلوكيات الصحية", "order": 1},
    {"id": "hg_c3_s5_r002", "subcategory_id": "hg_c3_s5", "name": "سجل أنشطة تعزيز الصحة", "order": 2},
    {"id": "hg_c3_s5_r003", "subcategory_id": "hg_c3_s5", "name": "خطة تعزيز السلوكيات الصحية", "order": 3},
    {"id": "hg_c3_s5_r004", "subcategory_id": "hg_c3_s5", "name": "إحصائية التزام الطلاب بالسلوكيات الصحية", "order": 4},
    {"id": "hg_c3_s5_r005", "subcategory_id": "hg_c3_s5", "name": "تقييم مسابقات أفضل فصل صحي", "order": 5},
    {"id": "hg_c3_s5_r006", "subcategory_id": "hg_c3_s5", "name": "توعية الطلاب بغسل اليدين", "order": 6},
    {"id": "hg_c3_s5_r007", "subcategory_id": "hg_c3_s5", "name": "تنسيق مع المعلمين لتعزيز السلوكيات", "order": 7},
    {"id": "hg_c3_s5_r008", "subcategory_id": "hg_c3_s5", "name": "تحسين وسائل تعزيز السلوكيات", "order": 8},
    {"id": "hg_c3_s5_r009", "subcategory_id": "hg_c3_s5", "name": "متابعة تطبيق السلوكيات في الفصول", "order": 9},
    {"id": "hg_c3_s5_r010", "subcategory_id": "hg_c3_s5", "name": "إجراءات تحفيز الطلاب", "order": 10},
    {"id": "hg_c3_s5_r011", "subcategory_id": "hg_c3_s5", "name": "دليل تعزيز السلوكيات الصحية", "order": 11},
    {"id": "hg_c3_s5_r012", "subcategory_id": "hg_c3_s5", "name": "ورشة عمل للمعلمين عن تعزيز السلوكيات", "order": 12},
    {"id": "hg_c3_s5_r013", "subcategory_id": "hg_c3_s5", "name": "حملة توعوية عن النظافة الشخصية", "order": 13},
    {"id": "hg_c3_s5_r014", "subcategory_id": "hg_c3_s5", "name": "مسح ميداني للسلوكيات الصحية", "order": 14},
    {"id": "hg_c3_s5_r015", "subcategory_id": "hg_c3_s5", "name": "استبيان قياس السلوكيات", "order": 15},
    {"id": "hg_c3_s5_r016", "subcategory_id": "hg_c3_s5", "name": "توثيق الأنشطة المعززة", "order": 16},
    {"id": "hg_c3_s5_r017", "subcategory_id": "hg_c3_s5", "name": "تقرير دوري شهري عن السلوكيات", "order": 17},
    {"id": "hg_c3_s5_r018", "subcategory_id": "hg_c3_s5", "name": "تحليل تحسن السلوكيات", "order": 18},
    {"id": "hg_c3_s5_r019", "subcategory_id": "hg_c3_s5", "name": "مذكرة تفاهم مع جهة داعمة", "order": 19},
    {"id": "hg_c3_s5_r020", "subcategory_id": "hg_c3_s5", "name": "إنجازات برنامج تعزيز السلوكيات", "order": 20},

    # hg_c4_s1 (تقديم محاضرات توعوية عن التغذية)
    {"id": "hg_c4_s1_r001", "subcategory_id": "hg_c4_s1", "name": "تقرير عن محاضرات التوعية بالتغذية السليمة", "order": 1},
    {"id": "hg_c4_s1_r002", "subcategory_id": "hg_c4_s1", "name": "سجل ورش عمل عن الغذاء الصحي", "order": 2},
    {"id": "hg_c4_s1_r003", "subcategory_id": "hg_c4_s1", "name": "خطة التوعية الغذائية", "order": 3},
    {"id": "hg_c4_s1_r004", "subcategory_id": "hg_c4_s1", "name": "إحصائية عدد المستفيدين من المحاضرات", "order": 4},
    {"id": "hg_c4_s1_r005", "subcategory_id": "hg_c4_s1", "name": "تقييم أثر المحاضرات على عادات الطلاب", "order": 5},
    {"id": "hg_c4_s1_r006", "subcategory_id": "hg_c4_s1", "name": "توعية الطلاب بأضرار الوجبات السريعة", "order": 6},
    {"id": "hg_c4_s1_r007", "subcategory_id": "hg_c4_s1", "name": "تنسيق مع أخصائي تغذية للمحاضرات", "order": 7},
    {"id": "hg_c4_s1_r008", "subcategory_id": "hg_c4_s1", "name": "تحسين مادة المحاضرات", "order": 8},
    {"id": "hg_c4_s1_r009", "subcategory_id": "hg_c4_s1", "name": "متابعة تطبيق النصائح الغذائية", "order": 9},
    {"id": "hg_c4_s1_r010", "subcategory_id": "hg_c4_s1", "name": "إجراءات تنظيم المحاضرات", "order": 10},
    {"id": "hg_c4_s1_r011", "subcategory_id": "hg_c4_s1", "name": "دليل التغذية السليمة", "order": 11},
    {"id": "hg_c4_s1_r012", "subcategory_id": "hg_c4_s1", "name": "ورشة عمل للطلاب عن إعداد وجبة صحية", "order": 12},
    {"id": "hg_c4_s1_r013", "subcategory_id": "hg_c4_s1", "name": "حملة توعوية عن التغذية عبر الإذاعة", "order": 13},
    {"id": "hg_c4_s1_r014", "subcategory_id": "hg_c4_s1", "name": "مسح ميداني للعادات الغذائية", "order": 14},
    {"id": "hg_c4_s1_r015", "subcategory_id": "hg_c4_s1", "name": "استبيان قياس وعي الطلاب بالتغذية", "order": 15},
    {"id": "hg_c4_s1_r016", "subcategory_id": "hg_c4_s1", "name": "توثيق المحاضرات", "order": 16},
    {"id": "hg_c4_s1_r017", "subcategory_id": "hg_c4_s1", "name": "تقرير دوري فصلي عن التوعية", "order": 17},
    {"id": "hg_c4_s1_r018", "subcategory_id": "hg_c4_s1", "name": "تحليل أثر التوعية على سلوكيات الشراء", "order": 18},
    {"id": "hg_c4_s1_r019", "subcategory_id": "hg_c4_s1", "name": "مذكرة تفاهم مع جمعية التغذية", "order": 19},
    {"id": "hg_c4_s1_r020", "subcategory_id": "hg_c4_s1", "name": "إنجازات برنامج التوعية الغذائية", "order": 20},

    # hg_c4_s2 (تنظيم ورش عن النظافة الشخصية)
    {"id": "hg_c4_s2_r001", "subcategory_id": "hg_c4_s2", "name": "تقرير عن ورش النظافة الشخصية للطلاب", "order": 1},
    {"id": "hg_c4_s2_r002", "subcategory_id": "hg_c4_s2", "name": "سجل محاضرات عن العناية بالأسنان", "order": 2},
    {"id": "hg_c4_s2_r003", "subcategory_id": "hg_c4_s2", "name": "خطة تنظيم ورش النظافة", "order": 3},
    {"id": "hg_c4_s2_r004", "subcategory_id": "hg_c4_s2", "name": "إحصائية عدد المشاركين في الورش", "order": 4},
    {"id": "hg_c4_s2_r005", "subcategory_id": "hg_c4_s2", "name": "تقييم فعالية ورش النظافة", "order": 5},
    {"id": "hg_c4_s2_r006", "subcategory_id": "hg_c4_s2", "name": "توعية الطلاب بغسل اليدين", "order": 6},
    {"id": "hg_c4_s2_r007", "subcategory_id": "hg_c4_s2", "name": "تنسيق مع طبيب أسنان للمشاركة", "order": 7},
    {"id": "hg_c4_s2_r008", "subcategory_id": "hg_c4_s2", "name": "تحسين محتوى الورش", "order": 8},
    {"id": "hg_c4_s2_r009", "subcategory_id": "hg_c4_s2", "name": "متابعة تطبيق النظافة الشخصية", "order": 9},
    {"id": "hg_c4_s2_r010", "subcategory_id": "hg_c4_s2", "name": "إجراءات تنظيم الورش", "order": 10},
    {"id": "hg_c4_s2_r011", "subcategory_id": "hg_c4_s2", "name": "دليل النظافة الشخصية", "order": 11},
    {"id": "hg_c4_s2_r012", "subcategory_id": "hg_c4_s2", "name": "ورشة عمل عن العناية بالبشرة", "order": 12},
    {"id": "hg_c4_s2_r013", "subcategory_id": "hg_c4_s2", "name": "حملة توعوية عن النظافة عبر الإذاعة", "order": 13},
    {"id": "hg_c4_s2_r014", "subcategory_id": "hg_c4_s2", "name": "مسح ميداني لعادات النظافة", "order": 14},
    {"id": "hg_c4_s2_r015", "subcategory_id": "hg_c4_s2", "name": "استبيان وعي الطلاب بالنظافة", "order": 15},
    {"id": "hg_c4_s2_r016", "subcategory_id": "hg_c4_s2", "name": "توثيق فعاليات الورش", "order": 16},
    {"id": "hg_c4_s2_r017", "subcategory_id": "hg_c4_s2", "name": "تقرير دوري فصلي عن الورش", "order": 17},
    {"id": "hg_c4_s2_r018", "subcategory_id": "hg_c4_s2", "name": "تحليل تحسن عادات النظافة", "order": 18},
    {"id": "hg_c4_s2_r019", "subcategory_id": "hg_c4_s2", "name": "مذكرة تفاهم مع عيادة أسنان", "order": 19},
    {"id": "hg_c4_s2_r020", "subcategory_id": "hg_c4_s2", "name": "إنجازات برنامج النظافة الشخصية", "order": 20},

    # hg_c4_s3 (توعية حول الأمراض المزمنة)
    {"id": "hg_c4_s3_r001", "subcategory_id": "hg_c4_s3", "name": "تقرير عن توعية الطلاب بالسكري", "order": 1},
    {"id": "hg_c4_s3_r002", "subcategory_id": "hg_c4_s3", "name": "سجل محاضرات عن ضغط الدم", "order": 2},
    {"id": "hg_c4_s3_r003", "subcategory_id": "hg_c4_s3", "name": "خطة التوعية بالأمراض المزمنة", "order": 3},
    {"id": "hg_c4_s3_r004", "subcategory_id": "hg_c4_s3", "name": "إحصائية عدد المستفيدين من التوعية", "order": 4},
    {"id": "hg_c4_s3_r005", "subcategory_id": "hg_c4_s3", "name": "تقييم أثر التوعية على المعرفة", "order": 5},
    {"id": "hg_c4_s3_r006", "subcategory_id": "hg_c4_s3", "name": "توعية الطلاب بالربو", "order": 6},
    {"id": "hg_c4_s3_r007", "subcategory_id": "hg_c4_s3", "name": "تنسيق مع جمعية السكري", "order": 7},
    {"id": "hg_c4_s3_r008", "subcategory_id": "hg_c4_s3", "name": "تحسين مواد التوعية", "order": 8},
    {"id": "hg_c4_s3_r009", "subcategory_id": "hg_c4_s3", "name": "متابعة فهم الطلاب", "order": 9},
    {"id": "hg_c4_s3_r010", "subcategory_id": "hg_c4_s3", "name": "إجراءات تنظيم المحاضرات", "order": 10},
    {"id": "hg_c4_s3_r011", "subcategory_id": "hg_c4_s3", "name": "دليل التعايش مع الأمراض المزمنة", "order": 11},
    {"id": "hg_c4_s3_r012", "subcategory_id": "hg_c4_s3", "name": "ورشة عمل عن السكري", "order": 12},
    {"id": "hg_c4_s3_r013", "subcategory_id": "hg_c4_s3", "name": "حملة توعوية عن الأمراض المزمنة", "order": 13},
    {"id": "hg_c4_s3_r014", "subcategory_id": "hg_c4_s3", "name": "مسح ميداني لانتشار الأمراض", "order": 14},
    {"id": "hg_c4_s3_r015", "subcategory_id": "hg_c4_s3", "name": "استبيان وعي الطلاب", "order": 15},
    {"id": "hg_c4_s3_r016", "subcategory_id": "hg_c4_s3", "name": "توثيق الأنشطة التوعوية", "order": 16},
    {"id": "hg_c4_s3_r017", "subcategory_id": "hg_c4_s3", "name": "تقرير دوري فصلي عن التوعية", "order": 17},
    {"id": "hg_c4_s3_r018", "subcategory_id": "hg_c4_s3", "name": "تحليل تحسن الوعي الصحي", "order": 18},
    {"id": "hg_c4_s3_r019", "subcategory_id": "hg_c4_s3", "name": "مذكرة تفاهم مع جمعية السكري", "order": 19},
    {"id": "hg_c4_s3_r020", "subcategory_id": "hg_c4_s3", "name": "إنجازات برنامج التوعية", "order": 20},

    # hg_c4_s4 (توعية حول الصحة النفسية)
    {"id": "hg_c4_s4_r001", "subcategory_id": "hg_c4_s4", "name": "تقرير عن توعية الطلاب بالصحة النفسية", "order": 1},
    {"id": "hg_c4_s4_r002", "subcategory_id": "hg_c4_s4", "name": "سجل ورش عن إدارة التوتر", "order": 2},
    {"id": "hg_c4_s4_r003", "subcategory_id": "hg_c4_s4", "name": "خطة التوعية بالصحة النفسية", "order": 3},
    {"id": "hg_c4_s4_r004", "subcategory_id": "hg_c4_s4", "name": "إحصائية عدد المستفيدين", "order": 4},
    {"id": "hg_c4_s4_r005", "subcategory_id": "hg_c4_s4", "name": "تقييم أثر التوعية على الطلاب", "order": 5},
    {"id": "hg_c4_s4_r006", "subcategory_id": "hg_c4_s4", "name": "توعية الطلاب بالتنمر", "order": 6},
    {"id": "hg_c4_s4_r007", "subcategory_id": "hg_c4_s4", "name": "تنسيق مع المرشد الطلابي", "order": 7},
    {"id": "hg_c4_s4_r008", "subcategory_id": "hg_c4_s4", "name": "تحسين مواد التوعية", "order": 8},
    {"id": "hg_c4_s4_r009", "subcategory_id": "hg_c4_s4", "name": "متابعة الصحة النفسية للطلاب", "order": 9},
    {"id": "hg_c4_s4_r010", "subcategory_id": "hg_c4_s4", "name": "إجراءات تنظيم الورش", "order": 10},
    {"id": "hg_c4_s4_r011", "subcategory_id": "hg_c4_s4", "name": "دليل الصحة النفسية", "order": 11},
    {"id": "hg_c4_s4_r012", "subcategory_id": "hg_c4_s4", "name": "ورشة عمل عن القلق", "order": 12},
    {"id": "hg_c4_s4_r013", "subcategory_id": "hg_c4_s4", "name": "حملة توعوية عن الصحة النفسية", "order": 13},
    {"id": "hg_c4_s4_r014", "subcategory_id": "hg_c4_s4", "name": "مسح ميداني للصحة النفسية", "order": 14},
    {"id": "hg_c4_s4_r015", "subcategory_id": "hg_c4_s4", "name": "استبيان قياس الصحة النفسية", "order": 15},
    {"id": "hg_c4_s4_r016", "subcategory_id": "hg_c4_s4", "name": "توثيق الأنشطة", "order": 16},
    {"id": "hg_c4_s4_r017", "subcategory_id": "hg_c4_s4", "name": "تقرير دوري فصلي", "order": 17},
    {"id": "hg_c4_s4_r018", "subcategory_id": "hg_c4_s4", "name": "تحليل تحسن الصحة النفسية", "order": 18},
    {"id": "hg_c4_s4_r019", "subcategory_id": "hg_c4_s4", "name": "مذكرة تفاهم مع جمعية نفسية", "order": 19},
    {"id": "hg_c4_s4_r020", "subcategory_id": "hg_c4_s4", "name": "إنجازات برنامج الصحة النفسية", "order": 20},

    # hg_c4_s5 (توعية حول الإسعافات الأولية)
    {"id": "hg_c4_s5_r001", "subcategory_id": "hg_c4_s5", "name": "تقرير عن تدريب الطلاب على الإسعافات الأولية", "order": 1},
    {"id": "hg_c4_s5_r002", "subcategory_id": "hg_c4_s5", "name": "سجل ورش عملية عن الإسعافات", "order": 2},
    {"id": "hg_c4_s5_r003", "subcategory_id": "hg_c4_s5", "name": "خطة التوعية بالإسعافات", "order": 3},
    {"id": "hg_c4_s5_r004", "subcategory_id": "hg_c4_s5", "name": "إحصائية عدد المتدربين", "order": 4},
    {"id": "hg_c4_s5_r005", "subcategory_id": "hg_c4_s5", "name": "تقييم مسابقة الإسعافات الأولية", "order": 5},
    {"id": "hg_c4_s5_r006", "subcategory_id": "hg_c4_s5", "name": "توعية الطلاب بالإنعاش القلبي", "order": 6},
    {"id": "hg_c4_s5_r007", "subcategory_id": "hg_c4_s5", "name": "تنسيق مع الهلال الأحمر", "order": 7},
    {"id": "hg_c4_s5_r008", "subcategory_id": "hg_c4_s5", "name": "تحسين أدوات التدريب", "order": 8},
    {"id": "hg_c4_s5_r009", "subcategory_id": "hg_c4_s5", "name": "متابعة استعداد الطلاب", "order": 9},
    {"id": "hg_c4_s5_r010", "subcategory_id": "hg_c4_s5", "name": "إجراءات تنظيم الورش", "order": 10},
    {"id": "hg_c4_s5_r011", "subcategory_id": "hg_c4_s5", "name": "دليل الإسعافات الأولية", "order": 11},
    {"id": "hg_c4_s5_r012", "subcategory_id": "hg_c4_s5", "name": "ورشة عمل عن الإسعافات للمعلمين", "order": 12},
    {"id": "hg_c4_s5_r013", "subcategory_id": "hg_c4_s5", "name": "حملة توعوية عن الإسعافات", "order": 13},
    {"id": "hg_c4_s5_r014", "subcategory_id": "hg_c4_s5", "name": "مسح ميداني لمعرفة الإسعافات", "order": 14},
    {"id": "hg_c4_s5_r015", "subcategory_id": "hg_c4_s5", "name": "استبيان وعي الطلاب", "order": 15},
    {"id": "hg_c4_s5_r016", "subcategory_id": "hg_c4_s5", "name": "توثيق الأنشطة", "order": 16},
    {"id": "hg_c4_s5_r017", "subcategory_id": "hg_c4_s5", "name": "تقرير دوري فصلي", "order": 17},
    {"id": "hg_c4_s5_r018", "subcategory_id": "hg_c4_s5", "name": "تحليل تحسن المهارات", "order": 18},
    {"id": "hg_c4_s5_r019", "subcategory_id": "hg_c4_s5", "name": "مذكرة تفاهم مع الهلال الأحمر", "order": 19},
    {"id": "hg_c4_s5_r020", "subcategory_id": "hg_c4_s5", "name": "إنجازات برنامج الإسعافات", "order": 20},

    # hg_c5_s1 (التنسيق مع المراكز الصحية)
    {"id": "hg_c5_s1_r001", "subcategory_id": "hg_c5_s1", "name": "تقرير عن التنسيق مع المركز الصحي", "order": 1},
    {"id": "hg_c5_s1_r002", "subcategory_id": "hg_c5_s1", "name": "سجل اجتماعات مع فريق الصحة المدرسية", "order": 2},
    {"id": "hg_c5_s1_r003", "subcategory_id": "hg_c5_s1", "name": "خطة التنسيق مع المركز الصحي", "order": 3},
    {"id": "hg_c5_s1_r004", "subcategory_id": "hg_c5_s1", "name": "إحصائية عدد الأنشطة المشتركة", "order": 4},
    {"id": "hg_c5_s1_r005", "subcategory_id": "hg_c5_s1", "name": "تقييم التعاون مع المركز", "order": 5},
    {"id": "hg_c5_s1_r006", "subcategory_id": "hg_c5_s1", "name": "توعية الطلاب بخدمات المركز", "order": 6},
    {"id": "hg_c5_s1_r007", "subcategory_id": "hg_c5_s1", "name": "تنسيق برامج التطعيم مع المركز", "order": 7},
    {"id": "hg_c5_s1_r008", "subcategory_id": "hg_c5_s1", "name": "تحسين قنوات التواصل", "order": 8},
    {"id": "hg_c5_s1_r009", "subcategory_id": "hg_c5_s1", "name": "متابعة الحالات المحولة للمركز", "order": 9},
    {"id": "hg_c5_s1_r010", "subcategory_id": "hg_c5_s1", "name": "إجراءات إحالة الطلاب", "order": 10},
    {"id": "hg_c5_s1_r011", "subcategory_id": "hg_c5_s1", "name": "دليل التنسيق مع المركز الصحي", "order": 11},
    {"id": "hg_c5_s1_r012", "subcategory_id": "hg_c5_s1", "name": "ورشة عمل مشتركة", "order": 12},
    {"id": "hg_c5_s1_r013", "subcategory_id": "hg_c5_s1", "name": "حملة توعوية بالتعاون مع المركز", "order": 13},
    {"id": "hg_c5_s1_r014", "subcategory_id": "hg_c5_s1", "name": "مسح ميداني لرضا أولياء الأمور", "order": 14},
    {"id": "hg_c5_s1_r015", "subcategory_id": "hg_c5_s1", "name": "استبيان عن خدمات المركز", "order": 15},
    {"id": "hg_c5_s1_r016", "subcategory_id": "hg_c5_s1", "name": "توثيق الاجتماعات", "order": 16},
    {"id": "hg_c5_s1_r017", "subcategory_id": "hg_c5_s1", "name": "تقرير دوري شهري عن التنسيق", "order": 17},
    {"id": "hg_c5_s1_r018", "subcategory_id": "hg_c5_s1", "name": "تحليل فعالية التنسيق", "order": 18},
    {"id": "hg_c5_s1_r019", "subcategory_id": "hg_c5_s1", "name": "مذكرة تفاهم مع المركز الصحي", "order": 19},
    {"id": "hg_c5_s1_r020", "subcategory_id": "hg_c5_s1", "name": "إنجازات التنسيق مع المركز", "order": 20},

    # hg_c5_s2 (التعاون مع مستشفيات المنطقة)
    {"id": "hg_c5_s2_r001", "subcategory_id": "hg_c5_s2", "name": "تقرير عن التعاون مع مستشفى المنطقة", "order": 1},
    {"id": "hg_c5_s2_r002", "subcategory_id": "hg_c5_s2", "name": "سجل تنظيم زيارات طلابية للمستشفى", "order": 2},
    {"id": "hg_c5_s2_r003", "subcategory_id": "hg_c5_s2", "name": "خطة التعاون مع المستشفيات", "order": 3},
    {"id": "hg_c5_s2_r004", "subcategory_id": "hg_c5_s2", "name": "إحصائية عدد الزيارات", "order": 4},
    {"id": "hg_c5_s2_r005", "subcategory_id": "hg_c5_s2", "name": "تقييم البرامج المشتركة", "order": 5},
    {"id": "hg_c5_s2_r006", "subcategory_id": "hg_c5_s2", "name": "توعية الطلاب بالخدمات الطبية", "order": 6},
    {"id": "hg_c5_s2_r007", "subcategory_id": "hg_c5_s2", "name": "تنسيق مع المستشفى للمحاضرات", "order": 7},
    {"id": "hg_c5_s2_r008", "subcategory_id": "hg_c5_s2", "name": "تحسين استقبال الحالات المحولة", "order": 8},
    {"id": "hg_c5_s2_r009", "subcategory_id": "hg_c5_s2", "name": "متابعة الطلاب المنومين", "order": 9},
    {"id": "hg_c5_s2_r010", "subcategory_id": "hg_c5_s2", "name": "إجراءات التحويل للمستشفى", "order": 10},
    {"id": "hg_c5_s2_r011", "subcategory_id": "hg_c5_s2", "name": "دليل التعاون مع المستشفيات", "order": 11},
    {"id": "hg_c5_s2_r012", "subcategory_id": "hg_c5_s2", "name": "ورشة عمل مع أطباء المستشفى", "order": 12},
    {"id": "hg_c5_s2_r013", "subcategory_id": "hg_c5_s2", "name": "حملة توعوية بالتعاون مع المستشفى", "order": 13},
    {"id": "hg_c5_s2_r014", "subcategory_id": "hg_c5_s2", "name": "مسح ميداني لرضا أولياء الأمور", "order": 14},
    {"id": "hg_c5_s2_r015", "subcategory_id": "hg_c5_s2", "name": "استبيان عن التعاون", "order": 15},
    {"id": "hg_c5_s2_r016", "subcategory_id": "hg_c5_s2", "name": "توثيق الأنشطة المشتركة", "order": 16},
    {"id": "hg_c5_s2_r017", "subcategory_id": "hg_c5_s2", "name": "تقرير دوري فصلي", "order": 17},
    {"id": "hg_c5_s2_r018", "subcategory_id": "hg_c5_s2", "name": "تحليل أثر التعاون", "order": 18},
    {"id": "hg_c5_s2_r019", "subcategory_id": "hg_c5_s2", "name": "مذكرة تفاهم مع المستشفى", "order": 19},
    {"id": "hg_c5_s2_r020", "subcategory_id": "hg_c5_s2", "name": "إنجازات التعاون", "order": 20},

    # hg_c5_s3 (متابعة حملات التوعية مع الجهات الخارجية)
    {"id": "hg_c5_s3_r001", "subcategory_id": "hg_c5_s3", "name": "تقرير عن متابعة حملات التوعية مع هيئة الغذاء والدواء", "order": 1},
    {"id": "hg_c5_s3_r002", "subcategory_id": "hg_c5_s3", "name": "سجل مشاركة في حملات وطنية", "order": 2},
    {"id": "hg_c5_s3_r003", "subcategory_id": "hg_c5_s3", "name": "خطة المشاركة في الحملات الخارجية", "order": 3},
    {"id": "hg_c5_s3_r004", "subcategory_id": "hg_c5_s3", "name": "إحصائية عدد الحملات المنفذة", "order": 4},
    {"id": "hg_c5_s3_r005", "subcategory_id": "hg_c5_s3", "name": "تقييم أثر الحملات", "order": 5},
    {"id": "hg_c5_s3_r006", "subcategory_id": "hg_c5_s3", "name": "توعية الطلاب باليوم العالمي للصحة", "order": 6},
    {"id": "hg_c5_s3_r007", "subcategory_id": "hg_c5_s3", "name": "تنسيق مع وزارة الصحة", "order": 7},
    {"id": "hg_c5_s3_r008", "subcategory_id": "hg_c5_s3", "name": "تحسين الترويج للحملات", "order": 8},
    {"id": "hg_c5_s3_r009", "subcategory_id": "hg_c5_s3", "name": "متابعة تنفيذ الحملات", "order": 9},
    {"id": "hg_c5_s3_r010", "subcategory_id": "hg_c5_s3", "name": "إجراءات استضافة جهات خارجية", "order": 10},
    {"id": "hg_c5_s3_r011", "subcategory_id": "hg_c5_s3", "name": "دليل الحملات التوعوية", "order": 11},
    {"id": "hg_c5_s3_r012", "subcategory_id": "hg_c5_s3", "name": "ورشة عمل مع جهات خارجية", "order": 12},
    {"id": "hg_c5_s3_r013", "subcategory_id": "hg_c5_s3", "name": "حملة توعوية عن الأكل الصحي", "order": 13},
    {"id": "hg_c5_s3_r014", "subcategory_id": "hg_c5_s3", "name": "مسح ميداني لوعي الطلاب", "order": 14},
    {"id": "hg_c5_s3_r015", "subcategory_id": "hg_c5_s3", "name": "استبيان قياس أثر الحملات", "order": 15},
    {"id": "hg_c5_s3_r016", "subcategory_id": "hg_c5_s3", "name": "توثيق الحملات", "order": 16},
    {"id": "hg_c5_s3_r017", "subcategory_id": "hg_c5_s3", "name": "تقرير دوري سنوي عن الحملات", "order": 17},
    {"id": "hg_c5_s3_r018", "subcategory_id": "hg_c5_s3", "name": "تحليل تأثير الحملات", "order": 18},
    {"id": "hg_c5_s3_r019", "subcategory_id": "hg_c5_s3", "name": "مذكرة تفاهم مع جهة خارجية", "order": 19},
    {"id": "hg_c5_s3_r020", "subcategory_id": "hg_c5_s3", "name": "إنجازات المشاركة في الحملات", "order": 20},

    # hg_c5_s4 (المشاركة في لجان الصحة المدرسية)
    {"id": "hg_c5_s4_r001", "subcategory_id": "hg_c5_s4", "name": "تقرير عن المشاركة في لجنة الصحة المدرسية", "order": 1},
    {"id": "hg_c5_s4_r002", "subcategory_id": "hg_c5_s4", "name": "سجل اجتماعات اللجنة", "order": 2},
    {"id": "hg_c5_s4_r003", "subcategory_id": "hg_c5_s4", "name": "خطة عمل اللجنة", "order": 3},
    {"id": "hg_c5_s4_r004", "subcategory_id": "hg_c5_s4", "name": "إحصائية عدد الاجتماعات", "order": 4},
    {"id": "hg_c5_s4_r005", "subcategory_id": "hg_c5_s4", "name": "تقييم أداء اللجنة", "order": 5},
    {"id": "hg_c5_s4_r006", "subcategory_id": "hg_c5_s4", "name": "توعية أعضاء اللجنة", "order": 6},
    {"id": "hg_c5_s4_r007", "subcategory_id": "hg_c5_s4", "name": "تنسيق مع أعضاء اللجنة", "order": 7},
    {"id": "hg_c5_s4_r008", "subcategory_id": "hg_c5_s4", "name": "تحسين توصيات اللجنة", "order": 8},
    {"id": "hg_c5_s4_r009", "subcategory_id": "hg_c5_s4", "name": "متابعة تنفيذ القرارات", "order": 9},
    {"id": "hg_c5_s4_r010", "subcategory_id": "hg_c5_s4", "name": "إجراءات تشكيل اللجنة", "order": 10},
    {"id": "hg_c5_s4_r011", "subcategory_id": "hg_c5_s4", "name": "دليل عمل اللجنة", "order": 11},
    {"id": "hg_c5_s4_r012", "subcategory_id": "hg_c5_s4", "name": "ورشة عمل لأعضاء اللجنة", "order": 12},
    {"id": "hg_c5_s4_r013", "subcategory_id": "hg_c5_s4", "name": "حملة توعوية من اللجنة", "order": 13},
    {"id": "hg_c5_s4_r014", "subcategory_id": "hg_c5_s4", "name": "مسح ميداني لآراء الطلاب", "order": 14},
    {"id": "hg_c5_s4_r015", "subcategory_id": "hg_c5_s4", "name": "استبيان رضا المعلمين", "order": 15},
    {"id": "hg_c5_s4_r016", "subcategory_id": "hg_c5_s4", "name": "توثيق محاضر الاجتماعات", "order": 16},
    {"id": "hg_c5_s4_r017", "subcategory_id": "hg_c5_s4", "name": "تقرير دوري شهري عن أعمال اللجنة", "order": 17},
    {"id": "hg_c5_s4_r018", "subcategory_id": "hg_c5_s4", "name": "تحليل إنجازات اللجنة", "order": 18},
    {"id": "hg_c5_s4_r019", "subcategory_id": "hg_c5_s4", "name": "مذكرة تفاهم مع جهات خارجية", "order": 19},
    {"id": "hg_c5_s4_r020", "subcategory_id": "hg_c5_s4", "name": "إنجازات اللجنة خلال العام", "order": 20},

    # hg_c5_s5 (التنسيق مع الصحة العامة)
    {"id": "hg_c5_s5_r001", "subcategory_id": "hg_c5_s5", "name": "تقرير عن التنسيق مع الصحة العامة في الأوبئة", "order": 1},
    {"id": "hg_c5_s5_r002", "subcategory_id": "hg_c5_s5", "name": "سجل متابعة تعاميم وزارة الصحة", "order": 2},
    {"id": "hg_c5_s5_r003", "subcategory_id": "hg_c5_s5", "name": "خطة التنسيق مع الصحة العامة", "order": 3},
    {"id": "hg_c5_s5_r004", "subcategory_id": "hg_c5_s5", "name": "إحصائية عدد التعاميم المنفذة", "order": 4},
    {"id": "hg_c5_s5_r005", "subcategory_id": "hg_c5_s5", "name": "تقييم إجراءات مكافحة العدوى", "order": 5},
    {"id": "hg_c5_s5_r006", "subcategory_id": "hg_c5_s5", "name": "توعية الطلاب بالوقاية من الأوبئة", "order": 6},
    {"id": "hg_c5_s5_r007", "subcategory_id": "hg_c5_s5", "name": "تنسيق مع فرق التقصي الوبائي", "order": 7},
    {"id": "hg_c5_s5_r008", "subcategory_id": "hg_c5_s5", "name": "تحسين الإبلاغ عن الأمراض", "order": 8},
    {"id": "hg_c5_s5_r009", "subcategory_id": "hg_c5_s5", "name": "متابعة تنفيذ إجراءات العزل", "order": 9},
    {"id": "hg_c5_s5_r010", "subcategory_id": "hg_c5_s5", "name": "إجراءات التعامل مع الاشتباه", "order": 10},
    {"id": "hg_c5_s5_r011", "subcategory_id": "hg_c5_s5", "name": "دليل التعامل مع الأوبئة", "order": 11},
    {"id": "hg_c5_s5_r012", "subcategory_id": "hg_c5_s5", "name": "ورشة عمل عن مكافحة العدوى", "order": 12},
    {"id": "hg_c5_s5_r013", "subcategory_id": "hg_c5_s5", "name": "حملة توعوية عن النظافة للوقاية", "order": 13},
    {"id": "hg_c5_s5_r014", "subcategory_id": "hg_c5_s5", "name": "مسح ميداني لمدى الوعي", "order": 14},
    {"id": "hg_c5_s5_r015", "subcategory_id": "hg_c5_s5", "name": "استبيان عن تطبيق الإجراءات", "order": 15},
    {"id": "hg_c5_s5_r016", "subcategory_id": "hg_c5_s5", "name": "توثيق الإبلاغ", "order": 16},
    {"id": "hg_c5_s5_r017", "subcategory_id": "hg_c5_s5", "name": "تقرير دوري شهري عن الصحة العامة", "order": 17},
    {"id": "hg_c5_s5_r018", "subcategory_id": "hg_c5_s5", "name": "تحليل فعالية التنسيق", "order": 18},
    {"id": "hg_c5_s5_r019", "subcategory_id": "hg_c5_s5", "name": "مذكرة تفاهم مع الصحة العامة", "order": 19},
    {"id": "hg_c5_s5_r020", "subcategory_id": "hg_c5_s5", "name": "إنجازات التنسيق مع الصحة العامة", "order": 20}
]

# قالب البرومبت
HEALTH_GUIDE_PROMPT_TEMPLATE = """أنت موجه صحي مسؤول عن تنفيذ البرامج الصحية المدرسية وتعزيز بيئة تعليمية آمنة وفق الأنظمة المعتمدة.

المطلوب:
- عرض معيار الأداء الوظيفي.
- عرض التصنيف الفرعي.
- كتابة تقرير مهني يوضح الإجراءات والممارسات المرتبطة بهذا التصنيف.

التقرير المطلوب: "{report_name}"
وهو يندرج تحت التصنيف الفرعي: "{subcategory_name}"
ضمن المعيار التربوي: "{criterion_name}"

{subject_line}
{lesson_line}
{grade_line}
{target_line}
{place_line}
{count_line}

ضوابط الكتابة:
- لغة إدارية صحية رسمية.
- إبراز دورك في الوقاية والتوعية والمتابعة الصحية.
- توضيح آلية تنفيذ البرامج الصحية المدرسية.
- الإشارة إلى رصد الحالات الصحية والتنسيق مع الجهات المختصة.
- بيان دورك في تهيئة بيئة مدرسية آمنة وصحية.
- إبراز استخدام التقنية أو النماذج المعتمدة في التوثيق.
- توضيح أثر الجهود على سلامة الطلاب واستقرار العملية التعليمية.
- صياغة عملية دقيقة من 5–7 أسطر.

 دورك كموجه صحي
1. رفع الوعي الصحي لدى الطلاب وتعزيز السلوكيات الوقائية بما يدعم جاهزيتهم للتعلم ويقلل من المشكلات الصحية المؤثرة على التحصيل.

2. نفذت مبادرة توعوية حول العادات الصحية اليومية وتأثيرها على التركيز والطاقة داخل الصف بما يعزز جودة التعلم.

3. قدمت لقاءات توعوية قصيرة، ووزعت مواد إرشادية، وتابعت الحالات الصحية البسيطة، ونسقت مع المعلمين لملاحظة أثر السلوك الصحي على الأداء الدراسي.

4. اعتمدت التعلم بالمواقف، والعرض التفاعلي، والمناقشة الموجهة، وربط المفاهيم الصحية بالحياة اليومية للطلاب داخل المدرسة وخارجها.

5. ارتفع وعي الطلاب بأهمية التغذية السليمة والنظافة الشخصية، وتحسن مستوى الانتباه خلال الحصص، وقلّت الشكاوى الصحية البسيطة.

6. الحاجة إلى تفعيل برامج متابعة مستمرة للسلوكيات الصحية، وتعزيز مشاركة الأسرة في دعم الممارسات الوقائية.

7. أوصي بإدراج خطة صحية سنوية تكاملية، وتنفيذ حملات دورية، وبناء شراكات مجتمعية تدعم الثقافة الصحية المدرسية.
**الحقول المطلوبة:**
1. الهدف التربوي
2. نبذة مختصرة
3. إجراءات التنفيذ
4. الاستراتيجيات المستخدمة
5. نقاط القوة
6. نقاط التحسين
7. التوصيات

يرجى تقديم الإجابة باللغة العربية الفصحى، وتنظيمها بحيث يكون كل حقل في سطر منفصل يبدأ برقمه فقط دون ذكر العنوان."""