# -*- coding: utf-8 -*-

# قائمة المعايير الرئيسية لمعلمة رياض الأطفال
KG_CRITERIA = [
    {"id": "kg_c1", "name": "أداء الواجبات الوظيفية", "weight": 10, "order": 1},
    {"id": "kg_c2", "name": "التفاعل مع المجتمع المهني", "weight": 5, "order": 2},
    {"id": "kg_c3", "name": "التفاعل مع أولياء الأمور", "weight": 5, "order": 3},
    {"id": "kg_c4", "name": "التنوع في استراتيجيات التدريس", "weight": 5, "order": 4},
    {"id": "kg_c5", "name": "تحسين نتائج المتعلمين", "weight": 5, "order": 5},
    {"id": "kg_c6", "name": "إعداد خطة شاملة وتفصيلية للأنشطة", "weight": 5, "order": 6},
    {"id": "kg_c7", "name": "تصميم خبرات تعلم مرنة ومبتكرة", "weight": 5, "order": 7},
    {"id": "kg_c8", "name": "توظيف تقنيات ووسائل التعلم المناسبة", "weight": 5, "order": 8},
    {"id": "kg_c9", "name": "التمكن من المادة العلمية", "weight": 5, "order": 9},
    {"id": "kg_c10", "name": "استخدام استراتيجيات تدريس فاعلة ومتنوعة", "weight": 5, "order": 10},
    {"id": "kg_c11", "name": "إشراك الأسرة في خطط النمو والتعلم", "weight": 5, "order": 11},
    {"id": "kg_c12", "name": "تهيئة بيئة تعليمية آمنة ومعززة للتطور النمائي والتعلم", "weight": 15, "order": 12},
    {"id": "kg_c13", "name": "توفير فرص متنوعة لدعم التفاعلات في بيئة التعلم", "weight": 5, "order": 13},
    {"id": "kg_c14", "name": "تقويم تعلم المتعلمين ومتابعة تقدمهم بانتظام", "weight": 5, "order": 14},
    {"id": "kg_c15", "name": "استثمار نتائج التقويم في تعزيز النمو والتعلم", "weight": 5, "order": 15},
    {"id": "kg_c16", "name": "إشراك الأسرة في نتائج التقويم", "weight": 5, "order": 16},
    {"id": "kg_c17", "name": "دعم تحقيق مستويات الأداء المستهدفة لكل متعلم", "weight": 5, "order": 17},
    {"id": "kg_c18", "name": "دعم مهارات المستقبل لدى المتعلمين", "weight": 5, "order": 18},
    {"id": "kg_c19", "name": "دعم اكتساب المتعلمين القيم والمبادئ والاتجاهات", "weight": 5, "order": 19},
]

# التصنيفات الفرعية (تم إنشاؤها من القائمة النقطية لكل معيار)
KG_SUBCATEGORIES = [
    # kg_c1
    {"id": "kg_c1_s1", "criterion_id": "kg_c1", "name": "الالتزام بالأنظمة واللوائح المنظمة للعمل", "order": 1},
    {"id": "kg_c1_s2", "criterion_id": "kg_c1", "name": "تطبيق أخلاقيات المهنة والسلوك الوظيفي", "order": 2},
    {"id": "kg_c1_s3", "criterion_id": "kg_c1", "name": "المحافظة على سرية بيانات الأطفال", "order": 3},
    {"id": "kg_c1_s4", "criterion_id": "kg_c1", "name": "تنفيذ المهام التربوية بانضباط ومسؤولية", "order": 4},
    # kg_c2
    {"id": "kg_c2_s1", "criterion_id": "kg_c2", "name": "المشاركة في البرامج المهنية وورش العمل", "order": 1},
    {"id": "kg_c2_s2", "criterion_id": "kg_c2", "name": "تبادل الخبرات مع الزميلات", "order": 2},
    {"id": "kg_c2_s3", "criterion_id": "kg_c2", "name": "الإسهام في تطوير البيئة التعليمية", "order": 3},
    {"id": "kg_c2_s4", "criterion_id": "kg_c2", "name": "الاستفادة من التغذية الراجعة لتحسين الأداء", "order": 4},
    # kg_c3
    {"id": "kg_c3_s1", "criterion_id": "kg_c3", "name": "التواصل المنتظم مع الأسرة", "order": 1},
    {"id": "kg_c3_s2", "criterion_id": "kg_c3", "name": "تزويد الأسرة بتقارير عن تقدم الطفل", "order": 2},
    {"id": "kg_c3_s3", "criterion_id": "kg_c3", "name": "إشراك الأسرة في دعم تعلم الطفل", "order": 3},
    {"id": "kg_c3_s4", "criterion_id": "kg_c3", "name": "الاستجابة لملاحظات ومقترحات أولياء الأمور", "order": 4},
    # kg_c4
    {"id": "kg_c4_s1", "criterion_id": "kg_c4", "name": "استخدام التعلم باللعب", "order": 1},
    {"id": "kg_c4_s2", "criterion_id": "kg_c4", "name": "تنويع أساليب العرض", "order": 2},
    {"id": "kg_c4_s3", "criterion_id": "kg_c4", "name": "مراعاة الفروق الفردية", "order": 3},
    {"id": "kg_c4_s4", "criterion_id": "kg_c4", "name": "توظيف أنشطة فردية وجماعية", "order": 4},
    # kg_c5
    {"id": "kg_c5_s1", "criterion_id": "kg_c5", "name": "تحديد أهداف تعليمية واضحة", "order": 1},
    {"id": "kg_c5_s2", "criterion_id": "kg_c5", "name": "متابعة تقدم الأطفال بانتظام", "order": 2},
    {"id": "kg_c5_s3", "criterion_id": "kg_c5", "name": "تقديم دعم للحالات التي تحتاج تدخل", "order": 3},
    {"id": "kg_c5_s4", "criterion_id": "kg_c5", "name": "تحفيز الأطفال لتحقيق تقدم مستمر", "order": 4},
    # kg_c6
    {"id": "kg_c6_s1", "criterion_id": "kg_c6", "name": "تحليل احتياجات الأطفال وخصائصهم النمائية", "order": 1},
    {"id": "kg_c6_s2", "criterion_id": "kg_c6", "name": "صياغة أهداف مناسبة للمرحلة العمرية", "order": 2},
    {"id": "kg_c6_s3", "criterion_id": "kg_c6", "name": "تصميم أنشطة مترابطة تدعم النمو الشامل", "order": 3},
    {"id": "kg_c6_s4", "criterion_id": "kg_c6", "name": "اختيار استراتيجيات ووسائل تعليمية ملائمة", "order": 4},
    {"id": "kg_c6_s5", "criterion_id": "kg_c6", "name": "تضمين أدوات تقويم متنوعة في الخطة", "order": 5},
    # kg_c7
    {"id": "kg_c7_s1", "criterion_id": "kg_c7", "name": "تصميم خبرات تعليمية قائمة على الاستكشاف", "order": 1},
    {"id": "kg_c7_s2", "criterion_id": "kg_c7", "name": "دمج الأنشطة الحسية والتطبيقية", "order": 2},
    {"id": "kg_c7_s3", "criterion_id": "kg_c7", "name": "مراعاة اهتمامات الأطفال", "order": 3},
    {"id": "kg_c7_s4", "criterion_id": "kg_c7", "name": "تعزيز التعلم من خلال المواقف اليومية", "order": 4},
    # kg_c8
    {"id": "kg_c8_s1", "criterion_id": "kg_c8", "name": "استخدام وسائل تعليمية مناسبة للفئة العمرية", "order": 1},
    {"id": "kg_c8_s2", "criterion_id": "kg_c8", "name": "توظيف التقنيات الحديثة لدعم التعلم", "order": 2},
    {"id": "kg_c8_s3", "criterion_id": "kg_c8", "name": "دعم تنمية المهارات المختلفة", "order": 3},
    {"id": "kg_c8_s4", "criterion_id": "kg_c8", "name": "تحقيق التوازن بين التعلم الحسي والمجرد", "order": 4},
    # kg_c9
    {"id": "kg_c9_s1", "criterion_id": "kg_c9", "name": "الفهم العميق لمحتوى التعلم", "order": 1},
    {"id": "kg_c9_s2", "criterion_id": "kg_c9", "name": "تبسيط المفاهيم للأطفال", "order": 2},
    {"id": "kg_c9_s3", "criterion_id": "kg_c9", "name": "ربط التعلم بخبرات الطفل اليومية", "order": 3},
    # kg_c10
    {"id": "kg_c10_s1", "criterion_id": "kg_c10", "name": "تطبيق استراتيجيات مخططة ومنظمة", "order": 1},
    {"id": "kg_c10_s2", "criterion_id": "kg_c10", "name": "تنويع أساليب التعليم", "order": 2},
    {"id": "kg_c10_s3", "criterion_id": "kg_c10", "name": "استخدام التعزيز الإيجابي", "order": 3},
    {"id": "kg_c10_s4", "criterion_id": "kg_c10", "name": "إدارة وقت الحصة بفاعلية", "order": 4},
    # kg_c11
    {"id": "kg_c11_s1", "criterion_id": "kg_c11", "name": "إشراك الأسرة في متابعة النمو النمائي", "order": 1},
    {"id": "kg_c11_s2", "criterion_id": "kg_c11", "name": "تقديم إرشادات لدعم التعلم المنزلي", "order": 2},
    {"id": "kg_c11_s3", "criterion_id": "kg_c11", "name": "إشراكهم في الأنشطة التربوية", "order": 3},
    # kg_c12
    {"id": "kg_c12_s1", "criterion_id": "kg_c12", "name": "تنظيم الأركان التعليمية بما يعزز الاستقلالية", "order": 1},
    {"id": "kg_c12_s2", "criterion_id": "kg_c12", "name": "توفير أدوات تعليمية آمنة ومتنوعة", "order": 2},
    {"id": "kg_c12_s3", "criterion_id": "kg_c12", "name": "تعزيز الأمان النفسي والانفعالي", "order": 3},
    {"id": "kg_c12_s4", "criterion_id": "kg_c12", "name": "دعم النمو المعرفي والاجتماعي والحركي", "order": 4},
    {"id": "kg_c12_s5", "criterion_id": "kg_c12", "name": "تحفيز الأطفال على المبادرة والمشاركة", "order": 5},
    # kg_c13
    {"id": "kg_c13_s1", "criterion_id": "kg_c13", "name": "تنظيم أنشطة تعاونية", "order": 1},
    {"id": "kg_c13_s2", "criterion_id": "kg_c13", "name": "تشجيع الحوار بين الأطفال", "order": 2},
    {"id": "kg_c13_s3", "criterion_id": "kg_c13", "name": "تصميم مواقف تعليمية تفاعلية", "order": 3},
    {"id": "kg_c13_s4", "criterion_id": "kg_c13", "name": "دعم اللعب الجماعي المنظم", "order": 4},
    # kg_c14
    {"id": "kg_c14_s1", "criterion_id": "kg_c14", "name": "استخدام أدوات تقويم متنوعة", "order": 1},
    {"id": "kg_c14_s2", "criterion_id": "kg_c14", "name": "توثيق تقدم كل طفل", "order": 2},
    {"id": "kg_c14_s3", "criterion_id": "kg_c14", "name": "تحليل نتائج التقويم", "order": 3},
    {"id": "kg_c14_s4", "criterion_id": "kg_c14", "name": "إعداد تقارير دورية", "order": 4},
    # kg_c15
    {"id": "kg_c15_s1", "criterion_id": "kg_c15", "name": "تعديل الخطط بناءً على نتائج التقويم", "order": 1},
    {"id": "kg_c15_s2", "criterion_id": "kg_c15", "name": "تصميم أنشطة علاجية أو إثرائية", "order": 2},
    {"id": "kg_c15_s3", "criterion_id": "kg_c15", "name": "معالجة جوانب الضعف", "order": 3},
    {"id": "kg_c15_s4", "criterion_id": "kg_c15", "name": "تعزيز نقاط القوة", "order": 4},
    # kg_c16
    {"id": "kg_c16_s1", "criterion_id": "kg_c16", "name": "إطلاع الأسرة على نتائج التقييم", "order": 1},
    {"id": "kg_c16_s2", "criterion_id": "kg_c16", "name": "مناقشة خطط الدعم", "order": 2},
    {"id": "kg_c16_s3", "criterion_id": "kg_c16", "name": "إشراك الأسرة في تنفيذ خطط التحسين", "order": 3},
    # kg_c17
    {"id": "kg_c17_s1", "criterion_id": "kg_c17", "name": "وضع أهداف فردية لكل طفل", "order": 1},
    {"id": "kg_c17_s2", "criterion_id": "kg_c17", "name": "متابعة تحقيق الأهداف", "order": 2},
    {"id": "kg_c17_s3", "criterion_id": "kg_c17", "name": "تقديم دعم فردي عند الحاجة", "order": 3},
    {"id": "kg_c17_s4", "criterion_id": "kg_c17", "name": "توثيق التقدم المحقق", "order": 4},
    # kg_c18
    {"id": "kg_c18_s1", "criterion_id": "kg_c18", "name": "تنمية مهارات التفكير والإبداع", "order": 1},
    {"id": "kg_c18_s2", "criterion_id": "kg_c18", "name": "تعزيز مهارات التواصل", "order": 2},
    {"id": "kg_c18_s3", "criterion_id": "kg_c18", "name": "غرس مهارات حل المشكلات", "order": 3},
    {"id": "kg_c18_s4", "criterion_id": "kg_c18", "name": "تشجيع التعلم الذاتي", "order": 4},
    # kg_c19
    {"id": "kg_c19_s1", "criterion_id": "kg_c19", "name": "غرس القيم الإيجابية", "order": 1},
    {"id": "kg_c19_s2", "criterion_id": "kg_c19", "name": "تعزيز احترام الآخرين", "order": 2},
    {"id": "kg_c19_s3", "criterion_id": "kg_c19", "name": "تنمية روح التعاون", "order": 3},
    {"id": "kg_c19_s4", "criterion_id": "kg_c19", "name": "دعم السلوكيات الإيجابية", "order": 4}
]

# قائمة التقارير (10 لكل تصنيف فرعي)
KG_REPORTS = [
    # kg_c1_s1
    {"id": "kg_c1_s1_r001", "subcategory_id": "kg_c1_s1", "name": "تقرير عن الالتزام بالأنظمة واللوائح المنظمة للعمل", "order": 1},
    {"id": "kg_c1_s1_r002", "subcategory_id": "kg_c1_s1", "name": "سجل متابعة تنفيذ اللوائح المنظمة", "order": 2},
    {"id": "kg_c1_s1_r003", "subcategory_id": "kg_c1_s1", "name": "خطة تحسين الالتزام بالأنظمة", "order": 3},
    {"id": "kg_c1_s1_r004", "subcategory_id": "kg_c1_s1", "name": "إحصائية مدى الالتزام باللوائح", "order": 4},
    {"id": "kg_c1_s1_r005", "subcategory_id": "kg_c1_s1", "name": "تقييم تطبيق الأنظمة في العمل", "order": 5},
    {"id": "kg_c1_s1_r006", "subcategory_id": "kg_c1_s1", "name": "توعية الموظفين بالأنظمة المنظمة", "order": 6},
    {"id": "kg_c1_s1_r007", "subcategory_id": "kg_c1_s1", "name": "تنسيق مع الإدارة لتطبيق اللوائح", "order": 7},
    {"id": "kg_c1_s1_r008", "subcategory_id": "kg_c1_s1", "name": "تحسين إجراءات الالتزام", "order": 8},
    {"id": "kg_c1_s1_r009", "subcategory_id": "kg_c1_s1", "name": "متابعة حالات المخالفات", "order": 9},
    {"id": "kg_c1_s1_r010", "subcategory_id": "kg_c1_s1", "name": "توثيق الالتزام بالأنظمة", "order": 10},
    # kg_c1_s2
    {"id": "kg_c1_s2_r001", "subcategory_id": "kg_c1_s2", "name": "تقرير عن تطبيق أخلاقيات المهنة والسلوك الوظيفي", "order": 1},
    {"id": "kg_c1_s2_r002", "subcategory_id": "kg_c1_s2", "name": "سجل متابعة السلوك المهني", "order": 2},
    {"id": "kg_c1_s2_r003", "subcategory_id": "kg_c1_s2", "name": "خطة تعزيز أخلاقيات المهنة", "order": 3},
    {"id": "kg_c1_s2_r004", "subcategory_id": "kg_c1_s2", "name": "إحصائية مدى الالتزام بأخلاقيات المهنة", "order": 4},
    {"id": "kg_c1_s2_r005", "subcategory_id": "kg_c1_s2", "name": "تقييم السلوك الوظيفي للمعلمات", "order": 5},
    {"id": "kg_c1_s2_r006", "subcategory_id": "kg_c1_s2", "name": "توعية بأخلاقيات المهنة", "order": 6},
    {"id": "kg_c1_s2_r007", "subcategory_id": "kg_c1_s2", "name": "تنسيق مع المشرفات لتعزيز السلوك", "order": 7},
    {"id": "kg_c1_s2_r008", "subcategory_id": "kg_c1_s2", "name": "تحسين الممارسات المهنية", "order": 8},
    {"id": "kg_c1_s2_r009", "subcategory_id": "kg_c1_s2", "name": "متابعة حالات السلوك غير اللائق", "order": 9},
    {"id": "kg_c1_s2_r010", "subcategory_id": "kg_c1_s2", "name": "توثيق تطبيق أخلاقيات المهنة", "order": 10},
    # kg_c1_s3
    {"id": "kg_c1_s3_r001", "subcategory_id": "kg_c1_s3", "name": "تقرير عن المحافظة على سرية بيانات الأطفال", "order": 1},
    {"id": "kg_c1_s3_r002", "subcategory_id": "kg_c1_s3", "name": "سجل ضبط الوصول للمعلومات", "order": 2},
    {"id": "kg_c1_s3_r003", "subcategory_id": "kg_c1_s3", "name": "خطة حماية بيانات الأطفال", "order": 3},
    {"id": "kg_c1_s3_r004", "subcategory_id": "kg_c1_s3", "name": "إحصائية مدى التزام السرية", "order": 4},
    {"id": "kg_c1_s3_r005", "subcategory_id": "kg_c1_s3", "name": "تقييم إجراءات حفظ البيانات", "order": 5},
    {"id": "kg_c1_s3_r006", "subcategory_id": "kg_c1_s3", "name": "توعية الموظفات بسرية المعلومات", "order": 6},
    {"id": "kg_c1_s3_r007", "subcategory_id": "kg_c1_s3", "name": "تنسيق مع إدارة المعلومات لحماية البيانات", "order": 7},
    {"id": "kg_c1_s3_r008", "subcategory_id": "kg_c1_s3", "name": "تحسين أنظمة الخصوصية", "order": 8},
    {"id": "kg_c1_s3_r009", "subcategory_id": "kg_c1_s3", "name": "متابعة حالات اختراق الخصوصية", "order": 9},
    {"id": "kg_c1_s3_r010", "subcategory_id": "kg_c1_s3", "name": "توثيق إجراءات السرية", "order": 10},
    # kg_c1_s4
    {"id": "kg_c1_s4_r001", "subcategory_id": "kg_c1_s4", "name": "تقرير عن تنفيذ المهام التربوية بانضباط ومسؤولية", "order": 1},
    {"id": "kg_c1_s4_r002", "subcategory_id": "kg_c1_s4", "name": "سجل إنجاز المهام اليومية", "order": 2},
    {"id": "kg_c1_s4_r003", "subcategory_id": "kg_c1_s4", "name": "خطة تحسين الانضباط الوظيفي", "order": 3},
    {"id": "kg_c1_s4_r004", "subcategory_id": "kg_c1_s4", "name": "إحصائية الالتزام بالمهام", "order": 4},
    {"id": "kg_c1_s4_r005", "subcategory_id": "kg_c1_s4", "name": "تقييم أداء المهام التربوية", "order": 5},
    {"id": "kg_c1_s4_r006", "subcategory_id": "kg_c1_s4", "name": "توعية بأهمية الانضباط", "order": 6},
    {"id": "kg_c1_s4_r007", "subcategory_id": "kg_c1_s4", "name": "تنسيق مع القيادة لتوزيع المهام", "order": 7},
    {"id": "kg_c1_s4_r008", "subcategory_id": "kg_c1_s4", "name": "تحسين تنظيم المهام", "order": 8},
    {"id": "kg_c1_s4_r009", "subcategory_id": "kg_c1_s4", "name": "متابعة حالات التأخير", "order": 9},
    {"id": "kg_c1_s4_r010", "subcategory_id": "kg_c1_s4", "name": "توثيق إنجاز المهام", "order": 10},
    # kg_c2_s1
    {"id": "kg_c2_s1_r001", "subcategory_id": "kg_c2_s1", "name": "تقرير عن المشاركة في البرامج المهنية وورش العمل", "order": 1},
    {"id": "kg_c2_s1_r002", "subcategory_id": "kg_c2_s1", "name": "سجل حضور الفعاليات المهنية", "order": 2},
    {"id": "kg_c2_s1_r003", "subcategory_id": "kg_c2_s1", "name": "خطة التطوير المهني", "order": 3},
    {"id": "kg_c2_s1_r004", "subcategory_id": "kg_c2_s1", "name": "إحصائية عدد البرامج المنفذة", "order": 4},
    {"id": "kg_c2_s1_r005", "subcategory_id": "kg_c2_s1", "name": "تقييم أثر المشاركة على الأداء", "order": 5},
    {"id": "kg_c2_s1_r006", "subcategory_id": "kg_c2_s1", "name": "توعية بأهمية التطوير المهني", "order": 6},
    {"id": "kg_c2_s1_r007", "subcategory_id": "kg_c2_s1", "name": "تنسيق مع وحدة التدريب", "order": 7},
    {"id": "kg_c2_s1_r008", "subcategory_id": "kg_c2_s1", "name": "تحسين اختيار البرامج", "order": 8},
    {"id": "kg_c2_s1_r009", "subcategory_id": "kg_c2_s1", "name": "متابعة تطبيق المكتسبات", "order": 9},
    {"id": "kg_c2_s1_r010", "subcategory_id": "kg_c2_s1", "name": "توثيق المشاركات المهنية", "order": 10},
    # kg_c2_s2
    {"id": "kg_c2_s2_r001", "subcategory_id": "kg_c2_s2", "name": "تقرير عن تبادل الخبرات مع الزميلات", "order": 1},
    {"id": "kg_c2_s2_r002", "subcategory_id": "kg_c2_s2", "name": "سجل اجتماعات التبادل المهني", "order": 2},
    {"id": "kg_c2_s2_r003", "subcategory_id": "kg_c2_s2", "name": "خطة تعزيز التعاون بين الزميلات", "order": 3},
    {"id": "kg_c2_s2_r004", "subcategory_id": "kg_c2_s2", "name": "إحصائية عدد جلسات التبادل", "order": 4},
    {"id": "kg_c2_s2_r005", "subcategory_id": "kg_c2_s2", "name": "تقييم فعالية تبادل الخبرات", "order": 5},
    {"id": "kg_c2_s2_r006", "subcategory_id": "kg_c2_s2", "name": "توعية بأهمية التعاون", "order": 6},
    {"id": "kg_c2_s2_r007", "subcategory_id": "kg_c2_s2", "name": "تنسيق لعقد لقاءات دورية", "order": 7},
    {"id": "kg_c2_s2_r008", "subcategory_id": "kg_c2_s2", "name": "تحسين آليات التبادل", "order": 8},
    {"id": "kg_c2_s2_r009", "subcategory_id": "kg_c2_s2", "name": "متابعة تطبيق الخبرات", "order": 9},
    {"id": "kg_c2_s2_r010", "subcategory_id": "kg_c2_s2", "name": "توثيق الخبرات المتبادلة", "order": 10},
    # kg_c2_s3
    {"id": "kg_c2_s3_r001", "subcategory_id": "kg_c2_s3", "name": "تقرير عن الإسهام في تطوير البيئة التعليمية", "order": 1},
    {"id": "kg_c2_s3_r002", "subcategory_id": "kg_c2_s3", "name": "سجل المبادرات التطويرية", "order": 2},
    {"id": "kg_c2_s3_r003", "subcategory_id": "kg_c2_s3", "name": "خطة تحسين البيئة الصفية", "order": 3},
    {"id": "kg_c2_s3_r004", "subcategory_id": "kg_c2_s3", "name": "إحصائية عدد التغييرات المطبقة", "order": 4},
    {"id": "kg_c2_s3_r005", "subcategory_id": "kg_c2_s3", "name": "تقييم أثر التطوير على التعلم", "order": 5},
    {"id": "kg_c2_s3_r006", "subcategory_id": "kg_c2_s3", "name": "توعية بأهمية البيئة المحفزة", "order": 6},
    {"id": "kg_c2_s3_r007", "subcategory_id": "kg_c2_s3", "name": "تنسيق مع الإدارة لتنفيذ التطوير", "order": 7},
    {"id": "kg_c2_s3_r008", "subcategory_id": "kg_c2_s3", "name": "تحسين جودة الأركان التعليمية", "order": 8},
    {"id": "kg_c2_s3_r009", "subcategory_id": "kg_c2_s3", "name": "متابعة استمرارية التطوير", "order": 9},
    {"id": "kg_c2_s3_r010", "subcategory_id": "kg_c2_s3", "name": "توثيق إسهامات التطوير", "order": 10},
    # kg_c2_s4
    {"id": "kg_c2_s4_r001", "subcategory_id": "kg_c2_s4", "name": "تقرير عن الاستفادة من التغذية الراجعة لتحسين الأداء", "order": 1},
    {"id": "kg_c2_s4_r002", "subcategory_id": "kg_c2_s4", "name": "سجل تلقي التغذية الراجعة", "order": 2},
    {"id": "kg_c2_s4_r003", "subcategory_id": "kg_c2_s4", "name": "خطة تحسين الأداء بناءً على التغذية", "order": 3},
    {"id": "kg_c2_s4_r004", "subcategory_id": "kg_c2_s4", "name": "إحصائية مدى الاستفادة من الملاحظات", "order": 4},
    {"id": "kg_c2_s4_r005", "subcategory_id": "kg_c2_s4", "name": "تقييم تطبيق التغذية الراجعة", "order": 5},
    {"id": "kg_c2_s4_r006", "subcategory_id": "kg_c2_s4", "name": "توعية بقيمة التغذية الراجعة", "order": 6},
    {"id": "kg_c2_s4_r007", "subcategory_id": "kg_c2_s4", "name": "تنسيق مع المشرفات لجمع التغذية", "order": 7},
    {"id": "kg_c2_s4_r008", "subcategory_id": "kg_c2_s4", "name": "تحسين آليات الاستجابة", "order": 8},
    {"id": "kg_c2_s4_r009", "subcategory_id": "kg_c2_s4", "name": "متابعة أثر التغذية على الأداء", "order": 9},
    {"id": "kg_c2_s4_r010", "subcategory_id": "kg_c2_s4", "name": "توثيق التحسينات المستندة للتغذية", "order": 10},
    # kg_c3_s1
    {"id": "kg_c3_s1_r001", "subcategory_id": "kg_c3_s1", "name": "تقرير عن التواصل المنتظم مع الأسرة", "order": 1},
    {"id": "kg_c3_s1_r002", "subcategory_id": "kg_c3_s1", "name": "سجل قنوات التواصل مع أولياء الأمور", "order": 2},
    {"id": "kg_c3_s1_r003", "subcategory_id": "kg_c3_s1", "name": "خطة تعزيز التواصل الأسري", "order": 3},
    {"id": "kg_c3_s1_r004", "subcategory_id": "kg_c3_s1", "name": "إحصائية عدد مرات التواصل", "order": 4},
    {"id": "kg_c3_s1_r005", "subcategory_id": "kg_c3_s1", "name": "تقييم فعالية التواصل", "order": 5},
    {"id": "kg_c3_s1_r006", "subcategory_id": "kg_c3_s1", "name": "توعية بأهمية التواصل", "order": 6},
    {"id": "kg_c3_s1_r007", "subcategory_id": "kg_c3_s1", "name": "تنسيق مع الإدارة لتوفير وسائل التواصل", "order": 7},
    {"id": "kg_c3_s1_r008", "subcategory_id": "kg_c3_s1", "name": "تحسين جودة التواصل", "order": 8},
    {"id": "kg_c3_s1_r009", "subcategory_id": "kg_c3_s1", "name": "متابعة استجابة الأسر", "order": 9},
    {"id": "kg_c3_s1_r010", "subcategory_id": "kg_c3_s1", "name": "توثيق التواصل مع الأسر", "order": 10},
    # kg_c3_s2
    {"id": "kg_c3_s2_r001", "subcategory_id": "kg_c3_s2", "name": "تقرير عن تزويد الأسرة بتقارير عن تقدم الطفل", "order": 1},
    {"id": "kg_c3_s2_r002", "subcategory_id": "kg_c3_s2", "name": "سجل إرسال التقارير الدورية", "order": 2},
    {"id": "kg_c3_s2_r003", "subcategory_id": "kg_c3_s2", "name": "خطة تحسين تقارير التقدم", "order": 3},
    {"id": "kg_c3_s2_r004", "subcategory_id": "kg_c3_s2", "name": "إحصائية مدى رضا الأسر عن التقارير", "order": 4},
    {"id": "kg_c3_s2_r005", "subcategory_id": "kg_c3_s2", "name": "تقييم وضوح التقارير", "order": 5},
    {"id": "kg_c3_s2_r006", "subcategory_id": "kg_c3_s2", "name": "توعية بأهمية متابعة التقارير", "order": 6},
    {"id": "kg_c3_s2_r007", "subcategory_id": "kg_c3_s2", "name": "تنسيق مع المعلمات لإعداد التقارير", "order": 7},
    {"id": "kg_c3_s2_r008", "subcategory_id": "kg_c3_s2", "name": "تحسين محتوى التقارير", "order": 8},
    {"id": "kg_c3_s2_r009", "subcategory_id": "kg_c3_s2", "name": "متابعة تفاعل الأسر مع التقارير", "order": 9},
    {"id": "kg_c3_s2_r010", "subcategory_id": "kg_c3_s2", "name": "توثيق التقارير المرسلة", "order": 10},
    # kg_c3_s3
    {"id": "kg_c3_s3_r001", "subcategory_id": "kg_c3_s3", "name": "تقرير عن إشراك الأسرة في دعم تعلم الطفل", "order": 1},
    {"id": "kg_c3_s3_r002", "subcategory_id": "kg_c3_s3", "name": "سجل مشاركات الأسر في الأنشطة", "order": 2},
    {"id": "kg_c3_s3_r003", "subcategory_id": "kg_c3_s3", "name": "خطة إشراك الأسر في التعلم", "order": 3},
    {"id": "kg_c3_s3_r004", "subcategory_id": "kg_c3_s3", "name": "إحصائية عدد الأسر المشاركة", "order": 4},
    {"id": "kg_c3_s3_r005", "subcategory_id": "kg_c3_s3", "name": "تقييم أثر الإشراك على تعلم الطفل", "order": 5},
    {"id": "kg_c3_s3_r006", "subcategory_id": "kg_c3_s3", "name": "توعية الأسر بدورهم في التعلم", "order": 6},
    {"id": "kg_c3_s3_r007", "subcategory_id": "kg_c3_s3", "name": "تنسيق مع الأسر لتحديد أدوارهم", "order": 7},
    {"id": "kg_c3_s3_r008", "subcategory_id": "kg_c3_s3", "name": "تحسين أنشطة الإشراك", "order": 8},
    {"id": "kg_c3_s3_r009", "subcategory_id": "kg_c3_s3", "name": "متابعة استمرارية مشاركة الأسر", "order": 9},
    {"id": "kg_c3_s3_r010", "subcategory_id": "kg_c3_s3", "name": "توثيق إسهامات الأسر", "order": 10},
    # kg_c3_s4
    {"id": "kg_c3_s4_r001", "subcategory_id": "kg_c3_s4", "name": "تقرير عن الاستجابة لملاحظات ومقترحات أولياء الأمور", "order": 1},
    {"id": "kg_c3_s4_r002", "subcategory_id": "kg_c3_s4", "name": "سجل ملاحظات أولياء الأمور", "order": 2},
    {"id": "kg_c3_s4_r003", "subcategory_id": "kg_c3_s4", "name": "خطة تحسين الاستجابة للملاحظات", "order": 3},
    {"id": "kg_c3_s4_r004", "subcategory_id": "kg_c3_s4", "name": "إحصائية عدد الملاحظات المستجابة", "order": 4},
    {"id": "kg_c3_s4_r005", "subcategory_id": "kg_c3_s4", "name": "تقييم سرعة الاستجابة", "order": 5},
    {"id": "kg_c3_s4_r006", "subcategory_id": "kg_c3_s4", "name": "توعية بأهمية الملاحظات", "order": 6},
    {"id": "kg_c3_s4_r007", "subcategory_id": "kg_c3_s4", "name": "تنسيق مع الإدارة لمعالجة المقترحات", "order": 7},
    {"id": "kg_c3_s4_r008", "subcategory_id": "kg_c3_s4", "name": "تحسين آليات استقبال الملاحظات", "order": 8},
    {"id": "kg_c3_s4_r009", "subcategory_id": "kg_c3_s4", "name": "متابعة تنفيذ التعديلات", "order": 9},
    {"id": "kg_c3_s4_r010", "subcategory_id": "kg_c3_s4", "name": "توثيق الاستجابات", "order": 10},
    # kg_c4_s1
    {"id": "kg_c4_s1_r001", "subcategory_id": "kg_c4_s1", "name": "تقرير عن استخدام التعلم باللعب", "order": 1},
    {"id": "kg_c4_s1_r002", "subcategory_id": "kg_c4_s1", "name": "سجل الألعاب التعليمية المنفذة", "order": 2},
    {"id": "kg_c4_s1_r003", "subcategory_id": "kg_c4_s1", "name": "خطة دمج التعلم باللعب", "order": 3},
    {"id": "kg_c4_s1_r004", "subcategory_id": "kg_c4_s1", "name": "إحصائية مدى استخدام الألعاب", "order": 4},
    {"id": "kg_c4_s1_r005", "subcategory_id": "kg_c4_s1", "name": "تقييم أثر اللعب على التعلم", "order": 5},
    {"id": "kg_c4_s1_r006", "subcategory_id": "kg_c4_s1", "name": "توعية بأهمية التعلم باللعب", "order": 6},
    {"id": "kg_c4_s1_r007", "subcategory_id": "kg_c4_s1", "name": "تنسيق مع الزميلات لتبادل أفكار الألعاب", "order": 7},
    {"id": "kg_c4_s1_r008", "subcategory_id": "kg_c4_s1", "name": "تحسين جودة الألعاب", "order": 8},
    {"id": "kg_c4_s1_r009", "subcategory_id": "kg_c4_s1", "name": "متابعة تفاعل الأطفال مع اللعب", "order": 9},
    {"id": "kg_c4_s1_r010", "subcategory_id": "kg_c4_s1", "name": "توثيق تجارب التعلم باللعب", "order": 10},
    # kg_c4_s2
    {"id": "kg_c4_s2_r001", "subcategory_id": "kg_c4_s2", "name": "تقرير عن تنويع أساليب العرض", "order": 1},
    {"id": "kg_c4_s2_r002", "subcategory_id": "kg_c4_s2", "name": "سجل أساليب العرض المستخدمة", "order": 2},
    {"id": "kg_c4_s2_r003", "subcategory_id": "kg_c4_s2", "name": "خطة تنويع استراتيجيات العرض", "order": 3},
    {"id": "kg_c4_s2_r004", "subcategory_id": "kg_c4_s2", "name": "إحصائية عدد الأساليب المطبقة", "order": 4},
    {"id": "kg_c4_s2_r005", "subcategory_id": "kg_c4_s2", "name": "تقييم فعالية تنويع العرض", "order": 5},
    {"id": "kg_c4_s2_r006", "subcategory_id": "kg_c4_s2", "name": "توعية بأهمية التنويع", "order": 6},
    {"id": "kg_c4_s2_r007", "subcategory_id": "kg_c4_s2", "name": "تنسيق مع المشرفات للتدريب على أساليب جديدة", "order": 7},
    {"id": "kg_c4_s2_r008", "subcategory_id": "kg_c4_s2", "name": "تحسين استخدام الوسائط المتعددة", "order": 8},
    {"id": "kg_c4_s2_r009", "subcategory_id": "kg_c4_s2", "name": "متابعة استجابة الأطفال للأساليب", "order": 9},
    {"id": "kg_c4_s2_r010", "subcategory_id": "kg_c4_s2", "name": "توثيق أساليب العرض المبتكرة", "order": 10},
    # kg_c4_s3
    {"id": "kg_c4_s3_r001", "subcategory_id": "kg_c4_s3", "name": "تقرير عن مراعاة الفروق الفردية", "order": 1},
    {"id": "kg_c4_s3_r002", "subcategory_id": "kg_c4_s3", "name": "سجل خطط التعلم الفردية", "order": 2},
    {"id": "kg_c4_s3_r003", "subcategory_id": "kg_c4_s3", "name": "خطة تلبية احتياجات جميع الأطفال", "order": 3},
    {"id": "kg_c4_s3_r004", "subcategory_id": "kg_c4_s3", "name": "إحصائية مدى مراعاة الفروق", "order": 4},
    {"id": "kg_c4_s3_r005", "subcategory_id": "kg_c4_s3", "name": "تقييم أثر التمايز على التعلم", "order": 5},
    {"id": "kg_c4_s3_r006", "subcategory_id": "kg_c4_s3", "name": "توعية بأهمية الفروق الفردية", "order": 6},
    {"id": "kg_c4_s3_r007", "subcategory_id": "kg_c4_s3", "name": "تنسيق مع معلمات التربية الخاصة", "order": 7},
    {"id": "kg_c4_s3_r008", "subcategory_id": "kg_c4_s3", "name": "تحسين أنشطة المجموعات", "order": 8},
    {"id": "kg_c4_s3_r009", "subcategory_id": "kg_c4_s3", "name": "متابعة تقدم كل طفل وفق قدراته", "order": 9},
    {"id": "kg_c4_s3_r010", "subcategory_id": "kg_c4_s3", "name": "توثيق استراتيجيات مراعاة الفروق", "order": 10},
    # kg_c4_s4
    {"id": "kg_c4_s4_r001", "subcategory_id": "kg_c4_s4", "name": "تقرير عن توظيف أنشطة فردية وجماعية", "order": 1},
    {"id": "kg_c4_s4_r002", "subcategory_id": "kg_c4_s4", "name": "سجل تنفيذ الأنشطة الفردية والجماعية", "order": 2},
    {"id": "kg_c4_s4_r003", "subcategory_id": "kg_c4_s4", "name": "خطة تحقيق التوازن بين الأنشطة", "order": 3},
    {"id": "kg_c4_s4_r004", "subcategory_id": "kg_c4_s4", "name": "إحصائية نسبة الأنشطة الفردية إلى الجماعية", "order": 4},
    {"id": "kg_c4_s4_r005", "subcategory_id": "kg_c4_s4", "name": "تقييم فعالية الأنشطة الجماعية", "order": 5},
    {"id": "kg_c4_s4_r006", "subcategory_id": "kg_c4_s4", "name": "توعية بأهمية العمل الجماعي", "order": 6},
    {"id": "kg_c4_s4_r007", "subcategory_id": "kg_c4_s4", "name": "تنسيق لتصميم أنشطة متنوعة", "order": 7},
    {"id": "kg_c4_s4_r008", "subcategory_id": "kg_c4_s4", "name": "تحسين بيئة الأنشطة الجماعية", "order": 8},
    {"id": "kg_c4_s4_r009", "subcategory_id": "kg_c4_s4", "name": "متابعة تفاعل الأطفال في المجموعات", "order": 9},
    {"id": "kg_c4_s4_r010", "subcategory_id": "kg_c4_s4", "name": "توثيق أثر الأنشطة على المهارات الاجتماعية", "order": 10},
    # kg_c5_s1
    {"id": "kg_c5_s1_r001", "subcategory_id": "kg_c5_s1", "name": "تقرير عن تحديد أهداف تعليمية واضحة", "order": 1},
    {"id": "kg_c5_s1_r002", "subcategory_id": "kg_c5_s1", "name": "سجل الأهداف التعليمية للفترة", "order": 2},
    {"id": "kg_c5_s1_r003", "subcategory_id": "kg_c5_s1", "name": "خطة صياغة الأهداف وفق المعايير", "order": 3},
    {"id": "kg_c5_s1_r004", "subcategory_id": "kg_c5_s1", "name": "إحصائية مدى وضوح الأهداف", "order": 4},
    {"id": "kg_c5_s1_r005", "subcategory_id": "kg_c5_s1", "name": "تقييم تحقيق الأهداف", "order": 5},
    {"id": "kg_c5_s1_r006", "subcategory_id": "kg_c5_s1", "name": "توعية بأهمية الأهداف الواضحة", "order": 6},
    {"id": "kg_c5_s1_r007", "subcategory_id": "kg_c5_s1", "name": "تنسيق مع المشرفات لمراجعة الأهداف", "order": 7},
    {"id": "kg_c5_s1_r008", "subcategory_id": "kg_c5_s1", "name": "تحسين صياغة الأهداف", "order": 8},
    {"id": "kg_c5_s1_r009", "subcategory_id": "kg_c5_s1", "name": "متابعة مدى ارتباط الأهداف بالأنشطة", "order": 9},
    {"id": "kg_c5_s1_r010", "subcategory_id": "kg_c5_s1", "name": "توثيق الأهداف المنجزة", "order": 10},
    # kg_c5_s2
    {"id": "kg_c5_s2_r001", "subcategory_id": "kg_c5_s2", "name": "تقرير عن متابعة تقدم الأطفال بانتظام", "order": 1},
    {"id": "kg_c5_s2_r002", "subcategory_id": "kg_c5_s2", "name": "سجل متابعة التقدم اليومي", "order": 2},
    {"id": "kg_c5_s2_r003", "subcategory_id": "kg_c5_s2", "name": "خطة تحسين آليات المتابعة", "order": 3},
    {"id": "kg_c5_s2_r004", "subcategory_id": "kg_c5_s2", "name": "إحصائية عدد مرات المتابعة", "order": 4},
    {"id": "kg_c5_s2_r005", "subcategory_id": "kg_c5_s2", "name": "تقييم دقة المتابعة", "order": 5},
    {"id": "kg_c5_s2_r006", "subcategory_id": "kg_c5_s2", "name": "توعية بأهمية المتابعة المنتظمة", "order": 6},
    {"id": "kg_c5_s2_r007", "subcategory_id": "kg_c5_s2", "name": "تنسيق مع أولياء الأمور لمتابعة التقدم", "order": 7},
    {"id": "kg_c5_s2_r008", "subcategory_id": "kg_c5_s2", "name": "تحسين استخدام أدوات المتابعة", "order": 8},
    {"id": "kg_c5_s2_r009", "subcategory_id": "kg_c5_s2", "name": "متابعة حالات التأخر", "order": 9},
    {"id": "kg_c5_s2_r010", "subcategory_id": "kg_c5_s2", "name": "توثيق نتائج المتابعة", "order": 10},
    # kg_c5_s3
    {"id": "kg_c5_s3_r001", "subcategory_id": "kg_c5_s3", "name": "تقرير عن تقديم دعم للحالات التي تحتاج تدخل", "order": 1},
    {"id": "kg_c5_s3_r002", "subcategory_id": "kg_c5_s3", "name": "سجل حالات الدعم المقدمة", "order": 2},
    {"id": "kg_c5_s3_r003", "subcategory_id": "kg_c5_s3", "name": "خطة تدخل مبكر", "order": 3},
    {"id": "kg_c5_s3_r004", "subcategory_id": "kg_c5_s3", "name": "إحصائية عدد الحالات المستفيدة", "order": 4},
    {"id": "kg_c5_s3_r005", "subcategory_id": "kg_c5_s3", "name": "تقييم فعالية الدعم المقدم", "order": 5},
    {"id": "kg_c5_s3_r006", "subcategory_id": "kg_c5_s3", "name": "توعية بأهمية التدخل المبكر", "order": 6},
    {"id": "kg_c5_s3_r007", "subcategory_id": "kg_c5_s3", "name": "تنسيق مع الأخصائيين لدعم الحالات", "order": 7},
    {"id": "kg_c5_s3_r008", "subcategory_id": "kg_c5_s3", "name": "تحسين خطط الدعم الفردي", "order": 8},
    {"id": "kg_c5_s3_r009", "subcategory_id": "kg_c5_s3", "name": "متابعة تطور الحالات", "order": 9},
    {"id": "kg_c5_s3_r010", "subcategory_id": "kg_c5_s3", "name": "توثيق إجراءات الدعم", "order": 10},
    # kg_c5_s4
    {"id": "kg_c5_s4_r001", "subcategory_id": "kg_c5_s4", "name": "تقرير عن تحفيز الأطفال لتحقيق تقدم مستمر", "order": 1},
    {"id": "kg_c5_s4_r002", "subcategory_id": "kg_c5_s4", "name": "سجل أساليب التحفيز المستخدمة", "order": 2},
    {"id": "kg_c5_s4_r003", "subcategory_id": "kg_c5_s4", "name": "خطة تعزيز الدافعية", "order": 3},
    {"id": "kg_c5_s4_r004", "subcategory_id": "kg_c5_s4", "name": "إحصائية مدى استجابة الأطفال للتحفيز", "order": 4},
    {"id": "kg_c5_s4_r005", "subcategory_id": "kg_c5_s4", "name": "تقييم أثر التحفيز على التقدم", "order": 5},
    {"id": "kg_c5_s4_r006", "subcategory_id": "kg_c5_s4", "name": "توعية بأهمية التحفيز", "order": 6},
    {"id": "kg_c5_s4_r007", "subcategory_id": "kg_c5_s4", "name": "تنسيق مع الأسر لتعزيز التحفيز", "order": 7},
    {"id": "kg_c5_s4_r008", "subcategory_id": "kg_c5_s4", "name": "تحسين أساليب المكافآت", "order": 8},
    {"id": "kg_c5_s4_r009", "subcategory_id": "kg_c5_s4", "name": "متابعة استمرارية التحفيز", "order": 9},
    {"id": "kg_c5_s4_r010", "subcategory_id": "kg_c5_s4", "name": "توثيق قصص النجاح", "order": 10},
    # kg_c6_s1
    {"id": "kg_c6_s1_r001", "subcategory_id": "kg_c6_s1", "name": "تقرير عن تحليل احتياجات الأطفال وخصائصهم النمائية", "order": 1},
    {"id": "kg_c6_s1_r002", "subcategory_id": "kg_c6_s1", "name": "سجل تحليل الخصائص العمرية", "order": 2},
    {"id": "kg_c6_s1_r003", "subcategory_id": "kg_c6_s1", "name": "خطة تشخيص احتياجات التعلم", "order": 3},
    {"id": "kg_c6_s1_r004", "subcategory_id": "kg_c6_s1", "name": "إحصائية نتائج التحليل", "order": 4},
    {"id": "kg_c6_s1_r005", "subcategory_id": "kg_c6_s1", "name": "تقييم دقة التحليل", "order": 5},
    {"id": "kg_c6_s1_r006", "subcategory_id": "kg_c6_s1", "name": "توعية بأهمية فهم خصائص الأطفال", "order": 6},
    {"id": "kg_c6_s1_r007", "subcategory_id": "kg_c6_s1", "name": "تنسيق مع الأخصائي النفسي لتحليل الاحتياجات", "order": 7},
    {"id": "kg_c6_s1_r008", "subcategory_id": "kg_c6_s1", "name": "تحسين أدوات التحليل", "order": 8},
    {"id": "kg_c6_s1_r009", "subcategory_id": "kg_c6_s1", "name": "متابعة تطبيق نتائج التحليل", "order": 9},
    {"id": "kg_c6_s1_r010", "subcategory_id": "kg_c6_s1", "name": "توثيق تحليل الاحتياجات", "order": 10},
    # kg_c6_s2
    {"id": "kg_c6_s2_r001", "subcategory_id": "kg_c6_s2", "name": "تقرير عن صياغة أهداف مناسبة للمرحلة العمرية", "order": 1},
    {"id": "kg_c6_s2_r002", "subcategory_id": "kg_c6_s2", "name": "سجل الأهداف المصاغة", "order": 2},
    {"id": "kg_c6_s2_r003", "subcategory_id": "kg_c6_s2", "name": "خطة تطوير الأهداف", "order": 3},
    {"id": "kg_c6_s2_r004", "subcategory_id": "kg_c6_s2", "name": "إحصائية مدى ملاءمة الأهداف", "order": 4},
    {"id": "kg_c6_s2_r005", "subcategory_id": "kg_c6_s2", "name": "تقييم وضوح الأهداف", "order": 5},
    {"id": "kg_c6_s2_r006", "subcategory_id": "kg_c6_s2", "name": "توعية بصياغة الأهداف", "order": 6},
    {"id": "kg_c6_s2_r007", "subcategory_id": "kg_c6_s2", "name": "تنسيق مع المشرفات لمراجعة الأهداف", "order": 7},
    {"id": "kg_c6_s2_r008", "subcategory_id": "kg_c6_s2", "name": "تحسين ربط الأهداف بالأنشطة", "order": 8},
    {"id": "kg_c6_s2_r009", "subcategory_id": "kg_c6_s2", "name": "متابعة تحقيق الأهداف", "order": 9},
    {"id": "kg_c6_s2_r010", "subcategory_id": "kg_c6_s2", "name": "توثيق الأهداف المناسبة", "order": 10},
    # kg_c6_s3
    {"id": "kg_c6_s3_r001", "subcategory_id": "kg_c6_s3", "name": "تقرير عن تصميم أنشطة مترابطة تدعم النمو الشامل", "order": 1},
    {"id": "kg_c6_s3_r002", "subcategory_id": "kg_c6_s3", "name": "سجل الأنشطة المصممة", "order": 2},
    {"id": "kg_c6_s3_r003", "subcategory_id": "kg_c6_s3", "name": "خطة دمج الأنشطة", "order": 3},
    {"id": "kg_c6_s3_r004", "subcategory_id": "kg_c6_s3", "name": "إحصائية تنوع الأنشطة", "order": 4},
    {"id": "kg_c6_s3_r005", "subcategory_id": "kg_c6_s3", "name": "تقييم الترابط بين الأنشطة", "order": 5},
    {"id": "kg_c6_s3_r006", "subcategory_id": "kg_c6_s3", "name": "توعية بأهمية النمو الشامل", "order": 6},
    {"id": "kg_c6_s3_r007", "subcategory_id": "kg_c6_s3", "name": "تنسيق مع معلمات المجالات الأخرى", "order": 7},
    {"id": "kg_c6_s3_r008", "subcategory_id": "kg_c6_s3", "name": "تحسين تسلسل الأنشطة", "order": 8},
    {"id": "kg_c6_s3_r009", "subcategory_id": "kg_c6_s3", "name": "متابعة أثر الأنشطة على النمو", "order": 9},
    {"id": "kg_c6_s3_r010", "subcategory_id": "kg_c6_s3", "name": "توثيق تصميم الأنشطة", "order": 10},
    # kg_c6_s4
    {"id": "kg_c6_s4_r001", "subcategory_id": "kg_c6_s4", "name": "تقرير عن اختيار استراتيجيات ووسائل تعليمية ملائمة", "order": 1},
    {"id": "kg_c6_s4_r002", "subcategory_id": "kg_c6_s4", "name": "سجل الاستراتيجيات المختارة", "order": 2},
    {"id": "kg_c6_s4_r003", "subcategory_id": "kg_c6_s4", "name": "خطة تحديث الوسائل", "order": 3},
    {"id": "kg_c6_s4_r004", "subcategory_id": "kg_c6_s4", "name": "إحصائية تنوع الاستراتيجيات", "order": 4},
    {"id": "kg_c6_s4_r005", "subcategory_id": "kg_c6_s4", "name": "تقييم ملاءمة الوسائل", "order": 5},
    {"id": "kg_c6_s4_r006", "subcategory_id": "kg_c6_s4", "name": "توعية بأهمية اختيار الاستراتيجيات", "order": 6},
    {"id": "kg_c6_s4_r007", "subcategory_id": "kg_c6_s4", "name": "تنسيق مع مركز مصادر التعلم", "order": 7},
    {"id": "kg_c6_s4_r008", "subcategory_id": "kg_c6_s4", "name": "تحسين استخدام الوسائل", "order": 8},
    {"id": "kg_c6_s4_r009", "subcategory_id": "kg_c6_s4", "name": "متابعة فعالية الاستراتيجيات", "order": 9},
    {"id": "kg_c6_s4_r010", "subcategory_id": "kg_c6_s4", "name": "توثيق اختيارات الوسائل", "order": 10},
    # kg_c6_s5
    {"id": "kg_c6_s5_r001", "subcategory_id": "kg_c6_s5", "name": "تقرير عن تضمين أدوات تقويم متنوعة في الخطة", "order": 1},
    {"id": "kg_c6_s5_r002", "subcategory_id": "kg_c6_s5", "name": "سجل أدوات التقويم المستخدمة", "order": 2},
    {"id": "kg_c6_s5_r003", "subcategory_id": "kg_c6_s5", "name": "خطة تطوير أدوات التقويم", "order": 3},
    {"id": "kg_c6_s5_r004", "subcategory_id": "kg_c6_s5", "name": "إحصائية تنوع أدوات التقويم", "order": 4},
    {"id": "kg_c6_s5_r005", "subcategory_id": "kg_c6_s5", "name": "تقييم مناسبة الأدوات", "order": 5},
    {"id": "kg_c6_s5_r006", "subcategory_id": "kg_c6_s5", "name": "توعية بأهمية التقويم المتنوع", "order": 6},
    {"id": "kg_c6_s5_r007", "subcategory_id": "kg_c6_s5", "name": "تنسيق مع وحدة القياس والتقويم", "order": 7},
    {"id": "kg_c6_s5_r008", "subcategory_id": "kg_c6_s5", "name": "تحسين جودة أدوات التقويم", "order": 8},
    {"id": "kg_c6_s5_r009", "subcategory_id": "kg_c6_s5", "name": "متابعة استخدام الأدوات", "order": 9},
    {"id": "kg_c6_s5_r010", "subcategory_id": "kg_c6_s5", "name": "توثيق أدوات التقويم", "order": 10},
    # kg_c7_s1
    {"id": "kg_c7_s1_r001", "subcategory_id": "kg_c7_s1", "name": "تقرير عن تصميم خبرات تعليمية قائمة على الاستكشاف", "order": 1},
    {"id": "kg_c7_s1_r002", "subcategory_id": "kg_c7_s1", "name": "سجل أنشطة الاستكشاف", "order": 2},
    {"id": "kg_c7_s1_r003", "subcategory_id": "kg_c7_s1", "name": "خطة دمج الاستكشاف في التعلم", "order": 3},
    {"id": "kg_c7_s1_r004", "subcategory_id": "kg_c7_s1", "name": "إحصائية عدد تجارب الاستكشاف", "order": 4},
    {"id": "kg_c7_s1_r005", "subcategory_id": "kg_c7_s1", "name": "تقييم أثر الاستكشاف على التعلم", "order": 5},
    {"id": "kg_c7_s1_r006", "subcategory_id": "kg_c7_s1", "name": "توعية بأهمية التعلم بالاكتشاف", "order": 6},
    {"id": "kg_c7_s1_r007", "subcategory_id": "kg_c7_s1", "name": "تنسيق مع المعلمات لتصميم خبرات", "order": 7},
    {"id": "kg_c7_s1_r008", "subcategory_id": "kg_c7_s1", "name": "تحسين بيئة الاستكشاف", "order": 8},
    {"id": "kg_c7_s1_r009", "subcategory_id": "kg_c7_s1", "name": "متابعة تفاعل الأطفال", "order": 9},
    {"id": "kg_c7_s1_r010", "subcategory_id": "kg_c7_s1", "name": "توثيق خبرات الاستكشاف", "order": 10},
    # kg_c7_s2
    {"id": "kg_c7_s2_r001", "subcategory_id": "kg_c7_s2", "name": "تقرير عن دمج الأنشطة الحسية والتطبيقية", "order": 1},
    {"id": "kg_c7_s2_r002", "subcategory_id": "kg_c7_s2", "name": "سجل الأنشطة الحسية", "order": 2},
    {"id": "kg_c7_s2_r003", "subcategory_id": "kg_c7_s2", "name": "خطة تعزيز التعلم الحسي", "order": 3},
    {"id": "kg_c7_s2_r004", "subcategory_id": "kg_c7_s2", "name": "إحصائية عدد الأنشطة التطبيقية", "order": 4},
    {"id": "kg_c7_s2_r005", "subcategory_id": "kg_c7_s2", "name": "تقييم أثر الأنشطة الحسية", "order": 5},
    {"id": "kg_c7_s2_r006", "subcategory_id": "kg_c7_s2", "name": "توعية بأهمية الحواس في التعلم", "order": 6},
    {"id": "kg_c7_s2_r007", "subcategory_id": "kg_c7_s2", "name": "تنسيق لتوفير المواد الحسية", "order": 7},
    {"id": "kg_c7_s2_r008", "subcategory_id": "kg_c7_s2", "name": "تحسين تنويع الأنشطة", "order": 8},
    {"id": "kg_c7_s2_r009", "subcategory_id": "kg_c7_s2", "name": "متابعة استجابة الأطفال", "order": 9},
    {"id": "kg_c7_s2_r010", "subcategory_id": "kg_c7_s2", "name": "توثيق الأنشطة الحسية", "order": 10},
    # kg_c7_s3
    {"id": "kg_c7_s3_r001", "subcategory_id": "kg_c7_s3", "name": "تقرير عن مراعاة اهتمامات الأطفال", "order": 1},
    {"id": "kg_c7_s3_r002", "subcategory_id": "kg_c7_s3", "name": "سجل اهتمامات الأطفال", "order": 2},
    {"id": "kg_c7_s3_r003", "subcategory_id": "kg_c7_s3", "name": "خطة تخصيص الأنشطة وفق الاهتمامات", "order": 3},
    {"id": "kg_c7_s3_r004", "subcategory_id": "kg_c7_s3", "name": "إحصائية مدى مراعاة الاهتمامات", "order": 4},
    {"id": "kg_c7_s3_r005", "subcategory_id": "kg_c7_s3", "name": "تقييم أثر مراعاة الاهتمامات", "order": 5},
    {"id": "kg_c7_s3_r006", "subcategory_id": "kg_c7_s3", "name": "توعية بأهمية الاستماع للأطفال", "order": 6},
    {"id": "kg_c7_s3_r007", "subcategory_id": "kg_c7_s3", "name": "تنسيق لجمع بيانات الاهتمامات", "order": 7},
    {"id": "kg_c7_s3_r008", "subcategory_id": "kg_c7_s3", "name": "تحسين تصميم الأنشطة", "order": 8},
    {"id": "kg_c7_s3_r009", "subcategory_id": "kg_c7_s3", "name": "متابعة تحفيز الأطفال", "order": 9},
    {"id": "kg_c7_s3_r010", "subcategory_id": "kg_c7_s3", "name": "توثيق مراعاة الاهتمامات", "order": 10},
    # kg_c7_s4
    {"id": "kg_c7_s4_r001", "subcategory_id": "kg_c7_s4", "name": "تقرير عن تعزيز التعلم من خلال المواقف اليومية", "order": 1},
    {"id": "kg_c7_s4_r002", "subcategory_id": "kg_c7_s4", "name": "سجل المواقف اليومية المستغلة", "order": 2},
    {"id": "kg_c7_s4_r003", "subcategory_id": "kg_c7_s4", "name": "خطة استثمار المواقف الحياتية", "order": 3},
    {"id": "kg_c7_s4_r004", "subcategory_id": "kg_c7_s4", "name": "إحصائية عدد المواقف", "order": 4},
    {"id": "kg_c7_s4_r005", "subcategory_id": "kg_c7_s4", "name": "تقييم أثر المواقف على التعلم", "order": 5},
    {"id": "kg_c7_s4_r006", "subcategory_id": "kg_c7_s4", "name": "توعية بأهمية التعلم من الحياة", "order": 6},
    {"id": "kg_c7_s4_r007", "subcategory_id": "kg_c7_s4", "name": "تنسيق مع الأسر لتعزيز المواقف", "order": 7},
    {"id": "kg_c7_s4_r008", "subcategory_id": "kg_c7_s4", "name": "تحسين ربط المنهج بالحياة", "order": 8},
    {"id": "kg_c7_s4_r009", "subcategory_id": "kg_c7_s4", "name": "متابعة تفاعل الأطفال", "order": 9},
    {"id": "kg_c7_s4_r010", "subcategory_id": "kg_c7_s4", "name": "توثيق المواقف التعليمية", "order": 10},
    # kg_c8_s1
    {"id": "kg_c8_s1_r001", "subcategory_id": "kg_c8_s1", "name": "تقرير عن استخدام وسائل تعليمية مناسبة للفئة العمرية", "order": 1},
    {"id": "kg_c8_s1_r002", "subcategory_id": "kg_c8_s1", "name": "سجل الوسائل المستخدمة", "order": 2},
    {"id": "kg_c8_s1_r003", "subcategory_id": "kg_c8_s1", "name": "خطة توفير وسائل ملائمة", "order": 3},
    {"id": "kg_c8_s1_r004", "subcategory_id": "kg_c8_s1", "name": "إحصائية مدى مناسبة الوسائل", "order": 4},
    {"id": "kg_c8_s1_r005", "subcategory_id": "kg_c8_s1", "name": "تقييم فعالية الوسائل", "order": 5},
    {"id": "kg_c8_s1_r006", "subcategory_id": "kg_c8_s1", "name": "توعية بأهمية اختيار الوسائل", "order": 6},
    {"id": "kg_c8_s1_r007", "subcategory_id": "kg_c8_s1", "name": "تنسيق مع مركز مصادر التعلم", "order": 7},
    {"id": "kg_c8_s1_r008", "subcategory_id": "kg_c8_s1", "name": "تحسين استخدام الوسائل", "order": 8},
    {"id": "kg_c8_s1_r009", "subcategory_id": "kg_c8_s1", "name": "متابعة صيانة الوسائل", "order": 9},
    {"id": "kg_c8_s1_r010", "subcategory_id": "kg_c8_s1", "name": "توثيق الوسائل المناسبة", "order": 10},
    # kg_c8_s2
    {"id": "kg_c8_s2_r001", "subcategory_id": "kg_c8_s2", "name": "تقرير عن توظيف التقنيات الحديثة لدعم التعلم", "order": 1},
    {"id": "kg_c8_s2_r002", "subcategory_id": "kg_c8_s2", "name": "سجل التقنيات المستخدمة", "order": 2},
    {"id": "kg_c8_s2_r003", "subcategory_id": "kg_c8_s2", "name": "خطة دمج التقنية في التعليم", "order": 3},
    {"id": "kg_c8_s2_r004", "subcategory_id": "kg_c8_s2", "name": "إحصائية عدد مرات استخدام التقنية", "order": 4},
    {"id": "kg_c8_s2_r005", "subcategory_id": "kg_c8_s2", "name": "تقييم أثر التقنية على التعلم", "order": 5},
    {"id": "kg_c8_s2_r006", "subcategory_id": "kg_c8_s2", "name": "توعية بأهمية التقنية", "order": 6},
    {"id": "kg_c8_s2_r007", "subcategory_id": "kg_c8_s2", "name": "تنسيق مع تقني المدرسة", "order": 7},
    {"id": "kg_c8_s2_r008", "subcategory_id": "kg_c8_s2", "name": "تحسين استخدام الأجهزة الذكية", "order": 8},
    {"id": "kg_c8_s2_r009", "subcategory_id": "kg_c8_s2", "name": "متابعة تحديث البرامج", "order": 9},
    {"id": "kg_c8_s2_r010", "subcategory_id": "kg_c8_s2", "name": "توثيق توظيف التقنية", "order": 10},
    # kg_c8_s3
    {"id": "kg_c8_s3_r001", "subcategory_id": "kg_c8_s3", "name": "تقرير عن دعم تنمية المهارات المختلفة", "order": 1},
    {"id": "kg_c8_s3_r002", "subcategory_id": "kg_c8_s3", "name": "سجل المهارات المستهدفة", "order": 2},
    {"id": "kg_c8_s3_r003", "subcategory_id": "kg_c8_s3", "name": "خطة تنمية المهارات", "order": 3},
    {"id": "kg_c8_s3_r004", "subcategory_id": "kg_c8_s3", "name": "إحصائية تقدم المهارات", "order": 4},
    {"id": "kg_c8_s3_r005", "subcategory_id": "kg_c8_s3", "name": "تقييم أثر الأنشطة على المهارات", "order": 5},
    {"id": "kg_c8_s3_r006", "subcategory_id": "kg_c8_s3", "name": "توعية بأهمية المهارات", "order": 6},
    {"id": "kg_c8_s3_r007", "subcategory_id": "kg_c8_s3", "name": "تنسيق مع معلمات التربية البدنية", "order": 7},
    {"id": "kg_c8_s3_r008", "subcategory_id": "kg_c8_s3", "name": "تحسين أنشطة تنمية المهارات", "order": 8},
    {"id": "kg_c8_s3_r009", "subcategory_id": "kg_c8_s3", "name": "متابعة تطور المهارات", "order": 9},
    {"id": "kg_c8_s3_r010", "subcategory_id": "kg_c8_s3", "name": "توثيق تنمية المهارات", "order": 10},
    # kg_c8_s4
    {"id": "kg_c8_s4_r001", "subcategory_id": "kg_c8_s4", "name": "تقرير عن تحقيق التوازن بين التعلم الحسي والمجرد", "order": 1},
    {"id": "kg_c8_s4_r002", "subcategory_id": "kg_c8_s4", "name": "سجل الأنشطة الحسية والمجردة", "order": 2},
    {"id": "kg_c8_s4_r003", "subcategory_id": "kg_c8_s4", "name": "خطة موازنة التعلم", "order": 3},
    {"id": "kg_c8_s4_r004", "subcategory_id": "kg_c8_s4", "name": "إحصائية نسبة الأنشطة", "order": 4},
    {"id": "kg_c8_s4_r005", "subcategory_id": "kg_c8_s4", "name": "تقييم التوازن", "order": 5},
    {"id": "kg_c8_s4_r006", "subcategory_id": "kg_c8_s4", "name": "توعية بأهمية التوازن", "order": 6},
    {"id": "kg_c8_s4_r007", "subcategory_id": "kg_c8_s4", "name": "تنسيق لتطوير أنشطة مجردة", "order": 7},
    {"id": "kg_c8_s4_r008", "subcategory_id": "kg_c8_s4", "name": "تحسين استخدام الرموز", "order": 8},
    {"id": "kg_c8_s4_r009", "subcategory_id": "kg_c8_s4", "name": "متابعة فهم الأطفال للمجردات", "order": 9},
    {"id": "kg_c8_s4_r010", "subcategory_id": "kg_c8_s4", "name": "توثيق التوازن", "order": 10},
    # kg_c9_s1
    {"id": "kg_c9_s1_r001", "subcategory_id": "kg_c9_s1", "name": "تقرير عن الفهم العميق لمحتوى التعلم", "order": 1},
    {"id": "kg_c9_s1_r002", "subcategory_id": "kg_c9_s1", "name": "سجل التطوير المهني في المحتوى", "order": 2},
    {"id": "kg_c9_s1_r003", "subcategory_id": "kg_c9_s1", "name": "خطة تعميق المعرفة بالمادة", "order": 3},
    {"id": "kg_c9_s1_r004", "subcategory_id": "kg_c9_s1", "name": "إحصائية مصادر المعرفة", "order": 4},
    {"id": "kg_c9_s1_r005", "subcategory_id": "kg_c9_s1", "name": "تقييم مستوى الفهم", "order": 5},
    {"id": "kg_c9_s1_r006", "subcategory_id": "kg_c9_s1", "name": "توعية بأهمية التمكن", "order": 6},
    {"id": "kg_c9_s1_r007", "subcategory_id": "kg_c9_s1", "name": "تنسيق مع المشرفات لتنمية المعرفة", "order": 7},
    {"id": "kg_c9_s1_r008", "subcategory_id": "kg_c9_s1", "name": "تحسين الرابط بين المفاهيم", "order": 8},
    {"id": "kg_c9_s1_r009", "subcategory_id": "kg_c9_s1", "name": "متابعة تطبيق المعرفة", "order": 9},
    {"id": "kg_c9_s1_r010", "subcategory_id": "kg_c9_s1", "name": "توثيق الفهم العميق", "order": 10},
    # kg_c9_s2
    {"id": "kg_c9_s2_r001", "subcategory_id": "kg_c9_s2", "name": "تقرير عن تبسيط المفاهيم للأطفال", "order": 1},
    {"id": "kg_c9_s2_r002", "subcategory_id": "kg_c9_s2", "name": "سجل طرق التبسيط المستخدمة", "order": 2},
    {"id": "kg_c9_s2_r003", "subcategory_id": "kg_c9_s2", "name": "خطة تحسين تبسيط المفاهيم", "order": 3},
    {"id": "kg_c9_s2_r004", "subcategory_id": "kg_c9_s2", "name": "إحصائية مدى فهم الأطفال", "order": 4},
    {"id": "kg_c9_s2_r005", "subcategory_id": "kg_c9_s2", "name": "تقييم فعالية التبسيط", "order": 5},
    {"id": "kg_c9_s2_r006", "subcategory_id": "kg_c9_s2", "name": "توعية بأهمية التبسيط", "order": 6},
    {"id": "kg_c9_s2_r007", "subcategory_id": "kg_c9_s2", "name": "تنسيق مع زميلات لتبادل أساليب التبسيط", "order": 7},
    {"id": "kg_c9_s2_r008", "subcategory_id": "kg_c9_s2", "name": "تحسين استخدام القصص", "order": 8},
    {"id": "kg_c9_s2_r009", "subcategory_id": "kg_c9_s2", "name": "متابعة استيعاب الأطفال", "order": 9},
    {"id": "kg_c9_s2_r010", "subcategory_id": "kg_c9_s2", "name": "توثيق تبسيط المفاهيم", "order": 10},
    # kg_c9_s3
    {"id": "kg_c9_s3_r001", "subcategory_id": "kg_c9_s3", "name": "تقرير عن ربط التعلم بخبرات الطفل اليومية", "order": 1},
    {"id": "kg_c9_s3_r002", "subcategory_id": "kg_c9_s3", "name": "سجل أمثلة الربط", "order": 2},
    {"id": "kg_c9_s3_r003", "subcategory_id": "kg_c9_s3", "name": "خطة تعزيز الربط بالحياة", "order": 3},
    {"id": "kg_c9_s3_r004", "subcategory_id": "kg_c9_s3", "name": "إحصائية عدد مرات الربط", "order": 4},
    {"id": "kg_c9_s3_r005", "subcategory_id": "kg_c9_s3", "name": "تقييم أثر الربط على التعلم", "order": 5},
    {"id": "kg_c9_s3_r006", "subcategory_id": "kg_c9_s3", "name": "توعية بأهمية الخبرات السابقة", "order": 6},
    {"id": "kg_c9_s3_r007", "subcategory_id": "kg_c9_s3", "name": "تنسيق مع الأسر لمعرفة خبرات الطفل", "order": 7},
    {"id": "kg_c9_s3_r008", "subcategory_id": "kg_c9_s3", "name": "تحسين استخدام أمثلة من حياة الطفل", "order": 8},
    {"id": "kg_c9_s3_r009", "subcategory_id": "kg_c9_s3", "name": "متابعة تفاعل الأطفال", "order": 9},
    {"id": "kg_c9_s3_r010", "subcategory_id": "kg_c9_s3", "name": "توثيق الربط بالخبرات", "order": 10},
    # kg_c10_s1
    {"id": "kg_c10_s1_r001", "subcategory_id": "kg_c10_s1", "name": "تقرير عن تطبيق استراتيجيات مخططة ومنظمة", "order": 1},
    {"id": "kg_c10_s1_r002", "subcategory_id": "kg_c10_s1", "name": "سجل الاستراتيجيات المطبقة", "order": 2},
    {"id": "kg_c10_s1_r003", "subcategory_id": "kg_c10_s1", "name": "خطة تنظيم الاستراتيجيات", "order": 3},
    {"id": "kg_c10_s1_r004", "subcategory_id": "kg_c10_s1", "name": "إحصائية عدد الاستراتيجيات", "order": 4},
    {"id": "kg_c10_s1_r005", "subcategory_id": "kg_c10_s1", "name": "تقييم تنظيم الاستراتيجيات", "order": 5},
    {"id": "kg_c10_s1_r006", "subcategory_id": "kg_c10_s1", "name": "توعية بأهمية التخطيط", "order": 6},
    {"id": "kg_c10_s1_r007", "subcategory_id": "kg_c10_s1", "name": "تنسيق مع المشرفات لمراجعة الخطط", "order": 7},
    {"id": "kg_c10_s1_r008", "subcategory_id": "kg_c10_s1", "name": "تحسين تسلسل الاستراتيجيات", "order": 8},
    {"id": "kg_c10_s1_r009", "subcategory_id": "kg_c10_s1", "name": "متابعة تطبيق الخطط", "order": 9},
    {"id": "kg_c10_s1_r010", "subcategory_id": "kg_c10_s1", "name": "توثيق الاستراتيجيات", "order": 10},
    # kg_c10_s2
    {"id": "kg_c10_s2_r001", "subcategory_id": "kg_c10_s2", "name": "تقرير عن تنويع أساليب التعليم", "order": 1},
    {"id": "kg_c10_s2_r002", "subcategory_id": "kg_c10_s2", "name": "سجل أساليب التعليم", "order": 2},
    {"id": "kg_c10_s2_r003", "subcategory_id": "kg_c10_s2", "name": "خطة تنويع الأساليب", "order": 3},
    {"id": "kg_c10_s2_r004", "subcategory_id": "kg_c10_s2", "name": "إحصائية عدد الأساليب", "order": 4},
    {"id": "kg_c10_s2_r005", "subcategory_id": "kg_c10_s2", "name": "تقييم فعالية التنويع", "order": 5},
    {"id": "kg_c10_s2_r006", "subcategory_id": "kg_c10_s2", "name": "توعية بأهمية التنويع", "order": 6},
    {"id": "kg_c10_s2_r007", "subcategory_id": "kg_c10_s2", "name": "تنسيق للتدريب على أساليب جديدة", "order": 7},
    {"id": "kg_c10_s2_r008", "subcategory_id": "kg_c10_s2", "name": "تحسين دمج الأساليب", "order": 8},
    {"id": "kg_c10_s2_r009", "subcategory_id": "kg_c10_s2", "name": "متابعة استجابة الأطفال", "order": 9},
    {"id": "kg_c10_s2_r010", "subcategory_id": "kg_c10_s2", "name": "توثيق تنويع الأساليب", "order": 10},
    # kg_c10_s3
    {"id": "kg_c10_s3_r001", "subcategory_id": "kg_c10_s3", "name": "تقرير عن استخدام التعزيز الإيجابي", "order": 1},
    {"id": "kg_c10_s3_r002", "subcategory_id": "kg_c10_s3", "name": "سجل أساليب التعزيز", "order": 2},
    {"id": "kg_c10_s3_r003", "subcategory_id": "kg_c10_s3", "name": "خطة تحسين التعزيز", "order": 3},
    {"id": "kg_c10_s3_r004", "subcategory_id": "kg_c10_s3", "name": "إحصائية عدد مرات التعزيز", "order": 4},
    {"id": "kg_c10_s3_r005", "subcategory_id": "kg_c10_s3", "name": "تقييم أثر التعزيز", "order": 5},
    {"id": "kg_c10_s3_r006", "subcategory_id": "kg_c10_s3", "name": "توعية بأهمية التعزيز", "order": 6},
    {"id": "kg_c10_s3_r007", "subcategory_id": "kg_c10_s3", "name": "تنسيق مع الأسر لتعزيز التعزيز", "order": 7},
    {"id": "kg_c10_s3_r008", "subcategory_id": "kg_c10_s3", "name": "تحسين استخدام المكافآت", "order": 8},
    {"id": "kg_c10_s3_r009", "subcategory_id": "kg_c10_s3", "name": "متابعة سلوك الأطفال", "order": 9},
    {"id": "kg_c10_s3_r010", "subcategory_id": "kg_c10_s3", "name": "توثيق التعزيز الإيجابي", "order": 10},
    # kg_c10_s4
    {"id": "kg_c10_s4_r001", "subcategory_id": "kg_c10_s4", "name": "تقرير عن إدارة وقت الحصة بفاعلية", "order": 1},
    {"id": "kg_c10_s4_r002", "subcategory_id": "kg_c10_s4", "name": "سجل توزيع الوقت", "order": 2},
    {"id": "kg_c10_s4_r003", "subcategory_id": "kg_c10_s4", "name": "خطة تحسين إدارة الوقت", "order": 3},
    {"id": "kg_c10_s4_r004", "subcategory_id": "kg_c10_s4", "name": "إحصائية مدى استغلال الوقت", "order": 4},
    {"id": "kg_c10_s4_r005", "subcategory_id": "kg_c10_s4", "name": "تقييم إدارة الحصة", "order": 5},
    {"id": "kg_c10_s4_r006", "subcategory_id": "kg_c10_s4", "name": "توعية بأهمية الوقت", "order": 6},
    {"id": "kg_c10_s4_r007", "subcategory_id": "kg_c10_s4", "name": "تنسيق مع المعلمات لتبادل خبرات إدارة الوقت", "order": 7},
    {"id": "kg_c10_s4_r008", "subcategory_id": "kg_c10_s4", "name": "تحسين جدولة الأنشطة", "order": 8},
    {"id": "kg_c10_s4_r009", "subcategory_id": "kg_c10_s4", "name": "متابعة التزام الأطفال", "order": 9},
    {"id": "kg_c10_s4_r010", "subcategory_id": "kg_c10_s4", "name": "توثيق إدارة الوقت", "order": 10},
    # kg_c11_s1
    {"id": "kg_c11_s1_r001", "subcategory_id": "kg_c11_s1", "name": "تقرير عن إشراك الأسرة في متابعة النمو النمائي", "order": 1},
    {"id": "kg_c11_s1_r002", "subcategory_id": "kg_c11_s1", "name": "سجل تواصل مع الأسر حول النمو", "order": 2},
    {"id": "kg_c11_s1_r003", "subcategory_id": "kg_c11_s1", "name": "خطة تعزيز مشاركة الأسرة", "order": 3},
    {"id": "kg_c11_s1_r004", "subcategory_id": "kg_c11_s1", "name": "إحصائية عدد الأسر المشاركة", "order": 4},
    {"id": "kg_c11_s1_r005", "subcategory_id": "kg_c11_s1", "name": "تقييم أثر المشاركة", "order": 5},
    {"id": "kg_c11_s1_r006", "subcategory_id": "kg_c11_s1", "name": "توعية بأهمية متابعة النمو", "order": 6},
    {"id": "kg_c11_s1_r007", "subcategory_id": "kg_c11_s1", "name": "تنسيق مع الأسر لجمع ملاحظات", "order": 7},
    {"id": "kg_c11_s1_r008", "subcategory_id": "kg_c11_s1", "name": "تحسين أدوات متابعة النمو", "order": 8},
    {"id": "kg_c11_s1_r009", "subcategory_id": "kg_c11_s1", "name": "متابعة تطور النمو", "order": 9},
    {"id": "kg_c11_s1_r010", "subcategory_id": "kg_c11_s1", "name": "توثيق مشاركة الأسرة", "order": 10},
    # kg_c11_s2
    {"id": "kg_c11_s2_r001", "subcategory_id": "kg_c11_s2", "name": "تقرير عن تقديم إرشادات لدعم التعلم المنزلي", "order": 1},
    {"id": "kg_c11_s2_r002", "subcategory_id": "kg_c11_s2", "name": "سجل الإرشادات المقدمة", "order": 2},
    {"id": "kg_c11_s2_r003", "subcategory_id": "kg_c11_s2", "name": "خطة تطوير الإرشادات", "order": 3},
    {"id": "kg_c11_s2_r004", "subcategory_id": "kg_c11_s2", "name": "إحصائية عدد الأسر المستفيدة", "order": 4},
    {"id": "kg_c11_s2_r005", "subcategory_id": "kg_c11_s2", "name": "تقييم فعالية الإرشادات", "order": 5},
    {"id": "kg_c11_s2_r006", "subcategory_id": "kg_c11_s2", "name": "توعية بأهمية التعلم المنزلي", "order": 6},
    {"id": "kg_c11_s2_r007", "subcategory_id": "kg_c11_s2", "name": "تنسيق مع الأسر لتصميم الإرشادات", "order": 7},
    {"id": "kg_c11_s2_r008", "subcategory_id": "kg_c11_s2", "name": "تحسين وسائل الإرشاد", "order": 8},
    {"id": "kg_c11_s2_r009", "subcategory_id": "kg_c11_s2", "name": "متابعة تطبيق الإرشادات", "order": 9},
    {"id": "kg_c11_s2_r010", "subcategory_id": "kg_c11_s2", "name": "توثيق الإرشادات", "order": 10},
    # kg_c11_s3
    {"id": "kg_c11_s3_r001", "subcategory_id": "kg_c11_s3", "name": "تقرير عن إشراك الأسرة في الأنشطة التربوية", "order": 1},
    {"id": "kg_c11_s3_r002", "subcategory_id": "kg_c11_s3", "name": "سجل الأنشطة بمشاركة الأسر", "order": 2},
    {"id": "kg_c11_s3_r003", "subcategory_id": "kg_c11_s3", "name": "خطة إشراك الأسر", "order": 3},
    {"id": "kg_c11_s3_r004", "subcategory_id": "kg_c11_s3", "name": "إحصائية عدد المشاركات", "order": 4},
    {"id": "kg_c11_s3_r005", "subcategory_id": "kg_c11_s3", "name": "تقييم أثر الإشراك", "order": 5},
    {"id": "kg_c11_s3_r006", "subcategory_id": "kg_c11_s3", "name": "توعية بأهمية المشاركة", "order": 6},
    {"id": "kg_c11_s3_r007", "subcategory_id": "kg_c11_s3", "name": "تنسيق مع الأسر لاختيار الأنشطة", "order": 7},
    {"id": "kg_c11_s3_r008", "subcategory_id": "kg_c11_s3", "name": "تحسين تنوع الأنشطة", "order": 8},
    {"id": "kg_c11_s3_r009", "subcategory_id": "kg_c11_s3", "name": "متابعة تفاعل الأسر", "order": 9},
    {"id": "kg_c11_s3_r010", "subcategory_id": "kg_c11_s3", "name": "توثيق مشاركة الأسر", "order": 10},
    # kg_c12_s1
    {"id": "kg_c12_s1_r001", "subcategory_id": "kg_c12_s1", "name": "تقرير عن تنظيم الأركان التعليمية بما يعزز الاستقلالية", "order": 1},
    {"id": "kg_c12_s1_r002", "subcategory_id": "kg_c12_s1", "name": "سجل تصميم الأركان", "order": 2},
    {"id": "kg_c12_s1_r003", "subcategory_id": "kg_c12_s1", "name": "خطة تطوير الأركان", "order": 3},
    {"id": "kg_c12_s1_r004", "subcategory_id": "kg_c12_s1", "name": "إحصائية مدى استخدام الأركان", "order": 4},
    {"id": "kg_c12_s1_r005", "subcategory_id": "kg_c12_s1", "name": "تقييم أثر الأركان على الاستقلالية", "order": 5},
    {"id": "kg_c12_s1_r006", "subcategory_id": "kg_c12_s1", "name": "توعية بأهمية الاستقلالية", "order": 6},
    {"id": "kg_c12_s1_r007", "subcategory_id": "kg_c12_s1", "name": "تنسيق مع المعلمات لتبادل أفكار الأركان", "order": 7},
    {"id": "kg_c12_s1_r008", "subcategory_id": "kg_c12_s1", "name": "تحسين تجهيزات الأركان", "order": 8},
    {"id": "kg_c12_s1_r009", "subcategory_id": "kg_c12_s1", "name": "متابعة تفاعل الأطفال", "order": 9},
    {"id": "kg_c12_s1_r010", "subcategory_id": "kg_c12_s1", "name": "توثيق تنظيم الأركان", "order": 10},
    # kg_c12_s2
    {"id": "kg_c12_s2_r001", "subcategory_id": "kg_c12_s2", "name": "تقرير عن توفير أدوات تعليمية آمنة ومتنوعة", "order": 1},
    {"id": "kg_c12_s2_r002", "subcategory_id": "kg_c12_s2", "name": "سجل الأدوات المتوفرة", "order": 2},
    {"id": "kg_c12_s2_r003", "subcategory_id": "kg_c12_s2", "name": "خطة تأمين أدوات آمنة", "order": 3},
    {"id": "kg_c12_s2_r004", "subcategory_id": "kg_c12_s2", "name": "إحصائية مدى تنوع الأدوات", "order": 4},
    {"id": "kg_c12_s2_r005", "subcategory_id": "kg_c12_s2", "name": "تقييم سلامة الأدوات", "order": 5},
    {"id": "kg_c12_s2_r006", "subcategory_id": "kg_c12_s2", "name": "توعية بأهمية الأمان", "order": 6},
    {"id": "kg_c12_s2_r007", "subcategory_id": "kg_c12_s2", "name": "تنسيق مع إدارة المدرسة لتوفير الأدوات", "order": 7},
    {"id": "kg_c12_s2_r008", "subcategory_id": "kg_c12_s2", "name": "تحسين جودة الأدوات", "order": 8},
    {"id": "kg_c12_s2_r009", "subcategory_id": "kg_c12_s2", "name": "متابعة صيانة الأدوات", "order": 9},
    {"id": "kg_c12_s2_r010", "subcategory_id": "kg_c12_s2", "name": "توثيق توفير الأدوات", "order": 10},
    # kg_c12_s3
    {"id": "kg_c12_s3_r001", "subcategory_id": "kg_c12_s3", "name": "تقرير عن تعزيز الأمان النفسي والانفعالي", "order": 1},
    {"id": "kg_c12_s3_r002", "subcategory_id": "kg_c12_s3", "name": "سجل ممارسات تعزيز الأمان", "order": 2},
    {"id": "kg_c12_s3_r003", "subcategory_id": "kg_c12_s3", "name": "خطة تحسين الأمان النفسي", "order": 3},
    {"id": "kg_c12_s3_r004", "subcategory_id": "kg_c12_s3", "name": "إحصائية مدى شعور الأطفال بالأمان", "order": 4},
    {"id": "kg_c12_s3_r005", "subcategory_id": "kg_c12_s3", "name": "تقييم فعالية الإجراءات", "order": 5},
    {"id": "kg_c12_s3_r006", "subcategory_id": "kg_c12_s3", "name": "توعية بأهمية الأمان النفسي", "order": 6},
    {"id": "kg_c12_s3_r007", "subcategory_id": "kg_c12_s3", "name": "تنسيق مع المرشد الطلابي", "order": 7},
    {"id": "kg_c12_s3_r008", "subcategory_id": "kg_c12_s3", "name": "تحسين بيئة الصف", "order": 8},
    {"id": "kg_c12_s3_r009", "subcategory_id": "kg_c12_s3", "name": "متابعة حالات القلق", "order": 9},
    {"id": "kg_c12_s3_r010", "subcategory_id": "kg_c12_s3", "name": "توثيق تعزيز الأمان", "order": 10},
    # kg_c12_s4
    {"id": "kg_c12_s4_r001", "subcategory_id": "kg_c12_s4", "name": "تقرير عن دعم النمو المعرفي والاجتماعي والحركي", "order": 1},
    {"id": "kg_c12_s4_r002", "subcategory_id": "kg_c12_s4", "name": "سجل أنشطة دعم النمو", "order": 2},
    {"id": "kg_c12_s4_r003", "subcategory_id": "kg_c12_s4", "name": "خطة تكامل النمو", "order": 3},
    {"id": "kg_c12_s4_r004", "subcategory_id": "kg_c12_s4", "name": "إحصائية تقدم الأطفال", "order": 4},
    {"id": "kg_c12_s4_r005", "subcategory_id": "kg_c12_s4", "name": "تقييم توازن النمو", "order": 5},
    {"id": "kg_c12_s4_r006", "subcategory_id": "kg_c12_s4", "name": "توعية بأهمية النمو الشامل", "order": 6},
    {"id": "kg_c12_s4_r007", "subcategory_id": "kg_c12_s4", "name": "تنسيق مع معلمات التربية البدنية", "order": 7},
    {"id": "kg_c12_s4_r008", "subcategory_id": "kg_c12_s4", "name": "تحسين الأنشطة الحركية", "order": 8},
    {"id": "kg_c12_s4_r009", "subcategory_id": "kg_c12_s4", "name": "متابعة التفاعل الاجتماعي", "order": 9},
    {"id": "kg_c12_s4_r010", "subcategory_id": "kg_c12_s4", "name": "توثيق دعم النمو", "order": 10},
    # kg_c12_s5
    {"id": "kg_c12_s5_r001", "subcategory_id": "kg_c12_s5", "name": "تقرير عن تحفيز الأطفال على المبادرة والمشاركة", "order": 1},
    {"id": "kg_c12_s5_r002", "subcategory_id": "kg_c12_s5", "name": "سجل مبادرات الأطفال", "order": 2},
    {"id": "kg_c12_s5_r003", "subcategory_id": "kg_c12_s5", "name": "خطة تعزيز المبادرة", "order": 3},
    {"id": "kg_c12_s5_r004", "subcategory_id": "kg_c12_s5", "name": "إحصائية عدد المشاركات", "order": 4},
    {"id": "kg_c12_s5_r005", "subcategory_id": "kg_c12_s5", "name": "تقييم أثر التحفيز", "order": 5},
    {"id": "kg_c12_s5_r006", "subcategory_id": "kg_c12_s5", "name": "توعية بأهمية المبادرة", "order": 6},
    {"id": "kg_c12_s5_r007", "subcategory_id": "kg_c12_s5", "name": "تنسيق مع الأسر لدعم المبادرات", "order": 7},
    {"id": "kg_c12_s5_r008", "subcategory_id": "kg_c12_s5", "name": "تحسين بيئة التشجيع", "order": 8},
    {"id": "kg_c12_s5_r009", "subcategory_id": "kg_c12_s5", "name": "متابعة تطور المبادرة", "order": 9},
    {"id": "kg_c12_s5_r010", "subcategory_id": "kg_c12_s5", "name": "توثيق قصص المبادرة", "order": 10},
    # kg_c13_s1
    {"id": "kg_c13_s1_r001", "subcategory_id": "kg_c13_s1", "name": "تقرير عن تنظيم أنشطة تعاونية", "order": 1},
    {"id": "kg_c13_s1_r002", "subcategory_id": "kg_c13_s1", "name": "سجل الأنشطة التعاونية", "order": 2},
    {"id": "kg_c13_s1_r003", "subcategory_id": "kg_c13_s1", "name": "خطة تعزيز العمل الجماعي", "order": 3},
    {"id": "kg_c13_s1_r004", "subcategory_id": "kg_c13_s1", "name": "إحصائية عدد الأنشطة", "order": 4},
    {"id": "kg_c13_s1_r005", "subcategory_id": "kg_c13_s1", "name": "تقييم فعالية التعاون", "order": 5},
    {"id": "kg_c13_s1_r006", "subcategory_id": "kg_c13_s1", "name": "توعية بأهمية العمل الجماعي", "order": 6},
    {"id": "kg_c13_s1_r007", "subcategory_id": "kg_c13_s1", "name": "تنسيق لتصميم أنشطة جماعية", "order": 7},
    {"id": "kg_c13_s1_r008", "subcategory_id": "kg_c13_s1", "name": "تحسين تنوع الأنشطة", "order": 8},
    {"id": "kg_c13_s1_r009", "subcategory_id": "kg_c13_s1", "name": "متابعة تفاعل المجموعات", "order": 9},
    {"id": "kg_c13_s1_r010", "subcategory_id": "kg_c13_s1", "name": "توثيق الأنشطة التعاونية", "order": 10},
    # kg_c13_s2
    {"id": "kg_c13_s2_r001", "subcategory_id": "kg_c13_s2", "name": "تقرير عن تشجيع الحوار بين الأطفال", "order": 1},
    {"id": "kg_c13_s2_r002", "subcategory_id": "kg_c13_s2", "name": "سجل جلسات الحوار", "order": 2},
    {"id": "kg_c13_s2_r003", "subcategory_id": "kg_c13_s2", "name": "خطة تطوير مهارات الحوار", "order": 3},
    {"id": "kg_c13_s2_r004", "subcategory_id": "kg_c13_s2", "name": "إحصائية عدد مرات الحوار", "order": 4},
    {"id": "kg_c13_s2_r005", "subcategory_id": "kg_c13_s2", "name": "تقييم مهارات الحوار", "order": 5},
    {"id": "kg_c13_s2_r006", "subcategory_id": "kg_c13_s2", "name": "توعية بأهمية الحوار", "order": 6},
    {"id": "kg_c13_s2_r007", "subcategory_id": "kg_c13_s2", "name": "تنسيق مع الأسر لتعزيز الحوار", "order": 7},
    {"id": "kg_c13_s2_r008", "subcategory_id": "kg_c13_s2", "name": "تحسين بيئة الحوار", "order": 8},
    {"id": "kg_c13_s2_r009", "subcategory_id": "kg_c13_s2", "name": "متابعة استماع الأطفال", "order": 9},
    {"id": "kg_c13_s2_r010", "subcategory_id": "kg_c13_s2", "name": "توثيق الحوارات", "order": 10},
    # kg_c13_s3
    {"id": "kg_c13_s3_r001", "subcategory_id": "kg_c13_s3", "name": "تقرير عن تصميم مواقف تعليمية تفاعلية", "order": 1},
    {"id": "kg_c13_s3_r002", "subcategory_id": "kg_c13_s3", "name": "سجل المواقف التفاعلية", "order": 2},
    {"id": "kg_c13_s3_r003", "subcategory_id": "kg_c13_s3", "name": "خطة تعزيز التفاعل", "order": 3},
    {"id": "kg_c13_s3_r004", "subcategory_id": "kg_c13_s3", "name": "إحصائية عدد المواقف", "order": 4},
    {"id": "kg_c13_s3_r005", "subcategory_id": "kg_c13_s3", "name": "تقييم أثر التفاعل", "order": 5},
    {"id": "kg_c13_s3_r006", "subcategory_id": "kg_c13_s3", "name": "توعية بأهمية التفاعل", "order": 6},
    {"id": "kg_c13_s3_r007", "subcategory_id": "kg_c13_s3", "name": "تنسيق لتبادل أفكار تفاعلية", "order": 7},
    {"id": "kg_c13_s3_r008", "subcategory_id": "kg_c13_s3", "name": "تحسين استخدام التقنية في التفاعل", "order": 8},
    {"id": "kg_c13_s3_r009", "subcategory_id": "kg_c13_s3", "name": "متابعة استجابة الأطفال", "order": 9},
    {"id": "kg_c13_s3_r010", "subcategory_id": "kg_c13_s3", "name": "توثيق المواقف التفاعلية", "order": 10},
    # kg_c13_s4
    {"id": "kg_c13_s4_r001", "subcategory_id": "kg_c13_s4", "name": "تقرير عن دعم اللعب الجماعي المنظم", "order": 1},
    {"id": "kg_c13_s4_r002", "subcategory_id": "kg_c13_s4", "name": "سجل ألعاب جماعية", "order": 2},
    {"id": "kg_c13_s4_r003", "subcategory_id": "kg_c13_s4", "name": "خطة تنظيم اللعب الجماعي", "order": 3},
    {"id": "kg_c13_s4_r004", "subcategory_id": "kg_c13_s4", "name": "إحصائية عدد مرات اللعب", "order": 4},
    {"id": "kg_c13_s4_r005", "subcategory_id": "kg_c13_s4", "name": "تقييم أثر اللعب على المهارات الاجتماعية", "order": 5},
    {"id": "kg_c13_s4_r006", "subcategory_id": "kg_c13_s4", "name": "توعية بأهمية اللعب", "order": 6},
    {"id": "kg_c13_s4_r007", "subcategory_id": "kg_c13_s4", "name": "تنسيق لتوفير مساحات للعب", "order": 7},
    {"id": "kg_c13_s4_r008", "subcategory_id": "kg_c13_s4", "name": "تحسين قواعد اللعب", "order": 8},
    {"id": "kg_c13_s4_r009", "subcategory_id": "kg_c13_s4", "name": "متابعة تفاعل الأطفال", "order": 9},
    {"id": "kg_c13_s4_r010", "subcategory_id": "kg_c13_s4", "name": "توثيق ألعاب جماعية", "order": 10},
    # kg_c14_s1
    {"id": "kg_c14_s1_r001", "subcategory_id": "kg_c14_s1", "name": "تقرير عن استخدام أدوات تقويم متنوعة", "order": 1},
    {"id": "kg_c14_s1_r002", "subcategory_id": "kg_c14_s1", "name": "سجل أدوات التقويم", "order": 2},
    {"id": "kg_c14_s1_r003", "subcategory_id": "kg_c14_s1", "name": "خطة تطوير أدوات التقويم", "order": 3},
    {"id": "kg_c14_s1_r004", "subcategory_id": "kg_c14_s1", "name": "إحصائية عدد الأدوات", "order": 4},
    {"id": "kg_c14_s1_r005", "subcategory_id": "kg_c14_s1", "name": "تقييم فعالية الأدوات", "order": 5},
    {"id": "kg_c14_s1_r006", "subcategory_id": "kg_c14_s1", "name": "توعية بأهمية التقويم المتنوع", "order": 6},
    {"id": "kg_c14_s1_r007", "subcategory_id": "kg_c14_s1", "name": "تنسيق مع وحدة القياس", "order": 7},
    {"id": "kg_c14_s1_r008", "subcategory_id": "kg_c14_s1", "name": "تحسين جودة الأدوات", "order": 8},
    {"id": "kg_c14_s1_r009", "subcategory_id": "kg_c14_s1", "name": "متابعة استخدام الأدوات", "order": 9},
    {"id": "kg_c14_s1_r010", "subcategory_id": "kg_c14_s1", "name": "توثيق أدوات التقويم", "order": 10},
    # kg_c14_s2
    {"id": "kg_c14_s2_r001", "subcategory_id": "kg_c14_s2", "name": "تقرير عن توثيق تقدم كل طفل", "order": 1},
    {"id": "kg_c14_s2_r002", "subcategory_id": "kg_c14_s2", "name": "سجل ملفات الإنجاز", "order": 2},
    {"id": "kg_c14_s2_r003", "subcategory_id": "kg_c14_s2", "name": "خطة تحسين التوثيق", "order": 3},
    {"id": "kg_c14_s2_r004", "subcategory_id": "kg_c14_s2", "name": "إحصائية مدى اكتمال التوثيق", "order": 4},
    {"id": "kg_c14_s2_r005", "subcategory_id": "kg_c14_s2", "name": "تقييم دقة التوثيق", "order": 5},
    {"id": "kg_c14_s2_r006", "subcategory_id": "kg_c14_s2", "name": "توعية بأهمية التوثيق", "order": 6},
    {"id": "kg_c14_s2_r007", "subcategory_id": "kg_c14_s2", "name": "تنسيق مع الإدارة لتوحيد السجلات", "order": 7},
    {"id": "kg_c14_s2_r008", "subcategory_id": "kg_c14_s2", "name": "تحسين استخدام التكنولوجيا في التوثيق", "order": 8},
    {"id": "kg_c14_s2_r009", "subcategory_id": "kg_c14_s2", "name": "متابعة تحديث السجلات", "order": 9},
    {"id": "kg_c14_s2_r010", "subcategory_id": "kg_c14_s2", "name": "توثيق التقدم", "order": 10},
    # kg_c14_s3
    {"id": "kg_c14_s3_r001", "subcategory_id": "kg_c14_s3", "name": "تقرير عن تحليل نتائج التقويم", "order": 1},
    {"id": "kg_c14_s3_r002", "subcategory_id": "kg_c14_s3", "name": "سجل تحليل البيانات", "order": 2},
    {"id": "kg_c14_s3_r003", "subcategory_id": "kg_c14_s3", "name": "خطة استخدام التحليل", "order": 3},
    {"id": "kg_c14_s3_r004", "subcategory_id": "kg_c14_s3", "name": "إحصائية مؤشرات الأداء", "order": 4},
    {"id": "kg_c14_s3_r005", "subcategory_id": "kg_c14_s3", "name": "تقييم دقة التحليل", "order": 5},
    {"id": "kg_c14_s3_r006", "subcategory_id": "kg_c14_s3", "name": "توعية بأهمية التحليل", "order": 6},
    {"id": "kg_c14_s3_r007", "subcategory_id": "kg_c14_s3", "name": "تنسيق مع وحدة القياس لتدريب", "order": 7},
    {"id": "kg_c14_s3_r008", "subcategory_id": "kg_c14_s3", "name": "تحسين أدوات التحليل", "order": 8},
    {"id": "kg_c14_s3_r009", "subcategory_id": "kg_c14_s3", "name": "متابعة تطبيق نتائج التحليل", "order": 9},
    {"id": "kg_c14_s3_r010", "subcategory_id": "kg_c14_s3", "name": "توثيق تحليل النتائج", "order": 10},
    # kg_c14_s4
    {"id": "kg_c14_s4_r001", "subcategory_id": "kg_c14_s4", "name": "تقرير عن إعداد تقارير دورية", "order": 1},
    {"id": "kg_c14_s4_r002", "subcategory_id": "kg_c14_s4", "name": "سجل التقارير المعدة", "order": 2},
    {"id": "kg_c14_s4_r003", "subcategory_id": "kg_c14_s4", "name": "خطة تحسين التقارير", "order": 3},
    {"id": "kg_c14_s4_r004", "subcategory_id": "kg_c14_s4", "name": "إحصائية عدد التقارير", "order": 4},
    {"id": "kg_c14_s4_r005", "subcategory_id": "kg_c14_s4", "name": "تقييم جودة التقارير", "order": 5},
    {"id": "kg_c14_s4_r006", "subcategory_id": "kg_c14_s4", "name": "توعية بأهمية التقارير", "order": 6},
    {"id": "kg_c14_s4_r007", "subcategory_id": "kg_c14_s4", "name": "تنسيق مع الإدارة لاعتماد التقارير", "order": 7},
    {"id": "kg_c14_s4_r008", "subcategory_id": "kg_c14_s4", "name": "تحسين وضوح التقارير", "order": 8},
    {"id": "kg_c14_s4_r009", "subcategory_id": "kg_c14_s4", "name": "متابعة تسليم التقارير", "order": 9},
    {"id": "kg_c14_s4_r010", "subcategory_id": "kg_c14_s4", "name": "توثيق إعداد التقارير", "order": 10},
    # kg_c15_s1
    {"id": "kg_c15_s1_r001", "subcategory_id": "kg_c15_s1", "name": "تقرير عن تعديل الخطط بناءً على نتائج التقويم", "order": 1},
    {"id": "kg_c15_s1_r002", "subcategory_id": "kg_c15_s1", "name": "سجل تعديلات الخطط", "order": 2},
    {"id": "kg_c15_s1_r003", "subcategory_id": "kg_c15_s1", "name": "خطة استجابة للنتائج", "order": 3},
    {"id": "kg_c15_s1_r004", "subcategory_id": "kg_c15_s1", "name": "إحصائية عدد التعديلات", "order": 4},
    {"id": "kg_c15_s1_r005", "subcategory_id": "kg_c15_s1", "name": "تقييم أثر التعديلات", "order": 5},
    {"id": "kg_c15_s1_r006", "subcategory_id": "kg_c15_s1", "name": "توعية بمرونة الخطط", "order": 6},
    {"id": "kg_c15_s1_r007", "subcategory_id": "kg_c15_s1", "name": "تنسيق مع المشرفات لمراجعة التعديلات", "order": 7},
    {"id": "kg_c15_s1_r008", "subcategory_id": "kg_c15_s1", "name": "تحسين سرعة التعديل", "order": 8},
    {"id": "kg_c15_s1_r009", "subcategory_id": "kg_c15_s1", "name": "متابعة تنفيذ التعديلات", "order": 9},
    {"id": "kg_c15_s1_r010", "subcategory_id": "kg_c15_s1", "name": "توثيق التعديلات", "order": 10},
    # kg_c15_s2
    {"id": "kg_c15_s2_r001", "subcategory_id": "kg_c15_s2", "name": "تقرير عن تصميم أنشطة علاجية أو إثرائية", "order": 1},
    {"id": "kg_c15_s2_r002", "subcategory_id": "kg_c15_s2", "name": "سجل الأنشطة العلاجية", "order": 2},
    {"id": "kg_c15_s2_r003", "subcategory_id": "kg_c15_s2", "name": "خطة دعم التعلم", "order": 3},
    {"id": "kg_c15_s2_r004", "subcategory_id": "kg_c15_s2", "name": "إحصائية عدد الأنشطة", "order": 4},
    {"id": "kg_c15_s2_r005", "subcategory_id": "kg_c15_s2", "name": "تقييم فعالية الأنشطة", "order": 5},
    {"id": "kg_c15_s2_r006", "subcategory_id": "kg_c15_s2", "name": "توعية بأهمية العلاج", "order": 6},
    {"id": "kg_c15_s2_r007", "subcategory_id": "kg_c15_s2", "name": "تنسيق مع الأخصائيين", "order": 7},
    {"id": "kg_c15_s2_r008", "subcategory_id": "kg_c15_s2", "name": "تحسين جودة الأنشطة", "order": 8},
    {"id": "kg_c15_s2_r009", "subcategory_id": "kg_c15_s2", "name": "متابعة تقدم الأطفال", "order": 9},
    {"id": "kg_c15_s2_r010", "subcategory_id": "kg_c15_s2", "name": "توثيق الأنشطة", "order": 10},
    # kg_c15_s3
    {"id": "kg_c15_s3_r001", "subcategory_id": "kg_c15_s3", "name": "تقرير عن معالجة جوانب الضعف", "order": 1},
    {"id": "kg_c15_s3_r002", "subcategory_id": "kg_c15_s3", "name": "سجل حالات الضعف", "order": 2},
    {"id": "kg_c15_s3_r003", "subcategory_id": "kg_c15_s3", "name": "خطة معالجة الضعف", "order": 3},
    {"id": "kg_c15_s3_r004", "subcategory_id": "kg_c15_s3", "name": "إحصائية مدى تحسن الضعف", "order": 4},
    {"id": "kg_c15_s3_r005", "subcategory_id": "kg_c15_s3", "name": "تقييم استراتيجيات المعالجة", "order": 5},
    {"id": "kg_c15_s3_r006", "subcategory_id": "kg_c15_s3", "name": "توعية بأهمية التدخل", "order": 6},
    {"id": "kg_c15_s3_r007", "subcategory_id": "kg_c15_s3", "name": "تنسيق مع أولياء الأمور", "order": 7},
    {"id": "kg_c15_s3_r008", "subcategory_id": "kg_c15_s3", "name": "تحسين خطط العلاج", "order": 8},
    {"id": "kg_c15_s3_r009", "subcategory_id": "kg_c15_s3", "name": "متابعة التطور", "order": 9},
    {"id": "kg_c15_s3_r010", "subcategory_id": "kg_c15_s3", "name": "توثيق المعالجة", "order": 10},
    # kg_c15_s4
    {"id": "kg_c15_s4_r001", "subcategory_id": "kg_c15_s4", "name": "تقرير عن تعزيز نقاط القوة", "order": 1},
    {"id": "kg_c15_s4_r002", "subcategory_id": "kg_c15_s4", "name": "سجل نقاط القوة", "order": 2},
    {"id": "kg_c15_s4_r003", "subcategory_id": "kg_c15_s4", "name": "خطة تنمية القوة", "order": 3},
    {"id": "kg_c15_s4_r004", "subcategory_id": "kg_c15_s4", "name": "إحصائية عدد المواهب", "order": 4},
    {"id": "kg_c15_s4_r005", "subcategory_id": "kg_c15_s4", "name": "تقييم أثر التعزيز", "order": 5},
    {"id": "kg_c15_s4_r006", "subcategory_id": "kg_c15_s4", "name": "توعية بأهمية تنمية المواهب", "order": 6},
    {"id": "kg_c15_s4_r007", "subcategory_id": "kg_c15_s4", "name": "تنسيق مع الأسر لرعاية المواهب", "order": 7},
    {"id": "kg_c15_s4_r008", "subcategory_id": "kg_c15_s4", "name": "تحسين أنشطة الإثراء", "order": 8},
    {"id": "kg_c15_s4_r009", "subcategory_id": "kg_c15_s4", "name": "متابعة تطور القوة", "order": 9},
    {"id": "kg_c15_s4_r010", "subcategory_id": "kg_c15_s4", "name": "توثيق تعزيز القوة", "order": 10},
    # kg_c16_s1
    {"id": "kg_c16_s1_r001", "subcategory_id": "kg_c16_s1", "name": "تقرير عن إطلاع الأسرة على نتائج التقييم", "order": 1},
    {"id": "kg_c16_s1_r002", "subcategory_id": "kg_c16_s1", "name": "سجل إرسال النتائج", "order": 2},
    {"id": "kg_c16_s1_r003", "subcategory_id": "kg_c16_s1", "name": "خطة تحسين إبلاغ الأسر", "order": 3},
    {"id": "kg_c16_s1_r004", "subcategory_id": "kg_c16_s1", "name": "إحصائية عدد الأسر المطلعة", "order": 4},
    {"id": "kg_c16_s1_r005", "subcategory_id": "kg_c16_s1", "name": "تقييم وضوح النتائج", "order": 5},
    {"id": "kg_c16_s1_r006", "subcategory_id": "kg_c16_s1", "name": "توعية بأهمية المتابعة", "order": 6},
    {"id": "kg_c16_s1_r007", "subcategory_id": "kg_c16_s1", "name": "تنسيق مع الأسر لمناقشة النتائج", "order": 7},
    {"id": "kg_c16_s1_r008", "subcategory_id": "kg_c16_s1", "name": "تحسين وسائل الإبلاغ", "order": 8},
    {"id": "kg_c16_s1_r009", "subcategory_id": "kg_c16_s1", "name": "متابعة استجابة الأسر", "order": 9},
    {"id": "kg_c16_s1_r010", "subcategory_id": "kg_c16_s1", "name": "توثيق الإطلاع", "order": 10},
    # kg_c16_s2
    {"id": "kg_c16_s2_r001", "subcategory_id": "kg_c16_s2", "name": "تقرير عن مناقشة خطط الدعم مع الأسرة", "order": 1},
    {"id": "kg_c16_s2_r002", "subcategory_id": "kg_c16_s2", "name": "سجل اجتماعات الدعم", "order": 2},
    {"id": "kg_c16_s2_r003", "subcategory_id": "kg_c16_s2", "name": "خطة تحسين المشاركة", "order": 3},
    {"id": "kg_c16_s2_r004", "subcategory_id": "kg_c16_s2", "name": "إحصائية عدد الاجتماعات", "order": 4},
    {"id": "kg_c16_s2_r005", "subcategory_id": "kg_c16_s2", "name": "تقييم فعالية المناقشات", "order": 5},
    {"id": "kg_c16_s2_r006", "subcategory_id": "kg_c16_s2", "name": "توعية بأهمية الدعم", "order": 6},
    {"id": "kg_c16_s2_r007", "subcategory_id": "kg_c16_s2", "name": "تنسيق مع الأخصائيين", "order": 7},
    {"id": "kg_c16_s2_r008", "subcategory_id": "kg_c16_s2", "name": "تحسين جودة الخطط", "order": 8},
    {"id": "kg_c16_s2_r009", "subcategory_id": "kg_c16_s2", "name": "متابعة تنفيذ الخطط", "order": 9},
    {"id": "kg_c16_s2_r010", "subcategory_id": "kg_c16_s2", "name": "توثيق المناقشات", "order": 10},
    # kg_c16_s3
    {"id": "kg_c16_s3_r001", "subcategory_id": "kg_c16_s3", "name": "تقرير عن إشراك الأسرة في تنفيذ خطط التحسين", "order": 1},
    {"id": "kg_c16_s3_r002", "subcategory_id": "kg_c16_s3", "name": "سجل مشاركات الأسر", "order": 2},
    {"id": "kg_c16_s3_r003", "subcategory_id": "kg_c16_s3", "name": "خطة تفعيل دور الأسرة", "order": 3},
    {"id": "kg_c16_s3_r004", "subcategory_id": "kg_c16_s3", "name": "إحصائية عدد المشاركين", "order": 4},
    {"id": "kg_c16_s3_r005", "subcategory_id": "kg_c16_s3", "name": "تقييم أثر المشاركة", "order": 5},
    {"id": "kg_c16_s3_r006", "subcategory_id": "kg_c16_s3", "name": "توعية بأهمية الشراكة", "order": 6},
    {"id": "kg_c16_s3_r007", "subcategory_id": "kg_c16_s3", "name": "تنسيق مع الأسر لتحديد أدوارهم", "order": 7},
    {"id": "kg_c16_s3_r008", "subcategory_id": "kg_c16_s3", "name": "تحسين آليات المتابعة المنزلية", "order": 8},
    {"id": "kg_c16_s3_r009", "subcategory_id": "kg_c16_s3", "name": "متابعة استمرارية المشاركة", "order": 9},
    {"id": "kg_c16_s3_r010", "subcategory_id": "kg_c16_s3", "name": "توثيق إشراك الأسرة", "order": 10},
    # kg_c17_s1
    {"id": "kg_c17_s1_r001", "subcategory_id": "kg_c17_s1", "name": "تقرير عن وضع أهداف فردية لكل طفل", "order": 1},
    {"id": "kg_c17_s1_r002", "subcategory_id": "kg_c17_s1", "name": "سجل الأهداف الفردية", "order": 2},
    {"id": "kg_c17_s1_r003", "subcategory_id": "kg_c17_s1", "name": "خطة تخصيص الأهداف", "order": 3},
    {"id": "kg_c17_s1_r004", "subcategory_id": "kg_c17_s1", "name": "إحصائية مدى تخصيص الأهداف", "order": 4},
    {"id": "kg_c17_s1_r005", "subcategory_id": "kg_c17_s1", "name": "تقييم ملاءمة الأهداف", "order": 5},
    {"id": "kg_c17_s1_r006", "subcategory_id": "kg_c17_s1", "name": "توعية بأهمية الفردية", "order": 6},
    {"id": "kg_c17_s1_r007", "subcategory_id": "kg_c17_s1", "name": "تنسيق مع الأسر لمعرفة قدرات الطفل", "order": 7},
    {"id": "kg_c17_s1_r008", "subcategory_id": "kg_c17_s1", "name": "تحسين صياغة الأهداف", "order": 8},
    {"id": "kg_c17_s1_r009", "subcategory_id": "kg_c17_s1", "name": "متابعة تحقيق الأهداف", "order": 9},
    {"id": "kg_c17_s1_r010", "subcategory_id": "kg_c17_s1", "name": "توثيق الأهداف الفردية", "order": 10},
    # kg_c17_s2
    {"id": "kg_c17_s2_r001", "subcategory_id": "kg_c17_s2", "name": "تقرير عن متابعة تحقيق الأهداف", "order": 1},
    {"id": "kg_c17_s2_r002", "subcategory_id": "kg_c17_s2", "name": "سجل متابعة الأهداف", "order": 2},
    {"id": "kg_c17_s2_r003", "subcategory_id": "kg_c17_s2", "name": "خطة متابعة دورية", "order": 3},
    {"id": "kg_c17_s2_r004", "subcategory_id": "kg_c17_s2", "name": "إحصائية مدى تحقيق الأهداف", "order": 4},
    {"id": "kg_c17_s2_r005", "subcategory_id": "kg_c17_s2", "name": "تقييم دقة المتابعة", "order": 5},
    {"id": "kg_c17_s2_r006", "subcategory_id": "kg_c17_s2", "name": "توعية بأهمية المتابعة", "order": 6},
    {"id": "kg_c17_s2_r007", "subcategory_id": "kg_c17_s2", "name": "تنسيق مع الأسر لمتابعة الأهداف", "order": 7},
    {"id": "kg_c17_s2_r008", "subcategory_id": "kg_c17_s2", "name": "تحسين أدوات المتابعة", "order": 8},
    {"id": "kg_c17_s2_r009", "subcategory_id": "kg_c17_s2", "name": "متابعة تعديل الأهداف", "order": 9},
    {"id": "kg_c17_s2_r010", "subcategory_id": "kg_c17_s2", "name": "توثيق متابعة الأهداف", "order": 10},
    # kg_c17_s3
    {"id": "kg_c17_s3_r001", "subcategory_id": "kg_c17_s3", "name": "تقرير عن تقديم دعم فردي عند الحاجة", "order": 1},
    {"id": "kg_c17_s3_r002", "subcategory_id": "kg_c17_s3", "name": "سجل حالات الدعم الفردي", "order": 2},
    {"id": "kg_c17_s3_r003", "subcategory_id": "kg_c17_s3", "name": "خطة تدخل فردي", "order": 3},
    {"id": "kg_c17_s3_r004", "subcategory_id": "kg_c17_s3", "name": "إحصائية عدد الحالات", "order": 4},
    {"id": "kg_c17_s3_r005", "subcategory_id": "kg_c17_s3", "name": "تقييم فعالية الدعم", "order": 5},
    {"id": "kg_c17_s3_r006", "subcategory_id": "kg_c17_s3", "name": "توعية بأهمية الدعم", "order": 6},
    {"id": "kg_c17_s3_r007", "subcategory_id": "kg_c17_s3", "name": "تنسيق مع الأخصائيين", "order": 7},
    {"id": "kg_c17_s3_r008", "subcategory_id": "kg_c17_s3", "name": "تحسين استراتيجيات الدعم", "order": 8},
    {"id": "kg_c17_s3_r009", "subcategory_id": "kg_c17_s3", "name": "متابعة تطور الحالة", "order": 9},
    {"id": "kg_c17_s3_r010", "subcategory_id": "kg_c17_s3", "name": "توثيق الدعم الفردي", "order": 10},
    # kg_c17_s4
    {"id": "kg_c17_s4_r001", "subcategory_id": "kg_c17_s4", "name": "تقرير عن توثيق التقدم المحقق", "order": 1},
    {"id": "kg_c17_s4_r002", "subcategory_id": "kg_c17_s4", "name": "سجل تقدم كل طفل", "order": 2},
    {"id": "kg_c17_s4_r003", "subcategory_id": "kg_c17_s4", "name": "خطة توثيق الإنجازات", "order": 3},
    {"id": "kg_c17_s4_r004", "subcategory_id": "kg_c17_s4", "name": "إحصائية مدى التوثيق", "order": 4},
    {"id": "kg_c17_s4_r005", "subcategory_id": "kg_c17_s4", "name": "تقييم جودة التوثيق", "order": 5},
    {"id": "kg_c17_s4_r006", "subcategory_id": "kg_c17_s4", "name": "توعية بأهمية التوثيق", "order": 6},
    {"id": "kg_c17_s4_r007", "subcategory_id": "kg_c17_s4", "name": "تنسيق مع الإدارة لحفظ السجلات", "order": 7},
    {"id": "kg_c17_s4_r008", "subcategory_id": "kg_c17_s4", "name": "تحسين استخدام التكنولوجيا", "order": 8},
    {"id": "kg_c17_s4_r009", "subcategory_id": "kg_c17_s4", "name": "متابعة تحديث التوثيق", "order": 9},
    {"id": "kg_c17_s4_r010", "subcategory_id": "kg_c17_s4", "name": "توثيق التقدم المحقق", "order": 10},
    # kg_c18_s1
    {"id": "kg_c18_s1_r001", "subcategory_id": "kg_c18_s1", "name": "تقرير عن تنمية مهارات التفكير والإبداع", "order": 1},
    {"id": "kg_c18_s1_r002", "subcategory_id": "kg_c18_s1", "name": "سجل أنشطة التفكير", "order": 2},
    {"id": "kg_c18_s1_r003", "subcategory_id": "kg_c18_s1", "name": "خطة تنمية الإبداع", "order": 3},
    {"id": "kg_c18_s1_r004", "subcategory_id": "kg_c18_s1", "name": "إحصائية عدد الأنشطة", "order": 4},
    {"id": "kg_c18_s1_r005", "subcategory_id": "kg_c18_s1", "name": "تقييم أثر الأنشطة", "order": 5},
    {"id": "kg_c18_s1_r006", "subcategory_id": "kg_c18_s1", "name": "توعية بأهمية التفكير", "order": 6},
    {"id": "kg_c18_s1_r007", "subcategory_id": "kg_c18_s1", "name": "تنسيق لتبادل أفكار إبداعية", "order": 7},
    {"id": "kg_c18_s1_r008", "subcategory_id": "kg_c18_s1", "name": "تحسين استخدام الأسئلة المفتوحة", "order": 8},
    {"id": "kg_c18_s1_r009", "subcategory_id": "kg_c18_s1", "name": "متابعة تطور التفكير", "order": 9},
    {"id": "kg_c18_s1_r010", "subcategory_id": "kg_c18_s1", "name": "توثيق تنمية التفكير", "order": 10},
    # kg_c18_s2
    {"id": "kg_c18_s2_r001", "subcategory_id": "kg_c18_s2", "name": "تقرير عن تعزيز مهارات التواصل", "order": 1},
    {"id": "kg_c18_s2_r002", "subcategory_id": "kg_c18_s2", "name": "سجل أنشطة التواصل", "order": 2},
    {"id": "kg_c18_s2_r003", "subcategory_id": "kg_c18_s2", "name": "خطة تحسين التواصل", "order": 3},
    {"id": "kg_c18_s2_r004", "subcategory_id": "kg_c18_s2", "name": "إحصائية مدى تطور التواصل", "order": 4},
    {"id": "kg_c18_s2_r005", "subcategory_id": "kg_c18_s2", "name": "تقييم فعالية الأنشطة", "order": 5},
    {"id": "kg_c18_s2_r006", "subcategory_id": "kg_c18_s2", "name": "توعية بأهمية التواصل", "order": 6},
    {"id": "kg_c18_s2_r007", "subcategory_id": "kg_c18_s2", "name": "تنسيق مع الأسر لتعزيز التواصل", "order": 7},
    {"id": "kg_c18_s2_r008", "subcategory_id": "kg_c18_s2", "name": "تحسين بيئة الحوار", "order": 8},
    {"id": "kg_c18_s2_r009", "subcategory_id": "kg_c18_s2", "name": "متابعة مهارات التعبير", "order": 9},
    {"id": "kg_c18_s2_r010", "subcategory_id": "kg_c18_s2", "name": "توثيق تعزيز التواصل", "order": 10},
    # kg_c18_s3
    {"id": "kg_c18_s3_r001", "subcategory_id": "kg_c18_s3", "name": "تقرير عن غرس مهارات حل المشكلات", "order": 1},
    {"id": "kg_c18_s3_r002", "subcategory_id": "kg_c18_s3", "name": "سجل مواقف حل المشكلات", "order": 2},
    {"id": "kg_c18_s3_r003", "subcategory_id": "kg_c18_s3", "name": "خطة تنمية حل المشكلات", "order": 3},
    {"id": "kg_c18_s3_r004", "subcategory_id": "kg_c18_s3", "name": "إحصائية عدد المشكلات المحلولة", "order": 4},
    {"id": "kg_c18_s3_r005", "subcategory_id": "kg_c18_s3", "name": "تقييم استراتيجيات الحل", "order": 5},
    {"id": "kg_c18_s3_r006", "subcategory_id": "kg_c18_s3", "name": "توعية بأهمية حل المشكلات", "order": 6},
    {"id": "kg_c18_s3_r007", "subcategory_id": "kg_c18_s3", "name": "تنسيق مع المعلمات لتصميم تحديات", "order": 7},
    {"id": "kg_c18_s3_r008", "subcategory_id": "kg_c18_s3", "name": "تحسين استخدام الألغاز", "order": 8},
    {"id": "kg_c18_s3_r009", "subcategory_id": "kg_c18_s3", "name": "متابعة تطور التفكير الناقد", "order": 9},
    {"id": "kg_c18_s3_r010", "subcategory_id": "kg_c18_s3", "name": "توثيق حل المشكلات", "order": 10},
    # kg_c18_s4
    {"id": "kg_c18_s4_r001", "subcategory_id": "kg_c18_s4", "name": "تقرير عن تشجيع التعلم الذاتي", "order": 1},
    {"id": "kg_c18_s4_r002", "subcategory_id": "kg_c18_s4", "name": "سجل مبادرات التعلم الذاتي", "order": 2},
    {"id": "kg_c18_s4_r003", "subcategory_id": "kg_c18_s4", "name": "خطة تعزيز الاستقلالية", "order": 3},
    {"id": "kg_c18_s4_r004", "subcategory_id": "kg_c18_s4", "name": "إحصائية عدد الأنشطة الذاتية", "order": 4},
    {"id": "kg_c18_s4_r005", "subcategory_id": "kg_c18_s4", "name": "تقييم أثر التعلم الذاتي", "order": 5},
    {"id": "kg_c18_s4_r006", "subcategory_id": "kg_c18_s4", "name": "توعية بأهمية التعلم الذاتي", "order": 6},
    {"id": "kg_c18_s4_r007", "subcategory_id": "kg_c18_s4", "name": "تنسيق مع الأسر لدعم التعلم الذاتي", "order": 7},
    {"id": "kg_c18_s4_r008", "subcategory_id": "kg_c18_s4", "name": "تحسين بيئة التعلم الذاتي", "order": 8},
    {"id": "kg_c18_s4_r009", "subcategory_id": "kg_c18_s4", "name": "متابعة استقلالية الأطفال", "order": 9},
    {"id": "kg_c18_s4_r010", "subcategory_id": "kg_c18_s4", "name": "توثيق التعلم الذاتي", "order": 10},
    # kg_c19_s1
    {"id": "kg_c19_s1_r001", "subcategory_id": "kg_c19_s1", "name": "تقرير عن غرس القيم الإيجابية", "order": 1},
    {"id": "kg_c19_s1_r002", "subcategory_id": "kg_c19_s1", "name": "سجل أنشطة تعزيز القيم", "order": 2},
    {"id": "kg_c19_s1_r003", "subcategory_id": "kg_c19_s1", "name": "خطة غرس القيم", "order": 3},
    {"id": "kg_c19_s1_r004", "subcategory_id": "kg_c19_s1", "name": "إحصائية مدى التزام الأطفال بالقيم", "order": 4},
    {"id": "kg_c19_s1_r005", "subcategory_id": "kg_c19_s1", "name": "تقييم فعالية الأنشطة", "order": 5},
    {"id": "kg_c19_s1_r006", "subcategory_id": "kg_c19_s1", "name": "توعية بأهمية القيم", "order": 6},
    {"id": "kg_c19_s1_r007", "subcategory_id": "kg_c19_s1", "name": "تنسيق مع الأسر لتعزيز القيم", "order": 7},
    {"id": "kg_c19_s1_r008", "subcategory_id": "kg_c19_s1", "name": "تحسين استخدام القصص", "order": 8},
    {"id": "kg_c19_s1_r009", "subcategory_id": "kg_c19_s1", "name": "متابعة سلوك الأطفال", "order": 9},
    {"id": "kg_c19_s1_r010", "subcategory_id": "kg_c19_s1", "name": "توثيق غرس القيم", "order": 10},
    # kg_c19_s2
    {"id": "kg_c19_s2_r001", "subcategory_id": "kg_c19_s2", "name": "تقرير عن تعزيز احترام الآخرين", "order": 1},
    {"id": "kg_c19_s2_r002", "subcategory_id": "kg_c19_s2", "name": "سجل أنشطة تعزيز الاحترام", "order": 2},
    {"id": "kg_c19_s2_r003", "subcategory_id": "kg_c19_s2", "name": "خطة تعزيز الاحترام", "order": 3},
    {"id": "kg_c19_s2_r004", "subcategory_id": "kg_c19_s2", "name": "إحصائية مدى احترام الأطفال", "order": 4},
    {"id": "kg_c19_s2_r005", "subcategory_id": "kg_c19_s2", "name": "تقييم أثر الأنشطة", "order": 5},
    {"id": "kg_c19_s2_r006", "subcategory_id": "kg_c19_s2", "name": "توعية بأهمية الاحترام", "order": 6},
    {"id": "kg_c19_s2_r007", "subcategory_id": "kg_c19_s2", "name": "تنسيق مع الأسر لتعزيز الاحترام", "order": 7},
    {"id": "kg_c19_s2_r008", "subcategory_id": "kg_c19_s2", "name": "تحسين نمذجة السلوك", "order": 8},
    {"id": "kg_c19_s2_r009", "subcategory_id": "kg_c19_s2", "name": "متابعة التعامل مع الآخرين", "order": 9},
    {"id": "kg_c19_s2_r010", "subcategory_id": "kg_c19_s2", "name": "توثيق تعزيز الاحترام", "order": 10},
    # kg_c19_s3
    {"id": "kg_c19_s3_r001", "subcategory_id": "kg_c19_s3", "name": "تقرير عن تنمية روح التعاون", "order": 1},
    {"id": "kg_c19_s3_r002", "subcategory_id": "kg_c19_s3", "name": "سجل أنشطة التعاون", "order": 2},
    {"id": "kg_c19_s3_r003", "subcategory_id": "kg_c19_s3", "name": "خطة تعزيز التعاون", "order": 3},
    {"id": "kg_c19_s3_r004", "subcategory_id": "kg_c19_s3", "name": "إحصائية عدد الأنشطة التعاونية", "order": 4},
    {"id": "kg_c19_s3_r005", "subcategory_id": "kg_c19_s3", "name": "تقييم روح التعاون", "order": 5},
    {"id": "kg_c19_s3_r006", "subcategory_id": "kg_c19_s3", "name": "توعية بأهمية التعاون", "order": 6},
    {"id": "kg_c19_s3_r007", "subcategory_id": "kg_c19_s3", "name": "تنسيق مع المعلمات لتصميم أنشطة جماعية", "order": 7},
    {"id": "kg_c19_s3_r008", "subcategory_id": "kg_c19_s3", "name": "تحسين العمل الجماعي", "order": 8},
    {"id": "kg_c19_s3_r009", "subcategory_id": "kg_c19_s3", "name": "متابعة تفاعل المجموعات", "order": 9},
    {"id": "kg_c19_s3_r010", "subcategory_id": "kg_c19_s3", "name": "توثيق تنمية التعاون", "order": 10},
    # kg_c19_s4
    {"id": "kg_c19_s4_r001", "subcategory_id": "kg_c19_s4", "name": "تقرير عن دعم السلوكيات الإيجابية", "order": 1},
    {"id": "kg_c19_s4_r002", "subcategory_id": "kg_c19_s4", "name": "سجل السلوكيات الإيجابية", "order": 2},
    {"id": "kg_c19_s4_r003", "subcategory_id": "kg_c19_s4", "name": "خطة تعزيز السلوك", "order": 3},
    {"id": "kg_c19_s4_r004", "subcategory_id": "kg_c19_s4", "name": "إحصائية عدد السلوكيات الإيجابية", "order": 4},
    {"id": "kg_c19_s4_r005", "subcategory_id": "kg_c19_s4", "name": "تقييم فعالية التعزيز", "order": 5},
    {"id": "kg_c19_s4_r006", "subcategory_id": "kg_c19_s4", "name": "توعية بأهمية السلوك الإيجابي", "order": 6},
    {"id": "kg_c19_s4_r007", "subcategory_id": "kg_c19_s4", "name": "تنسيق مع الأسر لمتابعة السلوك", "order": 7},
    {"id": "kg_c19_s4_r008", "subcategory_id": "kg_c19_s4", "name": "تحسين نظام المكافآت", "order": 8},
    {"id": "kg_c19_s4_r009", "subcategory_id": "kg_c19_s4", "name": "متابعة تعديل السلوك", "order": 9},
    {"id": "kg_c19_s4_r010", "subcategory_id": "kg_c19_s4", "name": "توثيق دعم السلوكيات", "order": 10}
]

# قالب البرومبت لمعلمة رياض الأطفال
KG_PROMPT_TEMPLATE = """أنت معلمة رياض أطفال خبيرة، مسؤولة عن تنمية مهارات الأطفال وتعزيز بيئة تعليمية آمنة ومحفزة وفق المناهج والأنظمة المعتمدة.

المطلوب:
- عرض المعيار الرئيسي.
- عرض التصنيف الفرعي.
- كتابة تقرير مهني يوضح الإجراءات والممارسات المرتبطة بهذا التصنيف.

التقرير المطلوب: "{report_name}"
وهو يندرج تحت التصنيف الفرعي: "{subcategory_name}"
ضمن المعيار: "{criterion_name}"

ضوابط الكتابة:
- لغة تربوية رسمية.
- إبراز دورك كمعلمة في تحقيق النمو الشامل للأطفال.
- توضيح الأنشطة والاستراتيجيات المستخدمة (مثل التعلم باللعب، الاستكشاف).
- الإشارة إلى كيفية مراعاة الفروق الفردية.
- بيان دورك في التواصل مع أولياء الأمور وإشراكهم.
- إبراز استخدام التقويم المستمر وأدوات التوثيق.
- توضيح أثر جهودك على تطور الأطفال وسلوكهم.
- صياغة دقيقة من 5–7 أسطر.

**الحقول المطلوبة:**
1. الهدف التربوي
2. نبذة مختصرة
3. إجراءات التنفيذ
4. الاستراتيجيات المستخدمة
5. نقاط القوة
6. نقاط التحسين
7. التوصيات

يرجى تقديم الإجابة باللغة العربية الفصحى، وتنظيمها بحيث يكون كل حقل في سطر منفصل يبدأ برقمه فقط دون ذكر العنوان."""