# student_counselor_prompt.py

# معايير الأداء الوظيفي (بدون نسب مئوية)
SG_CRITERIA = [
    {"id": "sg_c1", "name": "تقديم الإرشاد الفردي والجماعي للطلاب", "order": 1},
    {"id": "sg_c2", "name": "متابعة الحالات السلوكية والنفسية", "order": 2},
    {"id": "sg_c3", "name": "تنفيذ برامج وقائية وتوعوية", "order": 3},
    {"id": "sg_c4", "name": "التنسيق مع أولياء الأمور والمعلمين", "order": 4},
    {"id": "sg_c5", "name": "توثيق الحالات وإعداد التقارير", "order": 5}
]

# التصنيفات الفرعية (كما هي)
SG_SUBCATEGORIES = [
    # sg_c1
    {"id": "sg_c1_s1", "criterion_id": "sg_c1", "name": "إجراء مقابلات فردية مع الطلاب", "order": 1},
    {"id": "sg_c1_s2", "criterion_id": "sg_c1", "name": "تقديم إرشاد جماعي (ورش, مجموعات)", "order": 2},
    {"id": "sg_c1_s3", "criterion_id": "sg_c1", "name": "تقديم استشارات أكاديمية ومهنية", "order": 3},
    {"id": "sg_c1_s4", "criterion_id": "sg_c1", "name": "توجيه الطلاب ذوي الميول الخاصة", "order": 4},
    {"id": "sg_c1_s5", "criterion_id": "sg_c1", "name": "تعزيز الثقة بالنفس لدى الطلاب", "order": 5},
    # sg_c2
    {"id": "sg_c2_s1", "criterion_id": "sg_c2", "name": "دراسة الحالات الفردية وتشخيصها", "order": 1},
    {"id": "sg_c2_s2", "criterion_id": "sg_c2", "name": "التدخل في حالات التنمر والعنف", "order": 2},
    {"id": "sg_c2_s3", "criterion_id": "sg_c2", "name": "متابعة الطلاب المعرضين للخطر", "order": 3},
    {"id": "sg_c2_s4", "criterion_id": "sg_c2", "name": "التعامل مع القلق والاكتئاب", "order": 4},
    {"id": "sg_c2_s5", "criterion_id": "sg_c2", "name": "إحالة الحالات لمختصين عند الحاجة", "order": 5},
    # sg_c3
    {"id": "sg_c3_s1", "criterion_id": "sg_c3", "name": "تنفيذ برامج توعوية عن أضرار التدخين", "order": 1},
    {"id": "sg_c3_s2", "criterion_id": "sg_c3", "name": "تنظيم محاضرات عن الأمن الفكري", "order": 2},
    {"id": "sg_c3_s3", "criterion_id": "sg_c3", "name": "برامج توعوية عن الاستخدام الآمن للإنترنت", "order": 3},
    {"id": "sg_c3_s4", "criterion_id": "sg_c3", "name": "توعية حول المهارات الحياتية", "order": 4},
    {"id": "sg_c3_s5", "criterion_id": "sg_c3", "name": "تنظيم حملات ضد التنمر", "order": 5},
    # sg_c4
    {"id": "sg_c4_s1", "criterion_id": "sg_c4", "name": "التنسيق مع المعلمين لمتابعة الطلاب", "order": 1},
    {"id": "sg_c4_s2", "criterion_id": "sg_c4", "name": "التواصل مع أولياء الأمور بشأن سلوك الطلاب", "order": 2},
    {"id": "sg_c4_s3", "criterion_id": "sg_c4", "name": "عقد اجتماعات مع أولياء الأمور", "order": 3},
    {"id": "sg_c4_s4", "criterion_id": "sg_c4", "name": "التنسيق مع الإدارة والجهات الخارجية", "order": 4},
    {"id": "sg_c4_s5", "criterion_id": "sg_c4", "name": "المشاركة في لجنة التوجيه والإرشاد", "order": 5},
    # sg_c5
    {"id": "sg_c5_s1", "criterion_id": "sg_c5", "name": "توثيق الحالات الفردية وحفظها", "order": 1},
    {"id": "sg_c5_s2", "criterion_id": "sg_c5", "name": "إعداد تقارير دورية عن الأنشطة الإرشادية", "order": 2},
    {"id": "sg_c5_s3", "criterion_id": "sg_c5", "name": "تحليل البيانات السلوكية", "order": 3},
    {"id": "sg_c5_s4", "criterion_id": "sg_c5", "name": "رفع التقارير للإدارة", "order": 4},
    {"id": "sg_c5_s5", "criterion_id": "sg_c5", "name": "توثيق البرامج الوقائية المنفذة", "order": 5}
]

# قائمة التقارير الموسعة (20 لكل تصنيف فرعي)
SG_REPORTS = [
    # ========== sg_c1_s1 ==========
    {"id": "sg_c1_s1_r001", "subcategory_id": "sg_c1_s1", "name": "تقرير عن إجراء مقابلات فردية مع طلاب يعانون من صعوبات", "order": 1},
    {"id": "sg_c1_s1_r002", "subcategory_id": "sg_c1_s1", "name": "سجل استقبال الطلاب في مكتب الإرشاد", "order": 2},
    {"id": "sg_c1_s1_r003", "subcategory_id": "sg_c1_s1", "name": "تقرير عن متابعة حالة طالب موهوب", "order": 3},
    {"id": "sg_c1_s1_r004", "subcategory_id": "sg_c1_s1", "name": "توثيق مقابلات مع طلاب من ذوي الاحتياجات الخاصة", "order": 4},
    {"id": "sg_c1_s1_r005", "subcategory_id": "sg_c1_s1", "name": "تقرير عن جلسات إرشادية فردية لتحسين التحصيل", "order": 5},
    {"id": "sg_c1_s1_r006", "subcategory_id": "sg_c1_s1", "name": "سجل المقابلات الفردية الأسبوعي", "order": 6},
    {"id": "sg_c1_s1_r007", "subcategory_id": "sg_c1_s1", "name": "تقرير عن جلسات الدعم الفردي للطلاب الجدد", "order": 7},
    {"id": "sg_c1_s1_r008", "subcategory_id": "sg_c1_s1", "name": "توثيق حالات الإحالة الذاتية من الطلاب", "order": 8},
    {"id": "sg_c1_s1_r009", "subcategory_id": "sg_c1_s1", "name": "تقرير عن فعالية المقابلات الفردية في تحسين التحصيل الدراسي", "order": 9},
    {"id": "sg_c1_s1_r010", "subcategory_id": "sg_c1_s1", "name": "سجل متابعة الطلاب ذوي المشكلات الأسرية", "order": 10},
    {"id": "sg_c1_s1_r011", "subcategory_id": "sg_c1_s1", "name": "تقرير عن المقابلات الفردية مع طلاب المرحلة الانتقالية", "order": 11},
    {"id": "sg_c1_s1_r012", "subcategory_id": "sg_c1_s1", "name": "توثيق استخدام أدوات قياس الشخصية خلال المقابلات", "order": 12},
    {"id": "sg_c1_s1_r013", "subcategory_id": "sg_c1_s1", "name": "تقرير عن جلسات الإرشاد الفردي للطلاب المتفوقين", "order": 13},
    {"id": "sg_c1_s1_r014", "subcategory_id": "sg_c1_s1", "name": "سجل زيارات الطلاب المتكررة لمكتب الإرشاد", "order": 14},
    {"id": "sg_c1_s1_r015", "subcategory_id": "sg_c1_s1", "name": "تقرير عن المقابلات الفردية قبل الاختبارات", "order": 15},
    {"id": "sg_c1_s1_r016", "subcategory_id": "sg_c1_s1", "name": "توثيق حالات الطلاب المحولين من المعلمين", "order": 16},
    {"id": "sg_c1_s1_r017", "subcategory_id": "sg_c1_s1", "name": "تقرير عن مستوى رضا الطلاب عن المقابلات الفردية", "order": 17},
    {"id": "sg_c1_s1_r018", "subcategory_id": "sg_c1_s1", "name": "سجل المتابعة الهاتفية لحالات فردية", "order": 18},
    {"id": "sg_c1_s1_r019", "subcategory_id": "sg_c1_s1", "name": "تقرير عن المقابلات الفردية مع الطلاب المنقطعين", "order": 19},
    {"id": "sg_c1_s1_r020", "subcategory_id": "sg_c1_s1", "name": "توثيق نماذج خطة تعديل سلوك فردية", "order": 20},

    # ========== sg_c1_s2 ==========
    {"id": "sg_c1_s2_r001", "subcategory_id": "sg_c1_s2", "name": "تقرير عن ورش عمل جماعية لتنمية المهارات الاجتماعية", "order": 1},
    {"id": "sg_c1_s2_r002", "subcategory_id": "sg_c1_s2", "name": "سجل إرشاد جماعي لمجموعة من الطلاب", "order": 2},
    {"id": "sg_c1_s2_r003", "subcategory_id": "sg_c1_s2", "name": "تقرير عن برنامج تدريب الطلاب على حل المشكلات", "order": 3},
    {"id": "sg_c1_s2_r004", "subcategory_id": "sg_c1_s2", "name": "توثيق جلسات جماعية للتوجيه المهني", "order": 4},
    {"id": "sg_c1_s2_r005", "subcategory_id": "sg_c1_s2", "name": "تقرير عن فعالية الإرشاد الجماعي في تحسين السلوك", "order": 5},
    {"id": "sg_c1_s2_r006", "subcategory_id": "sg_c1_s2", "name": "سجل مجموعات الدعم النفسي للطلاب", "order": 6},
    {"id": "sg_c1_s2_r007", "subcategory_id": "sg_c1_s2", "name": "تقرير عن ورش إدارة الغضب", "order": 7},
    {"id": "sg_c1_s2_r008", "subcategory_id": "sg_c1_s2", "name": "توثيق برامج تدريب الأقران (Peer Counseling)", "order": 8},
    {"id": "sg_c1_s2_r009", "subcategory_id": "sg_c1_s2", "name": "تقرير عن مجموعات تحسين التواصل بين الطلاب", "order": 9},
    {"id": "sg_c1_s2_r010", "subcategory_id": "sg_c1_s2", "name": "سجل ورش عمل عن القيادة للطلاب", "order": 10},
    {"id": "sg_c1_s2_r011", "subcategory_id": "sg_c1_s2", "name": "تقرير عن مجموعات الدعم الدراسي", "order": 11},
    {"id": "sg_c1_s2_r012", "subcategory_id": "sg_c1_s2", "name": "توثيق جلسات جماعية لخفض القلق الاجتماعي", "order": 12},
    {"id": "sg_c1_s2_r013", "subcategory_id": "sg_c1_s2", "name": "تقرير عن فعالية الإرشاد الجمعي في تعزيز الانتماء", "order": 13},
    {"id": "sg_c1_s2_r014", "subcategory_id": "sg_c1_s2", "name": "سجل مشاركة الطلاب في مجموعات الحوار", "order": 14},
    {"id": "sg_c1_s2_r015", "subcategory_id": "sg_c1_s2", "name": "تقرير عن ورش عمل الذكاء العاطفي", "order": 15},
    {"id": "sg_c1_s2_r016", "subcategory_id": "sg_c1_s2", "name": "توثيق مجموعات المساعدة الذاتية للطلاب", "order": 16},
    {"id": "sg_c1_s2_r017", "subcategory_id": "sg_c1_s2", "name": "تقرير عن جلسات جماعية لتعزيز التفكير الإيجابي", "order": 17},
    {"id": "sg_c1_s2_r018", "subcategory_id": "sg_c1_s2", "name": "سجل ورش عمل عن مهارات الدراسة الفعالة", "order": 18},
    {"id": "sg_c1_s2_r019", "subcategory_id": "sg_c1_s2", "name": "تقرير عن مجموعات التعامل مع الضغوط", "order": 19},
    {"id": "sg_c1_s2_r020", "subcategory_id": "sg_c1_s2", "name": "توثيق برامج الإرشاد الجمعي لذوي صعوبات التعلم", "order": 20},

    # ========== sg_c1_s3 ==========
    {"id": "sg_c1_s3_r001", "subcategory_id": "sg_c1_s3", "name": "تقرير عن تقديم استشارات أكاديمية لطلاب الثانوي", "order": 1},
    {"id": "sg_c1_s3_r002", "subcategory_id": "sg_c1_s3", "name": "سجل توجيه طلاب لتخصصات مهنية", "order": 2},
    {"id": "sg_c1_s3_r003", "subcategory_id": "sg_c1_s3", "name": "تقرير عن مساعدة الطلاب في اختيار المسار", "order": 3},
    {"id": "sg_c1_s3_r004", "subcategory_id": "sg_c1_s3", "name": "توثيق استشارات حول الجامعات والكليات", "order": 4},
    {"id": "sg_c1_s3_r005", "subcategory_id": "sg_c1_s3", "name": "تقرير عن أثر الإرشاد الأكاديمي على قرارات الطلاب", "order": 5},
    {"id": "sg_c1_s3_r006", "subcategory_id": "sg_c1_s3", "name": "سجل الاستشارات الأكاديمية للطلاب المتفوقين", "order": 6},
    {"id": "sg_c1_s3_r007", "subcategory_id": "sg_c1_s3", "name": "تقرير عن توجيه طلاب المرحلة المتوسطة", "order": 7},
    {"id": "sg_c1_s3_r008", "subcategory_id": "sg_c1_s3", "name": "توثيق لقاءات مع أولياء الأمور حول التخصصات", "order": 8},
    {"id": "sg_c1_s3_r009", "subcategory_id": "sg_c1_s3", "name": "تقرير عن أيام المهنة المنظمة في المدرسة", "order": 9},
    {"id": "sg_c1_s3_r010", "subcategory_id": "sg_c1_s3", "name": "سجل المشاركة في معارض التخصصات", "order": 10},
    {"id": "sg_c1_s3_r011", "subcategory_id": "sg_c1_s3", "name": "تقرير عن الاستشارات المهنية لذوي الاحتياجات الخاصة", "order": 11},
    {"id": "sg_c1_s3_r012", "subcategory_id": "sg_c1_s3", "name": "توثيق استبانات الميول المهنية للطلاب", "order": 12},
    {"id": "sg_c1_s3_r013", "subcategory_id": "sg_c1_s3", "name": "تقرير عن متابعة خريجي المدرسة", "order": 13},
    {"id": "sg_c1_s3_r014", "subcategory_id": "sg_c1_s3", "name": "سجل زيارات ميدانية لجامعات وكليات", "order": 14},
    {"id": "sg_c1_s3_r015", "subcategory_id": "sg_c1_s3", "name": "تقرير عن ورش عمل السيرة الذاتية", "order": 15},
    {"id": "sg_c1_s3_r016", "subcategory_id": "sg_c1_s3", "name": "توثيق الاستشارات حول المنح الدراسية", "order": 16},
    {"id": "sg_c1_s3_r017", "subcategory_id": "sg_c1_s3", "name": "تقرير عن توجيه الطلاب لسوق العمل", "order": 17},
    {"id": "sg_c1_s3_r018", "subcategory_id": "sg_c1_s3", "name": "سجل اجتماعات مع مرشدين مهنيين خارجيين", "order": 18},
    {"id": "sg_c1_s3_r019", "subcategory_id": "sg_c1_s3", "name": "تقرير عن برنامج التخطيط للمستقبل", "order": 19},
    {"id": "sg_c1_s3_r020", "subcategory_id": "sg_c1_s3", "name": "توثيق الاستشارات الأكاديمية عبر المنصات الإلكترونية", "order": 20},

    # ========== sg_c1_s4 ==========
    {"id": "sg_c1_s4_r001", "subcategory_id": "sg_c1_s4", "name": "تقرير عن توجيه الطلاب ذوي الميول الفنية", "order": 1},
    {"id": "sg_c1_s4_r002", "subcategory_id": "sg_c1_s4", "name": "سجل متابعة الطلاب الموهوبين", "order": 2},
    {"id": "sg_c1_s4_r003", "subcategory_id": "sg_c1_s4", "name": "تقرير عن توجيه طلاب لتطوير مهاراتهم القيادية", "order": 3},
    {"id": "sg_c1_s4_r004", "subcategory_id": "sg_c1_s4", "name": "توثيق برامج لاكتشاف المواهب", "order": 4},
    {"id": "sg_c1_s4_r005", "subcategory_id": "sg_c1_s4", "name": "تقرير عن فعالية برامج تنمية الموهوبين", "order": 5},
    {"id": "sg_c1_s4_r006", "subcategory_id": "sg_c1_s4", "name": "سجل توجيه الطلاب الموهوبين رياضياً", "order": 6},
    {"id": "sg_c1_s4_r007", "subcategory_id": "sg_c1_s4", "name": "تقرير عن برامج رعاية الموهوبين في المجال العلمي", "order": 7},
    {"id": "sg_c1_s4_r008", "subcategory_id": "sg_c1_s4", "name": "توثيق مشاركة الموهوبين في مسابقات خارجية", "order": 8},
    {"id": "sg_c1_s4_r009", "subcategory_id": "sg_c1_s4", "name": "تقرير عن توجيه الطلاب ذوي الميول الأدبية", "order": 9},
    {"id": "sg_c1_s4_r010", "subcategory_id": "sg_c1_s4", "name": "سجل ورش عمل للطلاب المبتكرين", "order": 10},
    {"id": "sg_c1_s4_r011", "subcategory_id": "sg_c1_s4", "name": "تقرير عن برنامج تنمية القيادات الطلابية", "order": 11},
    {"id": "sg_c1_s4_r012", "subcategory_id": "sg_c1_s4", "name": "توثيق شراكات مع مؤسسات رعاية الموهوبين", "order": 12},
    {"id": "sg_c1_s4_r013", "subcategory_id": "sg_c1_s4", "name": "تقرير عن توجيه الطلاب ذوي الميول التقنية", "order": 13},
    {"id": "sg_c1_s4_r014", "subcategory_id": "sg_c1_s4", "name": "سجل متابعة الطلاب الموهوبين بعد التخرج", "order": 14},
    {"id": "sg_c1_s4_r015", "subcategory_id": "sg_c1_s4", "name": "تقرير عن برامج الإثراء الصيفي للموهوبين", "order": 15},
    {"id": "sg_c1_s4_r016", "subcategory_id": "sg_c1_s4", "name": "توثيق لقاءات مع أولياء أمور الموهوبين", "order": 16},
    {"id": "sg_c1_s4_r017", "subcategory_id": "sg_c1_s4", "name": "تقرير عن تقييم احتياجات الموهوبين", "order": 17},
    {"id": "sg_c1_s4_r018", "subcategory_id": "sg_c1_s4", "name": "سجل مشاركة الموهوبين في الأولمبيادات", "order": 18},
    {"id": "sg_c1_s4_r019", "subcategory_id": "sg_c1_s4", "name": "تقرير عن برامج التوجيه المهني للموهوبين", "order": 19},
    {"id": "sg_c1_s4_r020", "subcategory_id": "sg_c1_s4", "name": "توثيق قصص نجاح لطلاب موهوبين", "order": 20},

    # ========== sg_c1_s5 ==========
    {"id": "sg_c1_s5_r001", "subcategory_id": "sg_c1_s5", "name": "تقرير عن جلسات تعزيز الثقة بالنفس", "order": 1},
    {"id": "sg_c1_s5_r002", "subcategory_id": "sg_c1_s5", "name": "سجل أنشطة لتحسين صورة الذات لدى الطلاب", "order": 2},
    {"id": "sg_c1_s5_r003", "subcategory_id": "sg_c1_s5", "name": "تقرير عن برنامج 'أنا أستطيع'", "order": 3},
    {"id": "sg_c1_s5_r004", "subcategory_id": "sg_c1_s5", "name": "توثيق نتائج قياس الثقة بالنفس", "order": 4},
    {"id": "sg_c1_s5_r005", "subcategory_id": "sg_c1_s5", "name": "تقرير عن أثر البرامج على تحصيل الطلاب", "order": 5},
    {"id": "sg_c1_s5_r006", "subcategory_id": "sg_c1_s5", "name": "سجل جلسات تعزيز تقدير الذات للطالبات", "order": 6},
    {"id": "sg_c1_s5_r007", "subcategory_id": "sg_c1_s5", "name": "تقرير عن برنامج تنمية الشخصية للطلاب الخجولين", "order": 7},
    {"id": "sg_c1_s5_r008", "subcategory_id": "sg_c1_s5", "name": "توثيق أنشطة تعزيز الثقة من خلال الفن", "order": 8},
    {"id": "sg_c1_s5_r009", "subcategory_id": "sg_c1_s5", "name": "تقرير عن ورش عمل مواجهة النقد", "order": 9},
    {"id": "sg_c1_s5_r010", "subcategory_id": "sg_c1_s5", "name": "سجل برامج تعزيز الثقة قبل الامتحانات", "order": 10},
    {"id": "sg_c1_s5_r011", "subcategory_id": "sg_c1_s5", "name": "تقرير عن جلسات جماعية لتعزيز الحديث الإيجابي", "order": 11},
    {"id": "sg_c1_s5_r012", "subcategory_id": "sg_c1_s5", "name": "توثيق استخدام بطاقات التأكيد الإيجابي", "order": 12},
    {"id": "sg_c1_s5_r013", "subcategory_id": "sg_c1_s5", "name": "تقرير عن برنامج تعزيز الثقة لدى الموهوبين", "order": 13},
    {"id": "sg_c1_s5_r014", "subcategory_id": "sg_c1_s5", "name": "سجل متابعة تطور الثقة لدى طلاب الصف الأول", "order": 14},
    {"id": "sg_c1_s5_r015", "subcategory_id": "sg_c1_s5", "name": "تقرير عن ورش عمل التعامل مع الفشل", "order": 15},
    {"id": "sg_c1_s5_r016", "subcategory_id": "sg_c1_s5", "name": "توثيق مشاركة الطلاب في مسابقات لتعزيز الثقة", "order": 16},
    {"id": "sg_c1_s5_r017", "subcategory_id": "sg_c1_s5", "name": "تقرير عن برنامج 'نقاط قوتي'", "order": 17},
    {"id": "sg_c1_s5_r018", "subcategory_id": "sg_c1_s5", "name": "سجل لقاءات مع أولياء الأمور لدعم ثقة الأبناء", "order": 18},
    {"id": "sg_c1_s5_r019", "subcategory_id": "sg_c1_s5", "name": "تقرير عن أثر الرياضة على تعزيز الثقة", "order": 19},
    {"id": "sg_c1_s5_r020", "subcategory_id": "sg_c1_s5", "name": "توثيق حالات تحسن ملحوظ في الثقة", "order": 20},

    # ========== sg_c2_s1 ==========
    {"id": "sg_c2_s1_r001", "subcategory_id": "sg_c2_s1", "name": "تقرير دراسة حالة طالب يعاني من صعوبات تعلم", "order": 1},
    {"id": "sg_c2_s1_r002", "subcategory_id": "sg_c2_s1", "name": "سجل تشخيص حالات فرط الحركة", "order": 2},
    {"id": "sg_c2_s1_r003", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تحليل سلوك طالب عدواني", "order": 3},
    {"id": "sg_c2_s1_r004", "subcategory_id": "sg_c2_s1", "name": "توثيق أدوات التشخيص المستخدمة", "order": 4},
    {"id": "sg_c2_s1_r005", "subcategory_id": "sg_c2_s1", "name": "تقرير عن فريق دراسة الحالة", "order": 5},
    {"id": "sg_c2_s1_r006", "subcategory_id": "sg_c2_s1", "name": "سجل ملاحظة سلوك الطلاب في الفصل", "order": 6},
    {"id": "sg_c2_s1_r007", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تشخيص حالات القلق والاكتئاب", "order": 7},
    {"id": "sg_c2_s1_r008", "subcategory_id": "sg_c2_s1", "name": "توثيق مقابلات تشخيصية مع الطلاب", "order": 8},
    {"id": "sg_c2_s1_r009", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تحليل نتائج اختبارات الشخصية", "order": 9},
    {"id": "sg_c2_s1_r010", "subcategory_id": "sg_c2_s1", "name": "سجل دراسات حالة لطلاب منقطعين", "order": 10},
    {"id": "sg_c2_s1_r011", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تشخيص صعوبات الانتباه", "order": 11},
    {"id": "sg_c2_s1_r012", "subcategory_id": "sg_c2_s1", "name": "توثيق اجتماعات فريق دراسة الحالة", "order": 12},
    {"id": "sg_c2_s1_r013", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تشخيص حالات العنف الأسري", "order": 13},
    {"id": "sg_c2_s1_r014", "subcategory_id": "sg_c2_s1", "name": "سجل استخدام مقياس تقدير السلوك", "order": 14},
    {"id": "sg_c2_s1_r015", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تشخيص اضطرابات النطق", "order": 15},
    {"id": "sg_c2_s1_r016", "subcategory_id": "sg_c2_s1", "name": "توثيق تحويل حالات للتشخيص المتخصص", "order": 16},
    {"id": "sg_c2_s1_r017", "subcategory_id": "sg_c2_s1", "name": "تقرير عن دراسة حالة طالب موهوب", "order": 17},
    {"id": "sg_c2_s1_r018", "subcategory_id": "sg_c2_s1", "name": "سجل المقابلات مع المعلمين حول سلوك الطلاب", "order": 18},
    {"id": "sg_c2_s1_r019", "subcategory_id": "sg_c2_s1", "name": "تقرير عن تحليل أسباب التأخر الدراسي", "order": 19},
    {"id": "sg_c2_s1_r020", "subcategory_id": "sg_c2_s1", "name": "توثيق خطط التدخل المبني على التشخيص", "order": 20},

    # ========== sg_c2_s2 ==========
    {"id": "sg_c2_s2_r001", "subcategory_id": "sg_c2_s2", "name": "تقرير عن التدخل في حالة تنمر", "order": 1},
    {"id": "sg_c2_s2_r002", "subcategory_id": "sg_c2_s2", "name": "سجل متابعة طالب متورط في مشاجرة", "order": 2},
    {"id": "sg_c2_s2_r003", "subcategory_id": "sg_c2_s2", "name": "تقرير عن برنامج تعديل سلوك لطالب عدواني", "order": 3},
    {"id": "sg_c2_s2_r004", "subcategory_id": "sg_c2_s2", "name": "توثيق اجتماعات مع أولياء الأمور بسبب سلوك", "order": 4},
    {"id": "sg_c2_s2_r005", "subcategory_id": "sg_c2_s2", "name": "تقرير عن نتائج التدخل السلوكي", "order": 5},
    {"id": "sg_c2_s2_r006", "subcategory_id": "sg_c2_s2", "name": "سجل حالات التنمر الإلكتروني", "order": 6},
    {"id": "sg_c2_s2_r007", "subcategory_id": "sg_c2_s2", "name": "تقرير عن برنامج وساطة الأقران", "order": 7},
    {"id": "sg_c2_s2_r008", "subcategory_id": "sg_c2_s2", "name": "توثيق عقود سلوكية مع الطلاب", "order": 8},
    {"id": "sg_c2_s2_r009", "subcategory_id": "sg_c2_s2", "name": "تقرير عن متابعة الطالب المتنمر بعد التدخل", "order": 9},
    {"id": "sg_c2_s2_r010", "subcategory_id": "sg_c2_s2", "name": "سجل ورش عمل للطلاب حول احترام الآخرين", "order": 10},
    {"id": "sg_c2_s2_r011", "subcategory_id": "sg_c2_s2", "name": "تقرير عن التعامل مع حالات العنف الجماعي", "order": 11},
    {"id": "sg_c2_s2_r012", "subcategory_id": "sg_c2_s2", "name": "توثيق برامج تعزيز السلوك الإيجابي", "order": 12},
    {"id": "sg_c2_s2_r013", "subcategory_id": "sg_c2_s2", "name": "تقرير عن دور المرشد في فض النزاعات", "order": 13},
    {"id": "sg_c2_s2_r014", "subcategory_id": "sg_c2_s2", "name": "سجل استمارات قياس العنف المدرسي", "order": 14},
    {"id": "sg_c2_s2_r015", "subcategory_id": "sg_c2_s2", "name": "تقرير عن نتائج استبيان المناخ المدرسي", "order": 15},
    {"id": "sg_c2_s2_r016", "subcategory_id": "sg_c2_s2", "name": "توثيق حملات توعوية عن مخاطر التنمر", "order": 16},
    {"id": "sg_c2_s2_r017", "subcategory_id": "sg_c2_s2", "name": "تقرير عن متابعة الطلاب المعرضين للتنمر", "order": 17},
    {"id": "sg_c2_s2_r018", "subcategory_id": "sg_c2_s2", "name": "سجل اجتماعات مع لجنة مكافحة التنمر", "order": 18},
    {"id": "sg_c2_s2_r019", "subcategory_id": "sg_c2_s2", "name": "تقرير عن أثر برامج التوعية على خفض العنف", "order": 19},
    {"id": "sg_c2_s2_r020", "subcategory_id": "sg_c2_s2", "name": "توثيق قصص نجاح في تعديل السلوك العدواني", "order": 20},

    # ========== sg_c2_s3 ==========
    {"id": "sg_c2_s3_r001", "subcategory_id": "sg_c2_s3", "name": "تقرير عن متابعة طالب معرض للانقطاع عن المدرسة", "order": 1},
    {"id": "sg_c2_s3_r002", "subcategory_id": "sg_c2_s3", "name": "سجل زيارات منزلية لطلاب متغيبين", "order": 2},
    {"id": "sg_c2_s3_r003", "subcategory_id": "sg_c2_s3", "name": "تقرير عن متابعة طالب يعاني من إهمال أسري", "order": 3},
    {"id": "sg_c2_s3_r004", "subcategory_id": "sg_c2_s3", "name": "توثيق التنسيق مع خدمات حماية الطفل", "order": 4},
    {"id": "sg_c2_s3_r005", "subcategory_id": "sg_c2_s3", "name": "تقرير عن تحسن حالة طالب بعد المتابعة", "order": 5},
    {"id": "sg_c2_s3_r006", "subcategory_id": "sg_c2_s3", "name": "سجل متابعة الطلاب ذوي الغياب المتكرر", "order": 6},
    {"id": "sg_c2_s3_r007", "subcategory_id": "sg_c2_s3", "name": "تقرير عن برامج الدعم للطلاب المعرضين للخطر", "order": 7},
    {"id": "sg_c2_s3_r008", "subcategory_id": "sg_c2_s3", "name": "توثيق حالات التسرب المدرسي", "order": 8},
    {"id": "sg_c2_s3_r009", "subcategory_id": "sg_c2_s3", "name": "تقرير عن متابعة طلاب العمالة الوافدة", "order": 9},
    {"id": "sg_c2_s3_r010", "subcategory_id": "sg_c2_s3", "name": "سجل التواصل مع أولياء الأمور للطلاب المتعثرين", "order": 10},
    {"id": "sg_c2_s3_r011", "subcategory_id": "sg_c2_s3", "name": "تقرير عن برنامج العودة إلى المدرسة", "order": 11},
    {"id": "sg_c2_s3_r012", "subcategory_id": "sg_c2_s3", "name": "توثيق شراكات مع مؤسسات دعم الطلاب", "order": 12},
    {"id": "sg_c2_s3_r013", "subcategory_id": "sg_c2_s3", "name": "تقرير عن متابعة الطلاب ذوي المشكلات الصحية", "order": 13},
    {"id": "sg_c2_s3_r014", "subcategory_id": "sg_c2_s3", "name": "سجل حالات الطلاب المنقولين لمدارس أخرى", "order": 14},
    {"id": "sg_c2_s3_r015", "subcategory_id": "sg_c2_s3", "name": "تقرير عن أثر الدعم النفسي على استمرارية الطلاب", "order": 15},
    {"id": "sg_c2_s3_r016", "subcategory_id": "sg_c2_s3", "name": "توثيق لقاءات مع المرشد الاجتماعي", "order": 16},
    {"id": "sg_c2_s3_r017", "subcategory_id": "sg_c2_s3", "name": "تقرير عن متابعة الطلاب المفرج عنهم من دور الرعاية", "order": 17},
    {"id": "sg_c2_s3_r018", "subcategory_id": "sg_c2_s3", "name": "سجل إحصائي للطلاب المعرضين للخطر", "order": 18},
    {"id": "sg_c2_s3_r019", "subcategory_id": "sg_c2_s3", "name": "تقرير عن برامج التدخل المبكر", "order": 19},
    {"id": "sg_c2_s3_r020", "subcategory_id": "sg_c2_s3", "name": "توثيق خطط الرعاية الفردية", "order": 20},

    # ========== sg_c2_s4 ==========
    {"id": "sg_c2_s4_r001", "subcategory_id": "sg_c2_s4", "name": "تقرير عن جلسات دعم نفسي لطالب يعاني من قلق", "order": 1},
    {"id": "sg_c2_s4_r002", "subcategory_id": "sg_c2_s4", "name": "سجل متابعة طالب يعاني من اكتئاب", "order": 2},
    {"id": "sg_c2_s4_r003", "subcategory_id": "sg_c2_s4", "name": "تقرير عن استخدام تقنيات الاسترخاء مع الطلاب", "order": 3},
    {"id": "sg_c2_s4_r004", "subcategory_id": "sg_c2_s4", "name": "توثيق تحويل حالة لمرشد نفسي خارجي", "order": 4},
    {"id": "sg_c2_s4_r005", "subcategory_id": "sg_c2_s4", "name": "تقرير عن تحسن الحالة النفسية", "order": 5},
    {"id": "sg_c2_s4_r006", "subcategory_id": "sg_c2_s4", "name": "سجل جلسات العلاج باللعب", "order": 6},
    {"id": "sg_c2_s4_r007", "subcategory_id": "sg_c2_s4", "name": "تقرير عن برنامج إدارة القلق قبل الامتحانات", "order": 7},
    {"id": "sg_c2_s4_r008", "subcategory_id": "sg_c2_s4", "name": "توثيق استخدام مقياس القلق والاكتئاب", "order": 8},
    {"id": "sg_c2_s4_r009", "subcategory_id": "sg_c2_s4", "name": "تقرير عن مجموعات الدعم للطلاب القلقين", "order": 9},
    {"id": "sg_c2_s4_r010", "subcategory_id": "sg_c2_s4", "name": "سجل ورش عمل عن التفكير الإيجابي", "order": 10},
    {"id": "sg_c2_s4_r011", "subcategory_id": "sg_c2_s4", "name": "تقرير عن التعامل مع الطلاب ذوي الأفكار الانتحارية", "order": 11},
    {"id": "sg_c2_s4_r012", "subcategory_id": "sg_c2_s4", "name": "توثيق برامج تعزيز المرونة النفسية", "order": 12},
    {"id": "sg_c2_s4_r013", "subcategory_id": "sg_c2_s4", "name": "تقرير عن متابعة طلاب يعانون من اضطرابات الأكل", "order": 13},
    {"id": "sg_c2_s4_r014", "subcategory_id": "sg_c2_s4", "name": "سجل استشارات نفسية لأولياء الأمور", "order": 14},
    {"id": "sg_c2_s4_r015", "subcategory_id": "sg_c2_s4", "name": "تقرير عن أثر الرياضة على الصحة النفسية", "order": 15},
    {"id": "sg_c2_s4_r016", "subcategory_id": "sg_c2_s4", "name": "توثيق حالات التعافي من الاكتئاب", "order": 16},
    {"id": "sg_c2_s4_r017", "subcategory_id": "sg_c2_s4", "name": "تقرير عن برامج التوعية بالصحة النفسية", "order": 17},
    {"id": "sg_c2_s4_r018", "subcategory_id": "sg_c2_s4", "name": "سجل متابعة الطلاب بعد الأزمات", "order": 18},
    {"id": "sg_c2_s4_r019", "subcategory_id": "sg_c2_s4", "name": "تقرير عن استخدام الفنون في العلاج النفسي", "order": 19},
    {"id": "sg_c2_s4_r020", "subcategory_id": "sg_c2_s4", "name": "توثيق التعاون مع أخصائي الصحة النفسية", "order": 20},

    # ========== sg_c2_s5 ==========
    {"id": "sg_c2_s5_r001", "subcategory_id": "sg_c2_s5", "name": "تقرير عن إحالة طالب لطبيب نفسي", "order": 1},
    {"id": "sg_c2_s5_r002", "subcategory_id": "sg_c2_s5", "name": "سجل تحويل حالات لوحدة الخدمات", "order": 2},
    {"id": "sg_c2_s5_r003", "subcategory_id": "sg_c2_s5", "name": "تقرير عن التنسيق مع مستشفى الصحة النفسية", "order": 3},
    {"id": "sg_c2_s5_r004", "subcategory_id": "sg_c2_s5", "name": "توثيق متابعة حالة محولة", "order": 4},
    {"id": "sg_c2_s5_r005", "subcategory_id": "sg_c2_s5", "name": "تقرير عن إجراءات الإحالة والنتائج", "order": 5},
    {"id": "sg_c2_s5_r006", "subcategory_id": "sg_c2_s5", "name": "سجل تحويل حالات إلى الأخصائي الاجتماعي", "order": 6},
    {"id": "sg_c2_s5_r007", "subcategory_id": "sg_c2_s5", "name": "تقرير عن التنسيق مع مراكز تأهيل ذوي الاحتياجات", "order": 7},
    {"id": "sg_c2_s5_r008", "subcategory_id": "sg_c2_s5", "name": "توثيق نماذج الإحالة المستخدمة", "order": 8},
    {"id": "sg_c2_s5_r009", "subcategory_id": "sg_c2_s5", "name": "تقرير عن متابعة الحالات المحولة للعلاج", "order": 9},
    {"id": "sg_c2_s5_r010", "subcategory_id": "sg_c2_s5", "name": "سجل التواصل مع الجهات المختصة بحماية الطفل", "order": 10},
    {"id": "sg_c2_s5_r011", "subcategory_id": "sg_c2_s5", "name": "تقرير عن الإحالات المتعلقة بالصعوبات التعليمية", "order": 11},
    {"id": "sg_c2_s5_r012", "subcategory_id": "sg_c2_s5", "name": "توثيق تقارير المتابعة بعد الإحالة", "order": 12},
    {"id": "sg_c2_s5_r013", "subcategory_id": "sg_c2_s5", "name": "تقرير عن التنسيق مع مراكز مكافحة التدخين", "order": 13},
    {"id": "sg_c2_s5_r014", "subcategory_id": "sg_c2_s5", "name": "سجل الإحالات للعلاج الأسري", "order": 14},
    {"id": "sg_c2_s5_r015", "subcategory_id": "sg_c2_s5", "name": "تقرير عن نتائج التعاون مع الجهات الخارجية", "order": 15},
    {"id": "sg_c2_s5_r016", "subcategory_id": "sg_c2_s5", "name": "توثيق حالات الإحالة الطارئة", "order": 16},
    {"id": "sg_c2_s5_r017", "subcategory_id": "sg_c2_s5", "name": "تقرير عن أثر الإحالة على تحسن الطالب", "order": 17},
    {"id": "sg_c2_s5_r018", "subcategory_id": "sg_c2_s5", "name": "سجل استقبال تقارير من الجهات المحول إليها", "order": 18},
    {"id": "sg_c2_s5_r019", "subcategory_id": "sg_c2_s5", "name": "تقرير عن تحديث قاعدة بيانات الإحالات", "order": 19},
    {"id": "sg_c2_s5_r020", "subcategory_id": "sg_c2_s5", "name": "توثيق حالات الإحالة الناجحة", "order": 20},

    # ========== sg_c3_s1 ==========
    {"id": "sg_c3_s1_r001", "subcategory_id": "sg_c3_s1", "name": "تقرير عن برنامج توعوي عن أضرار التدخين", "order": 1},
    {"id": "sg_c3_s1_r002", "subcategory_id": "sg_c3_s1", "name": "سجل محاضرات عن مخاطر المخدرات", "order": 2},
    {"id": "sg_c3_s1_r003", "subcategory_id": "sg_c3_s1", "name": "تقرير عن مشاركة المدرسة في اليوم العالمي لمكافحة التدخين", "order": 3},
    {"id": "sg_c3_s1_r004", "subcategory_id": "sg_c3_s1", "name": "توثيق تعاون مع جمعية مكافحة التدخين", "order": 4},
    {"id": "sg_c3_s1_r005", "subcategory_id": "sg_c3_s1", "name": "تقرير عن وعي الطلاب بعد البرنامج", "order": 5},
    {"id": "sg_c3_s1_r006", "subcategory_id": "sg_c3_s1", "name": "سجل ورش عمل عن الإقلاع عن التدخين", "order": 6},
    {"id": "sg_c3_s1_r007", "subcategory_id": "sg_c3_s1", "name": "تقرير عن برنامج توعوي للطلاب المدخنين", "order": 7},
    {"id": "sg_c3_s1_r008", "subcategory_id": "sg_c3_s1", "name": "توثيق توزيع مطويات عن أضرار التدخين", "order": 8},
    {"id": "sg_c3_s1_r009", "subcategory_id": "sg_c3_s1", "name": "تقرير عن محاضرات التوعية بالتدخين السلبي", "order": 9},
    {"id": "sg_c3_s1_r010", "subcategory_id": "sg_c3_s1", "name": "سجل مسابقات توعوية عن المخدرات", "order": 10},
    {"id": "sg_c3_s1_r011", "subcategory_id": "sg_c3_s1", "name": "تقرير عن برنامج التوعية بأضرار الشيشة", "order": 11},
    {"id": "sg_c3_s1_r012", "subcategory_id": "sg_c3_s1", "name": "توثيق زيارات لعيادات مكافحة التدخين", "order": 12},
    {"id": "sg_c3_s1_r013", "subcategory_id": "sg_c3_s1", "name": "تقرير عن استبيان اتجاهات الطلاب نحو التدخين", "order": 13},
    {"id": "sg_c3_s1_r014", "subcategory_id": "sg_c3_s1", "name": "سجل اجتماعات مع أولياء الأمور حول مخاطر التدخين", "order": 14},
    {"id": "sg_c3_s1_r015", "subcategory_id": "sg_c3_s1", "name": "تقرير عن أثر البرامج على خفض التدخين", "order": 15},
    {"id": "sg_c3_s1_r016", "subcategory_id": "sg_c3_s1", "name": "توثيق حالات طلاب أقلعوا عن التدخين", "order": 16},
    {"id": "sg_c3_s1_r017", "subcategory_id": "sg_c3_s1", "name": "تقرير عن برنامج توعوي عن أضرار السجائر الإلكترونية", "order": 17},
    {"id": "sg_c3_s1_r018", "subcategory_id": "sg_c3_s1", "name": "سجل محاضرات عن تعزيز الصحة العامة", "order": 18},
    {"id": "sg_c3_s1_r019", "subcategory_id": "sg_c3_s1", "name": "تقرير عن فعالية اليوم المفتوح للتوعية", "order": 19},
    {"id": "sg_c3_s1_r020", "subcategory_id": "sg_c3_s1", "name": "توثيق شراكات مع وزارة الصحة", "order": 20},

    # ========== sg_c3_s2 ==========
    {"id": "sg_c3_s2_r001", "subcategory_id": "sg_c3_s2", "name": "تقرير عن ندوة عن الأمن الفكري", "order": 1},
    {"id": "sg_c3_s2_r002", "subcategory_id": "sg_c3_s2", "name": "سجل محاضرات عن الوسطية والاعتدال", "order": 2},
    {"id": "sg_c3_s2_r003", "subcategory_id": "sg_c3_s2", "name": "تقرير عن برنامج التحذير من الأفكار المتطرفة", "order": 3},
    {"id": "sg_c3_s2_r004", "subcategory_id": "sg_c3_s2", "name": "توثيق مشاركة طلاب في مسابقات وطنية", "order": 4},
    {"id": "sg_c3_s2_r005", "subcategory_id": "sg_c3_s2", "name": "تقرير عن أثر البرنامج على وعي الطلاب", "order": 5},
    {"id": "sg_c3_s2_r006", "subcategory_id": "sg_c3_s2", "name": "سجل ورش عمل عن تعزيز الانتماء الوطني", "order": 6},
    {"id": "sg_c3_s2_r007", "subcategory_id": "sg_c3_s2", "name": "تقرير عن برنامج حوار الأجيال", "order": 7},
    {"id": "sg_c3_s2_r008", "subcategory_id": "sg_c3_s2", "name": "توثيق لقاءات مع خبراء في الأمن الفكري", "order": 8},
    {"id": "sg_c3_s2_r009", "subcategory_id": "sg_c3_s2", "name": "تقرير عن استبيان قياس الوعي الفكري", "order": 9},
    {"id": "sg_c3_s2_r010", "subcategory_id": "sg_c3_s2", "name": "سجل أنشطة عن التسامح وقبول الآخر", "order": 10},
    {"id": "sg_c3_s2_r011", "subcategory_id": "sg_c3_s2", "name": "تقرير عن محاضرات عن مخاطر التطرف", "order": 11},
    {"id": "sg_c3_s2_r012", "subcategory_id": "sg_c3_s2", "name": "توثيق زيارات لمراكز فكرية", "order": 12},
    {"id": "sg_c3_s2_r013", "subcategory_id": "sg_c3_s2", "name": "تقرير عن برنامج تعزيز الهوية الوطنية", "order": 13},
    {"id": "sg_c3_s2_r014", "subcategory_id": "sg_c3_s2", "name": "سجل مسابقات في الأمن الفكري", "order": 14},
    {"id": "sg_c3_s2_r015", "subcategory_id": "sg_c3_s2", "name": "تقرير عن ورش عمل عن الإعلام الجديد", "order": 15},
    {"id": "sg_c3_s2_r016", "subcategory_id": "sg_c3_s2", "name": "توثيق مشاركة الطلاب في حملات وطنية", "order": 16},
    {"id": "sg_c3_s2_r017", "subcategory_id": "sg_c3_s2", "name": "تقرير عن أثر برامج الأمن الفكري على السلوك", "order": 17},
    {"id": "sg_c3_s2_r018", "subcategory_id": "sg_c3_s2", "name": "سجل محاضرات عن المواطنة الرقمية", "order": 18},
    {"id": "sg_c3_s2_r019", "subcategory_id": "sg_c3_s2", "name": "تقرير عن التعاون مع الجهات الأمنية", "order": 19},
    {"id": "sg_c3_s2_r020", "subcategory_id": "sg_c3_s2", "name": "توثيق حالات استشارية في الأمن الفكري", "order": 20},

    # ========== sg_c3_s3 ==========
    {"id": "sg_c3_s3_r001", "subcategory_id": "sg_c3_s3", "name": "تقرير عن ورشة الاستخدام الآمن للإنترنت", "order": 1},
    {"id": "sg_c3_s3_r002", "subcategory_id": "sg_c3_s3", "name": "سجل محاضرات عن التنمر الإلكتروني", "order": 2},
    {"id": "sg_c3_s3_r003", "subcategory_id": "sg_c3_s3", "name": "تقرير عن برنامج حماية الخصوصية", "order": 3},
    {"id": "sg_c3_s3_r004", "subcategory_id": "sg_c3_s3", "name": "توثيق توزيع مطويات عن الأمن السيبراني", "order": 4},
    {"id": "sg_c3_s3_r005", "subcategory_id": "sg_c3_s3", "name": "تقرير عن تفاعل الطلاب مع البرنامج", "order": 5},
    {"id": "sg_c3_s3_r006", "subcategory_id": "sg_c3_s3", "name": "سجل ورش عمل عن التصدي للإشاعات", "order": 6},
    {"id": "sg_c3_s3_r007", "subcategory_id": "sg_c3_s3", "name": "تقرير عن برنامج الاستخدام المسؤول لوسائل التواصل", "order": 7},
    {"id": "sg_c3_s3_r008", "subcategory_id": "sg_c3_s3", "name": "توثيق محاضرات عن مخاطر الألعاب الإلكترونية", "order": 8},
    {"id": "sg_c3_s3_r009", "subcategory_id": "sg_c3_s3", "name": "تقرير عن استبيان حول سلوكيات الطلاب على الإنترنت", "order": 9},
    {"id": "sg_c3_s3_r010", "subcategory_id": "sg_c3_s3", "name": "سجل لقاءات مع أولياء الأمور عن الرقابة الأسرية", "order": 10},
    {"id": "sg_c3_s3_r011", "subcategory_id": "sg_c3_s3", "name": "تقرير عن التعاون مع هيئة الاتصالات", "order": 11},
    {"id": "sg_c3_s3_r012", "subcategory_id": "sg_c3_s3", "name": "توثيق مسابقات حول الأمن السيبراني", "order": 12},
    {"id": "sg_c3_s3_r013", "subcategory_id": "sg_c3_s3", "name": "تقرير عن برنامج حماية الحسابات الشخصية", "order": 13},
    {"id": "sg_c3_s3_r014", "subcategory_id": "sg_c3_s3", "name": "سجل ورش عمل عن الإدمان الإلكتروني", "order": 14},
    {"id": "sg_c3_s3_r015", "subcategory_id": "sg_c3_s3", "name": "تقرير عن أثر التوعية على خفض التنمر الإلكتروني", "order": 15},
    {"id": "sg_c3_s3_r016", "subcategory_id": "sg_c3_s3", "name": "توثيق حالات تنمر إلكتروني وسبل معالجتها", "order": 16},
    {"id": "sg_c3_s3_r017", "subcategory_id": "sg_c3_s3", "name": "تقرير عن برنامج التوعية بالقرصنة الإلكترونية", "order": 17},
    {"id": "sg_c3_s3_r018", "subcategory_id": "sg_c3_s3", "name": "سجل محاضرات عن حماية البيانات", "order": 18},
    {"id": "sg_c3_s3_r019", "subcategory_id": "sg_c3_s3", "name": "تقرير عن مشاركة المدرسة في الأسبوع العالمي للتوعية الرقمية", "order": 19},
    {"id": "sg_c3_s3_r020", "subcategory_id": "sg_c3_s3", "name": "توثيق تقارير عن وعي الطلاب الرقمي", "order": 20},

    # ========== sg_c3_s4 ==========
    {"id": "sg_c3_s4_r001", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج تنمية المهارات الحياتية", "order": 1},
    {"id": "sg_c3_s4_r002", "subcategory_id": "sg_c3_s4", "name": "سجل ورش عمل عن حل المشكلات", "order": 2},
    {"id": "sg_c3_s4_r003", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج إدارة الوقت", "order": 3},
    {"id": "sg_c3_s4_r004", "subcategory_id": "sg_c3_s4", "name": "توثيق أنشطة عن التواصل الفعال", "order": 4},
    {"id": "sg_c3_s4_r005", "subcategory_id": "sg_c3_s4", "name": "تقرير عن تحسن مهارات الطلاب", "order": 5},
    {"id": "sg_c3_s4_r006", "subcategory_id": "sg_c3_s4", "name": "سجل ورش عمل عن اتخاذ القرار", "order": 6},
    {"id": "sg_c3_s4_r007", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج التفكير الناقد", "order": 7},
    {"id": "sg_c3_s4_r008", "subcategory_id": "sg_c3_s4", "name": "توثيق أنشطة عن التعاون والعمل الجماعي", "order": 8},
    {"id": "sg_c3_s4_r009", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج إدارة الغضب", "order": 9},
    {"id": "sg_c3_s4_r010", "subcategory_id": "sg_c3_s4", "name": "سجل ورش عمل عن القيادة", "order": 10},
    {"id": "sg_c3_s4_r011", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج التخطيط الشخصي", "order": 11},
    {"id": "sg_c3_s4_r012", "subcategory_id": "sg_c3_s4", "name": "توثيق أنشطة عن التعاطف", "order": 12},
    {"id": "sg_c3_s4_r013", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج المسؤولية الاجتماعية", "order": 13},
    {"id": "sg_c3_s4_r014", "subcategory_id": "sg_c3_s4", "name": "سجل ورش عمل عن مهارات التفاوض", "order": 14},
    {"id": "sg_c3_s4_r015", "subcategory_id": "sg_c3_s4", "name": "تقرير عن أثر المهارات الحياتية على التحصيل", "order": 15},
    {"id": "sg_c3_s4_r016", "subcategory_id": "sg_c3_s4", "name": "توثيق استبيانات قياس المهارات", "order": 16},
    {"id": "sg_c3_s4_r017", "subcategory_id": "sg_c3_s4", "name": "تقرير عن برنامج الإلقاء والتحدث أمام الجمهور", "order": 17},
    {"id": "sg_c3_s4_r018", "subcategory_id": "sg_c3_s4", "name": "سجل ورش عمل عن إدارة المشاريع", "order": 18},
    {"id": "sg_c3_s4_r019", "subcategory_id": "sg_c3_s4", "name": "تقرير عن التعاون مع مؤسسات تدريبية", "order": 19},
    {"id": "sg_c3_s4_r020", "subcategory_id": "sg_c3_s4", "name": "توثيق قصص نجاح في تنمية المهارات", "order": 20},

    # ========== sg_c3_s5 ==========
    {"id": "sg_c3_s5_r001", "subcategory_id": "sg_c3_s5", "name": "تقرير عن حملة مكافحة التنمر", "order": 1},
    {"id": "sg_c3_s5_r002", "subcategory_id": "sg_c3_s5", "name": "سجل فعاليات اليوم العالمي لمكافحة التنمر", "order": 2},
    {"id": "sg_c3_s5_r003", "subcategory_id": "sg_c3_s5", "name": "تقرير عن ورش عمل للطلاب عن التنمر", "order": 3},
    {"id": "sg_c3_s5_r004", "subcategory_id": "sg_c3_s5", "name": "توثيق مسابقات للتوعية بالتنمر", "order": 4},
    {"id": "sg_c3_s5_r005", "subcategory_id": "sg_c3_s5", "name": "تقرير عن انخفاض حالات التنمر بعد الحملة", "order": 5},
    {"id": "sg_c3_s5_r006", "subcategory_id": "sg_c3_s5", "name": "سجل محاضرات عن التنمر الجسدي", "order": 6},
    {"id": "sg_c3_s5_r007", "subcategory_id": "sg_c3_s5", "name": "تقرير عن برنامج تدريب الأقران لمكافحة التنمر", "order": 7},
    {"id": "sg_c3_s5_r008", "subcategory_id": "sg_c3_s5", "name": "توثيق توزيع مطويات عن التنمر", "order": 8},
    {"id": "sg_c3_s5_r009", "subcategory_id": "sg_c3_s5", "name": "تقرير عن استبيان حول انتشار التنمر", "order": 9},
    {"id": "sg_c3_s5_r010", "subcategory_id": "sg_c3_s5", "name": "سجل اجتماعات مع أولياء الأمور حول التنمر", "order": 10},
    {"id": "sg_c3_s5_r011", "subcategory_id": "sg_c3_s5", "name": "تقرير عن برنامج فن التعامل مع المتنمر", "order": 11},
    {"id": "sg_c3_s5_r012", "subcategory_id": "sg_c3_s5", "name": "توثيق مشاركة طلاب في أفلام توعوية", "order": 12},
    {"id": "sg_c3_s5_r013", "subcategory_id": "sg_c3_s5", "name": "تقرير عن ورش عمل عن التنمر اللفظي", "order": 13},
    {"id": "sg_c3_s5_r014", "subcategory_id": "sg_c3_s5", "name": "سجل برامج تعزيز الثقة لمواجهة التنمر", "order": 14},
    {"id": "sg_c3_s5_r015", "subcategory_id": "sg_c3_s5", "name": "تقرير عن التعاون مع جهات متخصصة", "order": 15},
    {"id": "sg_c3_s5_r016", "subcategory_id": "sg_c3_s5", "name": "توثيق حالات تنمر وعلاجها", "order": 16},
    {"id": "sg_c3_s5_r017", "subcategory_id": "sg_c3_s5", "name": "تقرير عن برنامج المدرسة الآمنة", "order": 17},
    {"id": "sg_c3_s5_r018", "subcategory_id": "sg_c3_s5", "name": "سجل مسرحيات توعوية عن التنمر", "order": 18},
    {"id": "sg_c3_s5_r019", "subcategory_id": "sg_c3_s5", "name": "تقرير عن أثر حملات التوعية على سلوك الطلاب", "order": 19},
    {"id": "sg_c3_s5_r020", "subcategory_id": "sg_c3_s5", "name": "توثيق شهادات طلاب ضد التنمر", "order": 20},

    # ========== sg_c4_s1 ==========
    {"id": "sg_c4_s1_r001", "subcategory_id": "sg_c4_s1", "name": "تقرير عن التنسيق مع معلمي الصفوف", "order": 1},
    {"id": "sg_c4_s1_r002", "subcategory_id": "sg_c4_s1", "name": "سجل اجتماعات مع المعلمين لمتابعة الطلاب", "order": 2},
    {"id": "sg_c4_s1_r003", "subcategory_id": "sg_c4_s1", "name": "تقرير عن تبادل المعلومات بين المرشد والمعلمين", "order": 3},
    {"id": "sg_c4_s1_r004", "subcategory_id": "sg_c4_s1", "name": "توثيق تقارير المعلمين عن الطلاب", "order": 4},
    {"id": "sg_c4_s1_r005", "subcategory_id": "sg_c4_s1", "name": "تقرير عن تحسن أداء الطلاب بفضل التعاون", "order": 5},
    {"id": "sg_c4_s1_r006", "subcategory_id": "sg_c4_s1", "name": "سجل تنسيق مع معلمي المواد", "order": 6},
    {"id": "sg_c4_s1_r007", "subcategory_id": "sg_c4_s1", "name": "تقرير عن اجتماعات تنسيقية دورية", "order": 7},
    {"id": "sg_c4_s1_r008", "subcategory_id": "sg_c4_s1", "name": "توثيق استمارات متابعة الطلاب", "order": 8},
    {"id": "sg_c4_s1_r009", "subcategory_id": "sg_c4_s1", "name": "تقرير عن ورش عمل مشتركة مع المعلمين", "order": 9},
    {"id": "sg_c4_s1_r010", "subcategory_id": "sg_c4_s1", "name": "سجل تبادل ملاحظات سلوكية", "order": 10},
    {"id": "sg_c4_s1_r011", "subcategory_id": "sg_c4_s1", "name": "تقرير عن التنسيق في تعديل سلوك طالب", "order": 11},
    {"id": "sg_c4_s1_r012", "subcategory_id": "sg_c4_s1", "name": "توثيق تقارير المعلمين عن طلاب موهوبين", "order": 12},
    {"id": "sg_c4_s1_r013", "subcategory_id": "sg_c4_s1", "name": "تقرير عن التعاون في برامج وقائية", "order": 13},
    {"id": "sg_c4_s1_r014", "subcategory_id": "sg_c4_s1", "name": "سجل اجتماعات مع معلمي التربية الخاصة", "order": 14},
    {"id": "sg_c4_s1_r015", "subcategory_id": "sg_c4_s1", "name": "تقرير عن تفعيل دور المعلم في الإرشاد", "order": 15},
    {"id": "sg_c4_s1_r016", "subcategory_id": "sg_c4_s1", "name": "توثيق ورش للمعلمين عن اكتشاف المشكلات", "order": 16},
    {"id": "sg_c4_s1_r017", "subcategory_id": "sg_c4_s1", "name": "تقرير عن نتائج التعاون على تحصيل الطلاب", "order": 17},
    {"id": "sg_c4_s1_r018", "subcategory_id": "sg_c4_s1", "name": "سجل زيارات للمعلمين في الفصول", "order": 18},
    {"id": "sg_c4_s1_r019", "subcategory_id": "sg_c4_s1", "name": "تقرير عن تنسيق مع مشرفي الأنشطة", "order": 19},
    {"id": "sg_c4_s1_r020", "subcategory_id": "sg_c4_s1", "name": "توثيق برامج توجيهية للمعلمين", "order": 20},

    # ========== sg_c4_s2 ==========
    {"id": "sg_c4_s2_r001", "subcategory_id": "sg_c4_s2", "name": "تقرير عن التواصل مع أولياء الأمور بشأن سلوك الطالب", "order": 1},
    {"id": "sg_c4_s2_r002", "subcategory_id": "sg_c4_s2", "name": "سجل المكالمات الهاتفية مع أولياء الأمور", "order": 2},
    {"id": "sg_c4_s2_r003", "subcategory_id": "sg_c4_s2", "name": "تقرير عن اجتماعات مع أولياء الأمور لتحسين السلوك", "order": 3},
    {"id": "sg_c4_s2_r004", "subcategory_id": "sg_c4_s2", "name": "توثيق رسائل البريد الإلكتروني مع أولياء الأمور", "order": 4},
    {"id": "sg_c4_s2_r005", "subcategory_id": "sg_c4_s2", "name": "تقرير عن رضا أولياء الأمور عن متابعة المرشد", "order": 5},
    {"id": "sg_c4_s2_r006", "subcategory_id": "sg_c4_s2", "name": "سجل استقبال أولياء الأمور في المدرسة", "order": 6},
    {"id": "sg_c4_s2_r007", "subcategory_id": "sg_c4_s2", "name": "تقرير عن تواصل مع أولياء أمور الطلاب المتفوقين", "order": 7},
    {"id": "sg_c4_s2_r008", "subcategory_id": "sg_c4_s2", "name": "توثيق إشعارات سلوكية لأولياء الأمور", "order": 8},
    {"id": "sg_c4_s2_r009", "subcategory_id": "sg_c4_s2", "name": "تقرير عن برامج توعية لأولياء الأمور", "order": 9},
    {"id": "sg_c4_s2_r010", "subcategory_id": "sg_c4_s2", "name": "سجل اتصالات هاتفية للغياب", "order": 10},
    {"id": "sg_c4_s2_r011", "subcategory_id": "sg_c4_s2", "name": "تقرير عن التنسيق مع أولياء الأمور في حالات التنمر", "order": 11},
    {"id": "sg_c4_s2_r012", "subcategory_id": "sg_c4_s2", "name": "توثيق استبيانات رضا أولياء الأمور", "order": 12},
    {"id": "sg_c4_s2_r013", "subcategory_id": "sg_c4_s2", "name": "تقرير عن اجتماعات فردية مع أولياء الأمور", "order": 13},
    {"id": "sg_c4_s2_r014", "subcategory_id": "sg_c4_s2", "name": "سجل التواصل مع أولياء الأمور عبر التطبيقات", "order": 14},
    {"id": "sg_c4_s2_r015", "subcategory_id": "sg_c4_s2", "name": "تقرير عن أثر التواصل على سلوك الطالب", "order": 15},
    {"id": "sg_c4_s2_r016", "subcategory_id": "sg_c4_s2", "name": "توثيق خطابات رسمية لأولياء الأمور", "order": 16},
    {"id": "sg_c4_s2_r017", "subcategory_id": "sg_c4_s2", "name": "تقرير عن برنامج شراكة أولياء الأمور", "order": 17},
    {"id": "sg_c4_s2_r018", "subcategory_id": "sg_c4_s2", "name": "سجل زيارات منزلية مع أولياء الأمور", "order": 18},
    {"id": "sg_c4_s2_r019", "subcategory_id": "sg_c4_s2", "name": "تقرير عن ورش عمل لأولياء الأمور", "order": 19},
    {"id": "sg_c4_s2_r020", "subcategory_id": "sg_c4_s2", "name": "توثيق قصص نجاح تعاون مع أولياء الأمور", "order": 20},

    # ========== sg_c4_s3 ==========
    {"id": "sg_c4_s3_r001", "subcategory_id": "sg_c4_s3", "name": "تقرير عن عقد اجتماعات مع أولياء الأمور", "order": 1},
    {"id": "sg_c4_s3_r002", "subcategory_id": "sg_c4_s3", "name": "سجل مجالس الآباء التي حضرها المرشد", "order": 2},
    {"id": "sg_c4_s3_r003", "subcategory_id": "sg_c4_s3", "name": "تقرير عن لقاءات توعوية لأولياء الأمور", "order": 3},
    {"id": "sg_c4_s3_r004", "subcategory_id": "sg_c4_s3", "name": "توثيق محاضر اجتماعات مع أولياء الأمور", "order": 4},
    {"id": "sg_c4_s3_r005", "subcategory_id": "sg_c4_s3", "name": "تقرير عن أثر الاجتماعات على متابعة أولياء الأمور", "order": 5},
    {"id": "sg_c4_s3_r006", "subcategory_id": "sg_c4_s3", "name": "سجل اجتماعات جماعية لأولياء الأمور", "order": 6},
    {"id": "sg_c4_s3_r007", "subcategory_id": "sg_c4_s3", "name": "تقرير عن ورش عمل لأولياء الأمور عن المهارات التربوية", "order": 7},
    {"id": "sg_c4_s3_r008", "subcategory_id": "sg_c4_s3", "name": "توثيق اجتماعات مع أولياء الأمور المتفوقين", "order": 8},
    {"id": "sg_c4_s3_r009", "subcategory_id": "sg_c4_s3", "name": "تقرير عن ندوات لأولياء الأمور عن الصحة النفسية", "order": 9},
    {"id": "sg_c4_s3_r010", "subcategory_id": "sg_c4_s3", "name": "سجل اجتماعات دورية مع لجنة أولياء الأمور", "order": 10},
    {"id": "sg_c4_s3_r011", "subcategory_id": "sg_c4_s3", "name": "تقرير عن مشاركة أولياء الأمور في الفعاليات المدرسية", "order": 11},
    {"id": "sg_c4_s3_r012", "subcategory_id": "sg_c4_s3", "name": "توثيق توصيات اجتماعات أولياء الأمور", "order": 12},
    {"id": "sg_c4_s3_r013", "subcategory_id": "sg_c4_s3", "name": "تقرير عن برنامج تدريب أولياء الأمور", "order": 13},
    {"id": "sg_c4_s3_r014", "subcategory_id": "sg_c4_s3", "name": "سجل استبانات أولياء الأمور بعد الاجتماعات", "order": 14},
    {"id": "sg_c4_s3_r015", "subcategory_id": "sg_c4_s3", "name": "تقرير عن اجتماعات لتعزيز التعاون الأسري", "order": 15},
    {"id": "sg_c4_s3_r016", "subcategory_id": "sg_c4_s3", "name": "توثيق محاضرات لأولياء الأمور عن الأمن الفكري", "order": 16},
    {"id": "sg_c4_s3_r017", "subcategory_id": "sg_c4_s3", "name": "تقرير عن أثر التوعية الأسرية على سلوك الطلاب", "order": 17},
    {"id": "sg_c4_s3_r018", "subcategory_id": "sg_c4_s3", "name": "سجل مشاركة أولياء الأمور في مجالس الآباء", "order": 18},
    {"id": "sg_c4_s3_r019", "subcategory_id": "sg_c4_s3", "name": "تقرير عن برنامج الأسرة والمدرسة", "order": 19},
    {"id": "sg_c4_s3_r020", "subcategory_id": "sg_c4_s3", "name": "توثيق قصص تعاون مع أولياء الأمور", "order": 20},

    # ========== sg_c4_s4 ==========
    {"id": "sg_c4_s4_r001", "subcategory_id": "sg_c4_s4", "name": "تقرير عن التنسيق مع الإدارة في قضايا الطلاب", "order": 1},
    {"id": "sg_c4_s4_r002", "subcategory_id": "sg_c4_s4", "name": "سجل التنسيق مع وحدة الخدمات الإرشادية", "order": 2},
    {"id": "sg_c4_s4_r003", "subcategory_id": "sg_c4_s4", "name": "تقرير عن التواصل مع مراكز الإرشاد الأسري", "order": 3},
    {"id": "sg_c4_s4_r004", "subcategory_id": "sg_c4_s4", "name": "توثيق خطابات التنسيق مع جهات خارجية", "order": 4},
    {"id": "sg_c4_s4_r005", "subcategory_id": "sg_c4_s4", "name": "تقرير عن فعالية التنسيق الخارجي", "order": 5},
    {"id": "sg_c4_s4_r006", "subcategory_id": "sg_c4_s4", "name": "سجل تنسيق مع مؤسسات المجتمع المحلي", "order": 6},
    {"id": "sg_c4_s4_r007", "subcategory_id": "sg_c4_s4", "name": "تقرير عن شراكات مع مستشفيات", "order": 7},
    {"id": "sg_c4_s4_r008", "subcategory_id": "sg_c4_s4", "name": "توثيق تعاون مع مراكز التنمية الاجتماعية", "order": 8},
    {"id": "sg_c4_s4_r009", "subcategory_id": "sg_c4_s4", "name": "تقرير عن التنسيق مع الشرطة المجتمعية", "order": 9},
    {"id": "sg_c4_s4_r010", "subcategory_id": "sg_c4_s4", "name": "سجل مشاركة في شبكات إرشادية", "order": 10},
    {"id": "sg_c4_s4_r011", "subcategory_id": "sg_c4_s4", "name": "تقرير عن التنسيق مع إدارة المدرسة في الأزمات", "order": 11},
    {"id": "sg_c4_s4_r012", "subcategory_id": "sg_c4_s4", "name": "توثيق اجتماعات مع قائد المدرسة", "order": 12},
    {"id": "sg_c4_s4_r013", "subcategory_id": "sg_c4_s4", "name": "تقرير عن تنسيق مع مشرفي التوجيه", "order": 13},
    {"id": "sg_c4_s4_r014", "subcategory_id": "sg_c4_s4", "name": "سجل مراسلات مع جهات حكومية", "order": 14},
    {"id": "sg_c4_s4_r015", "subcategory_id": "sg_c4_s4", "name": "تقرير عن التعاون مع منظمات غير ربحية", "order": 15},
    {"id": "sg_c4_s4_r016", "subcategory_id": "sg_c4_s4", "name": "توثيق برامج مشتركة مع جهات خارجية", "order": 16},
    {"id": "sg_c4_s4_r017", "subcategory_id": "sg_c4_s4", "name": "تقرير عن أثر الشراكات على الخدمات الإرشادية", "order": 17},
    {"id": "sg_c4_s4_r018", "subcategory_id": "sg_c4_s4", "name": "سجل تنسيق مع وسائل الإعلام", "order": 18},
    {"id": "sg_c4_s4_r019", "subcategory_id": "sg_c4_s4", "name": "تقرير عن التنسيق مع الجامعات", "order": 19},
    {"id": "sg_c4_s4_r020", "subcategory_id": "sg_c4_s4", "name": "توثيق مذكرات تفاهم مع جهات خارجية", "order": 20},

    # ========== sg_c4_s5 ==========
    {"id": "sg_c4_s5_r001", "subcategory_id": "sg_c4_s5", "name": "تقرير عن اجتماعات لجنة التوجيه والإرشاد", "order": 1},
    {"id": "sg_c4_s5_r002", "subcategory_id": "sg_c4_s5", "name": "سجل توصيات اللجنة ومتابعتها", "order": 2},
    {"id": "sg_c4_s5_r003", "subcategory_id": "sg_c4_s5", "name": "تقرير عن مساهمته في اللجنة", "order": 3},
    {"id": "sg_c4_s5_r004", "subcategory_id": "sg_c4_s5", "name": "توثيق محاضر اجتماعات اللجنة", "order": 4},
    {"id": "sg_c4_s5_r005", "subcategory_id": "sg_c4_s5", "name": "تقرير عن توصيات اللجنة المنفذة", "order": 5},
    {"id": "sg_c4_s5_r006", "subcategory_id": "sg_c4_s5", "name": "سجل متابعة قرارات اللجنة", "order": 6},
    {"id": "sg_c4_s5_r007", "subcategory_id": "sg_c4_s5", "name": "تقرير عن خطة اللجنة السنوية", "order": 7},
    {"id": "sg_c4_s5_r008", "subcategory_id": "sg_c4_s5", "name": "توثيق تقارير اللجنة المرفوعة للإدارة", "order": 8},
    {"id": "sg_c4_s5_r009", "subcategory_id": "sg_c4_s5", "name": "تقرير عن أدوار الأعضاء في اللجنة", "order": 9},
    {"id": "sg_c4_s5_r010", "subcategory_id": "sg_c4_s5", "name": "سجل اجتماعات اللجنة الفرعية", "order": 10},
    {"id": "sg_c4_s5_r011", "subcategory_id": "sg_c4_s5", "name": "تقرير عن مبادرات اللجنة", "order": 11},
    {"id": "sg_c4_s5_r012", "subcategory_id": "sg_c4_s5", "name": "توثيق تقييم أداء اللجنة", "order": 12},
    {"id": "sg_c4_s5_r013", "subcategory_id": "sg_c4_s5", "name": "تقرير عن توصيات اللجنة في تحسين السلوك", "order": 13},
    {"id": "sg_c4_s5_r014", "subcategory_id": "sg_c4_s5", "name": "سجل مشاركة اللجنة في الفعاليات", "order": 14},
    {"id": "sg_c4_s5_r015", "subcategory_id": "sg_c4_s5", "name": "تقرير عن نتائج اجتماعات اللجنة مع أولياء الأمور", "order": 15},
    {"id": "sg_c4_s5_r016", "subcategory_id": "sg_c4_s5", "name": "توثيق برامج اللجنة المنفذة", "order": 16},
    {"id": "sg_c4_s5_r017", "subcategory_id": "sg_c4_s5", "name": "تقرير عن أثر اللجنة على السياسات المدرسية", "order": 17},
    {"id": "sg_c4_s5_r018", "subcategory_id": "sg_c4_s5", "name": "سجل حضور اجتماعات اللجنة", "order": 18},
    {"id": "sg_c4_s5_r019", "subcategory_id": "sg_c4_s5", "name": "تقرير عن توصيات اللجنة في الأزمات", "order": 19},
    {"id": "sg_c4_s5_r020", "subcategory_id": "sg_c4_s5", "name": "توثيق محاضر اللجنة الإلكترونية", "order": 20},

    # ========== sg_c5_s1 ==========
    {"id": "sg_c5_s1_r001", "subcategory_id": "sg_c5_s1", "name": "تقرير عن توثيق حالات الطلاب في ملفات سرية", "order": 1},
    {"id": "sg_c5_s1_r002", "subcategory_id": "sg_c5_s1", "name": "سجل تحديث بيانات الحالات", "order": 2},
    {"id": "sg_c5_s1_r003", "subcategory_id": "sg_c5_s1", "name": "تقرير عن تنظيم أرشفة الحالات", "order": 3},
    {"id": "sg_c5_s1_r004", "subcategory_id": "sg_c5_s1", "name": "توثيق نموذج دراسة الحالة المستخدم", "order": 4},
    {"id": "sg_c5_s1_r005", "subcategory_id": "sg_c5_s1", "name": "تقرير عن مدى اكتمال ملفات الحالات", "order": 5},
    {"id": "sg_c5_s1_r006", "subcategory_id": "sg_c5_s1", "name": "سجل أرشفة الحالات إلكترونياً", "order": 6},
    {"id": "sg_c5_s1_r007", "subcategory_id": "sg_c5_s1", "name": "تقرير عن سرية المعلومات وحفظها", "order": 7},
    {"id": "sg_c5_s1_r008", "subcategory_id": "sg_c5_s1", "name": "توثيق نماذج الموافقة الخطية", "order": 8},
    {"id": "sg_c5_s1_r009", "subcategory_id": "sg_c5_s1", "name": "تقرير عن فهرسة الحالات", "order": 9},
    {"id": "sg_c5_s1_r010", "subcategory_id": "sg_c5_s1", "name": "سجل ترميز الحالات للحفاظ على الخصوصية", "order": 10},
    {"id": "sg_c5_s1_r011", "subcategory_id": "sg_c5_s1", "name": "تقرير عن أرشفة التقارير السابقة", "order": 11},
    {"id": "sg_c5_s1_r012", "subcategory_id": "sg_c5_s1", "name": "توثيق تحديثات ملفات الخريجين", "order": 12},
    {"id": "sg_c5_s1_r013", "subcategory_id": "sg_c5_s1", "name": "تقرير عن نظام التوثيق المتبع", "order": 13},
    {"id": "sg_c5_s1_r014", "subcategory_id": "sg_c5_s1", "name": "سجل صلاحية الوصول للملفات", "order": 14},
    {"id": "sg_c5_s1_r015", "subcategory_id": "sg_c5_s1", "name": "تقرير عن توثيق حالات الإحالة", "order": 15},
    {"id": "sg_c5_s1_r016", "subcategory_id": "sg_c5_s1", "name": "توثيق نماذج متابعة الحالات", "order": 16},
    {"id": "sg_c5_s1_r017", "subcategory_id": "sg_c5_s1", "name": "تقرير عن أرشفة ملفات الطلاب المحولة", "order": 17},
    {"id": "sg_c5_s1_r018", "subcategory_id": "sg_c5_s1", "name": "سجل حفظ المستندات الداعمة", "order": 18},
    {"id": "sg_c5_s1_r019", "subcategory_id": "sg_c5_s1", "name": "تقرير عن توثيق الحالات القديمة", "order": 19},
    {"id": "sg_c5_s1_r020", "subcategory_id": "sg_c5_s1", "name": "توثيق خطة الأرشفة السنوية", "order": 20},

    # ========== sg_c5_s2 ==========
    {"id": "sg_c5_s2_r001", "subcategory_id": "sg_c5_s2", "name": "تقرير شهري عن أنشطة الإرشاد", "order": 1},
    {"id": "sg_c5_s2_r002", "subcategory_id": "sg_c5_s2", "name": "سجل إحصائي للحالات المستفيدة", "order": 2},
    {"id": "sg_c5_s2_r003", "subcategory_id": "sg_c5_s2", "name": "تقرير عن أعداد المستفيدين من البرامج", "order": 3},
    {"id": "sg_c5_s2_r004", "subcategory_id": "sg_c5_s2", "name": "توثيق تقارير نصف فصلية", "order": 4},
    {"id": "sg_c5_s2_r005", "subcategory_id": "sg_c5_s2", "name": "تقرير عن تطور الحالات خلال الفصل", "order": 5},
    {"id": "sg_c5_s2_r006", "subcategory_id": "sg_c5_s2", "name": "سجل تقارير أسبوعية", "order": 6},
    {"id": "sg_c5_s2_r007", "subcategory_id": "sg_c5_s2", "name": "تقرير عن إنجازات المرشد", "order": 7},
    {"id": "sg_c5_s2_r008", "subcategory_id": "sg_c5_s2", "name": "توثيق تقارير ختامية للبرامج", "order": 8},
    {"id": "sg_c5_s2_r009", "subcategory_id": "sg_c5_s2", "name": "تقرير إحصائي عن أنواع الاستشارات", "order": 9},
    {"id": "sg_c5_s2_r010", "subcategory_id": "sg_c5_s2", "name": "سجل تقارير الفصل الدراسي", "order": 10},
    {"id": "sg_c5_s2_r011", "subcategory_id": "sg_c5_s2", "name": "تقرير عن توزيع الحالات حسب الصفوف", "order": 11},
    {"id": "sg_c5_s2_r012", "subcategory_id": "sg_c5_s2", "name": "توثيق تقارير اجتماعات اللجنة", "order": 12},
    {"id": "sg_c5_s2_r013", "subcategory_id": "sg_c5_s2", "name": "تقرير عن مؤشرات الأداء", "order": 13},
    {"id": "sg_c5_s2_r014", "subcategory_id": "sg_c5_s2", "name": "سجل تقارير متابعة الحالات الفردية", "order": 14},
    {"id": "sg_c5_s2_r015", "subcategory_id": "sg_c5_s2", "name": "تقرير سنوي شامل", "order": 15},
    {"id": "sg_c5_s2_r016", "subcategory_id": "sg_c5_s2", "name": "توثيق تقارير خاصة للإدارة", "order": 16},
    {"id": "sg_c5_s2_r017", "subcategory_id": "sg_c5_s2", "name": "تقرير عن إحصائيات التواصل مع أولياء الأمور", "order": 17},
    {"id": "sg_c5_s2_r018", "subcategory_id": "sg_c5_s2", "name": "سجل تقارير ورش العمل", "order": 18},
    {"id": "sg_c5_s2_r019", "subcategory_id": "sg_c5_s2", "name": "تقرير عن البرامج الوقائية", "order": 19},
    {"id": "sg_c5_s2_r020", "subcategory_id": "sg_c5_s2", "name": "توثيق تقارير قياس الأثر", "order": 20},

    # ========== sg_c5_s3 ==========
    {"id": "sg_c5_s3_r001", "subcategory_id": "sg_c5_s3", "name": "تقرير تحليل بيانات الحالات السلوكية", "order": 1},
    {"id": "sg_c5_s3_r002", "subcategory_id": "sg_c5_s3", "name": "سجل مؤشرات الأداء الإرشادي", "order": 2},
    {"id": "sg_c5_s3_r003", "subcategory_id": "sg_c5_s3", "name": "تقرير إحصائي عن أنواع المشكلات", "order": 3},
    {"id": "sg_c5_s3_r004", "subcategory_id": "sg_c5_s3", "name": "توثيق نتائج استبيانات الرضا", "order": 4},
    {"id": "sg_c5_s3_r005", "subcategory_id": "sg_c5_s3", "name": "تقرير عن توصيات بناء على التحليل", "order": 5},
    {"id": "sg_c5_s3_r006", "subcategory_id": "sg_c5_s3", "name": "سجل تحليل فجوات الأداء", "order": 6},
    {"id": "sg_c5_s3_r007", "subcategory_id": "sg_c5_s3", "name": "تقرير عن تحليل توزيع الحالات", "order": 7},
    {"id": "sg_c5_s3_r008", "subcategory_id": "sg_c5_s3", "name": "توثيق تحليل استبيانات المناخ المدرسي", "order": 8},
    {"id": "sg_c5_s3_r009", "subcategory_id": "sg_c5_s3", "name": "تقرير عن تحليل أسباب المشكلات", "order": 9},
    {"id": "sg_c5_s3_r010", "subcategory_id": "sg_c5_s3", "name": "سجل تحليل اتجاهات سلوكية", "order": 10},
    {"id": "sg_c5_s3_r011", "subcategory_id": "sg_c5_s3", "name": "تقرير عن مقارنات سنوية", "order": 11},
    {"id": "sg_c5_s3_r012", "subcategory_id": "sg_c5_s3", "name": "توثيق تحليل فعالية البرامج", "order": 12},
    {"id": "sg_c5_s3_r013", "subcategory_id": "sg_c5_s3", "name": "تقرير عن تحليل بيانات الغياب", "order": 13},
    {"id": "sg_c5_s3_r014", "subcategory_id": "sg_c5_s3", "name": "سجل تحليل نتائج المقاييس النفسية", "order": 14},
    {"id": "sg_c5_s3_r015", "subcategory_id": "sg_c5_s3", "name": "تقرير عن تحليل بيانات الإحالات", "order": 15},
    {"id": "sg_c5_s3_r016", "subcategory_id": "sg_c5_s3", "name": "توثيق تحليل استبيانات أولياء الأمور", "order": 16},
    {"id": "sg_c5_s3_r017", "subcategory_id": "sg_c5_s3", "name": "تقرير عن تحليل بيانات المتابعة", "order": 17},
    {"id": "sg_c5_s3_r018", "subcategory_id": "sg_c5_s3", "name": "سجل تحليل الاحتياجات الإرشادية", "order": 18},
    {"id": "sg_c5_s3_r019", "subcategory_id": "sg_c5_s3", "name": "تقرير عن تحليل بيانات المخاطر", "order": 19},
    {"id": "sg_c5_s3_r020", "subcategory_id": "sg_c5_s3", "name": "توثيق لوحة مؤشرات الأداء", "order": 20},

    # ========== sg_c5_s4 ==========
    {"id": "sg_c5_s4_r001", "subcategory_id": "sg_c5_s4", "name": "تقرير عن رفع تقارير للإدارة", "order": 1},
    {"id": "sg_c5_s4_r002", "subcategory_id": "sg_c5_s4", "name": "سجل التقارير المرفوعة للإدارة", "order": 2},
    {"id": "sg_c5_s4_r003", "subcategory_id": "sg_c5_s4", "name": "تقرير عن متابعة توصيات الإدارة", "order": 3},
    {"id": "sg_c5_s4_r004", "subcategory_id": "sg_c5_s4", "name": "توثيق تقارير خاصة لقائد المدرسة", "order": 4},
    {"id": "sg_c5_s4_r005", "subcategory_id": "sg_c5_s4", "name": "تقرير عن أثر التقارير على قرارات الإدارة", "order": 5},
    {"id": "sg_c5_s4_r006", "subcategory_id": "sg_c5_s4", "name": "سجل رفع تقارير شهرية", "order": 6},
    {"id": "sg_c5_s4_r007", "subcategory_id": "sg_c5_s4", "name": "تقرير عن تقارير استثنائية", "order": 7},
    {"id": "sg_c5_s4_r008", "subcategory_id": "sg_c5_s4", "name": "توثيق تقارير اجتماعات الإدارة", "order": 8},
    {"id": "sg_c5_s4_r009", "subcategory_id": "sg_c5_s4", "name": "تقرير عن مقترحات للإدارة", "order": 9},
    {"id": "sg_c5_s4_r010", "subcategory_id": "sg_c5_s4", "name": "سجل الردود على التقارير", "order": 10},
    {"id": "sg_c5_s4_r011", "subcategory_id": "sg_c5_s4", "name": "تقرير عن التوصيات المنفذة", "order": 11},
    {"id": "sg_c5_s4_r012", "subcategory_id": "sg_c5_s4", "name": "توثيق تقارير حول قضايا طارئة", "order": 12},
    {"id": "sg_c5_s4_r013", "subcategory_id": "sg_c5_s4", "name": "تقرير عن متابعة قرارات الإدارة", "order": 13},
    {"id": "sg_c5_s4_r014", "subcategory_id": "sg_c5_s4", "name": "سجل رفع تقارير نهاية العام", "order": 14},
    {"id": "sg_c5_s4_r015", "subcategory_id": "sg_c5_s4", "name": "تقرير عن عروض تقديمية للإدارة", "order": 15},
    {"id": "sg_c5_s4_r016", "subcategory_id": "sg_c5_s4", "name": "توثيق تقارير عن احتياجات الإرشاد", "order": 16},
    {"id": "sg_c5_s4_r017", "subcategory_id": "sg_c5_s4", "name": "تقرير عن توجيهات الإدارة", "order": 17},
    {"id": "sg_c5_s4_r018", "subcategory_id": "sg_c5_s4", "name": "سجل متابعة تقارير الإنجاز", "order": 18},
    {"id": "sg_c5_s4_r019", "subcategory_id": "sg_c5_s4", "name": "تقرير عن تقييم أداء المرشد من الإدارة", "order": 19},
    {"id": "sg_c5_s4_r020", "subcategory_id": "sg_c5_s4", "name": "توثيق توصيات الإدارة في التحسين", "order": 20},

    # ========== sg_c5_s5 ==========
    {"id": "sg_c5_s5_r001", "subcategory_id": "sg_c5_s5", "name": "تقرير عن توثيق البرامج الوقائية المنفذة", "order": 1},
    {"id": "sg_c5_s5_r002", "subcategory_id": "sg_c5_s5", "name": "سجل البرامج التوعوية", "order": 2},
    {"id": "sg_c5_s5_r003", "subcategory_id": "sg_c5_s5", "name": "تقرير عن عدد المستفيدين من البرامج", "order": 3},
    {"id": "sg_c5_s5_r004", "subcategory_id": "sg_c5_s5", "name": "توثيق صور من البرامج", "order": 4},
    {"id": "sg_c5_s5_r005", "subcategory_id": "sg_c5_s5", "name": "تقرير عن تقييم البرامج وأثرها", "order": 5},
    {"id": "sg_c5_s5_r006", "subcategory_id": "sg_c5_s5", "name": "سجل أرشفة مواد البرامج", "order": 6},
    {"id": "sg_c5_s5_r007", "subcategory_id": "sg_c5_s5", "name": "تقرير عن توثيق الحملات", "order": 7},
    {"id": "sg_c5_s5_r008", "subcategory_id": "sg_c5_s5", "name": "توثيق استبيانات تقييم البرامج", "order": 8},
    {"id": "sg_c5_s5_r009", "subcategory_id": "sg_c5_s5", "name": "تقرير عن توصيات تطوير البرامج", "order": 9},
    {"id": "sg_c5_s5_r010", "subcategory_id": "sg_c5_s5", "name": "سجل توثيق محاضرات التوعية", "order": 10},
    {"id": "sg_c5_s5_r011", "subcategory_id": "sg_c5_s5", "name": "تقرير عن أرشفة فيديوهات البرامج", "order": 11},
    {"id": "sg_c5_s5_r012", "subcategory_id": "sg_c5_s5", "name": "توثيق شهادات تقدير للمشاركين", "order": 12},
    {"id": "sg_c5_s5_r013", "subcategory_id": "sg_c5_s5", "name": "تقرير عن تقارير إعلامية عن البرامج", "order": 13},
    {"id": "sg_c5_s5_r014", "subcategory_id": "sg_c5_s5", "name": "سجل توثيق ورش العمل", "order": 14},
    {"id": "sg_c5_s5_r015", "subcategory_id": "sg_c5_s5", "name": "تقرير عن توثيق التعاون الخارجي", "order": 15},
    {"id": "sg_c5_s5_r016", "subcategory_id": "sg_c5_s5", "name": "توثيق ملصقات وبروشورات", "order": 16},
    {"id": "sg_c5_s5_r017", "subcategory_id": "sg_c5_s5", "name": "تقرير عن تغطية البرامج", "order": 17},
    {"id": "sg_c5_s5_r018", "subcategory_id": "sg_c5_s5", "name": "سجل متابعة البرامج المستقبلية", "order": 18},
    {"id": "sg_c5_s5_r019", "subcategory_id": "sg_c5_s5", "name": "تقرير عن إحصائيات البرامج", "order": 19},
    {"id": "sg_c5_s5_r020", "subcategory_id": "sg_c5_s5", "name": "توثيق قصص نجاح من البرامج", "order": 20}
]

# نموذج كتابة التقرير (تم حذف أي ذكر للنسب المئوية)
STUDENT_GUIDE_PROMPT_TEMPLATE = """أنت موجه طلابي متخصص في التوجيه والإرشاد، وتعمل وفق المعايير المهنية المعتمدة لدعم النمو النفسي والتربوي للطلبة.

المطلوب:
- عرض معيار الأداء الوظيفي.
- عرض التصنيف الفرعي.
- كتابة تقرير مهني يوضح الممارسات والإجراءات المنفذة في هذا الجانب.

التقرير المطلوب: "{report_name}"
وهو يندرج تحت التصنيف الفرعي: "{subcategory_name}"
ضمن المعيار التربوي: "{criterion_name}"

{subject_line}
{lesson_line}
{grade_line}
{target_line}
{place_line}
{count_line}

ضوابط الكتابة:
- لغة تربوية مهنية.
- إبراز دور الموجه في الوقاية، التدخل، والمتابعة.
- توضيح البرامج الإرشادية الفردية والجمعية عند الحاجة.
- بيان آلية دراسة الحالات وتصنيفها والتعامل معها.
- إبراز أثر الجهود على سلوك الطلبة وتحصيلهم ودافعيتهم.
- الإشارة إلى التعاون مع الأسرة والمعلمين والإدارة.
- توضيح جانب التوثيق وقياس الأثر والتحسين.
- صياغة واقعية تطبيقية من 5–7 أسطر.

دورك كموجه طلابي

1. تعزيز الصحة النفسية والاجتماعية للطلاب بما يدعم تحصيلهم الدراسي ويعزز توافقهم السلوكي داخل البيئة المدرسية.

2. قدمت برنامجًا إرشاديًا يستهدف دعم الطلاب في مهارات إدارة الضغوط وبناء الثقة بالنفس بما ينعكس على مشاركتهم الصفية واستقرارهم الأكاديمي.

3. نفذت جلسات إرشاد فردي وجماعي، ورصدت الحالات ذات الأولوية، ونسقت مع المعلمين لمتابعة الأثر داخل الصف، وتواصلت مع الأسرة عند الحاجة.

4. استخدمت الإرشاد المعرفي السلوكي، والحوار الموجه، وأنشطة التعلم الاجتماعي العاطفي، والتغذية الراجعة المستمرة لتعزيز وعي الطلاب بسلوكهم.

5. تحسن تفاعل الطلاب داخل الحصص، وانخفضت المشكلات السلوكية البسيطة، وظهر أثر إيجابي على دافعية التعلم والتواصل مع المعلمين.

6. الحاجة إلى توسيع نطاق البرامج الوقائية لتشمل جميع الصفوف، وتعزيز أدوات قياس الأثر لضمان استدامة التحسن السلوكي.

7. أوصي بإدماج مهارات التعلم الاجتماعي ضمن الخطة المدرسية، وتكثيف الشراكة مع المعلمين لرصد المؤشرات المبكرة، وتنظيم ورش توعوية لأولياء الأمور.
**الحقول المطلوبة:**
1. الهدف التربوي
2. نبذة مختصرة
3. إجراءات التنفيذ
4. الاستراتيجيات المستخدمة
5. نقاط القوة
6. نقاط التحسين
7. التوصيات

يرجى تقديم الإجابة باللغة العربية الفصحى، وتنظيمها بحيث يكون كل حقل في سطر منفصل يبدأ برقمه فقط دون ذكر العنوان."""