# vp_prompt.py

# معايير الأداء الوظيفي (بدون نسب مئوية)
VP_CRITERIA = [
    {"id": "vp_c1", "name": "تنظيم وإدارة العمل المدرسي", "order": 1},
    {"id": "vp_c2", "name": "متابعة الانضباط المدرسي والسلوك الطلابي", "order": 2},
    {"id": "vp_c3", "name": "الإشراف على تنفيذ الخطط والبرامج المدرسية", "order": 3},
    {"id": "vp_c4", "name": "تقييم أداء المعلمين وتحفيزهم", "order": 4},
    {"id": "vp_c5", "name": "التواصل مع أولياء الأمور والمجتمع", "order": 5}
]

# التصنيفات الفرعية
VP_SUBCATEGORIES = [
    # vp_c1
    {"id": "vp_c1_s1", "criterion_id": "vp_c1", "name": "توزيع المهام والإشراف على المناوبين", "order": 1},
    {"id": "vp_c1_s2", "criterion_id": "vp_c1", "name": "تنظيم جداول الحصص والإشراف اليومي", "order": 2},
    {"id": "vp_c1_s3", "criterion_id": "vp_c1", "name": "متابعة تنفيذ خطط الإخلاء والسلامة", "order": 3},
    {"id": "vp_c1_s4", "criterion_id": "vp_c1", "name": "إدارة الموارد المدرسية والصيانة", "order": 4},
    {"id": "vp_c1_s5", "criterion_id": "vp_c1", "name": "تنظيم سجلات الحضور والانصراف", "order": 5},
    # vp_c2
    {"id": "vp_c2_s1", "criterion_id": "vp_c2", "name": "متابعة انضباط الطلاب في الطابور والفصول", "order": 1},
    {"id": "vp_c2_s2", "criterion_id": "vp_c2", "name": "معالجة حالات الغياب والتأخير", "order": 2},
    {"id": "vp_c2_s3", "criterion_id": "vp_c2", "name": "متابعة السلوك العام ومعالجة المشكلات", "order": 3},
    {"id": "vp_c2_s4", "criterion_id": "vp_c2", "name": "تفعيل لائحة السلوك والمواظبة", "order": 4},
    {"id": "vp_c2_s5", "criterion_id": "vp_c2", "name": "تنظيم برامج توعوية للطلاب", "order": 5},
    # vp_c3
    {"id": "vp_c3_s1", "criterion_id": "vp_c3", "name": "متابعة تنفيذ الخطط الدراسية", "order": 1},
    {"id": "vp_c3_s2", "criterion_id": "vp_c3", "name": "الإشراف على البرامج والأنشطة المدرسية", "order": 2},
    {"id": "vp_c3_s3", "criterion_id": "vp_c3", "name": "متابعة خطط التحسين المدرسي", "order": 3},
    {"id": "vp_c3_s4", "criterion_id": "vp_c3", "name": "الإشراف على الاختبارات والتقويم", "order": 4},
    {"id": "vp_c3_s5", "criterion_id": "vp_c3", "name": "متابعة تنفيذ المبادرات التعليمية", "order": 5},
    # vp_c4
    {"id": "vp_c4_s1", "criterion_id": "vp_c4", "name": "تقييم أداء المعلمين من خلال الزيارات الصفية", "order": 1},
    {"id": "vp_c4_s2", "criterion_id": "vp_c4", "name": "تقديم تغذية راجعة للمعلمين", "order": 2},
    {"id": "vp_c4_s3", "criterion_id": "vp_c4", "name": "تحفيز المعلمين المتميزين", "order": 3},
    {"id": "vp_c4_s4", "criterion_id": "vp_c4", "name": "تنظيم برامج تطوير مهني للمعلمين", "order": 4},
    {"id": "vp_c4_s5", "criterion_id": "vp_c4", "name": "متابعة خطط المعلمين العلاجية", "order": 5},
    # vp_c5
    {"id": "vp_c5_s1", "criterion_id": "vp_c5", "name": "التواصل مع أولياء الأمور وحضور مجالس الآباء", "order": 1},
    {"id": "vp_c5_s2", "criterion_id": "vp_c5", "name": "تنظيم لقاءات توعوية لأولياء الأمور", "order": 2},
    {"id": "vp_c5_s3", "criterion_id": "vp_c5", "name": "المشاركة في الفعاليات المجتمعية", "order": 3},
    {"id": "vp_c5_s4", "criterion_id": "vp_c5", "name": "بناء شراكات مجتمعية للمدرسة", "order": 4},
    {"id": "vp_c5_s5", "criterion_id": "vp_c5", "name": "التعامل مع شكاوى واقتراحات أولياء الأمور", "order": 5}
]

# التقارير (20 تقريراً لكل تصنيف فرعي)
VP_REPORTS = [
    # vp_c1_s1 (توزيع المهام والإشراف على المناوبين)
    {"id": "vp_c1_s1_r001", "subcategory_id": "vp_c1_s1", "name": "تقرير توزيع مهام الإشراف اليومي على المعلمين", "order": 1},
    {"id": "vp_c1_s1_r002", "subcategory_id": "vp_c1_s1", "name": "سجل متابعة أداء المناوبين في الفسحة", "order": 2},
    {"id": "vp_c1_s1_r003", "subcategory_id": "vp_c1_s1", "name": "تقرير متابعة تنفيذ مهام لجنة التوجيه والإرشاد", "order": 3},
    {"id": "vp_c1_s1_r004", "subcategory_id": "vp_c1_s1", "name": "توثيق توزيع المهام على المعلمين في المناسبات", "order": 4},
    {"id": "vp_c1_s1_r005", "subcategory_id": "vp_c1_s1", "name": "تقرير عن آلية متابعة تنفيذ المهام الإدارية", "order": 5},
    {"id": "vp_c1_s1_r006", "subcategory_id": "vp_c1_s1", "name": "سجل توزيع مهام الإشراف على دخول الطلاب", "order": 6},
    {"id": "vp_c1_s1_r007", "subcategory_id": "vp_c1_s1", "name": "تقرير متابعة أداء المناوبين أثناء الحصص", "order": 7},
    {"id": "vp_c1_s1_r008", "subcategory_id": "vp_c1_s1", "name": "توثيق اجتماعات تنسيق المهام مع المناوبين", "order": 8},
    {"id": "vp_c1_s1_r009", "subcategory_id": "vp_c1_s1", "name": "تقرير عن مستوى الالتزام بالمهام الموزعة", "order": 9},
    {"id": "vp_c1_s1_r010", "subcategory_id": "vp_c1_s1", "name": "سجل متابعة الإشراف على دورات المياه", "order": 10},
    {"id": "vp_c1_s1_r011", "subcategory_id": "vp_c1_s1", "name": "تقرير عن توزيع مهام الإشراف على المقصف", "order": 11},
    {"id": "vp_c1_s1_r012", "subcategory_id": "vp_c1_s1", "name": "توثيق متابعة الإشراف على دخول الحافلات", "order": 12},
    {"id": "vp_c1_s1_r013", "subcategory_id": "vp_c1_s1", "name": "تقرير تقييم أداء المناوبين شهرياً", "order": 13},
    {"id": "vp_c1_s1_r014", "subcategory_id": "vp_c1_s1", "name": "سجل متابعة المناوبين في الفترات المسائية", "order": 14},
    {"id": "vp_c1_s1_r015", "subcategory_id": "vp_c1_s1", "name": "تقرير عن مدى رضا المعلمين عن توزيع المهام", "order": 15},
    {"id": "vp_c1_s1_r016", "subcategory_id": "vp_c1_s1", "name": "توثيق خطة توزيع المهام في الأيام المشهودة", "order": 16},
    {"id": "vp_c1_s1_r017", "subcategory_id": "vp_c1_s1", "name": "تقرير عن آلية التغطية عند غياب المناوبين", "order": 17},
    {"id": "vp_c1_s1_r018", "subcategory_id": "vp_c1_s1", "name": "سجل متابعة تنفيذ مهام الإشراف الأسبوعي", "order": 18},
    {"id": "vp_c1_s1_r019", "subcategory_id": "vp_c1_s1", "name": "تقرير عن تفعيل برنامج الإشراف الإلكتروني", "order": 19},
    {"id": "vp_c1_s1_r020", "subcategory_id": "vp_c1_s1", "name": "توثيق التغذية الراجعة حول أداء المناوبين", "order": 20},

    # vp_c1_s2 (تنظيم جداول الحصص والإشراف اليومي)
    {"id": "vp_c1_s2_r001", "subcategory_id": "vp_c1_s2", "name": "تقرير تنظيم جداول الحصص الدراسية", "order": 1},
    {"id": "vp_c1_s2_r002", "subcategory_id": "vp_c1_s2", "name": "سجل متابعة تنفيذ الجداول ومعالجة الفجوات", "order": 2},
    {"id": "vp_c1_s2_r003", "subcategory_id": "vp_c1_s2", "name": "تقرير الإشراف اليومي على الفسحة والطابور", "order": 3},
    {"id": "vp_c1_s2_r004", "subcategory_id": "vp_c1_s2", "name": "توثيق جدول مناوبة المعلمين", "order": 4},
    {"id": "vp_c1_s2_r005", "subcategory_id": "vp_c1_s2", "name": "تقرير عن انضباط المعلمين في الحضور", "order": 5},
    {"id": "vp_c1_s2_r006", "subcategory_id": "vp_c1_s2", "name": "سجل تعديلات الجداول الدراسية أثناء العام", "order": 6},
    {"id": "vp_c1_s2_r007", "subcategory_id": "vp_c1_s2", "name": "تقرير عن توزيع المعلمين على الفصول", "order": 7},
    {"id": "vp_c1_s2_r008", "subcategory_id": "vp_c1_s2", "name": "توثيق متابعة تنفيذ جداول الاحتياط", "order": 8},
    {"id": "vp_c1_s2_r009", "subcategory_id": "vp_c1_s2", "name": "تقرير عن انضباط الحصص الأولى والأخيرة", "order": 9},
    {"id": "vp_c1_s2_r010", "subcategory_id": "vp_c1_s2", "name": "سجل الإشراف على دخول الطلاب بعد الفسحة", "order": 10},
    {"id": "vp_c1_s2_r011", "subcategory_id": "vp_c1_s2", "name": "تقرير عن آلية توزيع الجداول للمعلمين الجدد", "order": 11},
    {"id": "vp_c1_s2_r012", "subcategory_id": "vp_c1_s2", "name": "توثيق متابعة تنفيذ جداول الأنشطة", "order": 12},
    {"id": "vp_c1_s2_r013", "subcategory_id": "vp_c1_s2", "name": "تقرير عن تفعيل نظام الجدول المدرسي الإلكتروني", "order": 13},
    {"id": "vp_c1_s2_r014", "subcategory_id": "vp_c1_s2", "name": "سجل متابعة تنفيذ جداول الحصص في الاختبارات", "order": 14},
    {"id": "vp_c1_s2_r015", "subcategory_id": "vp_c1_s2", "name": "تقرير عن مدى التزام المعلمين بالجداول", "order": 15},
    {"id": "vp_c1_s2_r016", "subcategory_id": "vp_c1_s2", "name": "توثيق اجتماعات تنسيق الجداول مع رؤساء الأقسام", "order": 16},
    {"id": "vp_c1_s2_r017", "subcategory_id": "vp_c1_s2", "name": "تقرير عن معالجة تعارض الجداول", "order": 17},
    {"id": "vp_c1_s2_r018", "subcategory_id": "vp_c1_s2", "name": "سجل متابعة الإشراف اليومي للمدخل الرئيسي", "order": 18},
    {"id": "vp_c1_s2_r019", "subcategory_id": "vp_c1_s2", "name": "تقرير عن تنظيم جداول الحصص للطلاب ذوي الاحتياجات", "order": 19},
    {"id": "vp_c1_s2_r020", "subcategory_id": "vp_c1_s2", "name": "توثيق تحليل الفجوات في الجداول وحلها", "order": 20},

    # vp_c1_s3 (متابعة تنفيذ خطط الإخلاء والسلامة)
    {"id": "vp_c1_s3_r001", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تنفيذ خطة الإخلاء في المدرسة", "order": 1},
    {"id": "vp_c1_s3_r002", "subcategory_id": "vp_c1_s3", "name": "سجل متابعة صيانة أدوات السلامة", "order": 2},
    {"id": "vp_c1_s3_r003", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تدريب الطلاب على خطط الطوارئ", "order": 3},
    {"id": "vp_c1_s3_r004", "subcategory_id": "vp_c1_s3", "name": "توثيق التعاون مع الدفاع المدني", "order": 4},
    {"id": "vp_c1_s3_r005", "subcategory_id": "vp_c1_s3", "name": "تقرير عن توفير بيئة آمنة في المدرسة", "order": 5},
    {"id": "vp_c1_s3_r006", "subcategory_id": "vp_c1_s3", "name": "سجل متابعة صلاحية طفايات الحريق", "order": 6},
    {"id": "vp_c1_s3_r007", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تنفيذ تجارب الإخلاء الدورية", "order": 7},
    {"id": "vp_c1_s3_r008", "subcategory_id": "vp_c1_s3", "name": "توثيق تدريب المعلمين على الإسعافات الأولية", "order": 8},
    {"id": "vp_c1_s3_r009", "subcategory_id": "vp_c1_s3", "name": "تقرير عن جاهزية مخارج الطوارئ", "order": 9},
    {"id": "vp_c1_s3_r010", "subcategory_id": "vp_c1_s3", "name": "سجل متابعة توعية الطلاب بأخطار الحريق", "order": 10},
    {"id": "vp_c1_s3_r011", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تنظيم ورش عمل للسلامة", "order": 11},
    {"id": "vp_c1_s3_r012", "subcategory_id": "vp_c1_s3", "name": "توثيق خطة الإخلاء السنوية", "order": 12},
    {"id": "vp_c1_s3_r013", "subcategory_id": "vp_c1_s3", "name": "تقرير عن توفير مهمات السلامة بالفصول", "order": 13},
    {"id": "vp_c1_s3_r014", "subcategory_id": "vp_c1_s3", "name": "سجل متابعة تنفيذ برنامج الأمن والسلامة", "order": 14},
    {"id": "vp_c1_s3_r015", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تدريب فريق الأمن والسلامة", "order": 15},
    {"id": "vp_c1_s3_r016", "subcategory_id": "vp_c1_s3", "name": "توثيق زيارات رجال الدفاع المدني للمدرسة", "order": 16},
    {"id": "vp_c1_s3_r017", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تطبيق إجراءات السلامة في المعامل", "order": 17},
    {"id": "vp_c1_s3_r018", "subcategory_id": "vp_c1_s3", "name": "سجل متابعة تنفيذ خطة الطوارئ", "order": 18},
    {"id": "vp_c1_s3_r019", "subcategory_id": "vp_c1_s3", "name": "تقرير عن تجهيز غرفة الصحة المدرسية", "order": 19},
    {"id": "vp_c1_s3_r020", "subcategory_id": "vp_c1_s3", "name": "توثيق تحليل نتائج تجارب الإخلاء", "order": 20},

    # vp_c1_s4 (إدارة الموارد المدرسية والصيانة)
    {"id": "vp_c1_s4_r001", "subcategory_id": "vp_c1_s4", "name": "تقرير عن متابعة نظافة المدرسة وفصولها", "order": 1},
    {"id": "vp_c1_s4_r002", "subcategory_id": "vp_c1_s4", "name": "سجل متابعة صيانة الأثاث والمرافق", "order": 2},
    {"id": "vp_c1_s4_r003", "subcategory_id": "vp_c1_s4", "name": "تقرير عن توفير الموارد التعليمية", "order": 3},
    {"id": "vp_c1_s4_r004", "subcategory_id": "vp_c1_s4", "name": "توثيق متابعة المخزون والمواد الاستهلاكية", "order": 4},
    {"id": "vp_c1_s4_r005", "subcategory_id": "vp_c1_s4", "name": "تقرير عن تجهيز الفصول الدراسية", "order": 5},
    {"id": "vp_c1_s4_r006", "subcategory_id": "vp_c1_s4", "name": "سجل متابعة أعمال النظافة اليومية", "order": 6},
    {"id": "vp_c1_s4_r007", "subcategory_id": "vp_c1_s4", "name": "تقرير عن صيانة أجهزة التكييف والتهوية", "order": 7},
    {"id": "vp_c1_s4_r008", "subcategory_id": "vp_c1_s4", "name": "توثيق متابعة توفير القرطاسية للمكتب", "order": 8},
    {"id": "vp_c1_s4_r009", "subcategory_id": "vp_c1_s4", "name": "تقرير عن جرد أثاث المدرسة", "order": 9},
    {"id": "vp_c1_s4_r010", "subcategory_id": "vp_c1_s4", "name": "سجل متابعة صيانة دورات المياه", "order": 10},
    {"id": "vp_c1_s4_r011", "subcategory_id": "vp_c1_s4", "name": "تقرير عن توفير وسائل السلامة في المختبرات", "order": 11},
    {"id": "vp_c1_s4_r012", "subcategory_id": "vp_c1_s4", "name": "توثيق متابعة المخزون من المواد التعليمية", "order": 12},
    {"id": "vp_c1_s4_r013", "subcategory_id": "vp_c1_s4", "name": "تقرير عن صيانة الملاعب والساحات", "order": 13},
    {"id": "vp_c1_s4_r014", "subcategory_id": "vp_c1_s4", "name": "سجل متابعة أعمال الدهانات والترميمات البسيطة", "order": 14},
    {"id": "vp_c1_s4_r015", "subcategory_id": "vp_c1_s4", "name": "تقرير عن توفير الاثاث للفصول الجديدة", "order": 15},
    {"id": "vp_c1_s4_r016", "subcategory_id": "vp_c1_s4", "name": "توثيق متابعة عقود الصيانة مع الشركات", "order": 16},
    {"id": "vp_c1_s4_r017", "subcategory_id": "vp_c1_s4", "name": "تقرير عن متابعة المخزون من أدوات النظافة", "order": 17},
    {"id": "vp_c1_s4_r018", "subcategory_id": "vp_c1_s4", "name": "سجل متابعة صيانة أجهزة الحاسب الآلي", "order": 18},
    {"id": "vp_c1_s4_r019", "subcategory_id": "vp_c1_s4", "name": "تقرير عن توفير مصادر التعلم", "order": 19},
    {"id": "vp_c1_s4_r020", "subcategory_id": "vp_c1_s4", "name": "توثيق تحليل احتياجات المدرسة من الموارد", "order": 20},

    # vp_c1_s5 (تنظيم سجلات الحضور والانصراف)
    {"id": "vp_c1_s5_r001", "subcategory_id": "vp_c1_s5", "name": "تقرير عن متابعة سجلات حضور الطلاب", "order": 1},
    {"id": "vp_c1_s5_r002", "subcategory_id": "vp_c1_s5", "name": "سجل متابعة انصراف الطلاب نهاية اليوم", "order": 2},
    {"id": "vp_c1_s5_r003", "subcategory_id": "vp_c1_s5", "name": "تقرير عن حالات الغياب ومعالجتها", "order": 3},
    {"id": "vp_c1_s5_r004", "subcategory_id": "vp_c1_s5", "name": "توثيق نظام البصمة أو الحضور اليومي", "order": 4},
    {"id": "vp_c1_s5_r005", "subcategory_id": "vp_c1_s5", "name": "تقرير إحصائي عن انضباط الطلاب", "order": 5},
    {"id": "vp_c1_s5_r006", "subcategory_id": "vp_c1_s5", "name": "سجل متابعة حضور الطلاب المتكرر غيابهم", "order": 6},
    {"id": "vp_c1_s5_r007", "subcategory_id": "vp_c1_s5", "name": "تقرير عن انضباط الطلاب في الحصص الأولى", "order": 7},
    {"id": "vp_c1_s5_r008", "subcategory_id": "vp_c1_s5", "name": "توثيق نظام الاذن بالانصراف المبكر", "order": 8},
    {"id": "vp_c1_s5_r009", "subcategory_id": "vp_c1_s5", "name": "تقرير عن حضور الطلاب بعد الاجازات", "order": 9},
    {"id": "vp_c1_s5_r010", "subcategory_id": "vp_c1_s5", "name": "سجل متابعة انصراف الطلاب بالحافلات", "order": 10},
    {"id": "vp_c1_s5_r011", "subcategory_id": "vp_c1_s5", "name": "تقرير عن آلية توثيق غياب المعلمين", "order": 11},
    {"id": "vp_c1_s5_r012", "subcategory_id": "vp_c1_s5", "name": "توثيق متابعة سجل الزوار", "order": 12},
    {"id": "vp_c1_s5_r013", "subcategory_id": "vp_c1_s5", "name": "تقرير عن تفعيل نظام الحضور الالكتروني", "order": 13},
    {"id": "vp_c1_s5_r014", "subcategory_id": "vp_c1_s5", "name": "سجل متابعة دوام الموظفين الاداريين", "order": 14},
    {"id": "vp_c1_s5_r015", "subcategory_id": "vp_c1_s5", "name": "تقرير عن نسب الغياب الشهرية", "order": 15},
    {"id": "vp_c1_s5_r016", "subcategory_id": "vp_c1_s5", "name": "توثيق متابعة حضور الطلاب بعد الفسحة", "order": 16},
    {"id": "vp_c1_s5_r017", "subcategory_id": "vp_c1_s5", "name": "تقرير عن انضباط طلاب المرحلة الثانوية", "order": 17},
    {"id": "vp_c1_s5_r018", "subcategory_id": "vp_c1_s5", "name": "سجل متابعة حضور الطلاب للاختبارات", "order": 18},
    {"id": "vp_c1_s5_r019", "subcategory_id": "vp_c1_s5", "name": "تقرير عن تطبيق لائحة الغياب", "order": 19},
    {"id": "vp_c1_s5_r020", "subcategory_id": "vp_c1_s5", "name": "توثيق تقارير الاحصاء الاسبوعي للحضور", "order": 20},

    # vp_c2_s1 (متابعة انضباط الطلاب في الطابور والفصول)
    {"id": "vp_c2_s1_r001", "subcategory_id": "vp_c2_s1", "name": "تقرير متابعة انضباط الطلاب في الطابور الصباحي", "order": 1},
    {"id": "vp_c2_s1_r002", "subcategory_id": "vp_c2_s1", "name": "سجل متابعة حضور الطلاب للحصص الأولى", "order": 2},
    {"id": "vp_c2_s1_r003", "subcategory_id": "vp_c2_s1", "name": "تقرير عن انضباط الطلاب أثناء الحصص", "order": 3},
    {"id": "vp_c2_s1_r004", "subcategory_id": "vp_c2_s1", "name": "توثيق حالات التأخير وعلاجها", "order": 4},
    {"id": "vp_c2_s1_r005", "subcategory_id": "vp_c2_s1", "name": "تقرير عن دور المناوبين في ضبط الانضباط", "order": 5},
    {"id": "vp_c2_s1_r006", "subcategory_id": "vp_c2_s1", "name": "سجل متابعة انضباط الطلاب في الحصص الأخيرة", "order": 6},
    {"id": "vp_c2_s1_r007", "subcategory_id": "vp_c2_s1", "name": "تقرير عن انضباط الطلاب أثناء الفسحة", "order": 7},
    {"id": "vp_c2_s1_r008", "subcategory_id": "vp_c2_s1", "name": "توثيق متابعة الالتزام بالزي المدرسي", "order": 8},
    {"id": "vp_c2_s1_r009", "subcategory_id": "vp_c2_s1", "name": "تقرير عن انضباط الطلاب في الاصطفاف الصباحي", "order": 9},
    {"id": "vp_c2_s1_r010", "subcategory_id": "vp_c2_s1", "name": "سجل متابعة انصراف الطلاب من الفصول", "order": 10},
    {"id": "vp_c2_s1_r011", "subcategory_id": "vp_c2_s1", "name": "تقرير عن دور الاذاعة المدرسية في تعزيز الانضباط", "order": 11},
    {"id": "vp_c2_s1_r012", "subcategory_id": "vp_c2_s1", "name": "توثيق متابعة انضباط طلاب المرحلة الابتدائية", "order": 12},
    {"id": "vp_c2_s1_r013", "subcategory_id": "vp_c2_s1", "name": "تقرير عن تأثير الانضباط على التحصيل الدراسي", "order": 13},
    {"id": "vp_c2_s1_r014", "subcategory_id": "vp_c2_s1", "name": "سجل متابعة انضباط الطلاب في الرحلات", "order": 14},
    {"id": "vp_c2_s1_r015", "subcategory_id": "vp_c2_s1", "name": "تقرير عن برنامج الطالب المثالي في الانضباط", "order": 15},
    {"id": "vp_c2_s1_r016", "subcategory_id": "vp_c2_s1", "name": "توثيق اجتماعات لجنة الانضباط", "order": 16},
    {"id": "vp_c2_s1_r017", "subcategory_id": "vp_c2_s1", "name": "تقرير عن انضباط الطلاب في المعامل", "order": 17},
    {"id": "vp_c2_s1_r018", "subcategory_id": "vp_c2_s1", "name": "سجل متابعة انضباط طلاب المرحلة المتوسطة", "order": 18},
    {"id": "vp_c2_s1_r019", "subcategory_id": "vp_c2_s1", "name": "تقرير عن انضباط الطلاب في المقصف", "order": 19},
    {"id": "vp_c2_s1_r020", "subcategory_id": "vp_c2_s1", "name": "توثيق تحليل مؤشرات الانضباط المدرسي", "order": 20},

    # vp_c2_s2 (معالجة حالات الغياب والتأخير)
    {"id": "vp_c2_s2_r001", "subcategory_id": "vp_c2_s2", "name": "تقرير عن متابعة الطلاب المتغيبين", "order": 1},
    {"id": "vp_c2_s2_r002", "subcategory_id": "vp_c2_s2", "name": "سجل التواصل مع أولياء أمور الطلاب المتغيبين", "order": 2},
    {"id": "vp_c2_s2_r003", "subcategory_id": "vp_c2_s2", "name": "تقرير عن تطبيق لائحة الغياب", "order": 3},
    {"id": "vp_c2_s2_r004", "subcategory_id": "vp_c2_s2", "name": "توثيق حالات التأخير المتكرر", "order": 4},
    {"id": "vp_c2_s2_r005", "subcategory_id": "vp_c2_s2", "name": "تقرير عن برامج تحسين الانضباط", "order": 5},
    {"id": "vp_c2_s2_r006", "subcategory_id": "vp_c2_s2", "name": "سجل متابعة الطلاب ذوي الغياب المزمن", "order": 6},
    {"id": "vp_c2_s2_r007", "subcategory_id": "vp_c2_s2", "name": "تقرير عن أسباب الغياب وعلاجها", "order": 7},
    {"id": "vp_c2_s2_r008", "subcategory_id": "vp_c2_s2", "name": "توثيق الانذارات للطلاب المتغيبين", "order": 8},
    {"id": "vp_c2_s2_r009", "subcategory_id": "vp_c2_s2", "name": "تقرير عن زيارات المرشد الطلابي للطلاب المتغيبين", "order": 9},
    {"id": "vp_c2_s2_r010", "subcategory_id": "vp_c2_s2", "name": "سجل متابعة حضور الطلاب بعد العودة من الغياب", "order": 10},
    {"id": "vp_c2_s2_r011", "subcategory_id": "vp_c2_s2", "name": "تقرير عن تأثير الغياب على المستوى الدراسي", "order": 11},
    {"id": "vp_c2_s2_r012", "subcategory_id": "vp_c2_s2", "name": "توثيق الاجراءات المتبعة مع الغياب بدون عذر", "order": 12},
    {"id": "vp_c2_s2_r013", "subcategory_id": "vp_c2_s2", "name": "تقرير عن برنامج تعزيز حضور الطلاب", "order": 13},
    {"id": "vp_c2_s2_r014", "subcategory_id": "vp_c2_s2", "name": "سجل متابعة التأخير الصباحي اليومي", "order": 14},
    {"id": "vp_c2_s2_r015", "subcategory_id": "vp_c2_s2", "name": "تقرير عن لقاءات أولياء الأمور لعلاج الغياب", "order": 15},
    {"id": "vp_c2_s2_r016", "subcategory_id": "vp_c2_s2", "name": "توثيق تطبيق نظام الغياب الالكتروني", "order": 16},
    {"id": "vp_c2_s2_r017", "subcategory_id": "vp_c2_s2", "name": "تقرير عن حالات الغياب الجماعي", "order": 17},
    {"id": "vp_c2_s2_r018", "subcategory_id": "vp_c2_s2", "name": "سجل متابعة حضور الطلاب بعد الاجازات", "order": 18},
    {"id": "vp_c2_s2_r019", "subcategory_id": "vp_c2_s2", "name": "تقرير عن نسب الغياب في الاختبارات", "order": 19},
    {"id": "vp_c2_s2_r020", "subcategory_id": "vp_c2_s2", "name": "توثيق تحليل بيانات الغياب ووضع الخطط", "order": 20},

    # vp_c2_s3 (متابعة السلوك العام ومعالجة المشكلات)
    {"id": "vp_c2_s3_r001", "subcategory_id": "vp_c2_s3", "name": "تقرير عن متابعة السلوك العام في المدرسة", "order": 1},
    {"id": "vp_c2_s3_r002", "subcategory_id": "vp_c2_s3", "name": "سجل معالجة المشكلات السلوكية", "order": 2},
    {"id": "vp_c2_s3_r003", "subcategory_id": "vp_c2_s3", "name": "تقرير عن عدد حالات التنمر ومعالجتها", "order": 3},
    {"id": "vp_c2_s3_r004", "subcategory_id": "vp_c2_s3", "name": "توثيق اجتماعات لجنة التوجيه والإرشاد", "order": 4},
    {"id": "vp_c2_s3_r005", "subcategory_id": "vp_c2_s3", "name": "تقرير عن برامج تعزيز السلوك الإيجابي", "order": 5},
    {"id": "vp_c2_s3_r006", "subcategory_id": "vp_c2_s3", "name": "سجل متابعة الطلاب ذوي المشكلات السلوكية", "order": 6},
    {"id": "vp_c2_s3_r007", "subcategory_id": "vp_c2_s3", "name": "تقرير عن حالات الشجار بين الطلاب", "order": 7},
    {"id": "vp_c2_s3_r008", "subcategory_id": "vp_c2_s3", "name": "توثيق الاجراءات التربوية للسلوكيات الخاطئة", "order": 8},
    {"id": "vp_c2_s3_r009", "subcategory_id": "vp_c2_s3", "name": "تقرير عن برنامج رفق للحد من التنمر", "order": 9},
    {"id": "vp_c2_s3_r010", "subcategory_id": "vp_c2_s3", "name": "سجل متابعة سلوك الطلاب في الفسحة", "order": 10},
    {"id": "vp_c2_s3_r011", "subcategory_id": "vp_c2_s3", "name": "تقرير عن دور المناوبين في رصد السلوكيات", "order": 11},
    {"id": "vp_c2_s3_r012", "subcategory_id": "vp_c2_s3", "name": "توثيق توقيع تعهدات على الطلاب", "order": 12},
    {"id": "vp_c2_s3_r013", "subcategory_id": "vp_c2_s3", "name": "تقرير عن برامج التوجيه الفردي للطلاب", "order": 13},
    {"id": "vp_c2_s3_r014", "subcategory_id": "vp_c2_s3", "name": "سجل متابعة سلوك الطلاب في الحافلات", "order": 14},
    {"id": "vp_c2_s3_r015", "subcategory_id": "vp_c2_s3", "name": "تقرير عن استجابة الطلاب للارشادات السلوكية", "order": 15},
    {"id": "vp_c2_s3_r016", "subcategory_id": "vp_c2_s3", "name": "توثيق الاحصائيات الشهرية للمشكلات السلوكية", "order": 16},
    {"id": "vp_c2_s3_r017", "subcategory_id": "vp_c2_s3", "name": "تقرير عن برامج تدريب الطلاب على المهارات الاجتماعية", "order": 17},
    {"id": "vp_c2_s3_r018", "subcategory_id": "vp_c2_s3", "name": "سجل متابعة التعديل السلوكي للطلاب", "order": 18},
    {"id": "vp_c2_s3_r019", "subcategory_id": "vp_c2_s3", "name": "تقرير عن مشاركة أولياء الأمور في علاج المشكلات", "order": 19},
    {"id": "vp_c2_s3_r020", "subcategory_id": "vp_c2_s3", "name": "توثيق تحليل المشكلات السلوكية وتوصيات العلاج", "order": 20},

    # vp_c2_s4 (تفعيل لائحة السلوك والمواظبة)
    {"id": "vp_c2_s4_r001", "subcategory_id": "vp_c2_s4", "name": "تقرير عن تطبيق لائحة السلوك والمواظبة", "order": 1},
    {"id": "vp_c2_s4_r002", "subcategory_id": "vp_c2_s4", "name": "سجل حالات المخالفات والعقوبات", "order": 2},
    {"id": "vp_c2_s4_r003", "subcategory_id": "vp_c2_s4", "name": "تقرير عن فعاليات توعوية حول اللائحة", "order": 3},
    {"id": "vp_c2_s4_r004", "subcategory_id": "vp_c2_s4", "name": "توثيق توقيع الطلاب على تعهد بالسلوك", "order": 4},
    {"id": "vp_c2_s4_r005", "subcategory_id": "vp_c2_s4", "name": "تقرير عن مدى التزام الطلاب بالزي المدرسي", "order": 5},
    {"id": "vp_c2_s4_r006", "subcategory_id": "vp_c2_s4", "name": "سجل متابعة المخالفات الطلابية اليومية", "order": 6},
    {"id": "vp_c2_s4_r007", "subcategory_id": "vp_c2_s4", "name": "تقرير عن تفعيل مواد اللائحة في حالات الغياب", "order": 7},
    {"id": "vp_c2_s4_r008", "subcategory_id": "vp_c2_s4", "name": "توثيق اجتماعات لجنة السلوك والمواظبة", "order": 8},
    {"id": "vp_c2_s4_r009", "subcategory_id": "vp_c2_s4", "name": "تقرير عن توزيع اللائحة للطلاب وأولياء الأمور", "order": 9},
    {"id": "vp_c2_s4_r010", "subcategory_id": "vp_c2_s4", "name": "سجل العقوبات التربوية المطبقة", "order": 10},
    {"id": "vp_c2_s4_r011", "subcategory_id": "vp_c2_s4", "name": "تقرير عن برامج التوعية بلائحة السلوك", "order": 11},
    {"id": "vp_c2_s4_r012", "subcategory_id": "vp_c2_s4", "name": "توثيق نماذج من قرارات لجنة السلوك", "order": 12},
    {"id": "vp_c2_s4_r013", "subcategory_id": "vp_c2_s4", "name": "تقرير عن مدى رضا المعلمين عن تطبيق اللائحة", "order": 13},
    {"id": "vp_c2_s4_r014", "subcategory_id": "vp_c2_s4", "name": "سجل متابعة تنفيذ القرارات التأديبية", "order": 14},
    {"id": "vp_c2_s4_r015", "subcategory_id": "vp_c2_s4", "name": "تقرير عن المخالفات الأكثر شيوعاً", "order": 15},
    {"id": "vp_c2_s4_r016", "subcategory_id": "vp_c2_s4", "name": "توثيق الاحصائيات الشهرية للمخالفات", "order": 16},
    {"id": "vp_c2_s4_r017", "subcategory_id": "vp_c2_s4", "name": "تقرير عن تفعيل بدائل العقوبات", "order": 17},
    {"id": "vp_c2_s4_r018", "subcategory_id": "vp_c2_s4", "name": "سجل توجيه الطلاب المخالفين للمرشد", "order": 18},
    {"id": "vp_c2_s4_r019", "subcategory_id": "vp_c2_s4", "name": "تقرير عن اثر تطبيق اللائحة على السلوك", "order": 19},
    {"id": "vp_c2_s4_r020", "subcategory_id": "vp_c2_s4", "name": "توثيق تطوير اللائحة بناء على المراجعة الداخلية", "order": 20},

    # vp_c2_s5 (تنظيم برامج توعوية للطلاب)
    {"id": "vp_c2_s5_r001", "subcategory_id": "vp_c2_s5", "name": "تقرير عن برامج توعوية للطلاب حول الانضباط", "order": 1},
    {"id": "vp_c2_s5_r002", "subcategory_id": "vp_c2_s5", "name": "سجل تنظيم محاضرات عن السلوك", "order": 2},
    {"id": "vp_c2_s5_r003", "subcategory_id": "vp_c2_s5", "name": "تقرير عن مسابقات أفضل فصل منضبط", "order": 3},
    {"id": "vp_c2_s5_r004", "subcategory_id": "vp_c2_s5", "name": "توثيق برامج رفق للإرشاد", "order": 4},
    {"id": "vp_c2_s5_r005", "subcategory_id": "vp_c2_s5", "name": "تقرير عن ورش عمل للطلاب حول المهارات الاجتماعية", "order": 5},
    {"id": "vp_c2_s5_r006", "subcategory_id": "vp_c2_s5", "name": "سجل برامج التوعية بأضرار التنمر", "order": 6},
    {"id": "vp_c2_s5_r007", "subcategory_id": "vp_c2_s5", "name": "تقرير عن محاضرات الأمن الفكري", "order": 7},
    {"id": "vp_c2_s5_r008", "subcategory_id": "vp_c2_s5", "name": "توثيق حملات توعوية عن النظافة", "order": 8},
    {"id": "vp_c2_s5_r009", "subcategory_id": "vp_c2_s5", "name": "تقرير عن برامج تعزيز قيم المواطنة", "order": 9},
    {"id": "vp_c2_s5_r010", "subcategory_id": "vp_c2_s5", "name": "سجل تنظيم مسابقات ثقافية عن السلوك", "order": 10},
    {"id": "vp_c2_s5_r011", "subcategory_id": "vp_c2_s5", "name": "تقرير عن مشاركة الطلاب في البرامج التوعوية", "order": 11},
    {"id": "vp_c2_s5_r012", "subcategory_id": "vp_c2_s5", "name": "توثيق برامج التوعية المرورية", "order": 12},
    {"id": "vp_c2_s5_r013", "subcategory_id": "vp_c2_s5", "name": "تقرير عن محاضرات الصحة النفسية", "order": 13},
    {"id": "vp_c2_s5_r014", "subcategory_id": "vp_c2_s5", "name": "سجل برامج تعزيز الثقة بالنفس", "order": 14},
    {"id": "vp_c2_s5_r015", "subcategory_id": "vp_c2_s5", "name": "تقرير عن أثر البرامج على السلوك", "order": 15},
    {"id": "vp_c2_s5_r016", "subcategory_id": "vp_c2_s5", "name": "توثيق شراكات مع جهات خارجية للتوعية", "order": 16},
    {"id": "vp_c2_s5_r017", "subcategory_id": "vp_c2_s5", "name": "تقرير عن برامج توعية الأمن والسلامة", "order": 17},
    {"id": "vp_c2_s5_r018", "subcategory_id": "vp_c2_s5", "name": "سجل محاضرات عن الرفق بالحيوان", "order": 18},
    {"id": "vp_c2_s5_r019", "subcategory_id": "vp_c2_s5", "name": "تقرير عن برامج توعية عن المخدرات", "order": 19},
    {"id": "vp_c2_s5_r020", "subcategory_id": "vp_c2_s5", "name": "توثيق تقييم البرامج التوعوية", "order": 20},

    # vp_c3_s1 (متابعة تنفيذ الخطط الدراسية)
    {"id": "vp_c3_s1_r001", "subcategory_id": "vp_c3_s1", "name": "تقرير متابعة تنفيذ الخطط الدراسية", "order": 1},
    {"id": "vp_c3_s1_r002", "subcategory_id": "vp_c3_s1", "name": "سجل متابعة دفاتر التحضير", "order": 2},
    {"id": "vp_c3_s1_r003", "subcategory_id": "vp_c3_s1", "name": "تقرير عن مدى التزام المعلمين بالمنهج", "order": 3},
    {"id": "vp_c3_s1_r004", "subcategory_id": "vp_c3_s1", "name": "توثيق اجتماعات تنسيق المواد", "order": 4},
    {"id": "vp_c3_s1_r005", "subcategory_id": "vp_c3_s1", "name": "تقرير عن تنفيذ الخطط العلاجية", "order": 5},
    {"id": "vp_c3_s1_r006", "subcategory_id": "vp_c3_s1", "name": "سجل متابعة توزيع المنهج على الفصول", "order": 6},
    {"id": "vp_c3_s1_r007", "subcategory_id": "vp_c3_s1", "name": "تقرير عن تنفيذ الخطط الاثرائية", "order": 7},
    {"id": "vp_c3_s1_r008", "subcategory_id": "vp_c3_s1", "name": "توثيق متابعة خطط التوزيع الزمني للمقررات", "order": 8},
    {"id": "vp_c3_s1_r009", "subcategory_id": "vp_c3_s1", "name": "تقرير عن تنفيذ المنهج في الفصول", "order": 9},
    {"id": "vp_c3_s1_r010", "subcategory_id": "vp_c3_s1", "name": "سجل متابعة استخدام الوسائل التعليمية", "order": 10},
    {"id": "vp_c3_s1_r011", "subcategory_id": "vp_c3_s1", "name": "تقرير عن مدى تطبيق استراتيجيات التدريس الحديثة", "order": 11},
    {"id": "vp_c3_s1_r012", "subcategory_id": "vp_c3_s1", "name": "توثيق اجتماعات معلمي المادة", "order": 12},
    {"id": "vp_c3_s1_r013", "subcategory_id": "vp_c3_s1", "name": "تقرير عن تكييف المنهج لذوي الاحتياجات", "order": 13},
    {"id": "vp_c3_s1_r014", "subcategory_id": "vp_c3_s1", "name": "سجل متابعة تنفيذ الأنشطة المصاحبة", "order": 14},
    {"id": "vp_c3_s1_r015", "subcategory_id": "vp_c3_s1", "name": "تقرير عن التقويم المستمر للطلاب", "order": 15},
    {"id": "vp_c3_s1_r016", "subcategory_id": "vp_c3_s1", "name": "توثيق متابعة أداء المعلمين الجدد", "order": 16},
    {"id": "vp_c3_s1_r017", "subcategory_id": "vp_c3_s1", "name": "تقرير عن تنفيذ الخطط الفصلية", "order": 17},
    {"id": "vp_c3_s1_r018", "subcategory_id": "vp_c3_s1", "name": "سجل متابعة الانتهاء من المنهج قبل الاختبارات", "order": 18},
    {"id": "vp_c3_s1_r019", "subcategory_id": "vp_c3_s1", "name": "تقرير عن مراجعة الخطط مع المشرفين التربويين", "order": 19},
    {"id": "vp_c3_s1_r020", "subcategory_id": "vp_c3_s1", "name": "توثيق تحليل نتائج تنفيذ الخطط", "order": 20},

    # vp_c3_s2 (الإشراف على البرامج والأنشطة المدرسية)
    {"id": "vp_c3_s2_r001", "subcategory_id": "vp_c3_s2", "name": "تقرير عن الإشراف على الأنشطة المدرسية", "order": 1},
    {"id": "vp_c3_s2_r002", "subcategory_id": "vp_c3_s2", "name": "سجل متابعة برامج النشاط الطلابي", "order": 2},
    {"id": "vp_c3_s2_r003", "subcategory_id": "vp_c3_s2", "name": "تقرير عن مشاركات المدرسة الخارجية", "order": 3},
    {"id": "vp_c3_s2_r004", "subcategory_id": "vp_c3_s2", "name": "توثيق الفعاليات والمناسبات", "order": 4},
    {"id": "vp_c3_s2_r005", "subcategory_id": "vp_c3_s2", "name": "تقرير عن أثر الأنشطة على الطلاب", "order": 5},
    {"id": "vp_c3_s2_r006", "subcategory_id": "vp_c3_s2", "name": "سجل متابعة تنفيذ النشاط الرياضي", "order": 6},
    {"id": "vp_c3_s2_r007", "subcategory_id": "vp_c3_s2", "name": "تقرير عن النشاط الثقافي والفني", "order": 7},
    {"id": "vp_c3_s2_r008", "subcategory_id": "vp_c3_s2", "name": "توثيق مشاركة الطلاب في المسابقات", "order": 8},
    {"id": "vp_c3_s2_r009", "subcategory_id": "vp_c3_s2", "name": "تقرير عن النشاط العلمي", "order": 9},
    {"id": "vp_c3_s2_r010", "subcategory_id": "vp_c3_s2", "name": "سجل متابعة الانشطة الاجتماعية", "order": 10},
    {"id": "vp_c3_s2_r011", "subcategory_id": "vp_c3_s2", "name": "تقرير عن برامج تنمية المهارات", "order": 11},
    {"id": "vp_c3_s2_r012", "subcategory_id": "vp_c3_s2", "name": "توثيق الانشطة الطلابية في الاذاعة", "order": 12},
    {"id": "vp_c3_s2_r013", "subcategory_id": "vp_c3_s2", "name": "تقرير عن النشاط الكشفي", "order": 13},
    {"id": "vp_c3_s2_r014", "subcategory_id": "vp_c3_s2", "name": "سجل متابعة تنفيذ خطة النشاط", "order": 14},
    {"id": "vp_c3_s2_r015", "subcategory_id": "vp_c3_s2", "name": "تقرير عن مشاركة اولياء الامور في الانشطة", "order": 15},
    {"id": "vp_c3_s2_r016", "subcategory_id": "vp_c3_s2", "name": "توثيق مسابقات المهارات اليدوية", "order": 16},
    {"id": "vp_c3_s2_r017", "subcategory_id": "vp_c3_s2", "name": "تقرير عن النشاط التطوعي", "order": 17},
    {"id": "vp_c3_s2_r018", "subcategory_id": "vp_c3_s2", "name": "سجل متابعة الفعاليات في الأسبوع التمهيدي", "order": 18},
    {"id": "vp_c3_s2_r019", "subcategory_id": "vp_c3_s2", "name": "تقرير عن النشاط الموسمي", "order": 19},
    {"id": "vp_c3_s2_r020", "subcategory_id": "vp_c3_s2", "name": "توثيق تقييم الانشطة ومدى تحقيقها للاهداف", "order": 20},

    # vp_c3_s3 (متابعة خطط التحسين المدرسي)
    {"id": "vp_c3_s3_r001", "subcategory_id": "vp_c3_s3", "name": "تقرير متابعة تنفيذ خطة التحسين المدرسي", "order": 1},
    {"id": "vp_c3_s3_r002", "subcategory_id": "vp_c3_s3", "name": "سجل اجتماعات فريق التحسين", "order": 2},
    {"id": "vp_c3_s3_r003", "subcategory_id": "vp_c3_s3", "name": "تقرير عن مؤشرات الأداء في الخطة", "order": 3},
    {"id": "vp_c3_s3_r004", "subcategory_id": "vp_c3_s3", "name": "توثيق المبادرات المرتبطة بالتحسين", "order": 4},
    {"id": "vp_c3_s3_r005", "subcategory_id": "vp_c3_s3", "name": "تقرير نتائج تقييم الخطة", "order": 5},
    {"id": "vp_c3_s3_r006", "subcategory_id": "vp_c3_s3", "name": "سجل متابعة تنفيذ برامج التحسين", "order": 6},
    {"id": "vp_c3_s3_r007", "subcategory_id": "vp_c3_s3", "name": "تقرير عن اولويات التحسين", "order": 7},
    {"id": "vp_c3_s3_r008", "subcategory_id": "vp_c3_s3", "name": "توثيق تحليل نتائج الاداء المدرسي", "order": 8},
    {"id": "vp_c3_s3_r009", "subcategory_id": "vp_c3_s3", "name": "تقرير عن مؤشرات نواتج التعلم", "order": 9},
    {"id": "vp_c3_s3_r010", "subcategory_id": "vp_c3_s3", "name": "سجل متابعة تنفيذ خطط تحسين نواتج التعلم", "order": 10},
    {"id": "vp_c3_s3_r011", "subcategory_id": "vp_c3_s3", "name": "تقرير عن مدى مشاركة المعلمين في التحسين", "order": 11},
    {"id": "vp_c3_s3_r012", "subcategory_id": "vp_c3_s3", "name": "توثيق خطط التحسين السابقة ونتائجها", "order": 12},
    {"id": "vp_c3_s3_r013", "subcategory_id": "vp_c3_s3", "name": "تقرير عن ممارسات التحسين المتميزة", "order": 13},
    {"id": "vp_c3_s3_r014", "subcategory_id": "vp_c3_s3", "name": "سجل متابعة تحقيق مستهدفات الخطة", "order": 14},
    {"id": "vp_c3_s3_r015", "subcategory_id": "vp_c3_s3", "name": "تقرير عن الاحتياجات التدريبية للتحسين", "order": 15},
    {"id": "vp_c3_s3_r016", "subcategory_id": "vp_c3_s3", "name": "توثيق ورش عمل فريق التحسين", "order": 16},
    {"id": "vp_c3_s3_r017", "subcategory_id": "vp_c3_s3", "name": "تقرير عن متابعة تنفيذ مبادرات التحسين", "order": 17},
    {"id": "vp_c3_s3_r018", "subcategory_id": "vp_c3_s3", "name": "سجل متابعة خطط التحسين في الاداء المدرسي", "order": 18},
    {"id": "vp_c3_s3_r019", "subcategory_id": "vp_c3_s3", "name": "تقرير عن مدى توافق الخطة مع رؤية المدرسة", "order": 19},
    {"id": "vp_c3_s3_r020", "subcategory_id": "vp_c3_s3", "name": "توثيق نتائج تقييم اثر التحسين", "order": 20},

    # vp_c3_s4 (الإشراف على الاختبارات والتقويم)
    {"id": "vp_c3_s4_r001", "subcategory_id": "vp_c3_s4", "name": "تقرير عن الإشراف على الاختبارات", "order": 1},
    {"id": "vp_c3_s4_r002", "subcategory_id": "vp_c3_s4", "name": "سجل متابعة سير الاختبارات", "order": 2},
    {"id": "vp_c3_s4_r003", "subcategory_id": "vp_c3_s4", "name": "تقرير عن نتائج الاختبارات وتحليلها", "order": 3},
    {"id": "vp_c3_s4_r004", "subcategory_id": "vp_c3_s4", "name": "توثيق اجتماعات لجنة الاختبارات", "order": 4},
    {"id": "vp_c3_s4_r005", "subcategory_id": "vp_c3_s4", "name": "تقرير عن تطبيق لائحة تقويم الطالب", "order": 5},
    {"id": "vp_c3_s4_r006", "subcategory_id": "vp_c3_s4", "name": "سجل متابعة تجهيز قاعات الاختبارات", "order": 6},
    {"id": "vp_c3_s4_r007", "subcategory_id": "vp_c3_s4", "name": "تقرير عن الاجراءات الاحترازية في الاختبارات", "order": 7},
    {"id": "vp_c3_s4_r008", "subcategory_id": "vp_c3_s4", "name": "توثيق توزيع المهام على الملاحظين", "order": 8},
    {"id": "vp_c3_s4_r009", "subcategory_id": "vp_c3_s4", "name": "تقرير عن التزام الطلاب بلوائح الاختبارات", "order": 9},
    {"id": "vp_c3_s4_r010", "subcategory_id": "vp_c3_s4", "name": "سجل متابعة رصد الدرجات", "order": 10},
    {"id": "vp_c3_s4_r011", "subcategory_id": "vp_c3_s4", "name": "تقرير عن حالات الغش ومعالجتها", "order": 11},
    {"id": "vp_c3_s4_r012", "subcategory_id": "vp_c3_s4", "name": "توثيق نماذج من اختبارات المواد", "order": 12},
    {"id": "vp_c3_s4_r013", "subcategory_id": "vp_c3_s4", "name": "تقرير عن تطبيق الاختبارات المركزية", "order": 13},
    {"id": "vp_c3_s4_r014", "subcategory_id": "vp_c3_s4", "name": "سجل متابعة تصحيح الاختبارات", "order": 14},
    {"id": "vp_c3_s4_r015", "subcategory_id": "vp_c3_s4", "name": "تقرير عن اعلان النتائج", "order": 15},
    {"id": "vp_c3_s4_r016", "subcategory_id": "vp_c3_s4", "name": "توثيق مراجعة نتائج الطلاب", "order": 16},
    {"id": "vp_c3_s4_r017", "subcategory_id": "vp_c3_s4", "name": "تقرير عن تحليل نتائج الاختبارات لكل مادة", "order": 17},
    {"id": "vp_c3_s4_r018", "subcategory_id": "vp_c3_s4", "name": "سجل متابعة اختبارات الدور الثاني", "order": 18},
    {"id": "vp_c3_s4_r019", "subcategory_id": "vp_c3_s4", "name": "تقرير عن تظلمات الطلاب ونتائجها", "order": 19},
    {"id": "vp_c3_s4_r020", "subcategory_id": "vp_c3_s4", "name": "توثيق توصيات تحسين العمل في الاختبارات القادمة", "order": 20},

    # vp_c3_s5 (متابعة تنفيذ المبادرات التعليمية)
    {"id": "vp_c3_s5_r001", "subcategory_id": "vp_c3_s5", "name": "تقرير متابعة تنفيذ المبادرات التعليمية", "order": 1},
    {"id": "vp_c3_s5_r002", "subcategory_id": "vp_c3_s5", "name": "سجل متابعة مبادرة تنمية القدرات", "order": 2},
    {"id": "vp_c3_s5_r003", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مشاركة المدرسة في مبادرات الوزارة", "order": 3},
    {"id": "vp_c3_s5_r004", "subcategory_id": "vp_c3_s5", "name": "توثيق أثر المبادرات على الطلاب", "order": 4},
    {"id": "vp_c3_s5_r005", "subcategory_id": "vp_c3_s5", "name": "تقرير عن برامج تنمية الموهوبين", "order": 5},
    {"id": "vp_c3_s5_r006", "subcategory_id": "vp_c3_s5", "name": "سجل متابعة مبادرة مهارات المستقبل", "order": 6},
    {"id": "vp_c3_s5_r007", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مبادرات التحول الرقمي", "order": 7},
    {"id": "vp_c3_s5_r008", "subcategory_id": "vp_c3_s5", "name": "توثيق مبادرة القراءة والحساب", "order": 8},
    {"id": "vp_c3_s5_r009", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مبادرات الريادة المدرسية", "order": 9},
    {"id": "vp_c3_s5_r010", "subcategory_id": "vp_c3_s5", "name": "سجل متابعة تنفيذ مبادرات النشاط", "order": 10},
    {"id": "vp_c3_s5_r011", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مبادرات دعم الطلاب المتعثرين", "order": 11},
    {"id": "vp_c3_s5_r012", "subcategory_id": "vp_c3_s5", "name": "توثيق مبادرة اللغة الانجليزية", "order": 12},
    {"id": "vp_c3_s5_r013", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مبادرات التوجيه المهني", "order": 13},
    {"id": "vp_c3_s5_r014", "subcategory_id": "vp_c3_s5", "name": "سجل متابعة مبادرة تنمية الإبداع", "order": 14},
    {"id": "vp_c3_s5_r015", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مبادرات الصحة المدرسية", "order": 15},
    {"id": "vp_c3_s5_r016", "subcategory_id": "vp_c3_s5", "name": "توثيق مبادرة الأمن الفكري", "order": 16},
    {"id": "vp_c3_s5_r017", "subcategory_id": "vp_c3_s5", "name": "تقرير عن مبادرات الشراكة المجتمعية", "order": 17},
    {"id": "vp_c3_s5_r018", "subcategory_id": "vp_c3_s5", "name": "سجل متابعة تنفيذ مبادرات التميز", "order": 18},
    {"id": "vp_c3_s5_r019", "subcategory_id": "vp_c3_s5", "name": "تقرير عن تقييم المبادرات المنفذة", "order": 19},
    {"id": "vp_c3_s5_r020", "subcategory_id": "vp_c3_s5", "name": "توثيق توصيات تطوير المبادرات", "order": 20},

    # vp_c4_s1 (تقييم أداء المعلمين من خلال الزيارات الصفية)
    {"id": "vp_c4_s1_r001", "subcategory_id": "vp_c4_s1", "name": "تقرير الزيارات الصفية للمعلمين", "order": 1},
    {"id": "vp_c4_s1_r002", "subcategory_id": "vp_c4_s1", "name": "سجل جدول الزيارات الصفية", "order": 2},
    {"id": "vp_c4_s1_r003", "subcategory_id": "vp_c4_s1", "name": "تقرير تقييم أداء المعلمين بناءً على الزيارات", "order": 3},
    {"id": "vp_c4_s1_r004", "subcategory_id": "vp_c4_s1", "name": "توثيق تغذية راجعة للمعلمين بعد الزيارة", "order": 4},
    {"id": "vp_c4_s1_r005", "subcategory_id": "vp_c4_s1", "name": "تقرير عن تطور أداء المعلمين", "order": 5},
    {"id": "vp_c4_s1_r006", "subcategory_id": "vp_c4_s1", "name": "سجل متابعة تنفيذ الزيارات المخططة", "order": 6},
    {"id": "vp_c4_s1_r007", "subcategory_id": "vp_c4_s1", "name": "تقرير عن الزيارات الصفية للمعلمين الجدد", "order": 7},
    {"id": "vp_c4_s1_r008", "subcategory_id": "vp_c4_s1", "name": "توثيق تقارير الزيارات الصفية", "order": 8},
    {"id": "vp_c4_s1_r009", "subcategory_id": "vp_c4_s1", "name": "تقرير عن أداء المعلمين في تنفيذ الدروس", "order": 9},
    {"id": "vp_c4_s1_r010", "subcategory_id": "vp_c4_s1", "name": "سجل ملاحظات الزيارات الصفية", "order": 10},
    {"id": "vp_c4_s1_r011", "subcategory_id": "vp_c4_s1", "name": "تقرير عن استخدام المعلمين لاستراتيجيات التدريس", "order": 11},
    {"id": "vp_c4_s1_r012", "subcategory_id": "vp_c4_s1", "name": "توثيق الزيارات الصفية المشتركة مع المشرفين", "order": 12},
    {"id": "vp_c4_s1_r013", "subcategory_id": "vp_c4_s1", "name": "تقرير عن تفاعل الطلاب في الحصص التي تمت زيارتها", "order": 13},
    {"id": "vp_c4_s1_r014", "subcategory_id": "vp_c4_s1", "name": "سجل متابعة توصيات الزيارات الصفية", "order": 14},
    {"id": "vp_c4_s1_r015", "subcategory_id": "vp_c4_s1", "name": "تقرير عن مدى التزام المعلمين بخطط الدروس", "order": 15},
    {"id": "vp_c4_s1_r016", "subcategory_id": "vp_c4_s1", "name": "توثيق نماذج من أدوات تقييم الزيارات", "order": 16},
    {"id": "vp_c4_s1_r017", "subcategory_id": "vp_c4_s1", "name": "تقرير عن الزيارات الصفية لمعلمي المواد المختلفة", "order": 17},
    {"id": "vp_c4_s1_r018", "subcategory_id": "vp_c4_s1", "name": "سجل تحليل نتائج الزيارات لكل معلم", "order": 18},
    {"id": "vp_c4_s1_r019", "subcategory_id": "vp_c4_s1", "name": "تقرير عن مدى تحسن اداء المعلمين بعد التغذية الراجعة", "order": 19},
    {"id": "vp_c4_s1_r020", "subcategory_id": "vp_c4_s1", "name": "توثيق خطة الزيارات الصفية للفصل القادم", "order": 20},

    # vp_c4_s2 (تقديم تغذية راجعة للمعلمين)
    {"id": "vp_c4_s2_r001", "subcategory_id": "vp_c4_s2", "name": "تقرير عن تقديم تغذية راجعة للمعلمين", "order": 1},
    {"id": "vp_c4_s2_r002", "subcategory_id": "vp_c4_s2", "name": "سجل لقاءات المتابعة مع المعلمين", "order": 2},
    {"id": "vp_c4_s2_r003", "subcategory_id": "vp_c4_s2", "name": "تقرير عن خطط تحسين أداء المعلمين", "order": 3},
    {"id": "vp_c4_s2_r004", "subcategory_id": "vp_c4_s2", "name": "توثيق الإشادة بالمعلمين المتميزين", "order": 4},
    {"id": "vp_c4_s2_r005", "subcategory_id": "vp_c4_s2", "name": "تقرير متابعة تنفيذ توصيات الزيارات", "order": 5},
    {"id": "vp_c4_s2_r006", "subcategory_id": "vp_c4_s2", "name": "سجل تقديم التغذية الراجعة المكتوبة", "order": 6},
    {"id": "vp_c4_s2_r007", "subcategory_id": "vp_c4_s2", "name": "تقرير عن جلسات التغذية الراجعة الفردية", "order": 7},
    {"id": "vp_c4_s2_r008", "subcategory_id": "vp_c4_s2", "name": "توثيق التغذية الراجعة الجماعية", "order": 8},
    {"id": "vp_c4_s2_r009", "subcategory_id": "vp_c4_s2", "name": "تقرير عن مدى رضا المعلمين عن التغذية الراجعة", "order": 9},
    {"id": "vp_c4_s2_r010", "subcategory_id": "vp_c4_s2", "name": "سجل متابعة تنفيذ خطط التطوير بعد التغذية الراجعة", "order": 10},
    {"id": "vp_c4_s2_r011", "subcategory_id": "vp_c4_s2", "name": "تقرير عن التغذية الراجعة للمعلمين ذوي الاداء الضعيف", "order": 11},
    {"id": "vp_c4_s2_r012", "subcategory_id": "vp_c4_s2", "name": "توثيق نماذج من خطط تحسين الاداء", "order": 12},
    {"id": "vp_c4_s2_r013", "subcategory_id": "vp_c4_s2", "name": "تقرير عن اثر التغذية الراجعة على تحسين التدريس", "order": 13},
    {"id": "vp_c4_s2_r014", "subcategory_id": "vp_c4_s2", "name": "سجل اجتماعات التغذية الراجعة مع رؤساء الاقسام", "order": 14},
    {"id": "vp_c4_s2_r015", "subcategory_id": "vp_c4_s2", "name": "تقرير عن دور التغذية الراجعة في رفع كفاءة المعلمين", "order": 15},
    {"id": "vp_c4_s2_r016", "subcategory_id": "vp_c4_s2", "name": "توثيق استمارات التغذية الراجعة المستخدمة", "order": 16},
    {"id": "vp_c4_s2_r017", "subcategory_id": "vp_c4_s2", "name": "تقرير عن توقيتات التغذية الراجعة ومدى ملاءمتها", "order": 17},
    {"id": "vp_c4_s2_r018", "subcategory_id": "vp_c4_s2", "name": "سجل متابعة تحسن المعلمين بعد التغذية الراجعة", "order": 18},
    {"id": "vp_c4_s2_r019", "subcategory_id": "vp_c4_s2", "name": "تقرير عن التغذية الراجعة في ضوء نتائج الطلاب", "order": 19},
    {"id": "vp_c4_s2_r020", "subcategory_id": "vp_c4_s2", "name": "توثيق توصيات تطوير آليات التغذية الراجعة", "order": 20},

    # vp_c4_s3 (تحفيز المعلمين المتميزين)
    {"id": "vp_c4_s3_r001", "subcategory_id": "vp_c4_s3", "name": "تقرير عن تكريم المعلمين المتميزين", "order": 1},
    {"id": "vp_c4_s3_r002", "subcategory_id": "vp_c4_s3", "name": "سجل حصر المعلمين المتميزين", "order": 2},
    {"id": "vp_c4_s3_r003", "subcategory_id": "vp_c4_s3", "name": "تقرير عن برامج تحفيز المعلمين", "order": 3},
    {"id": "vp_c4_s3_r004", "subcategory_id": "vp_c4_s3", "name": "توثيق مشاركة المعلمين في المسابقات", "order": 4},
    {"id": "vp_c4_s3_r005", "subcategory_id": "vp_c4_s3", "name": "تقرير عن أثر التحفيز على الأداء", "order": 5},
    {"id": "vp_c4_s3_r006", "subcategory_id": "vp_c4_s3", "name": "سجل تنظيم حفلات التكريم", "order": 6},
    {"id": "vp_c4_s3_r007", "subcategory_id": "vp_c4_s3", "name": "تقرير عن شهادات الشكر والتقدير", "order": 7},
    {"id": "vp_c4_s3_r008", "subcategory_id": "vp_c4_s3", "name": "توثيق الحوافز المادية للمتميزين", "order": 8},
    {"id": "vp_c4_s3_r009", "subcategory_id": "vp_c4_s3", "name": "تقرير عن معايير اختيار المعلمين المتميزين", "order": 9},
    {"id": "vp_c4_s3_r010", "subcategory_id": "vp_c4_s3", "name": "سجل ترشيحات المعلمين المتميزين", "order": 10},
    {"id": "vp_c4_s3_r011", "subcategory_id": "vp_c4_s3", "name": "تقرير عن نشر ثقافة التميز بين المعلمين", "order": 11},
    {"id": "vp_c4_s3_r012", "subcategory_id": "vp_c4_s3", "name": "توثيق قصص نجاح المعلمين المتميزين", "order": 12},
    {"id": "vp_c4_s3_r013", "subcategory_id": "vp_c4_s3", "name": "تقرير عن اثر التكريم على زملائهم", "order": 13},
    {"id": "vp_c4_s3_r014", "subcategory_id": "vp_c4_s3", "name": "سجل حصر مبادرات المعلمين المتميزين", "order": 14},
    {"id": "vp_c4_s3_r015", "subcategory_id": "vp_c4_s3", "name": "تقرير عن تحفيز المعلمين في المناسبات", "order": 15},
    {"id": "vp_c4_s3_r016", "subcategory_id": "vp_c4_s3", "name": "توثيق مشاركة اولياء الامور في التكريم", "order": 16},
    {"id": "vp_c4_s3_r017", "subcategory_id": "vp_c4_s3", "name": "تقرير عن برامج تحفيز المعلمين المبدعين", "order": 17},
    {"id": "vp_c4_s3_r018", "subcategory_id": "vp_c4_s3", "name": "سجل متابعة اداء المتميزين بعد التكريم", "order": 18},
    {"id": "vp_c4_s3_r019", "subcategory_id": "vp_c4_s3", "name": "تقرير عن اسهامات المتميزين في تطوير المدرسة", "order": 19},
    {"id": "vp_c4_s3_r020", "subcategory_id": "vp_c4_s3", "name": "توثيق توصيات تطوير نظام الحوافز", "order": 20},

    # vp_c4_s4 (تنظيم برامج تطوير مهني للمعلمين)
    {"id": "vp_c4_s4_r001", "subcategory_id": "vp_c4_s4", "name": "تقرير عن تنظيم برامج تطوير مهني للمعلمين", "order": 1},
    {"id": "vp_c4_s4_r002", "subcategory_id": "vp_c4_s4", "name": "سجل حضور المعلمين للدورات", "order": 2},
    {"id": "vp_c4_s4_r003", "subcategory_id": "vp_c4_s4", "name": "تقرير عن احتياجات التطوير المهني", "order": 3},
    {"id": "vp_c4_s4_r004", "subcategory_id": "vp_c4_s4", "name": "توثيق ورش العمل المنفذة داخل المدرسة", "order": 4},
    {"id": "vp_c4_s4_r005", "subcategory_id": "vp_c4_s4", "name": "تقرير عن أثر البرامج على أداء المعلمين", "order": 5},
    {"id": "vp_c4_s4_r006", "subcategory_id": "vp_c4_s4", "name": "سجل متابعة تنفيذ خطة التطوير المهني", "order": 6},
    {"id": "vp_c4_s4_r007", "subcategory_id": "vp_c4_s4", "name": "تقرير عن دورات تدريبية عن استراتيجيات التدريس", "order": 7},
    {"id": "vp_c4_s4_r008", "subcategory_id": "vp_c4_s4", "name": "توثيق مشاركة المعلمين في برامج الابتعاث", "order": 8},
    {"id": "vp_c4_s4_r009", "subcategory_id": "vp_c4_s4", "name": "تقرير عن البرامج التطويرية للمعلمين الجدد", "order": 9},
    {"id": "vp_c4_s4_r010", "subcategory_id": "vp_c4_s4", "name": "سجل متابعة استفادة المعلمين من الدورات", "order": 10},
    {"id": "vp_c4_s4_r011", "subcategory_id": "vp_c4_s4", "name": "تقرير عن تنظيم دورات في التقويم المستمر", "order": 11},
    {"id": "vp_c4_s4_r012", "subcategory_id": "vp_c4_s4", "name": "توثيق شراكات مع مراكز تدريب", "order": 12},
    {"id": "vp_c4_s4_r013", "subcategory_id": "vp_c4_s4", "name": "تقرير عن برامج التطوير الالكترونية", "order": 13},
    {"id": "vp_c4_s4_r014", "subcategory_id": "vp_c4_s4", "name": "سجل متابعة تنفيذ التدريب عن بعد", "order": 14},
    {"id": "vp_c4_s4_r015", "subcategory_id": "vp_c4_s4", "name": "تقرير عن اعداد خطط التطوير بناء على الاحتياجات", "order": 15},
    {"id": "vp_c4_s4_r016", "subcategory_id": "vp_c4_s4", "name": "توثيق حصر المعلمين الحاصلين على شهادات مهنية", "order": 16},
    {"id": "vp_c4_s4_r017", "subcategory_id": "vp_c4_s4", "name": "تقرير عن برامج تنمية القيادات المدرسية", "order": 17},
    {"id": "vp_c4_s4_r018", "subcategory_id": "vp_c4_s4", "name": "سجل متابعة تطبيق المعلمين لمخرجات التدريب", "order": 18},
    {"id": "vp_c4_s4_r019", "subcategory_id": "vp_c4_s4", "name": "تقرير عن تقييم البرامج التدريبية من المعلمين", "order": 19},
    {"id": "vp_c4_s4_r020", "subcategory_id": "vp_c4_s4", "name": "توثيق خطة التطوير المهني للعام القادم", "order": 20},

    # vp_c4_s5 (متابعة خطط المعلمين العلاجية)
    {"id": "vp_c4_s5_r001", "subcategory_id": "vp_c4_s5", "name": "تقرير متابعة تنفيذ خطط المعلمين العلاجية", "order": 1},
    {"id": "vp_c4_s5_r002", "subcategory_id": "vp_c4_s5", "name": "سجل متابعة تطور المعلمين", "order": 2},
    {"id": "vp_c4_s5_r003", "subcategory_id": "vp_c4_s5", "name": "تقرير عن فعالية الخطط العلاجية", "order": 3},
    {"id": "vp_c4_s5_r004", "subcategory_id": "vp_c4_s5", "name": "توثيق اجتماعات المتابعة مع المعلمين", "order": 4},
    {"id": "vp_c4_s5_r005", "subcategory_id": "vp_c4_s5", "name": "تقرير عن توصيات لتحسين الخطط", "order": 5},
    {"id": "vp_c4_s5_r006", "subcategory_id": "vp_c4_s5", "name": "سجل متابعة تنفيذ خطط المعلمين المتعثرين", "order": 6},
    {"id": "vp_c4_s5_r007", "subcategory_id": "vp_c4_s5", "name": "تقرير عن تحديد جوانب الضعف لدى المعلمين", "order": 7},
    {"id": "vp_c4_s5_r008", "subcategory_id": "vp_c4_s5", "name": "توثيق خطط تحسين الاداء للمعلمين الجدد", "order": 8},
    {"id": "vp_c4_s5_r009", "subcategory_id": "vp_c4_s5", "name": "تقرير عن متابعة تنفيذ توصيات المشرفين", "order": 9},
    {"id": "vp_c4_s5_r010", "subcategory_id": "vp_c4_s5", "name": "سجل متابعة تقدم المعلمين في الخطط", "order": 10},
    {"id": "vp_c4_s5_r011", "subcategory_id": "vp_c4_s5", "name": "تقرير عن دور التوجيه والارشاد المهني", "order": 11},
    {"id": "vp_c4_s5_r012", "subcategory_id": "vp_c4_s5", "name": "توثيق ورش العمل العلاجية", "order": 12},
    {"id": "vp_c4_s5_r013", "subcategory_id": "vp_c4_s5", "name": "تقرير عن تقييم اثر الخطط العلاجية على الطلاب", "order": 13},
    {"id": "vp_c4_s5_r014", "subcategory_id": "vp_c4_s5", "name": "سجل متابعة زيارات الدعم للمعلمين", "order": 14},
    {"id": "vp_c4_s5_r015", "subcategory_id": "vp_c4_s5", "name": "تقرير عن مدى التزام المعلمين بالخطط", "order": 15},
    {"id": "vp_c4_s5_r016", "subcategory_id": "vp_c4_s5", "name": "توثيق نماذج من الخطط العلاجية", "order": 16},
    {"id": "vp_c4_s5_r017", "subcategory_id": "vp_c4_s5", "name": "تقرير عن تحسين اداء المعلمين في ضوء نتائج الطلاب", "order": 17},
    {"id": "vp_c4_s5_r018", "subcategory_id": "vp_c4_s5", "name": "سجل متابعة تنفيذ الخطط لكل معلم", "order": 18},
    {"id": "vp_c4_s5_r019", "subcategory_id": "vp_c4_s5", "name": "تقرير عن معوقات تنفيذ الخطط العلاجية", "order": 19},
    {"id": "vp_c4_s5_r020", "subcategory_id": "vp_c4_s5", "name": "توثيق مراجعة وتحديث الخطط العلاجية", "order": 20},

    # vp_c5_s1 (التواصل مع أولياء الأمور وحضور مجالس الآباء)
    {"id": "vp_c5_s1_r001", "subcategory_id": "vp_c5_s1", "name": "تقرير عن التواصل مع أولياء الأمور", "order": 1},
    {"id": "vp_c5_s1_r002", "subcategory_id": "vp_c5_s1", "name": "سجل حضور مجالس الآباء", "order": 2},
    {"id": "vp_c5_s1_r003", "subcategory_id": "vp_c5_s1", "name": "تقرير عن قضايا أولياء الأمور ومعالجتها", "order": 3},
    {"id": "vp_c5_s1_r004", "subcategory_id": "vp_c5_s1", "name": "توثيق استبيانات رأي أولياء الأمور", "order": 4},
    {"id": "vp_c5_s1_r005", "subcategory_id": "vp_c5_s1", "name": "تقرير عن نسبة رضا أولياء الأمور", "order": 5},
    {"id": "vp_c5_s1_r006", "subcategory_id": "vp_c5_s1", "name": "سجل تواصل ولي الأمر مع المدرسة", "order": 6},
    {"id": "vp_c5_s1_r007", "subcategory_id": "vp_c5_s1", "name": "تقرير عن تنظيم لقاءات اولياء الامور الدورية", "order": 7},
    {"id": "vp_c5_s1_r008", "subcategory_id": "vp_c5_s1", "name": "توثيق مشاركة اولياء الامور في الانشطة", "order": 8},
    {"id": "vp_c5_s1_r009", "subcategory_id": "vp_c5_s1", "name": "تقرير عن قنوات التواصل المستخدمة", "order": 9},
    {"id": "vp_c5_s1_r010", "subcategory_id": "vp_c5_s1", "name": "سجل متابعة استفسارات أولياء الأمور", "order": 10},
    {"id": "vp_c5_s1_r011", "subcategory_id": "vp_c5_s1", "name": "تقرير عن مجالس الاباء وتوصياتها", "order": 11},
    {"id": "vp_c5_s1_r012", "subcategory_id": "vp_c5_s1", "name": "توثيق تفعيل منصة نور للتواصل", "order": 12},
    {"id": "vp_c5_s1_r013", "subcategory_id": "vp_c5_s1", "name": "تقرير عن تطبيق نظام الاشعارات", "order": 13},
    {"id": "vp_c5_s1_r014", "subcategory_id": "vp_c5_s1", "name": "سجل مشاركة اولياء الامور في التوجيه", "order": 14},
    {"id": "vp_c5_s1_r015", "subcategory_id": "vp_c5_s1", "name": "تقرير عن مدى رضا المعلمين عن تواصل اولياء الامور", "order": 15},
    {"id": "vp_c5_s1_r016", "subcategory_id": "vp_c5_s1", "name": "توثيق اتفاقيات شراكة مع مجلس الاباء", "order": 16},
    {"id": "vp_c5_s1_r017", "subcategory_id": "vp_c5_s1", "name": "تقرير عن تدريب اولياء الامور", "order": 17},
    {"id": "vp_c5_s1_r018", "subcategory_id": "vp_c5_s1", "name": "سجل متابعة حضور اولياء الامور للاجتماعات", "order": 18},
    {"id": "vp_c5_s1_r019", "subcategory_id": "vp_c5_s1", "name": "تقرير عن تطوير التواصل مع اولياء الامور", "order": 19},
    {"id": "vp_c5_s1_r020", "subcategory_id": "vp_c5_s1", "name": "توثيق تحليل نتائج استبيانات الرضا", "order": 20},

    # vp_c5_s2 (تنظيم لقاءات توعوية لأولياء الأمور)
    {"id": "vp_c5_s2_r001", "subcategory_id": "vp_c5_s2", "name": "تقرير عن تنظيم لقاءات توعوية لأولياء الأمور", "order": 1},
    {"id": "vp_c5_s2_r002", "subcategory_id": "vp_c5_s2", "name": "سجل محاضرات لأولياء الأمور", "order": 2},
    {"id": "vp_c5_s2_r003", "subcategory_id": "vp_c5_s2", "name": "تقرير عن برامج توعوية عن الانضباط", "order": 3},
    {"id": "vp_c5_s2_r004", "subcategory_id": "vp_c5_s2", "name": "توثيق إرشادات لأولياء الأمور", "order": 4},
    {"id": "vp_c5_s2_r005", "subcategory_id": "vp_c5_s2", "name": "تقرير عن تفاعل أولياء الأمور", "order": 5},
    {"id": "vp_c5_s2_r006", "subcategory_id": "vp_c5_s2", "name": "سجل محاضرات عن أساليب التربية", "order": 6},
    {"id": "vp_c5_s2_r007", "subcategory_id": "vp_c5_s2", "name": "تقرير عن ورش عمل لأولياء الأمور", "order": 7},
    {"id": "vp_c5_s2_r008", "subcategory_id": "vp_c5_s2", "name": "توثيق برامج توعية حول الاستخدام الامن للانترنت", "order": 8},
    {"id": "vp_c5_s2_r009", "subcategory_id": "vp_c5_s2", "name": "تقرير عن محاضرات عن الصحة النفسية للابناء", "order": 9},
    {"id": "vp_c5_s2_r010", "subcategory_id": "vp_c5_s2", "name": "سجل لقاءات توعية عن النظام المدرسي", "order": 10},
    {"id": "vp_c5_s2_r011", "subcategory_id": "vp_c5_s2", "name": "تقرير عن مشاركة متخصصين في التوعية", "order": 11},
    {"id": "vp_c5_s2_r012", "subcategory_id": "vp_c5_s2", "name": "توثيق برامج توعوية عن مكافحة التنمر", "order": 12},
    {"id": "vp_c5_s2_r013", "subcategory_id": "vp_c5_s2", "name": "تقرير عن تأثير اللقاءات على سلوك الطلاب", "order": 13},
    {"id": "vp_c5_s2_r014", "subcategory_id": "vp_c5_s2", "name": "سجل استبيانات حول احتياجات اولياء الامور التوعوية", "order": 14},
    {"id": "vp_c5_s2_r015", "subcategory_id": "vp_c5_s2", "name": "تقرير عن تطوير المحتوى التوعوي", "order": 15},
    {"id": "vp_c5_s2_r016", "subcategory_id": "vp_c5_s2", "name": "توثيق نشرات توعوية لأولياء الأمور", "order": 16},
    {"id": "vp_c5_s2_r017", "subcategory_id": "vp_c5_s2", "name": "تقرير عن قنوات التواصل للتوعية", "order": 17},
    {"id": "vp_c5_s2_r018", "subcategory_id": "vp_c5_s2", "name": "سجل تقييم اللقاءات من اولياء الامور", "order": 18},
    {"id": "vp_c5_s2_r019", "subcategory_id": "vp_c5_s2", "name": "تقرير عن برامج توعوية عن التغذية", "order": 19},
    {"id": "vp_c5_s2_r020", "subcategory_id": "vp_c5_s2", "name": "توثيق خطة التوعية السنوية", "order": 20},

    # vp_c5_s3 (المشاركة في الفعاليات المجتمعية)
    {"id": "vp_c5_s3_r001", "subcategory_id": "vp_c5_s3", "name": "تقرير عن مشاركة المدرسة في الفعاليات المجتمعية", "order": 1},
    {"id": "vp_c5_s3_r002", "subcategory_id": "vp_c5_s3", "name": "سجل المشاركات الخارجية", "order": 2},
    {"id": "vp_c5_s3_r003", "subcategory_id": "vp_c5_s3", "name": "تقرير عن الشراكات المجتمعية", "order": 3},
    {"id": "vp_c5_s3_r004", "subcategory_id": "vp_c5_s3", "name": "توثيق الزيارات المتبادلة مع المؤسسات", "order": 4},
    {"id": "vp_c5_s3_r005", "subcategory_id": "vp_c5_s3", "name": "تقرير عن أثر المشاركات المجتمعية", "order": 5},
    {"id": "vp_c5_s3_r006", "subcategory_id": "vp_c5_s3", "name": "سجل مشاركة المدرسة في المناسبات الوطنية", "order": 6},
    {"id": "vp_c5_s3_r007", "subcategory_id": "vp_c5_s3", "name": "تقرير عن المشاركات في المعارض", "order": 7},
    {"id": "vp_c5_s3_r008", "subcategory_id": "vp_c5_s3", "name": "توثيق المشاركة في حملات النظافة", "order": 8},
    {"id": "vp_c5_s3_r009", "subcategory_id": "vp_c5_s3", "name": "تقرير عن المشاركة في الايام العالمية", "order": 9},
    {"id": "vp_c5_s3_r010", "subcategory_id": "vp_c5_s3", "name": "سجل زيارات طلابية للمؤسسات", "order": 10},
    {"id": "vp_c5_s3_r011", "subcategory_id": "vp_c5_s3", "name": "تقرير عن مشاركة المدرسة في المسابقات الخارجية", "order": 11},
    {"id": "vp_c5_s3_r012", "subcategory_id": "vp_c5_s3", "name": "توثيق المشاركة في مبادرات المجتمع", "order": 12},
    {"id": "vp_c5_s3_r013", "subcategory_id": "vp_c5_s3", "name": "تقرير عن دور المدرسة في خدمة المجتمع", "order": 13},
    {"id": "vp_c5_s3_r014", "subcategory_id": "vp_c5_s3", "name": "سجل متابعة المشاركات المجتمعية للطلاب", "order": 14},
    {"id": "vp_c5_s3_r015", "subcategory_id": "vp_c5_s3", "name": "تقرير عن تنظيم زيارات للمعلمين للمؤسسات", "order": 15},
    {"id": "vp_c5_s3_r016", "subcategory_id": "vp_c5_s3", "name": "توثيق شراكات مع اقسام الشرطة", "order": 16},
    {"id": "vp_c5_s3_r017", "subcategory_id": "vp_c5_s3", "name": "تقرير عن المشاركة في الفعاليات الرياضية", "order": 17},
    {"id": "vp_c5_s3_r018", "subcategory_id": "vp_c5_s3", "name": "سجل استضافة شخصيات مجتمعية", "order": 18},
    {"id": "vp_c5_s3_r019", "subcategory_id": "vp_c5_s3", "name": "تقرير عن تكريم المدرسة من جهات خارجية", "order": 19},
    {"id": "vp_c5_s3_r020", "subcategory_id": "vp_c5_s3", "name": "توثيق خطة المشاركات المجتمعية", "order": 20},

    # vp_c5_s4 (بناء شراكات مجتمعية للمدرسة)
    {"id": "vp_c5_s4_r001", "subcategory_id": "vp_c5_s4", "name": "تقرير عن بناء شراكات مجتمعية للمدرسة", "order": 1},
    {"id": "vp_c5_s4_r002", "subcategory_id": "vp_c5_s4", "name": "سجل الاتفاقيات ومذكرات التفاهم", "order": 2},
    {"id": "vp_c5_s4_r003", "subcategory_id": "vp_c5_s4", "name": "تقرير عن دعم المؤسسات للمدرسة", "order": 3},
    {"id": "vp_c5_s4_r004", "subcategory_id": "vp_c5_s4", "name": "توثيق فعاليات مشتركة مع المجتمع", "order": 4},
    {"id": "vp_c5_s4_r005", "subcategory_id": "vp_c5_s4", "name": "تقرير عن استدامة الشراكات", "order": 5},
    {"id": "vp_c5_s4_r006", "subcategory_id": "vp_c5_s4", "name": "سجل الشراكة مع المراكز الصحية", "order": 6},
    {"id": "vp_c5_s4_r007", "subcategory_id": "vp_c5_s4", "name": "تقرير عن الشراكة مع المؤسسات الخيرية", "order": 7},
    {"id": "vp_c5_s4_r008", "subcategory_id": "vp_c5_s4", "name": "توثيق الشراكة مع الاندية الرياضية", "order": 8},
    {"id": "vp_c5_s4_r009", "subcategory_id": "vp_c5_s4", "name": "تقرير عن شراكة مع مراكز التدريب", "order": 9},
    {"id": "vp_c5_s4_r010", "subcategory_id": "vp_c5_s4", "name": "سجل متابعة تنفيذ بنود الشراكات", "order": 10},
    {"id": "vp_c5_s4_r011", "subcategory_id": "vp_c5_s4", "name": "تقرير عن اثر الشراكات على المدرسة", "order": 11},
    {"id": "vp_c5_s4_r012", "subcategory_id": "vp_c5_s4", "name": "توثيق لقاءات مع شركاء المجتمع", "order": 12},
    {"id": "vp_c5_s4_r013", "subcategory_id": "vp_c5_s4", "name": "تقرير عن الشراكة مع مكتب التعليم", "order": 13},
    {"id": "vp_c5_s4_r014", "subcategory_id": "vp_c5_s4", "name": "سجل المشاركات التطوعية", "order": 14},
    {"id": "vp_c5_s4_r015", "subcategory_id": "vp_c5_s4", "name": "تقرير عن استقطاب الدعم المادي", "order": 15},
    {"id": "vp_c5_s4_r016", "subcategory_id": "vp_c5_s4", "name": "توثيق حصر المؤسسات القابلة للشراكة", "order": 16},
    {"id": "vp_c5_s4_r017", "subcategory_id": "vp_c5_s4", "name": "تقرير عن تطوير الشراكات القائمة", "order": 17},
    {"id": "vp_c5_s4_r018", "subcategory_id": "vp_c5_s4", "name": "سجل متابعة تنفيذ المبادرات المشتركة", "order": 18},
    {"id": "vp_c5_s4_r019", "subcategory_id": "vp_c5_s4", "name": "تقرير عن قياس رضا الشركاء", "order": 19},
    {"id": "vp_c5_s4_r020", "subcategory_id": "vp_c5_s4", "name": "توثيق خطة بناء الشراكات للعام القادم", "order": 20},

    # vp_c5_s5 (التعامل مع شكاوى واقتراحات أولياء الأمور)
    {"id": "vp_c5_s5_r001", "subcategory_id": "vp_c5_s5", "name": "تقرير عن التعامل مع شكاوى أولياء الأمور", "order": 1},
    {"id": "vp_c5_s5_r002", "subcategory_id": "vp_c5_s5", "name": "سجل الشكاوى والاقتراحات", "order": 2},
    {"id": "vp_c5_s5_r003", "subcategory_id": "vp_c5_s5", "name": "تقرير عن تحليل الشكاوى ونتائجها", "order": 3},
    {"id": "vp_c5_s5_r004", "subcategory_id": "vp_c5_s5", "name": "توثيق آليات استقبال الشكاوى", "order": 4},
    {"id": "vp_c5_s5_r005", "subcategory_id": "vp_c5_s5", "name": "تقرير عن إجراءات تحسين الخدمة", "order": 5},
    {"id": "vp_c5_s5_r006", "subcategory_id": "vp_c5_s5", "name": "سجل متابعة الشكاوى حتى الاغلاق", "order": 6},
    {"id": "vp_c5_s5_r007", "subcategory_id": "vp_c5_s5", "name": "تقرير عن الشكاوى المتكررة", "order": 7},
    {"id": "vp_c5_s5_r008", "subcategory_id": "vp_c5_s5", "name": "توثيق الردود على الشكاوى", "order": 8},
    {"id": "vp_c5_s5_r009", "subcategory_id": "vp_c5_s5", "name": "تقرير عن الاقتراحات المقدمة من اولياء الامور", "order": 9},
    {"id": "vp_c5_s5_r010", "subcategory_id": "vp_c5_s5", "name": "سجل تصنيف الشكاوى حسب النوع", "order": 10},
    {"id": "vp_c5_s5_r011", "subcategory_id": "vp_c5_s5", "name": "تقرير عن وقت الاستجابة للشكاوى", "order": 11},
    {"id": "vp_c5_s5_r012", "subcategory_id": "vp_c5_s5", "name": "توثيق قنوات تلقي الشكاوى", "order": 12},
    {"id": "vp_c5_s5_r013", "subcategory_id": "vp_c5_s5", "name": "تقرير عن رضا أولياء الأمور عن معالجة الشكاوى", "order": 13},
    {"id": "vp_c5_s5_r014", "subcategory_id": "vp_c5_s5", "name": "سجل متابعة تنفيذ تحسينات بناء على الشكاوى", "order": 14},
    {"id": "vp_c5_s5_r015", "subcategory_id": "vp_c5_s5", "name": "تقرير عن تدريب الموظفين على التعامل مع الشكاوى", "order": 15},
    {"id": "vp_c5_s5_r016", "subcategory_id": "vp_c5_s5", "name": "توثيق تقارير الشكاوى الشهرية", "order": 16},
    {"id": "vp_c5_s5_r017", "subcategory_id": "vp_c5_s5", "name": "تقرير عن آلية تصعيد الشكاوى", "order": 17},
    {"id": "vp_c5_s5_r018", "subcategory_id": "vp_c5_s5", "name": "سجل استبيان رضا اولياء الامور عن الخدمات", "order": 18},
    {"id": "vp_c5_s5_r019", "subcategory_id": "vp_c5_s5", "name": "تقرير عن التوصيات لتحسين التعامل مع الشكاوى", "order": 19},
    {"id": "vp_c5_s5_r020", "subcategory_id": "vp_c5_s5", "name": "توثيق دليل اجراءات التعامل مع الشكاوى", "order": 20},
]

# قالب كتابة التقرير
VICE_PRINCIPAL_PROMPT_TEMPLATE = """أنت وكيل مدرسة تعمل وفق معايير الأداء الوظيفي المعتمدة في التعليم العام، وتمارس دورك القيادي التنفيذي في تنظيم العمل المدرسي ومتابعته.

المطلوب:
- عرض معيار الأداء الوظيفي.
- عرض التصنيف الفرعي.
- كتابة تقرير مهني متكامل يوضح الممارسات والإجراءات المرتبطة بهذا التصنيف.

التقرير المطلوب: "{report_name}"
وهو يندرج تحت التصنيف الفرعي: "{subcategory_name}"
ضمن المعيار التربوي: "{criterion_name}"

{subject_line}
{lesson_line}
{grade_line}
{target_line}
{place_line}
{count_line}

ضوابط الكتابة:
- لغة إدارية رسمية دقيقة.
- إبراز دور الوكيل في التنظيم، المتابعة، توزيع المهام، وضبط العمل.
- توضيح آلية التنفيذ والتوثيق.
- ربط العمل بتحسين الانضباط المدرسي وجودة الأداء العام.
- الإشارة إلى التنسيق مع قائد المدرسة والمعلمين والجهات ذات العلاقة.
- إبراز أثر الممارسة على البيئة المدرسية وتحقيق مستهدفات المدرسة.
- إظهار جانب المتابعة وقياس الأثر والتحسين المستمر.
- صياغة عملية واقعية من 5–7 أسطر متماسكة.

**الحقول المطلوبة:**
1. الهدف التربوي
2. نبذة مختصرة
3. إجراءات التنفيذ
4. الاستراتيجيات المستخدمة
5. نقاط القوة
6. نقاط التحسين
7. التوصيات

يرجى تقديم الإجابة باللغة العربية الفصحى، وتنظيمها بحيث يكون كل حقل في سطر منفصل يبدأ برقمه فقط دون ذكر العنوان."""